### ISSUE TITLE
[Q] How to skip examples?

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#1001]
How can I skip some training examples **especially when there are multiple data mapping steps (and only I can tell whether to skip in the middle)**. I tried to find docs related to this but couldn't find.

Specifically, I can imagine one can skip examples like this:
```
class ADataFlow(RNGDataFlow):

    def __init__(self, config):
        super(ADataFlow, self).__init__()
        ...

    def __len__(self):
        ...

    def __iter__(self):
        idxs = np.arange(len(self.dataset))
        self.rng.shuffle(idxs)
        for idx in idxs:
            imagef, labelf = self.dataset[idx]
            ... some processing ...
            if need_skip: continue               # <-- maybe like this
            yield something
```

However, for data flow efficiency, I am having multiple mapping functions.
```
ds = ADataFlow(config)
ds = MultiThreadMapData(ds, nr_thread=4, map_func=func_A)
aug_geo = [..., ..., ...]
aug_look = [..., ..., ...]
ds = AugmentImageComponents(ds, aug_geo, (0, 1), copy=False)
ds = AugmentImageComponents(ds, aug_look, (0,), copy=False)
ds = PrefetchDataZMQ(ds, nr_proc=4)
ds = MultiThreadMapData(ds, 2, func_B)
ds = BatchData(ds, 1)
```
What if I only can tell that an example is meaningless/un-wanted at **`func_B`**? How can I not include the example to `BatchData`? Is it possible?

For example, forcing to return [0, height, width, 3] (or [0x4] for GT boxes...) will do the trick (since concatenation will not work)? Other than possibly having different batch sizes every step, will this have some issue?

**Comment by ppwwyyxx** [comment]
Return None in the function.
This is mentioned in https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.MapData

**Comment by ywpkwon** [comment]
Wow, everything is already there. Sorry, I thought I went through quite much, but still, there are more! Thank you so much!
