### ISSUE TITLE
LMDB file format usage question

### ISSUE THREAD

**Issue by junsukchoe** [tensorpack/tensorpack#1006]
Hi,

I have a question about LMDB file format for dataflow.

In your tutorial, you use LocallyShuffleData for shuffling training data.
After that, I found LMDBSerializer.load has the shuffle argument.

Why do you use LocallyShuffleData instead of using the argument?
Is there any problem when I set the 'shuffle' argument True for shuffling the training data?

Thank you!

**Comment by ppwwyyxx** [comment]
@junsukchoe 'shuffle' will do random access on the file and will therefore put more pressure on the hard disk.

**Comment by junsukchoe** [comment]
Thank you for reply!

I have another question.

I am confused with 'LocallyShuffleData'. What does 'buffer_size' mean?
Does it mean the number of images? 

So, If I set the 'buffer_size' of LocallyShuffleData to the number of training data (e.g. 1,281,167 for ImageNet), then the shuffle occurs every one epoch?

**Comment by ppwwyyxx** [comment]
Please see updated documentation on what this dataflow does: https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.LocallyShuffleData

**Comment by junsukchoe** [comment]
Thanks a lot! I finally understand that.

Unfortunately, I found that LMDB deserialization is the bottleneck.
So, I try to implement the dataflow in a parallel way.

For example:

            from tensorpack.utils.compatible_serialize import loads

            ds = LMDBData(datadir, shuffle=False)
            ds = MultiThreadMapData(ds, nr_thread=25,
                                    map_func = lambda dp: loads(dp[1]))
            ds = LocallyShuffleData(ds, 50000)
            ds = PrefetchData(ds, 5000, 1)
            ds = MapDataComponent(ds, lambda x: cv2.imdecode(x, cv2.IMREAD_COLOR), 0)
            ds = AugmentImageCoordinates(ds, augmentors, coords_index=2, copy=False)
            ds = PrefetchDataZMQ(ds, 40)
            ds = BatchData(ds, 256, remainder=not isTrain)

At this time, I am worried about this multithread implementation. 
If the MultiThreadMapData forks the LMDBData, then all threads are expected to output the same datapoint. 
Is this true? 

Sorry for my poor background about parallel implementation.

**Comment by junsukchoe** [comment]
Yes, I also have found that mutli thread implementation is not faster than single thread implementation.

Thanks for kind reply! It really helps a lot.
