### ISSUE TITLE
How can I use hashtable in tensorpack?

### ISSUE THREAD

**Issue by SunskyF** [tensorpack/tensorpack#1008]
The tf.contrib.lookup.HashTable need init, how can I do that in a Session?
(https://www.tensorflow.org/api_docs/python/tf/contrib/lookup/HashTable)
Thx a lot!

**Comment by ppwwyyxx** [comment]
In general you can use the `RunOp` callback to run any ops.
However the table initializers should be run by default by tensorpack. The above commit 168f729 should resolve this.

**Comment by SunskyF** [comment]
Thx a lot!
