### ISSUE TITLE
Change the base model for FasterRCNN

### ISSUE THREAD

**Issue by FrancisFok** [tensorpack/tensorpack#1009]
I am trying using different base model for FasterRCNN. I get the base model in http://models.tensorpack.com/FasterRCNN/

When following the suggested example, using ImageNet-R50-AlignPadding.npz, the program runs with good results.

However, when i am using "vgg16.npz" or "alexnet.npz", the training could be completed. There is no bounding box finding in the result.

Is it only possible to use the base model in the section "FasterRCNN" in "http://models.tensorpack.com/FasterRCNN/" for faster rcnn?

**Comment by ppwwyyxx** [comment]
No that's not how things works. You'll need to modify the code to use a different base model.

**Comment by FrancisFok** [comment]
Thus, we need to add a subclass of DetectionModel.
Then, it may need to get the input/output tensor name.
Is there a way to check from the npz file?

**Comment by ppwwyyxx** [comment]
The `npz` file contains no information about network architecture.
