### ISSUE TITLE
Seems a bug in FasterRCNN example

### ISSUE THREAD

**Issue by SunskyF** [tensorpack/tensorpack#1011]
https://github.com/tensorpack/tensorpack/blob/168f729220d5be09d12a5941d1089c10898c5d87/examples/FasterRCNN/model_frcnn.py#L193
boxes.set_shape([None, cfg.DATA.NUM_CATEGORY, None])

The 'boxes' has the shape #catxnx4, however, set_shape([None, cfg.DATA.NUM_CATEGORY, None])
It seems a bug?

**Comment by ppwwyyxx** [comment]
Thanks for spotting this! This line has no effect and has been removed now.
