### ISSUE TITLE
Mesh Tensorflow support

### ISSUE THREAD

**Issue by innerop** [tensorpack/tensorpack#1013]
Mesh TF is capable of model parallel and data parallel configurations. Even both modes at the same time. But it seems like a new Google project and the only instruction they give to try it out is for TPU instances. I'm wondering if TensorPack will eventually include support for Mesh TF?

**Comment by ppwwyyxx** [comment]
We have no plans to do so, especially at this early stage when "Mesh TF" is still premature. I have found no evidence that this library works well for real-life problems on GPUs.
