### ISSUE TITLE
Page not found on tensorpack docs

### ISSUE THREAD

**Issue by DreamChaserMXF** [tensorpack/tensorpack#1016]
When I reading the docs of tensorpack, I clicked "TFDatasetInput" on [this](https://tensorpack.readthedocs.io/tutorial/input-source.html) page, my browser brought me to [this](https://tensorpack.readthedocs.io/en/latest/modules/input_source.html#tensorpack.input_source.TFDatasetInput) page, and it prompted that the page is not found.
Actually, I found the correct link is perhaps [this](https://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.TFDatasetInput).
I was wondering if it is a common problem, or one just appeared in my browser (Chrome 71.0.3578.98)?

**Comment by ppwwyyxx** [comment]
Thanks for finding this! The links were fixed now and should be effective in several minutes
