### ISSUE TITLE
how to adapt model-agnostic meta learning in tensorpack

### ISSUE THREAD

**Issue by john81923** [tensorpack/tensorpack#1025]
Hello,

I would like to do **model-agnostic meta learning** in tensorpack
The training algorithm of a **classification** task using model-agnostic meta learning is below:

We have fθ as the model with parameter θ , α,β are hyperparameters
1. in each iteration sample [ inputa, inputb, labela, labelb ] from training set 
2. forward inputa to fθ and evaluate the gradient using cross entropy
3. Compute adapted parameters with gradient descent:
4.  **θ'**  =  θ  - α∇θfθ(inputa)
5.  update  θ ← θ − β∇θf**θ'**(inputb)

[https://arxiv.org/abs/1703.03400](url)

The source code of model-agnostic meta learning from github is below:

           for j in range(num_updates - 1):
                    loss = self.loss_func(self.forward(inputa, fast_weights, reuse=True), labela)
                    grads = tf.gradients(loss, list(fast_weights.values()))
                    if FLAGS.stop_grad:
                        grads = [tf.stop_gradient(grad) for grad in grads]
                    gradients = dict(zip(fast_weights.keys(), grads))
                    fast_weights = dict(zip(fast_weights.keys(), [fast_weights[key] - self.update_lr*gradients[key] for key in fast_weights.keys()]))
                    output = self.forward(inputb, fast_weights, reuse=True)
                    task_outputbs.append(output)
                    task_lossesb.append(self.loss_func(output, labelb))
         
            task_output = [task_outputa, task_outputbs, task_lossa, task_lossesb]
[https://github.com/cbfinn/maml/blob/master/maml.py](url)

I'd like to know in tensorpack and using trainers,
how can I access model weights θ between the training iteration and forward with inputa, 
compute the gradient decent and adapted as  θ' 
and update the model weight θ using the task_lossesb as we used to do at the end of an iteration.

**Comment by ppwwyyxx** [comment]
Please see https://tensorpack.readthedocs.io/tutorial/training-interface.html, https://tensorpack.readthedocs.io/tutorial/extend/trainer.html.

To answer your question: `ModelDesc` and the existing trainers are all for single-cost optimization. So you can (1): formulate your task as a single-cost optimization or (2) write your own trainer (see tutorial above).

It appears to me that your problem can be formulated as a single-cost optimization problem. You just need to implement the function `f(inputs, weights) -> cost` in your equation, and your final cost is just f(θ - α∇θfθ), as your equation suggests.

**Comment by john81923** [comment]
Thanks for your reply. 
Yes, It can be formulated as a single-cost optimization problem as you mentioned.
 To implement function `f(inputs, weights) -> cost` is what i want to achieve here.

But, My Technical difficulty is that how to implement the function practically.
such as  accessed all the weights through tensorpack interface,
and pass it down to my model.

**Comment by ppwwyyxx** [comment]
Tensorpack is unrelated to how you implement your model. You can use any tensorflow symbolic functions that computes the output from the input.

You'll not be able to use "layer"-like abstractions because they do not provide you an interface to use different weights. You'll need to write the model on your own.

**Comment by john81923** [comment]
I try to adapt model-agnostic meta learning to tensorpack example FasterRCNN.
So, you mean that I can not use the "layer"  in example, I should rewrite the model on my own ?

**Comment by john81923** [comment]
Hi, I've got further questions.
Now, I'm writing my own functions. 
using `tf.nn.conv2D` instead of tensorpack` Conv2D`, so I can forwardly pass weights into layers.

here's what I do in tensorpack/example/FasterRCNN/train.py ,

`class ResNetC4Model(DetectionModel): `

    def construct_weights( self, backbone_dir='/project/project-mira6/mcs/fasterRCNNmodels/ImageNet-ResNet50.npz'):
        '''must call after '''
        # resnet variable 
        backbone_weights = np.load( backbone_dir ) 
        weights = {}
        weights['conv0/W'] = tf.Variable( backbone_weights['conv0/W:0'], name='conv0/W')
        weights['conv0/beta'] = tf.Variable( backbone_weights['conv0/bn/beta:0'], name='conv0/beta')
        weights['conv0/gamma'] = tf.Variable( backbone_weights['conv0/bn/gamma:0'], name='conv0/gamma')
        RESNET_NUM_BLOCK = [3, 4, 6, 3] 
        for g in [0,1,2,3]:
            for blc in range( RESNET_NUM_BLOCK[g]):
                for cv in np.arange(1,4):
                    weights[f'group{g}/block{blc}/conv{cv}/W'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/conv{cv}/W:0'],name=f'group{g}/block{blc}/conv{cv}/W' )
                    weights[f'group{g}/block{blc}/conv{cv}/gamma'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/conv{cv}/bn/gamma:0'],name=f'group{g}/block{blc}/conv{cv}/gamma' )
                    weights[f'group{g}/block{blc}/conv{cv}/beta'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/conv{cv}/bn/beta:0'], name=f'group{g}/block{blc}/conv{cv}/beta' )

                if blc == 0:
                    weights[f'group{g}/block{blc}/convshortcut/W'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/convshortcut/W:0'],name=f'group{g}/block{blc}/convshortcut/W' )
                    weights[f'group{g}/block{blc}/convshortcut/gamma'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/convshortcut/bn/gamma:0'],name=f'group{g}/block{blc}/convshortcut/gamma' )
                    weights[f'group{g}/block{blc}/convshortcut/beta'] = tf.Variable( backbone_weights[f'group{g}/block{blc}/convshortcut/bn/beta:0'],name=f'group{g}/block{blc}/convshortcut/beta' )
        # rpn
        weights['rpn/conv0/W']=tf.get_variable('rpn/conv0/W', shape=[3,3,1024,1024], initializer=tf.random_normal_initializer(stddev=0.01))
        weights['rpn/conv0/b']=tf.get_variable('rpn/conv0/b', shape=[1024], initializer=tf.zeros_initializer() )
        weights['rpn/class/W']=tf.get_variable('rpn/class/W', shape=[1,1,1024,15], initializer=tf.random_normal_initializer(stddev=0.01))
        weights['rpn/class/b']=tf.get_variable('rpn/class/b', shape=[15], initializer=tf.zeros_initializer() )
        weights['rpn/box/W']=tf.get_variable('rpn/box/W', shape=[1,1,1024,60], initializer=tf.random_normal_initializer(stddev=0.01))
        weights['rpn/box/b']=tf.get_variable('rpn/box/b', shape=[60], initializer=tf.zeros_initializer() )

        # frcnn FC layer
        weights['fastrcnn/class/W']=tf.get_variable('fastrcnn/class/W', shape=[2048, 81], initializer=tf.random_normal_initializer(stddev=0.01))
        weights['fastrcnn/class/b']=tf.get_variable('fastrcnn/class/b', shape=[81], initializer=tf.zeros_initializer() )
        weights['fastrcnn/box/W']=tf.get_variable('fastrcnn/box/W', shape=[2048, 324], initializer=tf.random_normal_initializer(stddev=0.01))
        weights['fastrcnn/box/b']=tf.get_variable('fastrcnn/box/b', shape=[324], initializer=tf.zeros_initializer() )
    
        return weights

    def build_graph(self, *inputs):
        inputs = dict(zip(self.input_names, inputs))
        is_training = get_current_tower_context().is_training
        image = self.preprocess(inputs['image'])     # 1CHW

        with tf.variable_scope('Meta_FasterRCNN', reuse=None) as training_scope:
            if 'weights' in dir(self):
                training_scope.reuse_variables()
                weights = self.weights
            else:
                # Define the weights
                self.weights = weights = self.construct_weights()
        
            
            featuremap = resnet_c4_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCK[:3], weights)`

I load the ResNet50.npz into tf.Variables and save it in a dictionary name `weights` , and pass it through my model in order to accomplish the function `f(inputs, weights) -> cost`

but, I'm have fatal errors such as : 

> [0107 03:39:27 @training.py:296] WRN [ReplicatedTrainer] Do not know how to sync variable 'tower0/Meta_FasterRCNN/conv0/W:0' across GPUs. Reason: Name should not have prefix 'tower0' in this trainer! This variable is trainable, so this is probably a fatal error.
[0107 03:39:27 @training.py:296] WRN [ReplicatedTrainer] Do not know how to sync variable 'tower0/Meta_FasterRCNN/conv0/beta:0' across GPUs. Reason: Name should not have prefix 'tower0' in this trainer! This variable is trainable, so this is probably a fatal error.

at the end I've got error:

> Traceback (most recent call last):
  File "train.py", line 592, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/interface.py", line 95, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/base.py", line 319, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/base.py", line 289, in train
    self.setup_callbacks(callbacks, monitors)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/base.py", line 189, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "train.py", line 422, in _setup_graph
    self.predictors = [self._build_coco_predictor(k % num_gpu) for k in range(self.num_predictor)]
  File "train.py", line 422, in <listcomp>
    self.predictors = [self._build_coco_predictor(k % num_gpu) for k in range(self.num_predictor)]
  File "train.py", line 436, in _build_coco_predictor
    graph_func = self.trainer.get_predictor(self._in_names, self._out_names, device=idx)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/tower.py", line 135, in get_predictor
    output_tensors = tower.get_tensors(output_names)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 405, in get_tensors
    return [self.get_tensor(name) for name in names]
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 405, in <listcomp>
    return [self.get_tensor(name) for name in names]
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 388, in get_tensor
    ret = get_op_or_tensor_by_name(name_with_ns)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/tfutils/common.py", line 134, in get_op_or_tensor_by_name
    return f(name)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/tfutils/common.py", line 129, in f
    return G.get_tensor_by_name(n)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3207, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3077, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'tower-pred-0/output/boxes:0' refers to a Tensor which does not exist. The operation, 'tower-pred-0/output/boxes', does not exist in the graph."
MultiProcessMapDataZMQ successfully cleaned-up.

**Comment by ppwwyyxx** [comment]
>  Do not know how to sync variable 'tower0/Meta_FasterRCNN/conv0/beta:0' across GPUs. Reason: Name should not have prefix 'tower0' in this trainer! This variable is trainable, so this is probably a fatal error.

As the error log says, you're not allowed to create a variable whose name starts with "tower0". This name is reserved for tensorpack to use. https://tensorpack.readthedocs.io/tutorial/trainer.html#rules-of-tower-function

> File "train.py", line 422, in _setup_graph
self.predictors = [self._build_coco_predictor(k % num_gpu) for k in range(self.num_predictor)]
File "train.py", line 422, in 
self.predictors = [self._build_coco_predictor(k % num_gpu) for k in range(self.num_predictor)]
File "train.py", line 436, in _build_coco_predictor
...
KeyError: "The name 'tower-pred-0/output/boxes:0' refers to a Tensor which does not exist. The operation, 'tower-pred-0/output/boxes', does not exist in the graph.

As the error log says, your callbacks needs the tensor "output/boxes:0" to do inference but this tensor does not exist in your graph.

**Comment by john81923** [comment]
As the Rules of Tower Function has mentioned:
> The creation of any trainable variables must respect reuse variable scope. To respect variable reuse (i.e. sharing), use tf.get_variable instead of tf.Variable in the function.

So, I am not able to use tf.Variable in the case. 
however, how can I initial my training variable  `weights[f'group{g}/block{blc}/conv{cv}/W']` with ResNet pre-trained weights using tf.get_variable  ?

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model-to-a-session

**Comment by ppwwyyxx** [comment]
The above was the standard way to load checkpoints, which is used by all the examples. If you like you can also just do `get_variable(initializer=tf.constant(...))`.

**Comment by john81923** [comment]
Thank you , it works!

I  have another question,
In meta-learning, there's` input_a `and `inputs_b` in each training iterations.
computing losses such as `loss( inputs_a, label_a)` and  `loss( inputs_b, label_b)` 
but  `get_train_dataflow` in FasterRCNN pass one image in each training iterations.

Thus, how can I get two or more data and labels from dataflow in each iterations

**Comment by john81923** [comment]
why would I get `WRN No gradient w.r.t 106 trainable variables: `when training?

> [0108 00:36:35 @gradproc.py:77] WRN No gradient w.r.t 106 trainable variables: conv0/bn/beta, conv0/bn/gamma, group0/block0/conv1/bn/gamma, group0/block0/conv1/bn/beta, group0/block0/conv2/bn/gamma, group0/block0/conv2/bn/beta, group0/block0/conv3/bn/gamma, group0/block0/conv3/bn/beta, group0/block0/convshortcut/bn/gamma, group0/block0/convshortcut/bn/beta, group0/block1/conv1/bn/gamma, group0/block1/conv1/bn/beta, group0/block1/conv2/bn/gamma, group0/block1/conv2/bn/beta, group0/block1/conv3/bn/gamma, group0/block1/conv3/bn/beta, group0/block2/conv1/bn/gamma, group0/block2/conv1/bn/beta, group0/block2/conv2/bn/gamma, group0/block2/conv2/bn/beta, group0/block2/conv3/bn/gamma, group0/block2/conv3/bn/beta, group1/block0/conv1/bn/gamma, group1/block0/conv1/bn/beta, group1/block0/conv2/bn/gamma, group1/block0/conv2/bn/beta, group1/block0/conv3/bn/gamma, group1/block0/conv3/bn/beta, group1/block0/convshortcut/bn/gamma, group1/block0/convshortcut/bn/beta, group1/block1/conv1/bn/gamma, group1/block1/conv1/bn/beta, group1/block1/conv2/bn/gamma, group1/block1/conv2/bn/beta, group1/block1/conv3/bn/gamma, group1/block1/conv3/bn/beta, group1/block2/conv1/bn/gamma, group1/block2/conv1/bn/beta, group1/block2/conv2/bn/gamma, group1/block2/conv2/bn/beta, group1/block2/conv3/bn/gamma, group1/block2/conv3/bn/beta, group1/block3/conv1/bn/gamma, group1/block3/conv1/bn/beta, group1/block3/conv2/bn/gamma, group1/block3/conv2/bn/beta, group1/block3/conv3/bn/gamma, group1/block3/conv3/bn/beta, group2/block0/conv1/bn/gamma, group2/block0/conv1/bn/beta, group2/block0/conv2/bn/gamma, group2/block0/conv2/bn/beta, group2/block0/conv3/bn/gamma, group2/block0/conv3/bn/beta, group2/block0/convshortcut/bn/gamma, group2/block0/convshortcut/bn/beta, group2/block1/conv1/bn/gamma, group2/block1/conv1/bn/beta, group2/block1/conv2/bn/gamma, group2/block1/conv2/bn/beta, group2/block1/conv3/bn/gamma, group2/block1/conv3/bn/beta, group2/block2/conv1/bn/gamma, group2/block2/conv1/bn/beta, group2/block2/conv2/bn/gamma, group2/block2/conv2/bn/beta, group2/block2/conv3/bn/gamma, group2/block2/conv3/bn/beta, group2/block3/conv1/bn/gamma, group2/block3/conv1/bn/beta, group2/block3/conv2/bn/gamma, group2/block3/conv2/bn/beta, group2/block3/conv3/bn/gamma, group2/block3/conv3/bn/beta, group2/block4/conv1/bn/gamma, group2/block4/conv1/bn/beta, group2/block4/conv2/bn/gamma, group2/block4/conv2/bn/beta, group2/block4/conv3/bn/gamma, group2/block4/conv3/bn/beta, group2/block5/conv1/bn/gamma, group2/block5/conv1/bn/beta, group2/block5/conv2/bn/gamma, group2/block5/conv2/bn/beta, group2/block5/conv3/bn/gamma, group2/block5/conv3/bn/beta, group3/block0/conv1/bn/gamma, group3/block0/conv1/bn/beta, group3/block0/conv2/bn/gamma, group3/block0/conv2/bn/beta, group3/block0/conv3/bn/gamma, group3/block0/conv3/bn/beta, group3/block0/convshortcut/bn/gamma, group3/block0/convshortcut/bn/beta, group3/block1/conv1/bn/gamma, group3/block1/conv1/bn/beta, group3/block1/conv2/bn/gamma, group3/block1/conv2/bn/beta, group3/block1/conv3/bn/gamma, group3/block1/conv3/bn/beta, group3/block2/conv1/bn/gamma, group3/block2/conv1/bn/beta, group3/block2/conv2/bn/gamma, group3/block2/conv2/bn/beta, group3/block2/conv3/bn/gamma, group3/block2/conv3/bn/beta

**Comment by ppwwyyxx** [comment]
You can modify the dataflow so that it produces two datapoints at a time.

**Comment by john81923** [comment]
Can you tell me how to modify the dataflow please. I have no idea.

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/extend/dataflow.html#more-data-processing

**Comment by ppwwyyxx** [comment]
```python
class ProcessingDataFlow(DataFlow):
  def __init__(self, ds):
    self.ds = ds
    
  def reset_state(self):
    self.ds.reset_state()

  def __iter__(self):
    a = {}
    for datapoint in self.ds:
      if a:
          a.update({k + '-2': v for k, v in datapoint.items()})
          yield a
          a = {}
      else:
          a.update(datapoint)

```

**Comment by john81923** [comment]
Thank you helps a lot
 I'd like to know according to code below:

 `       class DataFromList(RNGDataFlow):

    def __init__(self, lst, shuffle=True):
        """
        Args:
            lst (list): input list. Each element is a datapoint.
            shuffle (bool): shuffle data.
        """
        super(DataFromList, self).__init__()
        self.lst = lst
        self.shuffle = shuffle

    def __len__(self):
        return len(self.lst)

    def __iter__(self):
        if not self.shuffle:
            for k in self.lst:
                yield k
        else:
            idxs = np.arange(len(self.lst))
            self.rng.shuffle(idxs)
            for k in idxs:
                yield self.lst[k]`

Will the data list shuffle every training iteration?

**Comment by ppwwyyxx** [comment]
```python
        idxs = np.arange(len(self.lst))
        self.rng.shuffle(idxs)
        for k in idxs:
            yield self.lst[k]`
```
You can see from the code above that it will produce everything in the list after one shuffle.

This has nothing to do with training iteration because dataflow is unrelated to training.

**Comment by john81923** [comment]
So, will it shuffle again after it produce everything in the list?

**Comment by ppwwyyxx** [comment]
> So, will it shuffle again after it produce everything in the list?

Yes. That's literally what the code says. You can find tutorial online if you don't understand what "yield" means.

> such as, after training an epoch, will it shuffle the list again

That depends on your definition of "epoch". Dataflow knows nothing about training and nothing about "epoch".

**Comment by john81923** [comment]
Hi, I'd like to know how to implement an Update_Weights function : 
`weights = Update_Weights( loss, weights)` 
base on the optimizer of FasterRCNN below
`# optimizer function

     def optimizer(self):

        lr = tf.get_variable('learning_rate', initializer=0.003, trainable=False)
        tf.summary.scalar('learning_rate-summary', lr)

        # The learning rate is set for 8 GPUs, and we use trainers with average=False.
        lr = lr / 8.
        opt = tf.train.MomentumOptimizer(lr, 0.9)
        if cfg.TRAIN.NUM_GPUS < 8:
            opt = optimizer.AccumGradOptimizer(opt, 8 // cfg.TRAIN.NUM_GPUS)

        return opt`

thank you

**Comment by john81923** [comment]
sorry, I did not make my question  clear.
let me define it again.

My target is to update weight two times in an iteration. So here's what I do
I'm using a function that feeds inputs and weights and  return cost  `f(inputs, weights) -> cost` 
computes the gradients as ∇θ , learning rate as `lr`
Therefore, my final cost would be `f(inputs,  θ - lr*∇θ )` 

So, I have to access the accumulation  and the learning rate for my final cost.
Since the optimizer is defined in `class DetectionModel(ModelDesc):   def optimizer(self):` ,
is there any way I can access the slots and learning rate of optimizer through the tensorpack interface?

**Comment by john81923** [comment]
I tried computing gradients before final cost, but having error:
> Traceback (most recent call last):
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 551, in gradients
    grad_fn = ops.get_gradient_function(op)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2134, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: CropAndResizeGradImage

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 558, in <module>
>     launch_train_with_config(traincfg, trainer)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/interface.py", line 85, in launch_train_with_config
>     model._build_graph_get_cost, model.get_optimizer)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
>     return func(*args, **kwargs)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/tower.py", line 203, in setup_graph
>     train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 172, in _setup_graph
>     self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 222, in build
>     use_vs=[False] + [True] * (len(self.towers) - 1))
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
>     ret.append(func())
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorpack/train/tower.py", line 246, in get_grad_fn
>     aggregation_method=self.AGGREGATION_METHOD)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
>     colocate_gradients_with_ops=colocate_gradients_with_ops)
>   File "/auto/master05/john81923/ENV/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 555, in gradients
>     (op.name, op.type))
> LookupError: No gradient defined for operation 'tower0/gradients/tower0/roi_align/crop_and_resize/CropAndResize_grad/CropAndResizeGradImage' (op type: CropAndResizeGradImage)

why is the name 'tower' after 'tower' such as  'tower0/gradients/tower0/***'

**Comment by ppwwyyxx** [comment]
If you want to obtain the gradients you can just call `tf.gradients`. The optimizer interface seems not useful to you in this case.
The name is generated automatically by tensorflow and is you don't have to care about that.

**Comment by john81923** [comment]
Thanks for your kindness reply, 

yes, `tf.gradients` is what I used here
`grads = tf.gradients(total_cost, list(weights.values()))`

but it ends up with error :
> LookupError: No gradient defined for operation 'tower0/gradients/tower0/roi_align/crop_and_resize/CropAndResize_grad/CropAndResizeGradImage' (op type: CropAndResizeGradImage)

please help

**Comment by ppwwyyxx** [comment]
`CropAndResizeGradImage` is the gradient of `CropAndResize` and the error is saying tensorflow does not know how to compute the gradient of `CropAndResizeGradImage` which is required by your method

**Comment by john81923** [comment]
thank you for your reply,
Do you have any ideas why does this error pop-up after I add tf.gradients in my method?
cause it doesn't happen before I did this

**Comment by ppwwyyxx** [comment]
If you didn't use `tf.gradients` then your forward pass won't contain the `CropAndResizeGradImage` operation.

**Comment by john81923** [comment]
Thank you,  I've been searching for a while still not found any useful solutions.

Is there a way that I can fix this error ?

cause I am not quite sure why does it contain the` CropAndResizeGradImage` operation when I use `tf.gradients` and why doesn't it contained when not using `tf.gradients`

**Comment by ppwwyyxx** [comment]
The formula you wrote in your original question requires second order gradient of `f`.
`f` contains `CropAndResize` because `f` is a faster r-cnn.
This is a tensorflow question and unrelated to tensorpack. You can solve it by implementing the tensorflow operation that computes the second order gradient.
