### ISSUE TITLE
FasterRCNN Resnet50 training error with new restructured code commits (including commits today)

### ISSUE THREAD

**Issue by jwnsu** [tensorpack/tensorpack#1033]
Updated from recent code changes in tensorpack/FasterRCNN. A previously working training (on own dataset) is now giving following error:
`Traceback (most recent call last):
  File "./train.py", line 576, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/interface.py", line 84, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/trainers.py", line 193, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 225, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 121, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 116, in call_for_each_tower
    ret.append(func())
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 266, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 245, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 286, in __call__
    output = self._tower_fn(*args)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 262, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "./train.py", line 86, in build_graph
    features = self.backbone(image)
  File "./train.py", line 247, in backbone
    c2345 = resnet_fpn_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCKS)
  File "/home/dsu/ai/tfpack/examples/FasterRCNN/config.py", line 22, in __getattr__
    raise AttributeError(name)
AttributeError: RESNET_NUM_BLOCKS
`
Cannot figure out the error quickly.

If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
./train.py --gpu 0,1,2,3,4,5,6,7 --load data/ImageNet-ResNet50.npz --logdir output/fr50

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
own dataset with coco format. The training has passed dataset loading phase successfully.

(3) **If not using examples, tell us what you did here:**

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
see above
It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher accuracy, only in one of the two conditions can we help with it:
(1) You're unable to match the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to get high accuracy is a machine learning question and is
not our responsibility to figure out.

### 4. Your environment:
  + Python version: 3.5.2
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.  1.12.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`. latest 0.9.1
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used. 8 1080 Ti GPUs, ubuntu 16.04.5

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
`examples/FasterRCNN` is not a library. `examples/FasterRCNN` is an example, with multiple files. 
You cannot expect things to work if you combine an old version of one file with a newer version of another file.

**Comment by jwnsu** [comment]
Thx for quick response, all files in examples/FasterRCNN were updated/refreshed (have followed this code repository for past a couple of years).

**Comment by ppwwyyxx** [comment]
> A previously working training (on own dataset) 

I assume this means your own old code?

Does the code in tensorpack by itself (without modifications, trained on COCO) work?

**Comment by jwnsu** [comment]
all codes are directly from tensorpack, our changes are limited to dataset configuration only (our own dataset are coco format too, so changes are only to COCO_id_to_category_id and class_names). 

RESNET_NUM_BLOCKS in config.py is intact as latest tensorpack config.py file.

**Comment by jwnsu** [comment]
ok, we did a fresh pull from tensorpack, then applies our changes on top, the issue now goes away.
