### ISSUE TITLE
Faster RCNN `dataset` script cannot load custom datasets

### ISSUE THREAD

**Issue by xinli94** [tensorpack/tensorpack#1038]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
- Faster RCNN

- CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO mpirun -np 1 --output-filename tmp ./train.py  --logdir tmp --config MODE_MASK=False MODE_FPN=True TRAINER=horovod  |& grep -v "Read -1"

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
- Custom dataset

(3) **If not using examples, tell us what you did here:**

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.
```
Traceback (most recent call last):
  File "./train.py", line 472, in <module>
    train_dataflow = get_train_dataflow()
  File "/workspace/xli/tensorpack/examples/FasterRCNN/data.py", line 310, in get_train_dataflow
    roidbs = DetectionDataset().load_training_roidbs(TAG)
  File "/workspace/xli/tensorpack/examples/FasterRCNN/dataset.py", line 231, in load_training_roidbs
    cfg.DATA.BASEDIR, cfg.DATA.TRAIN, add_gt=True, add_mask=cfg.MODE_MASK)
  File "/workspace/xli/tensorpack/examples/FasterRCNN/dataset.py", line 184, in load_many
    ret.extend(coco.load(add_gt, add_mask=add_mask))
  File "/workspace/xli/tensorpack/examples/FasterRCNN/dataset.py", line 98, in load
    self._add_detection_gt(img, add_mask)
  File "/workspace/xli/tensorpack/examples/FasterRCNN/dataset.py", line 154, in _add_detection_gt
    self.COCO_id_to_category_id[obj['category_id']]
KeyError: 12
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5687,1],0]
  Exit code:    1
```

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

- Just want to let you know, it looks like line 25 ~ 31: `https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/dataset.py#L25`
It breaks the loading for a custom dataset.
It is not hard to fix on my end, just wondering if there will be any official fix soon!

### 4. Your environment:
+ Python version: - 3.5.2
+ TF version: python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'. - v1.12.0-0-ga6d8ffae09 1.12.0
+ Tensorpack version: python -c 'import tensorpack; print(tensorpack.__version__);'.
You can install Tensorpack master by pip install -U git+https://github.com/ppwwyyxx/tensorpack.git
and see if your issue is already solved. - 0.9.0.1
+ If you're not using tensorpack under a normal command line shell (e.g.,
using an IDE or jupyter notebook), please retry under a normal command line shell.
+ Hardware information, e.g. number of GPUs used. - 4 TITAN Xp

**Comment by ppwwyyxx** [comment]
If you're using a custom dataset in COCO format, modify the class `COCODetection` to make it work. You may need to change the dict `COCO_id_to_category_id` to an identity mapping.
