### ISSUE TITLE
getting warning "has invalid polygons!"

### ISSUE THREAD

**Issue by cpoptic** [tensorpack/tensorpack#1041]
I've adopted my dataset to COCO format.  The dataset consists of rectangular objects.  So I have set the 'segmentation' field to be the same 4 coordinates of the rectangular bounding box.  I keep getting Warning "Image ... has invalid polygons!"  Here are three object annotation examples:

obj {'id': 55468, 'image_id': '1541715161404', 'category_id': 9, 'bbox': [0, 47, 1024, 706], 'cat': 'dog', 'area': 674816, 'segmentation': [[0, 47, 1024, 706]], 'iscrowd': 0}
obj {'id': 55469, 'image_id': '1541715161404', 'category_id': 1, 'bbox': [4, 69, 1020, 706], 'cat': 'cat', 'area': 647192, 'segmentation': [[4, 69, 1020, 706]], 'iscrowd': 0}
obj {'id': 55470, 'image_id': '1541715161404', 'category_id': 1, 'bbox': [7, 72, 1017, 706], 'cat': 'cat', 'area': 640340, 'segmentation': [[7, 72, 1017, 706]], 'iscrowd': 0}

This looks like valid polygon coordinates.  Any idea what could cause this error?

**Comment by ppwwyyxx** [comment]
Segmentation expects a different format (x1, y1, x2, y2 ,x3, y3 ...). The documentation should have the details

**Comment by ppwwyyxx** [comment]
Closing as this issue is about COCO format and not very related to tensorpack.
