### ISSUE TITLE
How to use the model to train another format annotations, not json.

### ISSUE THREAD

**Issue by wanghanlin14250** [tensorpack/tensorpack#1044]
+ Note that you can implement a lot of features by extending Tensorpack
  (See http://tensorpack.readthedocs.io/en/latest/tutorial/index.html#extend-tensorpack).
  It does not have to be added to Tensorpack unless you have a good reason.

+ "Could you improve/implement an example/paper ?"
  -- The answer is: we have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you, unless it demonstrates 
  some Tensorpack features not yet demonstrated in the existing examples.
  If you don't know how to do something yourself, you may ask a usage question.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md
