### ISSUE TITLE
Fail to Convert Tensorpack Trained Models to .npz Model File

### ISSUE THREAD

**Issue by xinya-liu** [tensorpack/tensorpack#1045]
Hi there,

Hope someone could help me solve this problem I met while using dump-model-params.py file. I tried to convert the tensorpack trained Faster-RCNN models to .npz file format, but the .npz file I got was way too small than I expected (only 22 bytes for a checkpoint), and could't be used in further steps. I'm wondering if there's any error with the code or the original files. Can you offer some suggestions on how to solve this conversion problem? Thanks for your help!
I pasted the changed dump-model-params.py file I used below.

if __name__ == '__main__':
    
    meta0 = 'directory for local .meta file'
    input0 = 'directory for a model at one checkpoint'
    output0 = 'file_name'
    print('started.............')

    # this script does not need GPU
    os.environ['CUDA_VISIBLE_DEVICES'] = ''

    tf.train.import_meta_graph(meta0, clear_devices=True)

    print('loaded meta.............')

    # loading...
    if input0.endswith('.npz'):
        dic = np.load(input0)
    else:
        dic = varmanip.load_chkpt_vars(input0)
    dic = {get_op_tensor_name(k)[1]: v for k, v in six.iteritems(dic)}

    print('loaded input.............')

    # save variables that are GLOBAL, and either TRAINABLE or MODEL
    var_to_dump = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
    var_to_dump.extend(tf.get_collection(tf.GraphKeys.MODEL_VARIABLES))
    assert len(set(var_to_dump)) == len(var_to_dump), "TRAINABLE and MODEL variables have duplication!"
    globvarname = [k.name for k in tf.global_variables()]
    var_to_dump = set([k.name for k in var_to_dump if k.name in globvarname])

    for name in var_to_dump:
        assert name in dic, "Variable {} not found in the model!".format(name)

    dic_to_dump = {k: v for k, v in six.iteritems(dic) if k in var_to_dump}
    varmanip.save_chkpt_vars(dic_to_dump, output0)

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

Preliminary suggestions:
Check your checkpoint by `tf.train.NewCheckpointReader`
Check what your code has loaded by printing

**Comment by tutu1234** [comment]
Please print the the keys and their shape of var_to_dump, Maybe you don't import the meta and load ckpt  correctly.

**Comment by ppwwyyxx** [comment]
Closing due to no response.
