### ISSUE TITLE
FasterRCNN: how can i print out metrics (total_loss, bbox_loss, label) metrics on evaluation data 

### ISSUE THREAD

**Issue by ColonelKassad** [tensorpack/tensorpack#1052]
I am modifying the FasterRCNN example for my custom dataset which is NOT in Coco-format.
Then the evaluation is ran (say every 25 epochs) I'd like to see the loss-metrics computed on the evaluation dataset. I cannot use COCODetection because my annotations are in different format.
Any recommendations?
Thanks

**Comment by ppwwyyxx** [comment]
duplicate of #1004.

**Comment by ColonelKassad** [comment]
Thanks
