### ISSUE TITLE
AssertionError in LinearWrap when using Deconv2D

### ISSUE THREAD

**Issue by SNLan** [tensorpack/tensorpack#1053]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(3) **If not using examples, tell us what you did here:**
           l =  (LinearWrap(features)
                 .Deconv2D('deconv1', 512)
                 .Dropout('drop1')
                 .Deconv2D('deconv2', 256)
                 .Dropout('drop2')
                 .Deconv2D('deconv3', 128)
                 .Dropout('drop3')())

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

AssertionError: Calling LinearWrap.Deconv2D: neither a layer nor 'tf'! Did you forget to extract tensor from LinearWrap?

### 3. What you expected, if not obvious.

If you expect higher accuracy, only in one of the two conditions can we help with it:
(1) You're unable to match the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

When using Deconv2D in LinearWrap, it produces such error. But when replacing Deconv2D with Conv2DTranspose, the error is gone. 
If Deconv2D is an official function in tensorpack, I think it should also be supported in LinearWrap.

### 4. Your environment:
  + Python version:
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used.

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
Will push a fix soon. Note that `Deconv2D` is not a public interface and you should use `Conv2DTranspose` instead: https://tensorpack.readthedocs.io/modules/models.html
