### ISSUE TITLE
Resume model failed with Hovorod

### ISSUE THREAD

**Issue by YongyiTang92** [tensorpack/tensorpack#1054]
I am using tensorpack and hovorod for distributedd running. I want to resume the previous checkpoint, while I found unexpected runing with 'set_logger_dir'.

At first I follow this code https://github.com/tensorpack/benchmarks/blob/0bb41fa37a52c0430ea061dd2a12d353d35534fe/ResNet-Horovod/imagenet-resnet-horovod.py#L171 to initialize running. 
To resume running, I replace TrainConfig with AutoResumeTrainConfig and change the flag 'd' to 'k' as:

```
def get_config(model, data):
    ...
    return AutoResumeTrainConfig(
        model=model,
        data=data,
        callbacks=callbacks,
        steps_per_epoch=steps_per_epoch,
        max_epoch=FLAGS.num_epoch,
    ) 

...
# in main:
    hvd.init()
    logdir = os.path.join(FLAGS.model, 'train_log', 'Horovod-{}GPUs-{}Batch'.format(hvd.size(),FLAGS.batch_size))

    if hvd.rank() == 0:
        os.system("nvidia-smi")
        logger.set_logger_dir(logdir, 'k')
```

However, it will cause those hvd.rank()>0 cannot find the json file, and resulting following errors:

```
Traceback (most recent call last):
  File "./train.py", line 210, in <module>
    config = get_config(model, dataset)
  File "./train.py", line 165, in get_config
    max_epoch=FLAGS.num_epoch,
  File "/data1/rextang/.local/lib/python2.7/site-packages/tensorpack/train/config.py", line 215, in __init__
    last_epoch = self._get_last_epoch()
  File "/data1/rextang/.local/lib/python2.7/site-packages/tensorpack/train/config.py", line 237, in _get_last_epoch
    return JSONWriter.load_existing_epoch_number()
  File "/data1/rextang/.local/lib/python2.7/site-packages/tensorpack/callbacks/monitor.py", line 322, in load_existing_epoch_number
    stats = JSONWriter.load_existing_json()
  File "/data1/rextang/.local/lib/python2.7/site-packages/tensorpack/callbacks/monitor.py", line 308, in load_existing_json
    fname = os.path.join(dir, JSONWriter.FILENAME)
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
So, I place 'logger.my_set_logger_dir(logdir, 'k')' outside if hvd.rank() == 0:.
But in 'set_logger_dir', it mv the 'log.log' file in each hvd.rank() 
https://github.com/tensorpack/tensorpack/blob/master/tensorpack/utils/logger.py#L79
resulting the 'log.log' file in checkpoint dir is unexpected renamed, and others hvd.rank() can not find this file resulting error.

I finally got it fix by replacing  shutil.move(path, backup_name) to shutil.copy(path, backup_name). But am I do it in a collect way?

**Comment by ppwwyyxx** [comment]
Being able to automatically resume requires logging directory. Using horovod requires different logging directory for each process. So it appears there is no simple solution to this.

What I did is to manually set the epoch and load from a given checkpoint

**Comment by ppwwyyxx** [comment]
In all processes:
`starting_epoch=[the next epoch]`

In main processes or all processes (doesn't matter):
`sessinit=[load your model]`

These will do what `AutoResumeTrainConfig` is supposed to.

**Comment by ppwwyyxx** [comment]
(The document of `AutoResumeTrainConfig` was now updated to reflect this
