### ISSUE TITLE
Please review the following two lines.

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1057]
Hi, the `result` in line 164 should be a `dict` and `k` in line 166 is not defined:
https://github.com/tensorpack/tensorpack/blob/3ad0ed00a183f13563eb9b2568a8de57c148cbd3/tensorpack/dataflow/common.py#L163-L171

**Comment by ppwwyyxx** [comment]
dict is still not supported in many dataflows so I haven't touched these codepath yet. Thanks for finding the bug!
