### ISSUE TITLE
Type Hints

### ISSUE THREAD

**Issue by kkihara** [tensorpack/tensorpack#1060]
Is there any plan for supporting type hinting? I think this would be particularly useful as a generic type in DataFlows.

**Comment by ppwwyyxx** [comment]
It would be great to have. But I'm not sure how elegant it will be given that we still support Python 2. Contributions/suggestions are very welcome.

**Comment by kkihara** [comment]
Ah I see. I'd be happy to contribute, but that does seem complicated while supporting Python 2.
