### ISSUE TITLE
spelling error in R101-FPN (From Scratch) config

### ISSUE THREAD

**Issue by zhujl3** [tensorpack/tensorpack#1061]
When I evaluate R101-FPN (From Scratch) and use the official config:
MODE_FPN=True FPN.CASCADE=True
**BACKBONE.RESNET_NUM_BLOCKS**=[3,4,23,3]
FPN.NORM=GN BACKBONE.NORM=GN
FPN.FRCNN_HEAD_FUNC=fastrcnn_4conv1fc_gn_head
FPN.MRCNN_HEAD_FUNC=maskrcnn_up4conv_gn_head
PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800]
TRAIN.LR_SCHEDULE=[1500000,1580000,1620000]
BACKBONE.FREEZE_AT=0

I found that there is a **precision lost(AP=0.28, rather than ap=0.47)** at loaded model using evaluate function. And I notice that there are some params not loaded by graph:

group2/block10/conv1/W:0, group2/block10/conv1/gn/beta:0, group2/block10/conv1/gn/gamma:0, group2/block10/conv2/W:0 ...

These params are related with **resnet-101**. When I check the config, I found that the config text is confused BACKBONE.RESNET_NUM_BLOCKS with BACKBONE.RESNET_NUM_BLOCK

**So I change BACKBONE.RESNET_NUM_BLOCKS to BACKBONE.RESNET_NUM_BLOCK, and it works.**

**Comment by ppwwyyxx** [comment]
You're using new version of the command line arguments with old version of code.
The new version of code uses `RESNET_NUM_BLOCKS` only and has no issues.
