### ISSUE TITLE
Potential Issues of Batch Renormalization

### ISSUE THREAD

**Issue by scott89** [tensorpack/tensorpack#1065]
Hi! [Current implementation](https://github.com/tensorpack/tensorpack/blob/3f238a015b941041e58ed43e63d5306dbae979fc/tensorpack/models/batch_norm.py#L250) of batch renormalization puts scale and shift before renorm correction, which is inconsistent with the original paper. I think this might be a potential bug.

**Comment by ppwwyyxx** [comment]
You're not pointing at the [current implementation](https://github.com/tensorpack/tensorpack/blob/master/tensorpack/models/batch_norm.py)

**Comment by scott89** [comment]
Oh, I see. It's a historical commit. Thanks.
