### ISSUE TITLE
How to train/fine-tune flownet with new dataset?

### ISSUE THREAD

**Issue by chowkamlee81** [tensorpack/tensorpack#1069]
How to train/fine-tune flownet with new dataset? KIndly help

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model-to-a-session

**Comment by chowkamlee81** [comment]
I didnt got the answer which is desired. KIndly let s know how can i finetune flownet algo with new dataset? Kindly suggest

**Comment by ppwwyyxx** [comment]
To load a model to do fine tune: https://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model-to-a-session

To train on a new dataset: https://tensorpack.readthedocs.io/tutorial/dataflow.html
https://tensorpack.readthedocs.io/tutorial/extend/dataflow.html

**Comment by ppwwyyxx** [comment]
Closing due to lack of inactivity.
Feel free to reopen or add new issues if you have more questions.
