### ISSUE TITLE
auto_set_dir bug in windows 10

### ISSUE THREAD

**Issue by elisim** [tensorpack/tensorpack#1070]
Hey,

**line 158** in /tensorpack/utils/logger.py

`auto_dirname += ':%s' % name`

I run on windows 10. Unfortunately, windows doesn't support files with ':'.
Therefore, this line raise an error. 

The solution is to change the ':' to '_'.

**Comment by elisim** [comment]
**line 158** in /tensorpack/utils/logger.py

`auto_dirname += ':%s' % name`

**Comment by ppwwyyxx** [comment]
Should be fixed now. In general I recommend `logger.set_logger_dir(path)` to have a full control over the file name.
