### ISSUE TITLE
model/parameters optimization?

### ISSUE THREAD

**Issue by jheffez** [tensorpack/tensorpack#1073]
Is there a way, or AutoML tool like Adanet/mcfly, that we can use to optimize model/parameters?

**Comment by ppwwyyxx** [comment]
Tensorpack is a training interface and we do not implement any particular deep learning algorithm as a feature in tensorpack. For now at least I did not see anything that stops you from optimizing model/parameters, but this certainly depends on what exactly you want to do.

**Comment by jheffez** [comment]
uhmm..
