### ISSUE TITLE
Tensorpack 0.9.1 breaks compatibility with Tensorflow 1.10.0

### ISSUE THREAD

**Issue by JonasAmrich** [tensorpack/tensorpack#1074]
Tensorpack 0.9.1 sets environment variables `TF_ENABLE_WHILE_V2` and `TF_ENABLE_COND_V2` [1], which should enable new - still under development - implementation of tf.while_loop and tf.cond. While the comment in `tensorpack/libinfo.py` states that this implementation is available since tf 1.12 it does actually have effect since tf 1.10 [2].

Enabling the new tf.cond implementation in tf 1.10 results in weird behavior, e.g. getting ValueError when applying batchnorm - see the example below.

### Steps to reproduce
```
from tensorpack import DataFlow
from tensorflow.keras import layers

x = layers.Input(shape=(1,))
x = layers.BatchNormalization()(x)
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-0cd6dfbf7c14> in <module>()
      1 x = layers.Input(shape=(1,))
----> 2 x = layers.BatchNormalization()(x)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    734 
    735       if not in_deferred_mode:
--> 736         outputs = self.call(inputs, *args, **kwargs)
    737         if outputs is None:
    738           raise ValueError('A layer\'s `call` method should return a Tensor '

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in call(self, inputs, training)
    625       offset = math_ops.cast(offset, inputs.dtype)
    626     outputs = nn.batch_normalization(inputs,
--> 627                                      _broadcast(mean),
    628                                      _broadcast(variance),
    629                                      offset,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _broadcast(v)
    534     def _broadcast(v):
    535       if (v is not None and
--> 536           len(v.get_shape()) != ndims and
    537           reduction_axes != list(range(ndims - 1))):
    538         return array_ops.reshape(v, broadcast_shape)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in __len__(self)
    576     """Returns the rank of this shape, or raises ValueError if unspecified."""
    577     if self._dims is None:
--> 578       raise ValueError("Cannot take the length of Shape with unknown rank.")
    579     return self.ndims
    580 

ValueError: Cannot take the length of Shape with unknown rank.
```
You can also reproduce this without importing tensorpack - it's enough to set `TF_ENABLE_COND_V2`:
```
import os
os.environ['TF_ENABLE_COND_V2'] = '1'
```

### Fix
We can either set these variables only for tf >= 1.12, or don't set them at all. I'd prefer the latter, but I may be missing something. I'd be happy to provide (rather simple) PR for this.

### Environment:
  + Python version: 3.6.7
  + TF version: v1.10.0-0-g656e7a2b34 1.10.0
  + Tensorpack version: 0.9.1

[1] Introduced in 96f8f96
[2] `TF_ENABLE_COND_V2` was introduced in 1.10: https://github.com/tensorflow/tensorflow/commit/94b3db68ee2edb568b6b12d3063b72074910f878

**Comment by ppwwyyxx** [comment]
Thanks! Now it's disabled.

It was enabled it at first because it solves some bug in COND_V1.
But later I realized that V2 has some of its own bugs as well (e.g. https://github.com/tensorflow/tensorflow/issues/24517). So let's leave the decision to users.

**Comment by JonasAmrich** [comment]
Great, thanks for a quick reply!
