### ISSUE TITLE
Is there a way to define a model for evaluation callback purpose?

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#1075]
I have a question about (custom) evaluation callback.

Let's say:
(1) I created a callback `class MyEvalCallback(Callback)`. I.e., `callbacks=[..., MyEvalCallback(dataset_val), ...]`
(2) My network architecture somehow requires a known input size. I.e., `tf.placeholder(tf.float32, [None, IM_HEIGHT, IM_WIDTH, 3], 'image')` instead of `[None, None, None, 3]`.
(3) In the training, I am using a partial crop of training images (480x480), but in the evaluation, I want to inference entire images of (1024x1024).

My question is:
the `self.trainer.get_predictor(self._in_names, self._out_names)` in `Callback` seems to follow the training model definition, so if `dataset_val` provides 1024x1024 images, it complaines input size matching error.

What options I can do in this situation?
Is there a way I can define an evaluation model architecture (only difference would be a placeholder though)?

**Comment by ppwwyyxx** [comment]
You can create arbitrary operations in the graph in your callback's `setup_graph` method. For example:

```
with tf.variable_scope(tf.get_variable_scope(), reuse=True), TowerContext('mypredict', is_training=False):
    placeholders = [ my new placeholders ]
    build_graph(placeholders)
```

And you can just use `tf.get_tensor_by_name` to get your input/output tensors and use session.run to evaluate them in your callback.

**Comment by ywpkwon** [comment]
Thanks for your advice!
Please let me make sure three things in your advice:
(1) the placeholders will have `mypredict/` prefix (e.g., `mypredict/image:0`), right?
(2) You mentioned `tf.get_tensor_by_name` but more exactly `self.get_tensors_maybe_in_tower`? (No `get_tensor_by_name` in `tf` error.)
(3) "use session.run to evaluate them in your callback." means I can use `self.trainer.hooked_sess.run` in my callback?

**Comment by ppwwyyxx** [comment]
1. Yes
2. My bad. get_tensor_by_name is a method of a graph (self.graph.get_tensor_by_name). 

sess, not hooked_sess. See https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.Trainer.hooked_sess

**Comment by ywpkwon** [comment]
Related to (3), if it is `sess`, can I define `self.sess = tf.Session()` in the callback class? Or is there a way to access to existing usable `sess`?

**Comment by ppwwyyxx** [comment]
`self.trainer.sess` or `tf.get_default_session`.
