### ISSUE TITLE
Problem with loading model (A3C)

### ISSUE THREAD

**Issue by JamesBrightman** [tensorpack/tensorpack#1076]
### 1. What I did:
I'm training Breakout on google colab using the A3C implementation.
I have a model that has been pre-trained and I run this command to load;
```
!python train-atari.py --env Breakout-v0 --gpu 1 --load ./train_log/train-atari-Breakout-v0/graph-0210-201833
```
I receive this error:

Traceback (most recent call last):
  File "train-atari.py", line 301, in <module>
    train()
  File "train-atari.py", line 259, in train
    session_init=get_model_loader(args.load) if args.load else None,
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/sessinit.py", line 261, in get_model_loader
    return SaverRestore(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/sessinit.py", line 104, in __init__
    model_path = get_checkpoint_path(model_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/varmanip.py", line 185, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: ./train_log/train-atari-Breakout-v0/graph-0210-201833

My dir for A3C training files is the standard 'train_log/train-atari-Breakout-v0'. 
I think part of the problem may be that I have no '.model' files in my dir, only a graph-xxxx-xxxxxx.meta', a tensorboard file and a 'log.log'

Any help would be greatly appreciated.

**Comment by ppwwyyxx** [comment]
The argument `--load` should take a path to model, not graph.
If your directory does not contain a model, it may be just the training job haven't finished one epoch and saved one.

**Comment by JamesBrightman** [comment]
> The argument `--load` should take a path to model, not graph.
> If your directory does not contain a model, it may be just the training job haven't finished one epoch and saved one.

Ah I see, I didn't realise that a model was only saved after each epoch. It takes me an estimated 9 hours to train 1 epoch. If say I can only train maximum 4 hours continuously, would you recommend drastically lowering the num of steps per epoch? And would this effect training in any significant way?

Appreciate the very fast response!

**Comment by ppwwyyxx** [comment]
On a GPU it should take <20min per epoch.
As the README says, training without GPU may not result in a good model.

Changing the step number only has an effect on the parameter schedulers defined in the callbacks.

**Comment by JamesBrightman** [comment]
Then I must be doing something extremely wrong - I have it running on google colab in GPU accelerated mode and the time to complete 1 6000 step epoch is ~8 hours still. It sounds like it's still training on CPU somehow.

**Comment by ppwwyyxx** [comment]
Closing as it's a TF installation issue as discussed in #1077.
It would be easier to tell if full logs were provided, as suggested in the issue template.
