### ISSUE TITLE
Dataflow not working on CPU

### ISSUE THREAD

**Issue by catai** [tensorpack/tensorpack#1082]
+ Note that you can implement a lot of features by extending Tensorpack
  (See http://tensorpack.readthedocs.io/en/latest/tutorial/index.html#extend-tensorpack).
  It does not have to be added to Tensorpack unless you have a good reason.
My current deep learning models need a lot of memory to train. But I do not have enough GPU resources. I am considering of transferring my model to CPU version, in which large RAMs are easier to find. In order to do that, I need to make dataflow works on CPU.
 
+ "Could you improve/implement an example/paper ?"
  -- The answer is: we have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you, unless it demonstrates 
  some Tensorpack features not yet demonstrated in the existing examples.
  If you don't know how to do something yourself, you may ask a usage question.
I already have a GPU version of model, which has used both dataflow and training from tensorpack. But I could only test on a small model due to limited GPU memories and resources. I am planning to rewrite the model using cpu-tensorflow. But I need the dataflow works purely on CPU as well. Can you release a version of dataflow that only use cpu resources?

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by ppwwyyxx** [comment]
Closing in favor of #1083
