### ISSUE TITLE
Dataflow not working on servers with only CPU

### ISSUE THREAD

**Issue by catai** [tensorpack/tensorpack#1083]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:
  My current deep learning models need a lot of memory to train. But I do not have enough GPU resources. I am considering of transferring my model to CPU version, in which large RAMs are easier to find. In order to do that, I need to make dataflow functions works on CPU. But in the current version, there is import errors if the server do not GPU or NIVIDA. Is it possible to have the dataflow purely running on CPU?

(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste `git diff` here:**

(3) **If not using examples, tell us what you did:**

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `CMD 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

If you expect higher accuracy, only in one of the two conditions can we help with it:
(1) You're unable to match the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to get high accuracy is a machine learning question and is
not our responsibility to figure out.

### 4. Your environment:
  + Python version: 3.6
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. 0.12 -cpu
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`. 0.9.0.1
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used. 
No GPUs avaliable. Only CPU resources. The CPU version of Tensorflow was used.
I want to use the CPU version of dataflow also.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
Dataflow always runs purely on CPUs.

**Comment by catai** [comment]
In the newest version, it actually asks for GPU resources. Could you please double check about this or provide a link of the package that only uses CPU for dataflow? Thanks!

**Comment by ppwwyyxx** [comment]
> In the newest version, it actually asks for GPU resources

It must be something else that's asking for GPU resources.

> Could you please double check about this or provide a link of the package that only uses CPU for dataflow?

The entire dataflow package uses CPU and has not one line of code about GPU.

**Comment by catai** [comment]
when I open the file: ~/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py
it has this in the beginning: 
from ..utils.gpu import change_gpu
and then:
__all__ = ['PrefetchData', 'MultiProcessPrefetchData',
           'PrefetchDataZMQ', 'PrefetchOnGPUs', 'MultiThreadPrefetchData']

**Comment by ppwwyyxx** [comment]
No it does not. The only thing `PrefetchOnGPUs` does is to change an environment variable.
And `PrefetchOnGPUs` has also been marked deprecated for a long time: it does not exist in documentation, and a user should not use it.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template. Posting "what you observed" will let others have a better idea about the reason that causes your issue.

**Comment by ppwwyyxx** [comment]
Closing as there is no response. Feel free to reopen and add the details about the issue.
