### ISSUE TITLE
Default value for steps_per_epoch in TrainConfig

### ISSUE THREAD

**Issue by ZhangVision** [tensorpack/tensorpack#1084]
In the class TrainConfig, the default value for steps_per_epoch is len(dataflow), which is not appropriate in the multi-GPU case. It should be len(dataflow)//nGPU, right?

**Comment by ppwwyyxx** [comment]
You're responsible for setting a correct `steps_per_epoch` that works best for you.
In general, many trainers have no concept of "number of GPUs".
