### ISSUE TITLE
The actual usage of the quantized DoReFa weights

### ISSUE THREAD

**Issue by asjmasjm** [tensorpack/tensorpack#1086]
Previously response to a closed topic so post a new issue. 

I am wondering if there are any float tensors in the actual dorefa quantized network. Once the quantized weights are trained, we could either fixed-point them with the activation values and do fixed-point calculations or only do the fixed-point convolution in the convolution layers and perform the float-to-fixed-point conversions. 

The 2nd method seems unreasonable to convert the format so frequently but the 1st method might introduce the extra error caused by fixed-point. I have tried w4a4 and the error from fixed-point degraded the result a lot more compared to fixed-point w8a8. I am not sure what is the correct way to actually use the quantized weights.

The ulp seemed to apply the 2nd method. Does that mean the time cost of the format conversion is neglectable?

**Comment by ppwwyyxx** [comment]
Activation function on fixed point values (i.e., quantize->float + activataion + float->quantize) can be implemented as a lookup table.
Therefore in actual use, no floating point is involved and no extra quantization is needed.

**Comment by asjmasjm** [comment]
I am not sure whether I understand what you mean. Suppose we use the w2a2 to perform the convolution 1/3 * 1/3 * [1, 2, 1, 3] * [2, 1, 0, 3]' and get the activated feature value 1/9 * [2, 7, 2, 10] and then clip to 1/9 * [2, 7, 2, 9] if using the clip(0, 1) after the convolution layer. Then it is convolved with the next weights 1/3 * [2, 2, 2, 2]' and we get 1/27 * [18, 18, 22, 22]. 

No floating values are involved in the example above but it does not match your "quantize->float + activataion + float->quantize" explanation. Do you directly match the [1, 2, 1, 3] [2, 1, 0, 3] combination to the result [2, 7, 2, 9]?

**Comment by ppwwyyxx** [comment]
Now I'm confused about what you're asking. 
I've probably misunderstood your  questions. There is no floating point operations involved in an actual deployment. And there won't be any extra quantization error. Why do you think the opposite?

**Comment by asjmasjm** [comment]
Sorry for omitting that I fuse the batch normal parameters into the weights. In the training phase, the float weights are like [0.3333 * bn_gamma, 0.6667 * bn_gamma, 0.3333 * bn_gamma, 0.3333 * bn_gamma]. The errors are generated after the fused weights are fixed-point to int8 and multiply with fixed-point feature values as the training does not quantize bn parameters. Without the bn layer, I think everything goes well.

**Comment by ppwwyyxx** [comment]
> 1. Is there any way to hide the floating point bn calculation? LUT maybe, but the size of the table could be very large if the bitwidth is long (>6)?

LUT. The table size is 2^activation bitwidth; And in practice we never use any bitwidth >4.

> 2. Even for the fixed point operation, how to deal with the potential accumulation overflow? It seems impossible to make the intermediate additon result in int16 if there are more channels with large kernel size.

You can save the addition result (the popcnt) into int16 or larger ints. They don't have to be stored, because the LUT is monotonic. Once you obtain the value, you immediately know which item in the LUT you need.

**Comment by asjmasjm** [comment]
For some reason no int32 variables is allowed even as the temporary one to pick the intermediate accumulated result... And I can not train the network using weights less than 4 bits. Actually a sharp decrease appear once 3 bits are applied and maybe it is relative to the structure of the network. I think I will try LUT in w4a4 anyway.

**Comment by asjmasjm** [comment]
>The table size is 2^activation bitwidth;
I am not clear about this conclusion.

Suppose the weigth and activation bitwidths are both 2 and suppose we convolve weights 1/3 * [-3~3, ... -3~3] with activations 1/3 * [0~3, ... ,0~3]' and get 1/9 * [-9~9 + ... + -9~9] = K * a0, where a0 is an integer in a rather large range. 

After the following bn and clip process we get a1 = clip(gamma * K * a0 + beta, 0, 1). Therefore the interger a0 should be retained within these areas:

[int(-beta*K/gamma), int((1-beta)*K/gamma)] if gamma >0

[int((1-beta)*K/gamma), int(-beta*K/gamma)] if gamma <0 

Within this area we perform Fa(a1), so the LUT is calculated as (1-beta)*K/gamma - (-beta*K/gamma) = K/gamma = (2^(activation bitwidth) - 1) * (2^(weight bitwidth) - 1) / gamma

What is the problem about my understanding of the LUT?

**Comment by ppwwyyxx** [comment]
`Fa(a1)` only has `2^activation bitwidth` possible output values. So these are the number of elements needed in the lookup table. You don't need to cover every possible inputs in the range, because `Fa(clip(gamma / K * a0 + beta, 0, 1))` is weakly-monotonic w.r.t `a0`.

**Comment by asjmasjm** [comment]
I kinda catch up with you now. So you mean that multiple indices in the LUT map to one value and the indexing should be like LUT[i>>activation_bitwidth] instead of LUT[i].

**Comment by ppwwyyxx** [comment]
Maybe it will be less confusing if we just call it "table", not "look up table".
Yes multiple inputs map to the same output. And in terms of the actual implementation, I'm not sure what we used in actual deployment but at least you can use integer comparisons to achieve it.

**Comment by asjmasjm** [comment]
Another question brought by this...

I notice the tensorpack put the bn layer before activation (clip) layer while in tensorlayer after activation layer:
https://tensorlayercn.readthedocs.io/zh/latest/_modules/tensorlayer/layers/convolution/dorefa_conv.html#DorefaConv2d 

The order do matters as the negative convolved result can be converted to 0.0 to 1.0 if it go through bn layer before clip and thus kept after clip. It will not be kept if go through clip layer first.

I do not know what is the more reasonable?

**Comment by ppwwyyxx** [comment]
Clip need to come after BN so that the inputs to `Fa` can be within [0, 1].

In general, it's best to not trust third-party layer code, as mentioned in https://tensorpack.readthedocs.io/tutorial/symbolic.html.

**Comment by asjmasjm** [comment]
Okay I see... and appreciate your patience greatly.

**Comment by ppwwyyxx** [comment]
Closing and feel free to reopen or just ask if you have more questions.
