### ISSUE TITLE
Possible typo in documentation for FasterRCNN/DetectionDataset/load_training_roidbs

### ISSUE THREAD

**Issue by dcyoung** [tensorpack/tensorpack#1088]
The documentation for `DetectionDataset -> load_training_roidbs` indicates that each instance should have the key `category`. 
https://github.com/tensorpack/tensorpack/blob/d0e410ad3fc2fe9bd2289cfe79cee4e0a4ab5399/examples/FasterRCNN/dataset.py#L215

However, it looks like the coco dataset produces the key `class`: https://github.com/tensorpack/tensorpack/blob/d0e410ad3fc2fe9bd2289cfe79cee4e0a4ab5399/examples/FasterRCNN/dataset.py#L163

And the key `class` is expected elsewhere. For example: 
https://github.com/tensorpack/tensorpack/blob/152c4c2c057c653cfca18fe27ce90557c7275d73/examples/FasterRCNN/data.py#L303

Is it safe to assume this is a typo in the docs? Or did i miss the inclusion of the `category` key somewhere else?

**Comment by ppwwyyxx** [comment]
Thanks! It's a typo in docs.
