### ISSUE TITLE
where is the pre-trained models source code

### ISSUE THREAD

**Issue by chengyw** [tensorpack/tensorpack#1090]
Dear there,
I want to train resnet with my data, can you show me source code of http://models.tensorpack.com/FasterRCNN/ImageNet-R50-AlignPadding.npz

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet

**Comment by chengyw** [comment]
> https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet

thank you!
I have used this one also, but i found the code is different with examples/FasterRCNN backbone.
one use activation but another not. i use my trained resnet model to train FasterRCNN, after some epochs, the cost is NAN. but i use the pre-trained model:http://models.tensorpack.com/FasterRCNN/ImageNet-R50-AlignPadding.npz is ok.
![image](https://user-images.githubusercontent.com/18695918/53161608-444acd00-3605-11e9-98d5-77b576762bbd.png)
![image](https://user-images.githubusercontent.com/18695918/53161664-5dec1480-3605-11e9-9897-354ae035aedc.png)

**Comment by ppwwyyxx** [comment]
The one in FasterRCNN also uses activation:
https://github.com/tensorpack/tensorpack/blob/d8d35fb57fd8524ee53e030c062455c37b89474f/examples/FasterRCNN/basemodel.py#L76

As to why it goes to NaN, it is a machine learning question and do not appear to be related to tensorpack.

**Comment by chengyw** [comment]
> The one in FasterRCNN also uses activation:
> [tensorpack/examples/FasterRCNN/basemodel.py](https://github.com/tensorpack/tensorpack/blob/d8d35fb57fd8524ee53e030c062455c37b89474f/examples/FasterRCNN/basemodel.py#L76)
> 
> Line 76 in [d8d35fb](/tensorpack/tensorpack/commit/d8d35fb57fd8524ee53e030c062455c37b89474f)
> 
>  argscope(Conv2D, use_bias=False, activation=nonlin, 
> As to why it goes to NaN, it is a machine learning question and do not appear to be related to tensorpack.
