### ISSUE TITLE
[DQN] No module named 'ale_python_interface'

### ISSUE THREAD

**Issue by JamesBrightman** [tensorpack/tensorpack#1091]
### 1. What you did:

I'm trying to use the DQN implementation with Gym. To do this I run 
```
python! DQN.py --env = BreakoutDeterministic-v4
```
 (as suggested in the readme).

However, it gives this error - 

Traceback (most recent call last):
  File "./DQN.py", line 15, in <module>
    from atari import AtariPlayer
  File "/content/drive/Dissertation/DQN-Tensorpack/atari.py", line 11, in <module>
    from ale_python_interface import ALEInterface
ModuleNotFoundError: No module named 'ale_python_interface' 

I can't seem to find a way to install 'ale_python_interface' on google colab. I don't even want to use ALE, but it seems it is necessary for running the DQN training, even with Gym as it has to reference the Atari.py file, which contains ALE import. 

Any help would be greatly appreciated. 
Thanks.

**Comment by ppwwyyxx** [comment]
Thanks for the suggestions. Now `ale_python_interface` will not be required if you use gym environment.

**Comment by JamesBrightman** [comment]
Thanks for the quick change - pulled the master again and all works well.

Regards,
James
