### ISSUE TITLE
How to make a coordinate dependent augmentor?

### ISSUE THREAD

**Issue by dcyoung** [tensorpack/tensorpack#1093]
I'm attempting to modify the FRCNN dataflow to generate a random crop containing at least one box, instead of resizing the entire image. I'd like to accomplish this with an Augmentor which would transform the coordinates after defining the crop region. However, choosing this crop region depends on the coordinates of the boxes. At a glance, this seems at odds with the intended design of Augmentor.

Is there an easy way to create an augmentor subclass which accomplishes this coordinate dependent behavior, or would this necessitate using `Map`?

**Comment by ppwwyyxx** [comment]
It sounds like this goes out of the abstraction of augmentors because you need to make changes on the datapoint-level, not on the image-level. You need to use `MapData` or similar methods to modify the data points directly.

**Comment by ppwwyyxx** [comment]
Since the existing code already uses `MapData`, you can add your changes in `preprocess`.

**Comment by dcyoung** [comment]
Thanks for the confirmation. Placing changes in the mapped `preprocess` method worked just fine.
