### ISSUE TITLE
Hed Question

### ISSUE THREAD

**Issue by johnjamin11** [tensorpack/tensorpack#1095]
Hi,
I am trying to test the model using your tensorpack implementation. 
For most of the images the testing runs just fine. 
However, I ran into memory issue and tried to fix the line in run function under Hed.py from
im = cv2.resize(im, (im.shape[1] // 16\*16, im.shape[0] // 16\*16))[None, :, :, :].astype('float32')
to
im = cv2.resize(im, (im.shape[1] // 2, im.shape[0] // 2))[None, :, :, :].astype('float32')

then i ran into shape error:
InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,1,1530,2315] vs. shape[1] = [1,1,1530,2314]

So here is my question, 
1. What exactly does shapes//16*16 do? 
2. Why does it always result in +1 difference if I change the division value on that line?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
https://stackoverflow.com/questions/1535596/what-is-the-reason-for-having-in-python

The model requires input shapes to be a multiple of 16.

**Comment by johnjamin11** [comment]
Hey, 
Yeah, I tested again with the muliple of 16 as you mentioned but still having the same problem. 
Always has the mismatch in the end. 

In the original code, you've divided height and width with a value of 16 x 16 (on line 282). 
I don't think this is the problem of // or /. 
This line is really not changing the shape of an image, rather it just adds one dimension to fit it onto input tensor. But when I modify the code in a way that will actually change the values of width and height, then the error is there. Could you please check on this?

**Comment by ppwwyyxx** [comment]
I cannot understand what exactly you did and what you saw. If you're looking to solve an unexpected problem you met, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by ppwwyyxx** [comment]
> In the original code, you've divided height and width with a value of 16 x 16 (on line 282).

This is not true. `a // 16 * 16` will divide `a` by 16 and multiply it by 16. See https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by johnjamin11** [comment]
You are totally right. I cannot believe I missed the simple thing..
Now the problem is completely solved. Thank you very much.
