### ISSUE TITLE
Question: Is it designed this way that reset_state() in RNGDataFlow has to be manually called before iteration?

### ISSUE THREAD

**Issue by elmirador** [tensorpack/tensorpack#1098]
I noticed that in `RNGDataFlow`
https://github.com/tensorpack/tensorpack/blob/964f5d0349705c5118f59b722f60395f1a6ff9eb/tensorpack/dataflow/base.py#L151

This class also doesn't have `__init__` to call `self.reset_state`. So I guess it should be manually called before using the dataflow as an iterator?

**Comment by ppwwyyxx** [comment]
You are responsible for calling it. https://tensorpack.readthedocs.io/tutorial/dataflow.html#use-dataflow-outside-tensorpack
