### ISSUE TITLE
Use MultiProcessMapData (or PrefetchDataZMQ) with imgaug results in the same augmentation parameter sequence

### ISSUE THREAD

**Issue by elmirador** [tensorpack/tensorpack#1099]
Code to reproduce the issue:
https://gist.github.com/elmirador/8d79a4ef336c14cc91b1e8e83761ae88

If I understand it correctly, `MultiProcessMapData` (or `PrefetchDataZMQ`) forks a bunch of child processes to run `map_func`.
The problem is that the `rng` inside the Augmentor is only initialized (or re-initialized) by a seed whenever `reset_state` is called. Usually, `reset_state` is only called during the construction of the Augmentor.
By using `MultiProcessMapData`, child processes will directly copy the Augmentor to run `map_func`. Since they don't call `reset_state` by themselves (and they shouldn't), the `rng` in every child processes will have the same seed which results in the same parameter sequence.

"The lack of randomness" becomes even clearer when `map_func` is heavy (say, we need 0.01s to pre-process the data and then do a Gamma augmentation).

One can simply call `reset_state` in `map_func` to solve this issue, it should be safe since every process is independent. I don't think this is a bug since everything is working properly but I think maybe it's worthy to point this out.

**Comment by ppwwyyxx** [comment]
What you described is mentioned as Point(4) here: https://tensorpack.readthedocs.io/tutorial/extend/augmentor.html#design-of-tensorpack-s-imgaug-module. If you use the builtins like `AugmentImageComponent`, this is done automatically for you. Otherwise you'll have to do it yourself now.

I wanted to find a better place to mention this to users (or warn users), but haven't yet done it.
Or there might be a way to automatically do this (by some fork handler, for example).

Marking this issue as an enhancement.

**Comment by elmirador** [comment]
Actually, numpy has the same issue. The child process for whatever reason doesn't re-initialize themselves with a new seed. Python's `random` module, on the other hand, is completely fine though.

**Comment by ppwwyyxx** [comment]
Now the augmentors automatically reset their RNG after fork, in Python>=3.7.
Python's `random` module does the same in Python>=3.7, and does inefficient syncing in Python <3.7 (ref.: https://github.com/numpy/numpy/issues/9650#issuecomment-327144993).

Added some more docs to clarify this behavior.

**Comment by elmirador** [comment]
Thanks! Really appreciate the clearer doc!

**Comment by ArtificialNotImbecile** [comment]
In [FasterRCNN dataflow](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/data.py#L96), augmentation is done without builtins like `AugmentImageComponent()` who are responsible for  calling `self.augs.reset_state()`  in dataflow's `reset_state()` method, so is this dataflow assumes python >=3.7 ? Shall we call `self.aug.reset_state()`  before `tfms = self.aug.get_transform(im) `if using python < 3.7?

**Comment by ppwwyyxx** [comment]
The FasterRCNN dataflow already has enough randomness from random shuffle, so there is not much need to set the augmentation seed. Similar for the imagenet one.

In the imagenet example, you're using threads for each worker, instead of processes. And there is no need to reset RNG for threads.
