### ISSUE TITLE
Misuse of tf.image.non_max_suppression in FasterRCNN 

### ISSUE THREAD

**Issue by LandyGuo** [tensorpack/tensorpack#1102]
Hi yuxin, I noticed that  `tf.image.non_max_suppression` is used for intra-class nms [here,](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/model_frcnn.py#L208) but boxes are decoded as x1y1x2y2, however  `tf.image.non_max_suppression` needs boxes of `y1x1y2x2` order,  unless I missed sth.

**Comment by bairdzhang** [comment]
It seems swap x and y does not change the behaviour of NMS?

**Comment by ppwwyyxx** [comment]
Right. It does not matter.
