### ISSUE TITLE
Question: calculating flops

### ISSUE THREAD

**Issue by Sirius083** [tensorpack/tensorpack#1105]
Is there an easy way to calculating FLOPS of a model.
I have trained the denseNet model under your tensorpack implementation.
(https://github.com/YixuanLi/densenet-tensorflow)
After freezing the graph to a pb file, I want to calculate the total FLOPs of the model.
I tried the flowing code:
graph = load_pb(graph_pb_path)
with graph.as_default():
       flops = tf.profiler.profile(graph, options = tf.profiler.ProfileOptionBuilder.float_operation())
But tensorflow gives out an error, since the example does not set the input tensor shape for training.

I tried the checkpoint-prof.py file but still can't avoid the problem.

Do I need to retrain the model? 

Thanks in advance.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/shufflenet.py

**Comment by ppwwyyxx** [comment]
Closing since the question seems to be resolved. Feel free to reopen if otherwise.
