### ISSUE TITLE
Dose the do_visualize func in FasterRCNN train.py not provide visualize of mask prediction ? ?

### ISSUE THREAD

**Issue by svjack** [tensorpack/tensorpack#1107]
mask prediction of DetectionResult can be retrieved by add output/masks to output_names, But it the 
draw_final_outputs func not resize mask with the prediction bbox and past (or padding) it to the full image size, so the directly use of draw_mask func seemed induce some error, If i am misunderstand, make me clear 
Thank you.

**Comment by ppwwyyxx** [comment]
The function does not contain mask visualization.
`--predict` contains it.
