### ISSUE TITLE
Proper way to use only relevant FRCNN weights from GN training

### ISSUE THREAD

**Issue by dcyoung** [tensorpack/tensorpack#1108]
Context:
I was able to use GN to improve training of an FRCNN model on 8xV100s. Training was launched like so:

```bash
    ./train.py \
        --logdir=logs/$(date +%Y%m%dT%H%M%S) \
        --config \
        MODE_MASK=False \
        MODE_FPN=True \
        DATA.BASEDIR=$DATA_ROOT/$DATASET_VERSION \
        BACKBONE.WEIGHTS=$PRE_TRAINED_IMAGENET_WEIGHTS_LOCAL_PATH \
        FPN.NORM=GN \
        BACKBONE.NORM=GN \
        FPN.FRCNN_HEAD_FUNC=fastrcnn_4conv1fc_gn_head
```

Model predicts well when using the matching config:

```bash
./train.py \
    --predict /path/to/image \
    --load /path/to/pre_trained/GN/checkpoint \
    --config \
    DATA.BASEDIR=/path/to/data \
    MODE_MASK=False \
    MODE_FPN=True \
    FPN.NORM=GN \
    BACKBONE.NORM=GN \
    FPN.FRCNN_HEAD_FUNC=fastrcnn_4conv1fc_gn_head
```

I am then attempting to use these same pre-trained weights to predict with a non-GN config:

```bash
./train.py \
    --predict /path/to/image \
    --load /path/to/pre_trained/GN/checkpoint \
    --config \
    DATA.BASEDIR=/path/to/data \
    MODE_MASK=False \
    MODE_FPN=True
```

And receive no predictions. 

Looking at the source for the `fpn_model` and the backbone, I am left with the impression that the weights of the standard FPN model should still work when restored from a pre-trained checkpoint resulting from a GN config.... where the inputs to the GN layers would be redirected to the outputs of the GN layers, but maintain the same tensor names... effectively bypassing the GN layers, and ignoring the associated weights. Temporarily ignoring the discussion of how to properly load the weights, **is this assumption correct?** Or am I misunderstanding the implementation of the model architecture?

Moving on with the assumption that a standard FPN model will support weights trained with a GN config, I am wondering about the easiest path to restoration. Following the source into the PredictConfig, it appears that the SessionInit is using a SaverRestore, which appears to be performing a restore agnostic to the model architecture that was provided in the PredictConfig. 

Does tensorpack provides a means of restoring a model given the architecture defined by the model provided in the Config, rather than reading the model from the checkpoint. Perhaps loading tensors by name? **Is there a suggested workflow within tensorpack to restore in this way?**

An initial run through the docs has me thinking along the lines of exporting the GN pre-trained model to `.npz`, and then reloading with `DictRestore`, hoping that the internal `SessionUpdate` is effectively restoring intersecting tensors by name. **Would this workflow accomplish the desired restoration behavior?**

If so, **does the FasterRCNN example code already include a method to export to `.npz`.**

Thanks!

**Comment by ppwwyyxx** [comment]
>  I am left with the impression that the weights of the standard FPN model should still work when restored from a pre-trained checkpoint resulting from a GN config.... where the inputs to the GN layers would be redirected to the outputs of the GN layers, but maintain the same tensor names... effectively bypassing the GN layers, and ignoring the associated weights. Temporarily ignoring the discussion of how to properly load the weights, is this assumption correct? Or am I misunderstanding the implementation of the model architecture?

What you said about the architecture is correct. This means the model will load properly. This does not mean the model will predict properly.

> Moving on with the assumption that a standard FPN model will support weights trained with a GN config

Same as above. The weights will load like you did. The weights will not predict properly, and there is no way to make it so.

> Does tensorpack provides a means of restoring a model given the architecture defined by the model provided in the Config

In tensorpack, restoring a checkpoint means loading the variables in the checkpoint in the graph, and that's what it is.
I do not understand what "restoring a model given the architecture defined by the model provided in the Config" means exactly. 

> hoping that the internal SessionUpdate is effectively restoring intersecting tensors by name. 
It is already "restoring intersecting tensors by name", no matter whether you use `DictRestore` or `SaverRestore`.

**Comment by dcyoung** [comment]
I see. It seems I haven't done my homework on Group Normalization. I had a fundamental misunderstanding that it could be ignored without implications to the rest of the model, similar to BN. Thank you for the clarification! I appreciate it.

I was a little surprised to see the difference in inference performance between GN and non-GN models. Moving from a standard FPN model to a GN-FPN model, I'm seeing an average increase of ~70% in inference time. 

For now I will predict with a GN config, until i have retrained without GN. 

Thanks again!
