### ISSUE TITLE
How to modify activation during Inference with Tensorpack?

### ISSUE THREAD

**Issue by minhson** [tensorpack/tensorpack#1114]
Hello, 
I would like to modify activation (the output of conv layer) during inference?
Could you help me to do that?

Thanks you very much!

**Comment by ppwwyyxx** [comment]
I'm not sure what you mean by "modify activation".

But the graph is defined by yourself, so you can do whatever computation by defining the graph. I don't see how is that related to tensorpack.

**Comment by ppwwyyxx** [comment]
Closing since no clarification was provided on the question.
