### ISSUE TITLE
Is it possible to use cross gpu batchnorm without tensorpack trainer

### ISSUE THREAD

**Issue by MrWanter** [tensorpack/tensorpack#1117]
Hi! I'm wondering if it is possible to use cross gpu batchnorm without tensorpack trainer, I have tried using it in my code, but the model seems not trained properly with poor test results, thank you!

**Comment by ppwwyyxx** [comment]
It is certainly possible if you implement something like the tensorpack trainer.

**Comment by MrWanter** [comment]
Thanks, it works!
