### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by roger1993** [tensorpack/tensorpack#1118]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**

Faster-RCNN

(2) **If you're using examples, have you made any changes to the examples? Paste `git diff` here:**

Nothing changed, use the dataset with coco format

(3) **If not using examples, tell us what you did:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let other __reproduce__ your issues. 
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
When I start to train the faster rcnn, it will report the error as below:
Traceback (most recent call last):
  File "train.py", line 516, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/.local/lib/python3.5/site-packages/tensorpack/train/interface.py", line 91, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/home/.local/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/.local/lib/python3.5/site-packages/tensorpack/train/tower.py", line 218, in setup_graph
    get_cost_fn = TowerFuncWrapper(get_cost_fn, input_signature)
  File "/home/.local/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 274, in __init__
    raise ValueError("Invalid input name: '{}'".format(name))
ValueError: Invalid input name: 'image:0'

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `CMD 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html 
before posting.

If you expect certain accuracy, only in one of the two conditions can we help with it:
(1) You're unable to reproduce the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to train a model to certain accuracy is a machine learning question.
We do not answer machine learning questions and it is your responsibility to 
figure out how to make your models more accurate.

### 4. Your environment:
  + Python version:
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

the config as below:

[0325 16:07:18 @logger.py:90] Argv: train.py --config MODE_MASK=False MODE_FPN=True DATA.BASEDIR=data BACKBONE.WEIGHTS=COCO-R101FPN-MaskRCNN-Standard.npz
[0325 16:07:18 @config.py:278] Config: ------------------------------------------
{'BACKBONE': {'FREEZE_AFFINE': False,
              'FREEZE_AT': 2,
              'NORM': 'FreezeBN',
              'RESNET_NUM_BLOCKS': [3, 4, 23, 3],
              'STRIDE_1X1': False,
              'TF_PAD_MODE': False,
              'WEIGHTS': 'COCO-R101FPN-MaskRCNN-Standard.npz'},
 'CASCADE': {'BBOX_REG_WEIGHTS': [[10.0, 10.0, 5.0, 5.0], [20.0, 20.0, 10.0, 10.0],
                                  [30.0, 30.0, 15.0, 15.0]],
             'IOUS': [0.5, 0.6, 0.7]},
 'DATA': {'ABSOLUTE_COORD': True,
          'BASEDIR': 'data',
          'CLASS_NAMES': ['BG', 'iron_lighter', 'black_lighter', 'cutter', 'battery', 'scissor'],
          'NUM_CATEGORY': 5,
          'NUM_CLASS': 6,
          'TRAIN': 'train',
          'VAL': ('val',)},
 'FPN': {'ANCHOR_STRIDES': (4, 8, 16, 32, 64),
         'CASCADE': False,
         'FRCNN_CONV_HEAD_DIM': 256,
         'FRCNN_FC_HEAD_DIM': 1024,
         'FRCNN_HEAD_FUNC': 'fastrcnn_2fc_head',
         'MRCNN_HEAD_FUNC': 'maskrcnn_up4conv_head',
         'NORM': 'None',
         'NUM_CHANNEL': 256,
         'PROPOSAL_MODE': 'Level',
         'RESOLUTION_REQUIREMENT': 32},
 'FRCNN': {'BATCH_PER_IM': 512,
           'BBOX_REG_WEIGHTS': [10.0, 10.0, 5.0, 5.0],
           'FG_RATIO': 0.25,
           'FG_THRESH': 0.5},
 'MODE_FPN': True,
 'MODE_MASK': False,
 'MRCNN': {'HEAD_DIM': 256},
 'PREPROC': {'MAX_SIZE': 1344.0,
             'PIXEL_MEAN': [123.675, 116.28, 103.53],
             'PIXEL_STD': [58.395, 57.12, 57.375],
             'TEST_SHORT_EDGE_SIZE': 800,
             'TRAIN_SHORT_EDGE_SIZE': [800, 800]},
 'RPN': {'ANCHOR_RATIOS': (0.5, 1.0, 2.0),
         'ANCHOR_SIZES': (32, 64, 128, 256, 512),
         'ANCHOR_STRIDE': 16,
         'BATCH_PER_IM': 256,
         'CROWD_OVERLAP_THRESH': 9.99,
         'FG_RATIO': 0.5,
         'HEAD_DIM': 1024,
         'MIN_SIZE': 0,
         'NEGATIVE_ANCHOR_THRESH': 0.3,
         'NUM_ANCHOR': 15,
         'POSITIVE_ANCHOR_THRESH': 0.7,
         'PROPOSAL_NMS_THRESH': 0.7,
         'TEST_PER_LEVEL_NMS_TOPK': 1000,
         'TEST_POST_NMS_TOPK': 1000,
         'TEST_PRE_NMS_TOPK': 6000,
         'TRAIN_PER_LEVEL_NMS_TOPK': 2000,
         'TRAIN_POST_NMS_TOPK': 2000,
         'TRAIN_PRE_NMS_TOPK': 12000},
 'TEST': {'FRCNN_NMS_THRESH': 0.5,
          'RESULTS_PER_IM': 100,
          'RESULT_SCORE_THRESH': 0.05,
          'RESULT_SCORE_THRESH_VIS': 0.3},
 'TRAIN': {'BASE_LR': 0.01,
           'EVAL_PERIOD': 25,
           'LR_SCHEDULE': [240000, 320000, 360000],
           'NUM_GPUS': 2,
           'STARTING_EPOCH': 1,
           'STEPS_PER_EPOCH': 500,
           'WARMUP': 1000,
           'WARMUP_INIT_LR': 0.0033000000000000004,
           'WEIGHT_DECAY': 0.0001},
 'TRAINER': 'replicated'}
[0325 16:07:18 @train.py:469] Warm Up Schedule (steps, value): [(0, 0.0033000000000000004), (1000, 0.01)]
[0325 16:07:18 @train.py:470] LR Schedule (epochs, value): [(2, 0.01), (1920.0, 0.001), (2560.0, 0.00010000000000000002)]
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
[0325 16:07:18 @dataset.py:45] Instances loaded from data/annotations/train.json.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 882/882 [00:00<00:00, 6673.01it/s]
[0325 16:07:18 @timer.py:50] Load Groundtruth Boxes for train finished, time:0.1414 sec.
[0325 16:07:18 @data.py:49] Ground-Truth Boxes:
| class         |   #box |
|:--------------|-------:|
| BG            |      0 |
| iron_lighter  |    285 |
| black_lighter |   1518 |
| cutter        |    712 |
| battery       |   1593 |
| scissor       |    613 |
| total         |   4721 |
[0325 16:07:18 @data.py:294] Filtered 3 images which contain no non-crowd groudtruth boxes. Total #images for training: 879
[0325 16:07:18 @train.py:474] Total passes of the training set is: 3276.5
[0325 16:07:18 @prof.py:46] WRN [GPUUtilizationTracker] Both devices and CUDA_VISIBLE_DEVICES are None! Will monitor all 2 visible GPUs!
[0325 16:07:20 @training.py:50] [DataParallel] Training a model of 2 towers.
[0325 16:07:20 @interface.py:43] Automatically applying StagingInput on the DataFlow.

**Comment by ppwwyyxx** [comment]
Thanks for reporting. You can checkout the examples at the  v0.9.1 tag AND reinstall tensorpack 0.9.1 for now to get it running. I'll fix this bug later.

**Comment by ppwwyyxx** [comment]
I'm unable to reproduce your issue, so please complete the issue template in the way described above.

**Comment by ppwwyyxx** [comment]
I fixed the issue based on my best guess of what happened. My guess is that you're running an old version (<= 0.9.1) of FasterRCNN examples with tensorpack > 0.9.1, which can trigger this bug.
Now it should be fixed, and if you're still seeing any issues, please complete the issue template so I don't have to guess.

**Comment by roger1993** [comment]
Problem has been solved, thanks
