### ISSUE TITLE
How to do inference in GAN (Image2Image.py)

### ISSUE THREAD

**Issue by HongyangGao** [tensorpack/tensorpack#1120]
Hi there,

I am using example Image2Image.py super resolution. Like image classification tasks, I want to add an InferenceRunner in callbacks. 
![image](https://user-images.githubusercontent.com/6397103/55008717-62fb0580-4faf-11e9-92c8-22a83d280baa.png)

But it shows error like this:

KeyError: "The name 'InferenceTower/cost:0' refers to a Tensor which does not exist. The operation, 'InferenceTower/cost', does not exist in the graph."

I notice that GAN uses TowerTrainer. May I know how to use Inference runner under this setting? Thank you.

**Comment by ppwwyyxx** [comment]
The error is telling you that 'cost' does not exist in the graph, so there is no way to inference it. You can only inference tensors that exist.

**Comment by HongyangGao** [comment]
I see. That works for me. Thank you very much.
