### ISSUE TITLE
Assign model to my graph

### ISSUE THREAD

**Issue by Guocode** [tensorpack/tensorpack#1121]
When I try to use tensorpack as a part of my code to get an accuracy of a model, outside it I define a Keras model, but it turns out to have a conflict between the two models, when I add
```
child_graph = tf.Graph()
    with child_graph.as_default():
```
before the tensorpack train, it is solved, I wonder if there is any way to put the training on my own graph or session.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
