### ISSUE TITLE
ImportError: cannot import name 'get_tf_version_number'

### ISSUE THREAD

**Issue by saikiranvanam** [tensorpack/tensorpack#1122]
While running the below line:
from tensorpack.tfutils.common import get_tf_version_number
I get below error:
ImportError: cannot import name 'get_tf_version_number'

I imported the tesorpack package through github clone as mentioned in this github site.

**Comment by ppwwyyxx** [comment]
`get_tf_version_number` does not make sense (because there is TF 1.10) and was deprecated half a year ago (https://github.com/tensorpack/tensorpack/commit/b673b24cf19fcfeda367dd023bc04c035e5b6d64#diff-3a128bdb78dfe138c82e2546d899de9f). Please use `get_tf_version_tuple` instead.
