### ISSUE TITLE
general queries regarding stn

### ISSUE THREAD

**Issue by kakashi571** [tensorpack/tensorpack#1124]
# If you meet any unexpected problems when running the code, or want to report bugs, please STOP here. Go to the following link instead and fill out the information there:
https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md

Otherwise, you can post here for:
1. Feature Requests:
  + Note that you can implement a lot of features by extending Tensorpack
   (See http://tensorpack.readthedocs.io/tutorial/index.html#extend-tensorpack).
   It does not have to be added to Tensorpack unless you have a good reason.

2. Questions on Using/Understanding Tensorpack:
  + Your question is probably answered in [tutorials](http://tensorpack.readthedocs.io/tutorial/index.html#user-tutorials). Read it first.
  + We answer "HOW to do X with Tensorpack" for a well-defined X.
    We also answer "HOW/WHY Tensorpack does X" for some X that Tensorpack or its examples are doing.

Some typical questions that we DO NOT answer:

+ "Could you improve/implement an example/paper ?" --

  We have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you.
  If you don't know how to do something yourself, you may ask a usage question.
+ "The examples do not perform as expected after I change the models/dataset/parameters/etc."

  Tensorpack maintainers make sure the examples perform well without modifications.
  But it's your job to pick the model and parameters that are suitable for your own situation.
  We cannot help with such questions unless they appear to be a bug in tensorpack.

+ "Why my own model doesn't perform well?", "I don't understand this paper you implement.",
  "How should I change the parameters for my own dataset?"

  We do not answer machine learning questions.

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

what are the img,coords in sample(img,coords)?
And can I use this STN on a single image of my own?

**Comment by ppwwyyxx** [comment]
> what are the img,coords in sample(img,coords)?

`img` is an image.
`coords` are coordinates to sample from the image.

> And can I use this STN on a single image of my own?

I don't understand what you're asking.
You're allowed to use the code to do anything.
How to do them depends on what you want to do.

**Comment by kakashi571** [comment]
so you are saying "coords" is a tensor containing coordinates of img?

**Comment by ppwwyyxx** [comment]
Yes.
As the code says it is a tensor of shape `(B, H2, W2, 2)` which means it contains `B x H2 x W2` coordinates.

**Comment by kakashi571** [comment]
so how can we extract the coordinates from img.get_shape() and store them in coords as a tensor?

**Comment by ppwwyyxx** [comment]
This is a tensorflow question and unrelated to tensorpack.
You can use functions like `tf.meshgrid`.

**Comment by kakashi571** [comment]
okay, thank you for your help.

**Comment by kakashi571** [comment]
giving an error in sample function i.e Dimensions must be equal, but are 2 and 3 for 'clip_by_value_1/Minimum' (op: 'Minimum') with input shapes: [2], [3].

**Comment by ppwwyyxx** [comment]
Please use the function following its documentation.

If you cannot solve the issue please post issues following the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
