### ISSUE TITLE
ValueError: Layer named InstanceNorm5d is already registered!

### ISSUE THREAD

**Issue by saikiranvanam** [tensorpack/tensorpack#1125]
runfile('D:/Major Project/git5/custom_ops.py', wdir='D:/Major Project/git5')
Traceback (most recent call last):

  File "<ipython-input-18-640d115a9bd8>", line 1, in <module>
    runfile('D:/Major Project/git5/custom_ops.py', wdir='D:/Major Project/git5')

  File "C:\Users\sai4v\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\sai4v\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Major Project/git5/custom_ops.py", line 29, in <module>
    def InstanceNorm5d(x, epsilon=1e-5, use_affine=True, gamma_init=None, data_format='channels_last'):

  File "C:\Users\sai4v\Anaconda3\lib\site-packages\tensorpack\models\registry.py", line 143, in wrapper
    _register(func.__name__, wrapped_func)

  File "C:\Users\sai4v\Anaconda3\lib\site-packages\tensorpack\models\registry.py", line 25, in _register
    raise ValueError("Layer named {} is already registered!".format(name))

ValueError: Layer named InstanceNorm5d is already registered!

**Comment by ppwwyyxx** [comment]
You have two `InstanceNorm5d` in your code with `@layer_register` and this is not allowed

**Comment by saikiranvanam** [comment]
Code link: https://github.com/tkuanlun350/3DUnet-Tensorflow-Brats18
Sir, above is the code which i'm trying and getting issue. Sir, the solution which you told I tried but I didn't get it. Can you please look into my code and tell where should I correct it?
Thanks in advance.

**Comment by ppwwyyxx** [comment]
The code looks correct. Please DO NOT run it in jupyter notebooks or other notebooks/IDEs: they have bugs.

If you can reproduce the issue under a normal shell environment, please include details on how to reproduce it: just a link is far from enough.

**Comment by ppwwyyxx** [comment]
When you post this issue you've ignored the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)), which have also instructed users to not trust jupyter / IDEs.

**Comment by ppwwyyxx** [comment]
The commit https://github.com/tensorpack/tensorpack/commit/d48cce3aa399db11a4e6fc35a5a896c96a92b641 linked above would also resolve the issue: it does not make the issue disappear (because I think it is an issue of jupyter notebooks / IDEs). But it will delay throwing the exception until you use `LinearWrap` on the layers. From the code you linked to it appears `LinerWrap` was not used so it will probably be safe.
