### ISSUE TITLE
NotImplementedError after I reinstalled Ubuntu

### ISSUE THREAD

**Issue by yzpick** [tensorpack/tensorpack#1128]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 4. Your environment:
  + Python version: 3.6.7
  + TF version: 1.13.1`python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
  + Tensorpack version: 0.9.4`python -c 'import tensorpack; print(tensorpack.__version__);'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used. 2

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.
===================================================
I got the NotImplementedError after I reinstalled Ubuntu. Everything worked fine before.

File "/home/xxx/.local/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by ppwwyyxx** [comment]
It appears that you implemented `ModelDesc` with methods (probably `_get_inputs`) that are deprecated 1 year ago.

Please update your code following the interface of `ModelDesc` or the examples, e.g.:
https://github.com/tensorpack/tensorpack/blob/f9bf54073a8e1edc546e8a615fc02806d40c760a/examples/basics/mnist-convnet.py#L19-L25

**Comment by yzpick** [comment]
Thanks, I updated the code with new interface, the error is gone.
