### ISSUE TITLE
Request help on get_rpn_anchor_input

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1130]
The code is as follows:
  
    import numpy as np
    import cv2
    from config import finalize_configs, config as cfg
    finalize_configs(is_training=False)
    from data import get_rpn_anchor_input
    im = cv2.imread('VOC2012/JPEGImages/2012_004314.jpg')
    boxes = np.array([[304,189,262,22]], dtype=np.float32)
    is_crowd = np.zeros((1,), dtype=np.int8)
    anchor_labels, anchor_boxes = get_rpn_anchor_input(im, boxes, is_crowd)
    anchors_pos = np.where(anchor_labels==1)
    print(anchors_pos)
    anchors_neg = np.where(anchor_labels==0)
    anchors_ign = np.where(anchor_labels==-1)
    print(len(anchors_neg[0]))
    print(len(anchors_ign[0]))
    
the result is 
  
    (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))
    256
    573184

I'm not sure why the rpn labels for positive anchors is 0? Could you please give some advice? Thanks.

**Comment by ppwwyyxx** [comment]
Because `is_crowd=1`.

**Comment by Remember2018** [comment]
Hi @ppwwyyxx , thanks a lot for your kind reply! 
I'm not sure why the anchors are related to the `is_crowd` parameter. The `is_crowd` seems to be related to the `segmentation`. And the label generation of anchors for RPN is just related to the ground truth boxes, right? Why does the `is_crowd` have an impact to the anchors? And in the above example, the positive anchors is None. I may missed something, could you please give some advice? Thanks.

**Comment by ppwwyyxx** [comment]
`is_crowd=1` means the box is not a box of an instance so I exclude it from positive anchors. This follows the official implementation in Detectron.

Whether you want to include it is up to you.

**Comment by Remember2018** [comment]
@ppwwyyxx thanks a lot for your kind comments and suggestions!  
I think I need to read the Detectron. I must miss many things in the literature. Thanks!

**Comment by Remember2018** [comment]
Hi @ppwwyyxx , in the above example, I set the `is_crowd=0`, and the ground truth box seems still be excluded. Maybe adding an `ADD_GTBOXES`  into the comment would be great!

**Comment by ppwwyyxx** [comment]
There are other reasons making the anchors negative, e.g. the iou is too small, etc.
This purely depends on your data, and without knowing what your data is like (e.g., the shape of it) and how you execute the code (e.g., the configs) there is not much I can tell.

If you expect others to investigate an unexpected issue, please include details for others to reproduce it.

**Comment by Remember2018** [comment]
@ppwwyyxx I'm Sooooory! I forgot to resize the image with short side length. And in the config, I set the following parameters:

        # anchors -------------------------
        _C.RPN.ANCHOR_STRIDE = 16
        # _C.RPN.ANCHOR_SIZES = (32, 64, 128, 256, 512)   # sqrtarea of the anchor box
        # _C.RPN.ANCHOR_RATIOS = (0.5, 1., 2.)
        _C.RPN.ANCHOR_SIZES = (16, 32, 64, 128, 256)   # sqrtarea of the anchor box
        _C.RPN.ANCHOR_RATIOS = (0.125, 0.25, 0.5, 1., 2., 4., 8.)
        _C.RPN.POSITIVE_ANCHOR_THRESH = 0.7
        _C.RPN.NEGATIVE_ANCHOR_THRESH = 0.3

So the following script would work fine now.

      import numpy as np
        import cv2
        
        from tensorpack.dataflow import (
            DataFromList, MapDataComponent, MultiProcessMapDataZMQ, MultiThreadMapData, TestDataSpeed, imgaug)
        from common import (
            CustomResize, DataFromListOfDict, box_to_point8,
            filter_boxes_inside_shape, point8_to_box, segmentation_to_mask, np_iou)
        
        from config import finalize_configs, config as cfg
        finalize_configs(is_training=False)
        from data import get_rpn_anchor_input
        im = cv2.imread('2012_004314.jpg')
        boxes = np.array([[304,189,262,22]], dtype=np.float32)
        
        aug = imgaug.AugmentorList(
                [CustomResize(cfg.PREPROC.TRAIN_SHORT_EDGE_SIZE, cfg.PREPROC.MAX_SIZE)])
        # augmentation:
        im, params = aug.augment_return_params(im)
        points = box_to_point8(boxes)
        points = aug.augment_coords(points, params)
        boxes = point8_to_box(points)
        
        is_crowd = np.zeros((1,), dtype=np.int8)
        anchor_labels, anchor_boxes = get_rpn_anchor_input(im, boxes, is_crowd)
        anchors_pos = np.where(anchor_labels==1)
        print(anchors_pos)
        anchors_neg = np.where(anchor_labels==0)
        anchors_ign = np.where(anchor_labels==-1)
        print(len(anchors_neg[0]))
        print(len(anchors_ign[0]))

the result is:

        (array([16, 17, 18]), array([42, 42, 42]), array([29, 29, 29]))
        253
        573184

I'm sorry for bothering you for my misunderstanding and thanks for your time!
