### ISSUE TITLE
how to apply gradient clipping in tensorpack

### ISSUE THREAD

**Issue by john81923** [tensorpack/tensorpack#1131]
Can not found the gradient clipping interface.

I found a relative function called ` tfutils.gradproc.GlobalNormClip` but I need some example for applying the function into my model.

please help 
thank you

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/d04c8444d4571ccfb8a872ce71acdbcfb39fcdfe/examples/Char-RNN/char-rnn.py#L109-L112

**Comment by john81923** [comment]
@ppwwyyxx  Thank you so much
