### ISSUE TITLE
Can you use different bit-width parameters for different layers? Why not?

### ISSUE THREAD

**Issue by joshclancy** [tensorpack/tensorpack#1137]
In the dorefa.py program, this is commented:

"""
    Return the three quantization functions fw, fa, fg, for weights, activations and gradients respectively
    It's unsafe to call this function multiple times with different parameters
"""

I am attempting to have different layers with different bitwidth activations. Can you please explain why this is a problem? 

Also just to be sure I am jumping into the correct rabbit hole, a 2-bit activation would then be able to convey 4 distinct "codes" correct? As in, the activation function is quantized to become 4 distinct messages.

**Comment by ppwwyyxx** [comment]
> I am attempting to have different layers with different bitwidth activations. Can you please explain why this is a problem?

There is no problem anymore since TF1.7. 
I should remove the documentation.

> 2-bit activation would then be able to convey 4 distinct "codes" correct? As in, the activation function is quantized to become 4 distinct messages.

I do not know what "code" or "message" mean but this sound correct.

**Comment by joshclancy** [comment]
Thanks for the quick response!

I suppose I am asking whether 2-bit activations are really 2-bit. Which now sounds silly haha.

**Comment by ppwwyyxx** [comment]
The documentation was fixed in 8dd254be676d89000a7f4f6fd5cebe78b3499789
