### ISSUE TITLE
How to do multi-scale training efficiently

### ISSUE THREAD

**Issue by yzpick** [tensorpack/tensorpack#1138]
Hi, given a dataset with a fixed image size, I want to randomly scale the images for different batches so that the trained network is robust to images with different scales. Is there an efficient way to do it? I tried to use imgaug.randomresize, but clearly it is not batch-independently. Thanks!

**Comment by ppwwyyxx** [comment]
You can use https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.MapDataComponent and do whatever to your data (including calling augmentors) in the mapping function.

**Comment by yzpick** [comment]
I assume I can add sth like this into my code:
    ds = MapData(ds, lambda dp: [split_input_2(dp[0])[0],split_input_2(dp[0])[1]])
    +++++++
**ds = MapDataComponent(ds, lambda x: cv2.resize(x, (np.random.randint(2, 5) * PATCH_SIZE, np.random.randint(2, 5) * PATCH_SIZE)), 0)**
    +++++++++++
    ds = BatchData(ds, BATCH_SIZE, remainder=not isTrain)

but then, because the model init used PATCH_SIZE, which is fixed at the beginning and cannot match the following resized data feed, how can I solve this issue?

class Model(ModelDesc):
    def __init__(self, **height=PATCH_SIZE, width=PATCH_SIZE**):
        super(Model, self).__init__()
        self.height = height
        self.width = width

    def inputs(self):
        return [InputDesc(tf.float32, (None, self.height, self.width, 3), 'input'),
                InputDesc(tf.float32, (None, self.height, self.width, 3), 'gt'),
                ]

**Comment by ppwwyyxx** [comment]
If your data has different size, you cannot create a model with fixed input size. You need to use `None` for the input size.

**Comment by yzpick** [comment]
Yeah, however, i have several customized layers rely on the height and width, if I change the init to None size, then I got all the ValueError("None values not supported.") in the following customized layer. Wondering if you know a way to bypass this issue for multi-scale training?

**Comment by yzpick** [comment]
OK. I figured it out. Thanks!

**Comment by yzpick** [comment]
Sorry, have to reopen it, since I found out that the following does not work, the image size was fixed and did not change epoch by epoch.
   **rd = np.random.randint(1, 6)
   ds = MapDataComponent(ds, lambda x: cv2.resize(x, (rd * PATCH_SIZE, rd * PATCH_SIZE)), 0)**

I also tried sth like this:
    def myresize(ds):
        augmentors2 = [
            imgaug.RandomResize(xrange=[2,3], aspect_ratio_thres=0),
       ]   
       ds = AugmentImageComponent(ds, augmentors2) 
       return ds
    ds = MapDataComponent(ds, myresize, 0)
or this:
    def myresize(ds):
        rd = np.random.randint(1, 6) 
        ds = cv2.resize(ds, (rd * PATCH_SIZE, rd * PATCH_SIZE))
        return ds
    ds = MapDataComponent(ds, myresize, 0)
all did not work.
Can you please give an example on using augmentors in MapDataComponent? 
Thanks!

**Comment by ppwwyyxx** [comment]
Because you generate the random number only once.
If you want to have different sizes you need to generate the random number inside the lambda.

**Comment by yzpick** [comment]
if I put them inside like this:
    ds = MapDataComponent(ds, lambda x: cv2.resize(x, (np.random.randint(1, 6) * PATCH_SIZE, np.random.randint(1, 6) * PATCH_SIZE)), 0)
    ds = MapData(ds, lambda dp: [split_input_2(dp[0])[0],split_input_2(dp[0])[1]])
    ds = BatchData(ds, BATCH_SIZE, remainder=not isTrain)

 then here are the errors:

[0411 15:58:27 @common.py:145] ERR Shape of all arrays to be batched: [(768, 768, 3), (1280, 1280, 3), (1024, 1024, 3), (1280, 1280, 3)]
[0411 15:58:27 @common.py:142] ERR Cannot batch data. Perhaps they are of inconsistent shape?

where should I put the mapdatacomponent exactly?

**Comment by ppwwyyxx** [comment]
You apparently cannot batch data of different shapes, right?
So you probably want to transform your images after batching them and transform all images in a batch with the same size.

**Comment by yzpick** [comment]
I tried, then the opencv function cannot work:
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3427: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

**Comment by ppwwyyxx** [comment]
Sorry but I can't see how is this related to tensorpack.

**Comment by yzpick** [comment]
I simply change the order:

    ds = BatchData(ds, BATCH_SIZE, remainder=not isTrain)
    ds = MapDataComponent(ds, lambda x: cv2.resize(x, (np.random.randint(1, 6) * PATCH_SIZE, np.random.randint(1, 6) * PATCH_SIZE)), 0)
    ds = MapData(ds, lambda dp: [split_input_2(dp[0])[0],split_input_2(dp[0])[1]])
it seems after the batchdata, the ds has a different data format that opencv cannot process, but I don't know what exactly changed. since if you put the MapDataComponent in front batchdata, opencv resize can work.

**Comment by ppwwyyxx** [comment]
>  after the batchdata, the ds has a different data format that opencv cannot process, but I don't know what exactly changed.

after `BatchData`, the data becomes a batch.

i.e. it has one more dimension.

**Comment by yzpick** [comment]
Thanks, I still have one thing I don't understand.

I am trying to do this:
**for ii in range(0, len(ds))**:
        print(ii)
        for i in range(1, BATCH_SIZE):#dp[0] [4,256,512,3] 
            **ds** = MapDataComponent(**ds**, lambda x: cv2.resize(x[i,:,:,:], (2 * PATCH_SIZE, 2 * 2 * PATCH_SIZE)), **ii**)
   
which does not work, I assume I pass the ds with index ii so that the x in lambda should be the image batch [batchnum, height, width, channel], but clearly it is not, since cv2.resize cannot process it.  But your MapDataComponent clearly states that "input DataFlow which produces either list or dict." and "index (int or str) – index or key of the component." 

But if i did sth like this:
ii=0
**for dp in ds.get_data()**:
        print(ii)
        for i in range(1, BATCH_SIZE):#dp[0] [4,256,512,3] 
            **dp[0]**= MapDataComponent(**dp[0]**, lambda x: cv2.resize(x[i,:,:,:], (2 * PATCH_SIZE, 2 * 2 * PATCH_SIZE)), **ii**)
        ii=ii+1
the code can run, but after i printing out the result, the dataflow size did not change at all, the image size is still the PATCH_SIZE.

I don't know what I should input into the MapDataComponent now.

**Comment by ppwwyyxx** [comment]
I do not understand your question, but this will do multi-scale training:
```python
def resize(x):
    size = (np.random.randint(1, 6) * PATCH_SIZE, np.random.randint(1, 6) * PATCH_SIZE)
    x = [cv2.resize(a, size) for a in x]
    return np.asarray(x)

ds = BatchData(ds, BATCH_SIZE, remainder=not isTrain, use_list=True)
ds = MapDataComponent(ds, resize, 0)
```

**Comment by yzpick** [comment]
finally.... Thanks so much!
