### ISSUE TITLE
I'm building a Docker image for tensorpack, what should directories should I mount?

### ISSUE THREAD

**Issue by AndreaPi** [tensorpack/tensorpack#1139]
Hi,

first of all, compliments for the impressive piece of work! I just recently started using tensorpack, after meeting @ppwwyyxx in the Matterport's Mask R-CNN repo, but it looks great. I'm working with Mask R-CNN, and I'd like to build a Docker image for tensorpack. What files/directories from the tensorpack home dir should I map to the Docker container? For now I'm mostly running some examples from a Jupyter server started inside the container, so for sure I need to map `examples` and `tensorpack`. 

However, I may need to do actual development inside the container, because the Docker images contains all the CUDA/tensorflow-gpu libraries I need in order to use my machine's GPUs. In this case, which directories/files should I map at runtime? All the directories except for `docs`? I guess I don't need `setup.cfg` and `setup.py` (they're only needed when I build the image, not when I run the container). Do I need to map `tox.ini`?

**Comment by ppwwyyxx** [comment]
Thanks for your support.
If your goal is to use tensorpack, `tensorpack/` and `examples/` are enough.
`scripts/` contains some small scripts to work with checkpoints. They may be useful but they are quite simple so you may write your own as well.
