### ISSUE TITLE
Mapillary Vistas Dataset

### ISSUE THREAD

**Issue by AlbertoMCS** [tensorpack/tensorpack#1140]
Hi, 

I've been trying to train Mask RCNN pretrained with COCO dataset with Mapillary dataset ( I followed this repo https://github.com/matterport/Mask_RCNN). 

I managed to transform Mapillary Vistas datastet into COCO format but no succeed when trainnig the model. I just was able to get a checkpoint using 2 images, when I try to train with more than 2 images a "MemoryError" came up. I tried in Google Cloud using 8 V100 GPU but even with that power I wasn't able to train it.

After looking at your repo I saw you implemented Mask RCNN so I would like to try your repo with Mapillary Dataset, do you think that this make sense? will I have to change your code dramatically to adapt Mapillary dataset to your model?.

Many thanks, 
Alberto.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md explains how to train on a different dataset.

**Comment by monjurulkarim** [comment]
@AlbertoMCS Hi, how did you transform Mapillary Vistas dataset into COCO format? I am also trying to train the Mask RCNN inplementation by matterport  with Mapillary Vistas dataset. 
If you could share how you did transform the data would be very helpful for me.
Thanks.

**Comment by AlbertoMCS** [comment]
Hi @monjurulkarim,  I used this repo to convert Mapillary dataset into COCO format: 

https://github.com/Luodian/Mapillary2COCO

**Comment by monjurulkarim** [comment]
@AlbertoMCS Many thanks!

**Comment by AlbertoMCS** [comment]
Hi @monjurulkarim you have to request the data from Mapillary Dataset website: 

https://www.mapillary.com/dataset/vistas?pKey=cc5dEAyQECBFF9MN3MbdZA&lat=-1.696362232706349&lng=-35.07353824409381&z=2.59180623161258

After the request is sent they will get back to you by email providing a link to the data.

**Comment by monjurulkarim** [comment]
@AlbertoMCS Many thanks! I really appreciate it.

**Comment by monjurulkarim** [comment]
@AlbertoMCS Hi, how long did it take for you to completely convert the dataset? It is taking too long for me. I started 8 days ago, but still it's working.

**Comment by AlbertoMCS** [comment]
Hi @monjurulkarim , 

Yes, it takes time. As long as the script is working you should be happy. 

It took me 7-8 days to split the instances images into small elements and 4-5 days to create the json files. I guess it also depend on the machine you are using, mine has a CORE i7 7th Gen.

**Comment by g-luo** [comment]
@AlbertoMCS do you have the original meta files for the dataset, including the GPS coordinates?
