### ISSUE TITLE
FasterRCNN: How can I get more bounding boxes for an image?

### ISSUE THREAD

**Issue by zlian2016** [tensorpack/tensorpack#1141]
Hi! Thanks for Tensorpack!

Now, I need more(30 or more) bounding boxes for an image. How can I do this?

Thank you!

**Comment by ppwwyyxx** [comment]
I'm not sure I understand your question. 

If you are running a pre-trained FasterRCNN model from tensorpack model zoo and expect to see more boxes, you can adjust the threshold in `cfg.TEST.RESULT_SCORE_THRESH_VIS`.

**Comment by zlian2016** [comment]
> I'm not sure I understand your question.
> 
> If you are running a pre-trained FasterRCNN model from tensorpack model zoo and expect to see more boxes, you can adjust the threshold in `cfg.TEST.RESULT_SCORE_THRESH_VIS`.

Thank you! I will have a try and come back later!
