### ISSUE TITLE
ImportError: No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by zlian2016** [tensorpack/tensorpack#1143]
Hi! Thanks for tensorpack!

I installed the dependencies:
python=3.5.6
tensorflow=1.10.0
pycocotools: pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI (cocotools on windows, pycocotools=2.0)

But I got an Error when I run the train.py. 'ImportError: No module named 'pycocotools._mask''
I need some help! Thank you!

**Comment by ppwwyyxx** [comment]
I believe this is an issue of the project https://github.com/philferriere/cocoapi you're using and unrelated to tensorpack.

**Comment by AndreaPi** [comment]
as @ppwwyyxx said, this may be an issue related to Phil's project. Try this version instead and let us know if this works:

`pip3 install git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI`

You're training on COCO, right?
