### ISSUE TITLE
Understanding better the Fast R-CNN implementation

### ISSUE THREAD

**Issue by AndreaPi** [tensorpack/tensorpack#1144]
Hi,

reading the [Notes for the Faster R-CNN example](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md) I'm a little bit confused. Point 2 of the section **Model** says

> We use ROIAlign, and tf.image.crop_and_resize is NOT ROIAlign.

But point 4 of section **Speed** says

> This implementation does not use specialized CUDA ops (e.g. AffineChannel, ROIAlign). Therefore it might be slower than other highly-optimized implementations.

So, is ROIAlign used or not?

**Comment by ppwwyyxx** [comment]
It is used. https://github.com/tensorpack/tensorpack/blob/400a07e62553ad4d77c6630762eafd36739cc4ac/examples/FasterRCNN/model_box.py#L157

**Comment by AndreaPi** [comment]
Ok, I'll make a PR changing point 4 of section **Speed** in [NOTES.md](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md) to:

> This implementation does not use specialized CUDA ops (e.g. AffineChannel). Therefore it might be slower than other highly-optimized implementations. 

unless you have something against it.

**Comment by ppwwyyxx** [comment]
It does not use specialized CUDA  ops for roialign. This is still true.
