### ISSUE TITLE
Adding Jupyter notebook examples for instance segmentation

### ISSUE THREAD

**Issue by AndreaPi** [tensorpack/tensorpack#1145]
I think that adding some Jupyter notebooks illustrating the application of the Mask R-CNN to the COCO dataset would foster widespread adoption of this great project. Something like [this](https://github.com/matterport/Mask_RCNN/blob/master/samples/coco/inspect_data.ipynb) or [this](https://github.com/matterport/Mask_RCNN/blob/master/samples/coco/inspect_model.ipynb).

If you don't have time/plans to implement this feature, I _might_ try to create a PR. In this case, where should I put the notebooks inside the project? Would [this location](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) be ok?

**Comment by ppwwyyxx** [comment]
Thanks! That location would be great.

**Comment by ppwwyyxx** [comment]
Added an example of fine-tuning on toy dataset: https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/BALLOON.md
