### ISSUE TITLE
"ValueError: not enough values to unpack (expected 2, got 1)" when running train.py in Mapillary Dataset.

### ISSUE THREAD

**Issue by AlbertoMCS** [tensorpack/tensorpack#1146]
Hi,

Sorry for not use the format provided to report a bug but I thought this issue is better explained this way. 

I have Mapillary Dataset in this format: 
COCO/DIR/
  annotations/
    instances_train2017.json
    instances_val2017.json
  train2017/
      __CRyFzoDOXn6unQ6a3DnQ.jpg
      __d47X7jIPcnuZkob5C_DA.jpg
      _0A_W6lEi-7W0RvVEiKkyQ.jpg
      _0P04ZWQtMtPMwx3lgLdWA.jpg
      _0R1piHytmNxzCyp5YjF8g.jpg
  
val2017/
    _3wOt13eozLKpGw0yOBBrg.jpg
    _4g6iIzKJPj_8_PTRPIV3Q.jpg

I want to first train it with 5 images train and 2 images val. 

When running this command (I am working in Colab)

!python train.py --config \
    MODE_MASK=True MODE_FPN=True \
    DATA.BASEDIR=/content/drive/Colab Notebooks/otro/tensorpack/examples/FasterRCNN/COCO/DIR \
    BACKBONE.WEIGHTS=/content/drive/Colab Notebooks/otro/tensorpack/examples/FasterRCNN/models/ImageNet-R50-AlignPadding.npz

I get this error: 

Traceback (most recent call last):
  File "train.py", line 418, in <module>
    cfg.update_args(args.config)
  File "/content/drive/Colab Notebooks/otro/tensorpack/examples/FasterRCNN/config.py", line 46, in update_args
    keys, v = cfg.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

Any idea what's the problem? 

Thanks.

**Comment by ppwwyyxx** [comment]
> Colab Notebooks

There is a space in between and therefore they end up being two arguments.
You need to quote your command line arguments.

**Comment by AlbertoMCS** [comment]
Hi, 

Sorry I think I don't understand well. What do I have to quote exactly? , what do you mean about "command line arguments"?

Thanks a lot.
Alberto.

**Comment by ppwwyyxx** [comment]
"DATA.BASEDIR=/content/drive/Colab Notebooks/otro/tensorpack/examples/FasterRCNN/COCO/DIR"

and similarly for the weights
