### ISSUE TITLE
multi-pod  with multi-gpu running on kubernetes

### ISSUE THREAD

**Issue by perrynzhou** [tensorpack/tensorpack#1149]
### 1. Running Multi-Pod With Multi-GPUS:

(1) **Multi-Pods Running Four Or More GPUS,Each Pod Contains Four GPUS**

(2) **Running Script For Python(imagenet-xxx.py) From Your Project**

(3) **Parameter Is The Same To Your Example**

### 2. I observed:

(1) **communication between gpu can't work**

(2) **gradient not be update between gpus**

### 3. What you expected, if not obvious.

(1)**description for your guiedeline too sample?**
(2)**can you give me details document about your case with multi-machine with multi-gpus?**

### 4. Your environment:
  + Python version: python3
  + Hhorovod version:0.16.0
  + Tensorpack version: 0.9.4

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
