### ISSUE TITLE
MemoryError when train FasterRCNN example with Mapillary Dataset, 4 x NVIDIA Tesla T4

### ISSUE THREAD

**Issue by AlbertoMCS** [tensorpack/tensorpack#1152]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:
TRAIN FasterRCNN network with Mapillary Dataset

(1) **If you're using examples, what's the command you run:**
python3 train.py --config MODE_MASK=True MODE_FPN=True 'DATA.BASEDIR=/home/federicolondon2019/tensorpack/COCO/DIR' 'BACKBONE.WEIGHTS
=/home/federicolondon2019/tensorpack/models/ImageNet-R50-AlignPadding.npz'

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
I changed dataset.py and config.py. 

DATASET.PY:  (from line 17 to 32)
Original:
```python
class COCODetection:
    # handle the weird (but standard) split of train and val
    _INSTANCE_TO_BASEDIR = {
        'valminusminival2014': 'val2014',
        'minival2014': 'val2014',
    }

    COCO_id_to_category_id = {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 27: 25, 28: 26, 31: 27, 32: 28, 33: 29, 34: 30, 35: 31, 36: 32, 37: 33, 38: 34, 39: 35, 40: 36, 41: 37, 42: 38, 43: 39, 44: 40, 46: 41, 47: 42, 48: 43, 49: 44, 50: 45, 51: 46, 52: 47, 53: 48, 54: 49, 55: 50, 56: 51, 57: 52, 58: 53, 59: 54, 60: 55, 61: 56, 62: 57, 63: 58, 64: 59, 65: 60, 67: 61, 70: 62, 72: 63, 73: 64, 74: 65, 75: 66, 76: 67, 77: 68, 78: 69, 79: 70, 80: 71, 81: 72, 82: 73, 84: 74, 85: 75, 86: 76, 87: 77, 88: 78, 89: 79, 90: 80}  # noqa
    """
    Mapping from the incontinuous COCO category id to an id in [1, #category]
    For your own dataset, this should usually be an identity mapping.
    """

    # 80 names for COCO
    class_names = [
        "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch", "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors", "teddy bear", "hair drier", "toothbrush"]  # noqa
```

Now: 
```
class COCODetection:
    # handle the weird (but standard) split of train and val
    _INSTANCE_TO_BASEDIR = {
        'valminusminival2014': **'val2017',**
        'minival2014': '**val2017**',
    }

    COCO_id_to_category_id = **{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25, 26: 26, 27: 27, 28: 28, 29: 29, 30: 30, 31: 31, 32: 32, 33: 33, 34: 34, 35: 35, 36: 36, 37: 37, 38: 38}**  # noqa
    """
    Mapping from the incontinuous COCO category id to an id in [1, #category]
    For your own dataset, this should usually be an identity mapping.
    """

    # 80 names for COCO
    class_names = [
        **'BG', 'Bird', 'Ground_Animal', 'Crosswalk_Plain', 'Person', 'Bicyclist', 'Motorcyclist', 'Other_Rider', 'Lane_Marking_-_Crosswalk', 'Banner', 'Bench', 'Bike_Rack', 'Billboard', 'Catch_Basin', 'CCTV_Camera', 'Fire_Hydrant', 'Junction_Box', 'Mailbox', 'Manhole', 'Phone_Booth', 'Street_Light', 'Pole', 'Traffic_Sign_Frame', 'Utility_Pole', 'Traffic_Light', 'Traffic_Sign_(Back)', 'Traffic_Sign_(Front)', 'Trash_Can', 'Bicycle', 'Boat', 'Bus', 'Car', 'Caravan', 'Motorcycle', 'Other_Vehicle', 'Trailer', 'Truck', 'Wheeled_Slow'**]  # 
```
CONFIG.PY (from 82 to 96)

Original:
```
# dataset -----------------------
_C.DATA.BASEDIR = '/path/to/your/DATA/DIR'
# All TRAIN dataset will be concatenated for training.
_C.DATA.TRAIN = ('train2014', 'valminusminival2014')   # i.e. trainval35k, AKA train2017
# Each VAL dataset will be evaluated separately (instead of concatenated)
_C.DATA.VAL = ('minival2014', )  # AKA val2017
# This two config will be populated later by the dataset loader:
_C.DATA.NUM_CATEGORY = 0  # without the background class (e.g., 80 for COCO)
_C.DATA.CLASS_NAMES = []  # NUM_CLASS (NUM_CATEGORY+1) strings, the first is "BG".
# whether the coordinates in the annotations are absolute pixel values, or a relative value in [0, 1]
_C.DATA.ABSOLUTE_COORD = True
_C.DATA.NUM_WORKERS = 5  # number of data loading workers

# basemodel ----------------------
_C.BACKBONE.WEIGHTS = ''   # /path/to/weights.npz

Now: 
# dataset -----------------------
_C.DATA.BASEDIR = '**/home/federicolondon2019/tensorpack/COCO/DIR'**
# All TRAIN dataset will be concatenated for training.
_C.DATA.TRAIN = **('train2017')**   # i.e. trainval35k, AKA train2017
# Each VAL dataset will be evaluated separately (instead of concatenated)
_C.DATA.VAL = **('val2017')**  # AKA val2017
# This two config will be populated later by the dataset loader:
_C.DATA.NUM_CATEGORY = **37**  # without the background class (e.g., 80 for COCO)
_C.DATA.CLASS_NAMES = **['BG', 'Bird', 'Ground_Animal', 'Crosswalk_Plain', 'Person', 'Bicyclist', 'Motorcyclist', 'Other_Rider', 'Lane_Marking_-_Crosswalk', 'Banner', 'Bench', 'Bike_Rack', 'Billboard', 'Catch_Basin', 'CCTV_Camera', 'Fire_Hydrant', 'Junction_Box', 'Mailbox', 'Manhole', 'Phone_Booth', 'Street_Light', 'Pole', 'Traffic_Sign_Frame', 'Utility_Pole', 'Traffic_Light', 'Traffic_Sign_(Back)', 'Traffic_Sign_(Front)', 'Trash_Can', 'Bicycle', 'Boat', 'Bus', 'Car', 'Caravan', 'Motorcycle', 'Other_Vehicle', 'Trailer', 'Truck', 'Wheeled_Slow'**]  # NUM_CLASS (NUM_CATEGORY+1) strings, the first is "BG".
# whether the coordinates in the annotations are absolute pixel values, or a relative value in [0, 1]
_C.DATA.ABSOLUTE_COORD = True
_C.DATA.NUM_WORKERS = 5  # number of data loading workers

# basemodel ----------------------
_C.BACKBONE.WEIGHTS = **'/home/federicolondon2019/tensorpack/models/ImageNet-R50-AlignPadding.npz'   # /path/to/weights.npz
[Mapillary_FasterRCNN.docx](https://github.com/tensorpack/tensorpack/files/3085597/Mapillary_FasterRCNN.docx)
**
```

(3) **If not using examples, tell us what you did:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let other __reproduce__ your issues. 
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
I get a MemoryError when running train.py in Google Cloud with 4 Tesla T4

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `CMD 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.
I only included 5 images to train and 2 images to val

### 3. What you expected, if not obvious.
I expected to get a log 

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html 
before posting.

If you expect certain accuracy, only in one of the two conditions can we help with it:
(1) You're unable to reproduce the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to train a model to certain accuracy is a machine learning question.
We do not answer machine learning questions and it is your responsibility to 
figure out how to make your models more accurate.

### 4. Your environment:
  + Python version: 3.5.3 
  + TF version: 1.13.1
  + Tensorpack version: v0.9.4
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

Attached the entire output when running. 

Thanks
[Mapillary_FasterRCNN.pdf](https://github.com/tensorpack/tensorpack/files/3085611/Mapillary_FasterRCNN.pdf)

**Comment by ppwwyyxx** [comment]
Please include your logs as requested in the issue template.
You can change number of dataflow workers with `cfg.DATA.NUM_WORKERS` to reduce memory usage.

**Comment by AlbertoMCS** [comment]
Hi ppwwyyxx, 

Thanks for your recommendation. 

I increased the number of GPU to 8 Tesla V100 and I decreased the cfg.DATA.NUM_WORKERS to 1 but I  still get MemoryError when trainning with Mapillary Dataset, I am just using 5 images to train and 2 to validate. 

I didn't change anything from the last post, just cfg.DATA.NUM_WORKERS. 

The completed log is attached as pdf. 

Any idea what is happening?

Thanks for your support!
[Faster_RCNN_8GPU_MVD.pdf](https://github.com/tensorpack/tensorpack/files/3112474/Faster_RCNN_8GPU_MVD.pdf)

**Comment by ppwwyyxx** [comment]
How large is the CPU memory and what's the amount of memory you observed (from `top -o %MEM`, screenshot will be helpful) that the code is taking before it crashed?

**Comment by AlbertoMCS** [comment]
Hi ppwwyyxx, 

Thanks for your answer.

I changed the CPU from 2 units to 16 and the MemoryError disappear!. However after finishing the first epoch I got this error: 

```
[0424 15:42:46 @input_source.py:556] Pre-filling StagingArea ...
[0424 15:42:50 @input_source.py:560] 1 element was put into StagingArea on each tower.
2019-04-24 15:45:30.227941: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
[0424 15:45:53 @param.py:161] [HyperParamSetter] At global_step=1, learning_rate changes from 0.003300 to 0.003307
  0%|2                                                                                                                                          |1/500[03:07<25:56:02, 0.01it/s]
100%|##########################################################################################################################################################################################|500/500[41:59<00:00, 0.02it/s]
[0424 16:24:46 @base.py:285] Epoch 1 (global_step 500) finished, time:41 minutes 59 seconds.
[0424 16:24:46 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0424 16:24:46 @misc.py:109] Estimated Time Left: 20 days 23 hours 27 minutes 50 seconds
2019-04-24 16:24:46.991885: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 522, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/train/interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/train/base.py", line 344, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/train/base.py", line 316, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/train/base.py", line 288, in main_loop
    self._callbacks.trigger_epoch()
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/callbacks/base.py", line 156, in trigger_epoch
    self._trigger_epoch()
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/callbacks/group.py", line 97, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/callbacks/base.py", line 156, in trigger_epoch
    self._trigger_epoch()
  File "/home/federicolondon2019/.local/lib/python3.5/site-packages/tensorpack/callbacks/prof.py", line 85, in _trigger_epoch
    if stats == -1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
MultiProcessMapDataZMQ successfully cleaned-up.
```
Attached the full log if needed.
[log_16CPU_8GPUV100.pdf](https://github.com/tensorpack/tensorpack/files/3114142/log_16CPU_8GPUV100.pdf)


Let me know if you want me to open a new issue with this error or you think post it here is OK,

Thank you, 
Alberto.

**Comment by ppwwyyxx** [comment]
>  if stats == -1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
MultiProcessMapDataZMQ successfully cleaned-up.

This issue was fixed a week ago in tensorpack. You can install latest tensorpack with `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`

**Comment by AlbertoMCS** [comment]
Hi, 

Thank you for the response. 

I installed latest version of tensorpack and now the training process works.

Every epoch takes 25 minutes approx. I interrupted the trainning running after the second epoch because I would like to test the inference before trying to train the entire Mapillary Dataset, and these files were created in a new folder called train_log:

- events.out.tfevents.1556184012.instance-1
- graph-0425-092053.meta
- log.txt
- stats.json

I have 2 questions: 

1- I think any of these files correspond with the new model trained?, in other words, when the model file will be created? do I have to wait till a number of epochs?

Thanks a lot.

**Comment by ppwwyyxx** [comment]
> 1- I think any of these files correspond with the new model trained?, in other words, when the model file will be created? do I have to wait till a number of epochs?

See code below in the example:
https://github.com/tensorpack/tensorpack/blob/5982977058218f6aae47e74dad6deb898bbb3062/examples/FasterRCNN/train.py#L192-L194

> python train.py --predict input1.jpg --load C:/Users/GOM81687/Desktop/tensorpack/models/COCO-R101FPN-MaskRCNN-BetterParams.npz --config MODE_MASK=True MODE_FPN=True DATA.BASEDIR=C:/Users/GOM81687/Desktop/tensorpack/COCO/DIR BACKBONE.WEIGHTS=C:/Users/GOM81687/Desktop/tensorpack/models/ImageNet-R50-AlignPadding.npz

Your command is wrong.  See [README](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN#inference):
> Evaluation and prediction will need to be run with the corresponding configs used in training.
