### ISSUE TITLE
How to use Synchronized Multi-GPU Batch Normalization in the validation or testing phase?

### ISSUE THREAD

**Issue by MiZhangWhuer** [tensorpack/tensorpack#1154]
Hi, yuxin! I am trying to use the Synchronized Multi-GPU Batch Normalization in the testing phase as follows:

def preact_conv(inputs, n_filters, kernel_size=[3, 3], dropout_p=0.2, bnscope=None):
    # preact = tf.nn.relu(slim.batch_norm(inputs, fused=True))
    preact = tf.nn.relu(BatchNorm(bnscope, inputs))
    conv = slim.conv2d(preact, n_filters, kernel_size, activation_fn=None, normalizer_fn=None)
    if dropout_p != 0.0:
        conv = slim.dropout(conv, keep_prob=(1.0 - dropout_p))
    return conv

In the code, I replace the slim.batch_norm with BatchNorm in tensorpack. Everything run smoothly in the training phase. However, the following error occurs during the testing phase:
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 859, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable 0/gamma already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? 

How can I use BatchNorm layer in tensorpack correctly in the testing phase? Could you please provide more examples?

**Comment by ppwwyyxx** [comment]
All tensorpack examples that have BatchNorm use BatchNorm correctly in testing phase.

For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by MiZhangWhuer** [comment]
> All tensorpack examples that have BatchNorm use BatchNorm correctly in testing phase.
> 
> For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

@ppwwyyxx Thanks for the repaid reply. I have checked my code again, and find that this issue is caused by the incorrect usage of tf.name_scope and tf.variable_scope. In the training phase, the "tower0" "tower1"...seem to affect the variable scopes. I modify the code as follows and it works:

    scope = scope[scope.find('/') + 1:]
    with tf.name_scope(scope) as sc:
        cur_bnscope = sc  # different bn name within different transitions
        if is_training:
            cur_bnscope = cur_bnscope[cur_bnscope.find('/') + 1:]
	    with tf.name_scope(cur_bnscope):
		# print('bnscope', bnscope)
		preact = tf.nn.relu(BatchNorm(bnscope, inputs))
		# preact = tf.nn.relu(slim.batch_norm(inputs, fused=True))
		conv = slim.conv2d(preact, n_filters, kernel_size, activation_fn=None, normalizer_fn=None)
		if dropout_p != 0.0:
		    conv = slim.dropout(conv, keep_prob=(1.0 - dropout_p))
		return conv

**Comment by ppwwyyxx** [comment]
See rule 3: https://tensorpack.readthedocs.io/tutorial/trainer.html#rules-of-tower-function. In short, you should not let name of the variables (and also name of layers) depend on the name scope.
