### ISSUE TITLE
Stuck on Pre-filling StagingArea

### ISSUE THREAD

**Issue by snownus** [tensorpack/tensorpack#1155]
Settings:
Tensorflow 1.9.0
Cuda 9.0
Tensorpack 0.8.9

I use the official training code (alexnet-dorefa.py), but stuck on Pre-filling StagingArea. When I change the `SyncMultiGPUTrainerReplicated` -> `SyncMultiGPUTrainerParameterServer`, the training works. Can anyone provide some suggestions? I have tried to change tensorflow version  1.9.0, 1.10.0, 1.11.0, and tensorpack to latest one 0.9.4, but still fails if using official SyncMultiGPUTrainerReplicated.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by snownus** [comment]
@ppwwyyxx ， I have created another issue followed the template you sent.
