### ISSUE TITLE
Example on neural network architecture searching (NAS)

### ISSUE THREAD

**Issue by MiZhangWhuer** [tensorpack/tensorpack#1157]
Is there any plan to give some examples on neural network architecture searching task (NAS)?
I think providing the NAS examples help understand how tensorpack benefit the dynamic architecture searching, which offers the SOTA directions on deep learning task.

**Comment by ppwwyyxx** [comment]
This is answered in the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE/feature-requests.md).

In brief, if you can train one network, then you can train many networks, then you can do NAS.
