### ISSUE TITLE
Cropping and Padding input image and labels for data augmentation

### ISSUE THREAD

**Issue by MiZhangWhuer** [tensorpack/tensorpack#1159]
Hi, yuxin. I tried to implement the cropping and padding in the data augmentation stage as follows:
   
         def preprocess(imandlabel):

                im, label = imandlabel
                assert im is not None, 'aaaaaa'
                assert label is not None, 'bbbbbbb'

                im = im.astype('float32')
                label = label.astype('uint8')
                print('***************************')
                print('img_bef', im.shape)
                print('label_bef', label.shape)
                print('***************************')

                # im = randomHueSaturationValue(im, hue_shift_limit=(-50, 50), sat_shift_limit=(-50, 50), val_shift_limit=(-50, 50))
                #
                # im, label = randomScale(im, label)
                # im, label = randomHorizontalFlip(im, label)
                im, label = randomCropPad(im, label, side, side, ignore_label=255, isTrain=isTrain,
                                          isSqueeze=False)
                ret = [im]
                # if isDownSample:
                #     label = cv2.resize(label, (gr_shape / 8, gr_shape / 8), interpolation=cv2.INTER_NEAREST)
                label = np.asarray(label, dtype='uint8')
                print('***************************')
                print('img_aft', im.shape)
                print('label_aft', label.shape)
                print('***************************')
                ret.append(label)
                return ret

            ds = MapDataComponent(ds, preprocess)
            if isTrain:
               ds = BatchData(ds, args.batch_size // args.nr_gpu, remainder=not isTrain)
               ds = PrefetchData(ds, 5, 5)

I follow the tensorpack advance documentation with "MapDataComponent" function. However, the program gets hunging up. When the "ds = MapDataComponent(ds, preprocess)" is commented from source code, the program runs smooth. How can I use the MapDataComponent function correctly?

**Comment by ppwwyyxx** [comment]
Could yoy try commenting out `PrefetchData`? This may show you the correct error messages.

Also, what you need may be `MapData`.

**Comment by ppwwyyxx** [comment]
Closing as there is no response.
