### ISSUE TITLE
assert isinstance(cost, tf.Tensor),  cost AssertionError: None

### ISSUE THREAD

**Issue by INERKIDFYN** [tensorpack/tensorpack#1162]
### 1.My code:https://paste.ubuntu.com/p/CzB8fTXQ7g/
I wrote the code according to examples/resnet
### 2.My error:https://paste.ubuntu.com/p/fWJtjrw9m4/
I want to know why the cost is None. I am sure that the input(images) is right and not None.

### 3. My environment:
  + Python version: 3.6.
  + TF version: 1.13.1(tensorflow-gpu).
  + Tensorpack version: 0.9.4.

**Comment by ppwwyyxx** [comment]
You seem to be following examples that are more than 1 years old.

If you look at any of the examples in this repo, you need to `return cost` in `build_graph` instead of setting `self.cost`.

**Comment by INERKIDFYN** [comment]
@ppwwyyxx 
It works! Thank you soooooooo much!
