### ISSUE TITLE
FasterRCNN ease of use 

### ISSUE THREAD

**Issue by stealthdaimma** [tensorpack/tensorpack#1163]
First of all, thank you very much for putting so much work and make your project in public.

I've been looking for a framework that is easy to use to do multi-GPU training for object detection and segmentation, and stumbled across Tensorpack and the FasterRCNN example. I was initially intrigued by the simplicity and ease of use in the 'basics' examples. 

Object detection and segmentation are some of the most popular tasks. To make Tensorpack more accessible and widespread, the FasterRCNN example should serve as a simple baseline to show how to do multi-GPU training easy regardless of the model (say SSD, YOLO, etc.) and the dataset for general detection/ segmentation. 

But from looking at the FasterRCNN example, IMHO it looks pretty complicated and not so easy to use, unlike one of the 'basics' examples. 

- First, 'train.py' has more than 500 lines of code, and all the code for training, evaluation, and inference are in the same 'train.py.'  And it was pretty time-consuming to understand the structure. I would appreciate if we have a separate file like test.py to do the inference. I understand that during training, periodic evaluation is needed to check accuracy, but code like 'do_evaluate()' can just go to 'eval.py', and 'do_predict()' can go to test.py. 

- Also, ResNetC4Model and ResNetFPNModel classes are very long, but they do not need to be in 'train.py' and can be placed in another file.  If people want to deploy their own model like SSD,  they are more interested in the code that is used for training as in 'train.py' than the RCNN models. 'train.py' just needs DetectionModel class, and that model can just inherit DetectionModel class. 

- And I was confused why I found things like 'get_all_anchors' are in 'data.py'. IMHO they can be better placed at 'model_rpn.py' or something. 

- For training with the user's own dataset, I think users would appreciate more detailed documentation in 'dataset.py'.

I'm not an expert like you. But these are some of the enhancement suggestions I had. Again, I really appreciate your hard work continuous improvement for this project.

**Comment by ppwwyyxx** [comment]
Thanks for your suggestions! They make more sense indeed. 
I'll improve the code structure based on them.

**Comment by ppwwyyxx** [comment]
All done. Thanks for your suggestions!

For users' own dataset, just added an example of fine-tuning on toy dataset: https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/BALLOON.md
