### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by junxiaoge** [tensorpack/tensorpack#1166]
You encountered this error while training your dataset
![1556264003(1)](https://user-images.githubusercontent.com/28887820/56791100-dc00ad80-6838-11e9-8237-c2da9fc1734a.png)

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

Also read the docs https://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.ModelSaver

**Comment by songgc** [comment]
It is better to fix the dependency issue first.
apt install libcap-dev
pip install python-prctl

**Comment by ppwwyyxx** [comment]
Closing as there is no response after a week.
