### ISSUE TITLE
export-model.py:58 Attempting to use uninitialized value filter

### ISSUE THREAD

**Issue by kolinwei** [tensorpack/tensorpack#1170]
I user command line like this,
python export-model.py --export compact --load ShuffleNetV2-1x.npz
but i meet this error

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value filter
	 [[node filter (defined at export-model.py:58) ]]
	 [[node filter (defined at export-model.py:58) ]]

why?

**Comment by ppwwyyxx** [comment]
Because this is not the right way to use it and the right way to use `export-model.py` is written in its code. It is not for ShuffleNet and you cannot use it for shufflenet.

See https://tensorpack.readthedocs.io/tutorial/inference.html
