### ISSUE TITLE
An error of the function(viz_cam)

### ISSUE THREAD

**Issue by INERKIDFYN** [tensorpack/tensorpack#1171]
### 1. code:

(1) **I used the example:  https://github.com/tensorpack/tensorpack/blob/v0.9.4/examples/Saliency/CAM-resnet.py:**

(2) **I changed the example a little bit. This is my code:  https://paste.ubuntu.com/p/RwQKCHc5rS/**

(3)**The train_log:**
![捕获1](https://user-images.githubusercontent.com/42964873/56898482-b935f980-6ac3-11e9-85cb-aed0201c4677.PNG)

### 2. error:

(1) **My error:  https://paste.ubuntu.com/p/pTZyz59qW2/**

(2) **I want to know how can I get the layer 'pool5'**

### 3. My environment:
py36
![捕获](https://user-images.githubusercontent.com/42964873/56898320-5ba1ad00-6ac3-11e9-98e1-74af223da0b0.PNG)

**Comment by INERKIDFYN** [comment]
I've worked it out! 'pool5/output' is right

**Comment by ppwwyyxx** [comment]
Yes. See https://tensorpack.readthedocs.io/tutorial/symbolic.html#access-relevant-tensors
