### ISSUE TITLE
How to understand the data shuffling in get_data function

### ISSUE THREAD

**Issue by BigFishMaster** [tensorpack/tensorpack#1172]
When I use the resnet code to train my own model， I find ```steps_per_epoch``` is set to 1281167, which is the size of ImagNet training data. If I want to sample one thousand images, should this parameter be set to 1000 ?
[code url](https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L101)
```python
    return TrainConfig(
        model=model,
        data=data,
        callbacks=callbacks,
        steps_per_epoch=100 if args.fake else 1281167 // args.batch,
        max_epoch=105,
    )
```
I wonder that if the ```steps_per_epoch``` is not equal to dataset size:
1. how does this ```__iter__``` work?  
2. Will ```self.shuffle```  only be used once when obtaining the iterator?  If the yield data is not enough, will this function be recalled, then shuffle data and yield data again?
3.  Must the ```__len__``` function return a value which is number of times yield from ``` __iter__``` function ?
4. If mutliple processors are used to prefetch data, do they have different random seeds for shuffling? And, how to ensure the mini-batch including nonredundant samples?

*Could you provide any useful documents to help me ?*
[code url](https://github.com/tensorpack/tensorpack/blob/master/tensorpack/dataflow/dataset/ilsvrc.py#L169)
```python
    def __len__(self):
        return len(self.imglist)

    def __iter__(self):
        idxs = np.arange(len(self.imglist))
        if self.shuffle:
            self.rng.shuffle(idxs)
        for k in idxs:
            fname, label = self.imglist[k]
            fname = os.path.join(self.full_dir, fname)
            yield [fname, label]
```

**Comment by ppwwyyxx** [comment]
>  If I want to sample one thousand images, should this parameter be set to 1000 ?

No. See https://tensorpack.readthedocs.io/tutorial/extend/trainer.html#assumptions-of-base-trainer :
> steps_per_epoch can be any number you set and it only affects the schedule of callbacks

You should write a new dataflow which produces 1000 images.

> how does this __iter__ work?
Unaffected as mentioned above.

> Will self.shuffle only be used once when obtaining the iterator? If the yield data is not enough, will this function be recalled, then shuffle data and yield data again?

It will be called more than once. That's how people do shuffle.

> Must the __len__ function return a value which is number of times yield from __iter__ function ?

No for training. This is answered in https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.DataFlow

> If mutliple processors are used to prefetch data, do they have different random seeds for shuffling? 

They do.

> And, how to ensure the mini-batch including nonredundant samples?

If you use `PrefetchData*`, it is not ensured. You're subject to birthday paradox. This is explained in https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.PrefetchDataZMQ

`MultiProcessMapData`/`MultiThreadMapData` can use multiple processes/threads and also ensure non-redundant samples.
