### ISSUE TITLE
Panoptic segmentation

### ISSUE THREAD

**Issue by AlbertoMCS** [tensorpack/tensorpack#1174]
Hi, 

Amazing tool and amazing support when problems come up. 

I wondering if there is in this repo some example implementing Panoptic segmentation? 

Thanks,
Alberto.

**Comment by ppwwyyxx** [comment]
I don't have short term plan to implement panoptic segmentation.
It shouldn't be very hard: on top of the Mask R-CNN example you'll just need to add some extra information in the data loader and a new branch in the FPN model.
