### ISSUE TITLE
Differing results compared to Detectron and Matterport

### ISSUE THREAD

**Issue by fuzzyBatman** [tensorpack/tensorpack#1176]
I am training a red blood cell detector using the Faster R-CNN model. These are the results using tensorpack.

![output](https://user-images.githubusercontent.com/5787026/57218288-3d710b00-6ff5-11e9-9516-f63807932c2f.png)

These are the results using matterport/Mask_RCNN

![ypdbrmhfcscfxawv_res](https://user-images.githubusercontent.com/5787026/57218374-6e514000-6ff5-11e9-94d0-624ff891ac87.png)

Using Detectron's Mask R-CNN

![akvjocfxbvxldnuj png](https://user-images.githubusercontent.com/5787026/57218444-9b9dee00-6ff5-11e9-9fe5-4ce5c61fd209.png)

I tried tuning some config parameters, but the output is the same. Is there something crucial I need to know to use this library?

**Comment by fuzzyBatman** [comment]
On varying the config parameters, it is always the same set of RBCs detected but with differing bboxes.

**Comment by ppwwyyxx** [comment]
I think your code did something different in each framework (different configurations, different architectures, etc) or you may make a mistake in using it. But without more details there isn't much I can tell from the image.
The tensorpack implementation is able to reproduce performance of the models in Detectron model zoo (which matterport's cannot), as you can see from the README. It faithfully supports most features available in Detectron.

**Comment by fuzzyBatman** [comment]
Alright. I will look into it.

I am not able to make the LR drop over time.
It starts at `0.00033` and increases for 1000 steps, as per the config, and then is a constant `0.001`

I read in the config file that LR_Schedule should decay the LR if `bs!=8`. Where can I modify the batch size? At some point, the loss hits a region after which it starts increasing again.

**Comment by ppwwyyxx** [comment]
The log will print the time the LR will drop. You can change the LR schedule in config.
The batch size is equal to the number of GPUs you use which is also printed in the log.

**Comment by ppwwyyxx** [comment]
From the results it does look like the model is doing something reasonable, but it is only doing it in a small region. So you might be using the model in a wrong way. But no one can debug by looking at the image. Any details you provide can be helpful.

**Comment by fuzzyBatman** [comment]
Ah. I see. Thanks for the info.
I am making some changes so as to get the LR to drop sooner.
Will test and update.

One question for now is, is there support for grayscale images? I'll have to load the images in RGB and train?

**Comment by ppwwyyxx** [comment]
There is no support for grayscale images

**Comment by ppwwyyxx** [comment]
I don't think when to drop LR will make such differences, though. There should be something larger that's different in your code or settings.

**Comment by armandmcqueen** [comment]
It could, in theory, be an issue with some batch size config (RPN.BATCH_PER_IM, FRCNN.BATCH_PER_IM, TEST.RESULTS_PER_IM, etc). Your data has a high number of boxes compared to COCO. Perhaps too many valid results get filtered before prediction or perhaps you are only training on a subset of the labels. 

But given the obvious spatial distribution of results, it seems more likely to be an issue related to cropping or resizing.

**Comment by fuzzyBatman** [comment]
@ppwwyyxx , @armandmcqueen  - Thank you both for the info.

I am planning to test this with Faster R-CNN and Mask R-CNN. Will let you know how it goes and will ask for any help if required. You can close the issue if you want.

**Comment by fuzzyBatman** [comment]
So, turns out I messed with the `RPN.ANCHOR_SIZES` and `FPN.ANCHOR_STRIDES`

Faster R-CNN results

![output](https://user-images.githubusercontent.com/5787026/57567405-ea260080-73d8-11e9-8295-0e29aeb53448.png)

I do not understand why all of them aren't detected though. Config? Need to train more?

**Comment by ppwwyyxx** [comment]
I would guess there are other configs not correctly set.

**Comment by fuzzyBatman** [comment]
Config used

```
_C.TRAIN.NUM_GPUS = None         # by default, will be set from code
_C.TRAIN.WEIGHT_DECAY = 1e-4
_C.TRAIN.BASE_LR = 1e-3                # Originally 1e-2. Gives NaN loss
_C.TRAIN.WARMUP = 1000 
_C.TRAIN.WARMUP_INIT_LR = 1e-3 * 0.33         # Originally 1e-2 * 0.33
_C.TRAIN.STEPS_PER_EPOCH = 500
_C.TRAIN.STARTING_EPOCH = 1

_C.TRAIN.LR_SCHEDULE = [3000, 6400, 9600, 12800]
_C.TRAIN.EVAL_PERIOD = 25

_C.PREPROC.TRAIN_SHORT_EDGE_SIZE = [512, 512]  # [min, max] to sample from
_C.PREPROC.TEST_SHORT_EDGE_SIZE = 512
_C.PREPROC.MAX_SIZE = 512

_C.RPN.FG_RATIO = 0.5  # fg ratio among selected RPN anchors
_C.RPN.BATCH_PER_IM = 512  # total (across FPN levels) number of anchors that are marked valid
_C.RPN.MIN_SIZE = 0
_C.RPN.PROPOSAL_NMS_THRESH = 0.9

_C.RPN.TRAIN_PRE_NMS_TOPK = 12000
_C.RPN.TRAIN_POST_NMS_TOPK = 2000
_C.RPN.TEST_PRE_NMS_TOPK = 6000
_C.RPN.TEST_POST_NMS_TOPK = 2000  
# for FPN, #proposals per-level and #proposals after merging are (for now) the same
# if FPN.PROPOSAL_MODE = 'Joint', these options have no effect
_C.RPN.TRAIN_PER_LEVEL_NMS_TOPK = 2000
_C.RPN.TEST_PER_LEVEL_NMS_TOPK = 1000

# fastrcnn training ---------------------
_C.FRCNN.BATCH_PER_IM = 512
_C.FRCNN.BBOX_REG_WEIGHTS = [20., 20., 10., 10.]  # Detectron: 10, 10, 5, 5
_C.FRCNN.FG_THRESH = 0.5
_C.FRCNN.FG_RATIO = 0.25  # fg ratio in a ROI batch

# FPN -------------------------
_C.FPN.ANCHOR_STRIDES = (4, 8, 16, 32, 64) 
_C.FPN.PROPOSAL_MODE = 'Level' 
_C.FPN.NUM_CHANNEL = 256
_C.FPN.NORM = 'None' 
# The head option is only used in FPN. For C4 models, the head is C5
_C.FPN.FRCNN_HEAD_FUNC = 'fastrcnn_2fc_head'
# choices: fastrcnn_2fc_head, fastrcnn_4conv1fc_{,gn_}head
_C.FPN.FRCNN_CONV_HEAD_DIM = 256
_C.FPN.FRCNN_FC_HEAD_DIM = 1024
_C.FPN.MRCNN_HEAD_FUNC = 'maskrcnn_up4conv_head'   # choices: maskrcnn_up4conv_{,gn_}head

# Mask-RCNN
_C.MRCNN.HEAD_DIM = 256

# Cascade-RCNN, only available in FPN mode
_C.FPN.CASCADE = False

# testing -----------------------
_C.TEST.FRCNN_NMS_THRESH = 0.5

_C.TEST.RESULT_SCORE_THRESH = 0.0
_C.TEST.RESULT_SCORE_THRESH_VIS = 0.5   # only visualize confident results
_C.TEST.RESULTS_PER_IM = 400
```

**Comment by fuzzyBatman** [comment]
The previous image is for `_C.RPN.BATCH_PER_IM = 256`

For `_C.RPN.BATCH_PER_IM = 512`

![output](https://user-images.githubusercontent.com/5787026/57569654-6b40c000-73f8-11e9-8d01-e4a03fa463f2.png)

**Comment by fuzzyBatman** [comment]
Tuning `_C.RPN.TRAIN_PER_LEVEL_NMS_TOPK`, `_C.RPN.TEST_PER_LEVEL_NMS_TOPK` and `_C.TEST.FRCNN_NMS_THRESH` made a difference.

![output](https://user-images.githubusercontent.com/5787026/57570883-53246d00-7407-11e9-8390-5bde32c4a43d.png)

**Comment by fuzzyBatman** [comment]
The matterport/Mask_RCNN library gives an inference time of 1.7 seconds per 512x512 image (at least in this scenario). We need to detect RBCs in around 700 images to analyse an entire sample.

This library is much more efficient. Total execution time (inclusive of RBC localisation by hacking some components of the Faster R-CNN example) is 4-5 minutes. matterport/Mask_RCNN furnishes 15-17 minutes.

Thank you for making this amazing library open-source. It seems well polished in every aspect.
