### ISSUE TITLE
The train or predict of Faster Rcnn can't be  with batchsize more than 1.  It is a point to optimize. 

### ISSUE THREAD

**Issue by maliyong** [tensorpack/tensorpack#1180]
I studied with your code tensorpack--Faster Rcnn. But I found your code didn't support train or predict with batchsize more than 1.

**Comment by ppwwyyxx** [comment]
Yes. It is mentioned in https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md#implementation-notes.
