### ISSUE TITLE
About StoppableThread Class

### ISSUE THREAD

**Issue by CloudFlyCN** [tensorpack/tensorpack#1187]
In file `tensorpack\utils\concurrency.py` :

    def __init__(self, evt=None):
        """
        Args:
            evt(threading.Event): if None, will create one.
        """
        super(StoppableThread, self).__init__()
        if evt is None:
            evt = threading.Event()
        self._stop_evt = evt    

    def stop(self):
        """ Stop the thread"""
        self._stop_evt.set()

    def stopped(self):
        """
        Returns:
            bool: whether the thread is stopped or not
        """
        return self._stop_evt.isSet()

Does `isSet = True` means the thread is stopped?

However, in [official manual](https://docs.python.org/3/library/threading.html) about `Event()`，it is written as below:

> This is one of the simplest mechanisms for communication between threads: one thread signals an event and other threads wait for it.

> An event object manages an internal flag that can be set to true with the  set() method and reset to false with the clear() method. The wait() method blocks until the flag is true.

I wonder where I misunderstand, Thank you.

**Comment by ppwwyyxx** [comment]
> Does isSet = True means the thread is stopped?

Yes.
