### ISSUE TITLE
Loss diverge when training Imagenet with ResNet18.

### ISSUE THREAD

**Issue by dxbdxx** [tensorpack/tensorpack#1188]
Hi, I am training Imagenet using ResNet18 but the loss diverge, could you give some advices?

### 1. What you did:
First I use mode='cpu' in **SyncMultiGPUTrainerReplicated** in **imagenet-resnet.py** , and run the following code:
```
python examples/ResNet/imagenet-resnet.py \
                --data '/common-data/jlong.yuan/imagenet/raw/imagenet-data' \
                -d 18 \
                --mode resnet \
                --batch 256 
```

### 2. What you observed:
The loss diverge. Here is the log:
[32m[0514 09:35:21 @logger.py:90][0m Argv: examples/ResNet/imagenet-resnet.py --data /common-data/jlong.yuan/imagenet/raw/imagenet-data -d 18 --mode resnet --batch 256
[32m[0514 09:35:21 @imagenet-resnet.py:55][0m Running on 4 towers. Batch size per tower: 64
[32m[0514 09:35:22 @parallel.py:311][0m [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[32m[0514 09:35:22 @ilsvrc.py:128][0m [ILSVRC12] Assuming directory /common-data/jlong.yuan/imagenet/raw/imagenet-data/val has 'train' structure.
[32m[0514 09:35:23 @prof.py:47][0m [5m[31mWRN[0m [GPUUtilizationTracker] Both devices and CUDA_VISIBLE_DEVICES are None! Will monitor all 4 visible GPUs!
[32m[0514 09:35:23 @training.py:50][0m [DataParallel] Training a model of 4 towers.
[32m[0514 09:35:23 @interface.py:43][0m Automatically applying StagingInput on the DataFlow.
[32m[0514 09:35:23 @input_source.py:223][0m Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[32m[0514 09:35:23 @training.py:110][0m Building graph for training tower 0 on device /gpu:0 ...
[32m[0514 09:35:23 @registry.py:135][0m conv0 input: [None, 3, 224, 224]
[32m[0514 09:35:23 @registry.py:143][0m conv0 output: [None, 64, 112, 112]
[32m[0514 09:35:23 @registry.py:135][0m pool0 input: [None, 64, 112, 112]
[32m[0514 09:35:23 @registry.py:143][0m pool0 output: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:135][0m group0/block0/conv1 input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group0/block0/conv1 output: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:135][0m group0/block0/conv2 input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group0/block0/conv2 output: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:135][0m group0/block1/conv1 input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group0/block1/conv1 output: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:135][0m group0/block1/conv2 input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group0/block1/conv2 output: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:135][0m group1/block0/conv1 input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group1/block0/conv1 output: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:135][0m group1/block0/conv2 input: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:143][0m group1/block0/conv2 output: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:135][0m group1/block0/convshortcut input: [None, 64, 56, 56]
[32m[0514 09:35:23 @registry.py:143][0m group1/block0/convshortcut output: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:135][0m group1/block1/conv1 input: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:143][0m group1/block1/conv1 output: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:135][0m group1/block1/conv2 input: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:143][0m group1/block1/conv2 output: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:135][0m group2/block0/conv1 input: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:143][0m group2/block0/conv1 output: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:135][0m group2/block0/conv2 input: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:143][0m group2/block0/conv2 output: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:135][0m group2/block0/convshortcut input: [None, 128, 28, 28]
[32m[0514 09:35:23 @registry.py:143][0m group2/block0/convshortcut output: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:135][0m group2/block1/conv1 input: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:143][0m group2/block1/conv1 output: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:135][0m group2/block1/conv2 input: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:143][0m group2/block1/conv2 output: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:135][0m group3/block0/conv1 input: [None, 256, 14, 14]
[32m[0514 09:35:23 @registry.py:143][0m group3/block0/conv1 output: [None, 512, 7, 7]
[32m[0514 09:35:23 @registry.py:135][0m group3/block0/conv2 input: [None, 512, 7, 7]
[32m[0514 09:35:23 @registry.py:143][0m group3/block0/conv2 output: [None, 512, 7, 7]
[32m[0514 09:35:23 @registry.py:135][0m group3/block0/convshortcut input: [None, 256, 14, 14]
[32m[0514 09:35:24 @registry.py:143][0m group3/block0/convshortcut output: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:135][0m group3/block1/conv1 input: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:143][0m group3/block1/conv1 output: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:135][0m group3/block1/conv2 input: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:143][0m group3/block1/conv2 output: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:135][0m gap input: [None, 512, 7, 7]
[32m[0514 09:35:24 @registry.py:143][0m gap output: [None, 512]
[32m[0514 09:35:24 @registry.py:135][0m linear input: [None, 512]
[32m[0514 09:35:24 @registry.py:143][0m linear output: [None, 1000]
[32m[0514 09:35:24 @regularize.py:97][0m regularize_cost() found 21 variables to regularize.
[32m[0514 09:35:24 @regularize.py:21][0m The following tensors will be regularized: conv0/W:0, group0/block0/conv1/W:0, group0/block0/conv2/W:0, group0/block1/conv1/W:0, group0/block1/conv2/W:0, group1/block0/conv1/W:0, group1/block0/conv2/W:0, group1/block0/convshortcut/W:0, group1/block1/conv1/W:0, group1/block1/conv2/W:0, group2/block0/conv1/W:0, group2/block0/conv2/W:0, group2/block0/convshortcut/W:0, group2/block1/conv1/W:0, group2/block1/conv2/W:0, group3/block0/conv1/W:0, group3/block0/conv2/W:0, group3/block0/convshortcut/W:0, group3/block1/conv1/W:0, group3/block1/conv2/W:0, linear/W:0
[32m[0514 09:35:24 @training.py:110][0m Building graph for training tower 1 on device /gpu:1 ...
[32m[0514 09:35:25 @regularize.py:97][0m regularize_cost() found 21 variables to regularize.
[32m[0514 09:35:25 @training.py:110][0m Building graph for training tower 2 on device /gpu:2 ...
[32m[0514 09:35:26 @regularize.py:97][0m regularize_cost() found 21 variables to regularize.
[32m[0514 09:35:26 @training.py:110][0m Building graph for training tower 3 on device /gpu:3 ...
[32m[0514 09:35:27 @regularize.py:97][0m regularize_cost() found 21 variables to regularize.
[32m[0514 09:35:29 @training.py:348][0m 'sync_variables_from_main_tower' includes 492 operations.
[32m[0514 09:35:29 @model_utils.py:67][0m [36mList of Trainable Variables: 
[0mname                                   shape               #elements
-------------------------------------  ----------------  -----------
conv0/W:0                              [7, 7, 3, 64]            9408
conv0/bn/gamma:0                       [64]                       64
conv0/bn/beta:0                        [64]                       64
group0/block0/conv1/W:0                [3, 3, 64, 64]          36864
group0/block0/conv1/bn/gamma:0         [64]                       64
group0/block0/conv1/bn/beta:0          [64]                       64
group0/block0/conv2/W:0                [3, 3, 64, 64]          36864
group0/block0/conv2/bn/gamma:0         [64]                       64
group0/block0/conv2/bn/beta:0          [64]                       64
group0/block1/conv1/W:0                [3, 3, 64, 64]          36864
group0/block1/conv1/bn/gamma:0         [64]                       64
group0/block1/conv1/bn/beta:0          [64]                       64
group0/block1/conv2/W:0                [3, 3, 64, 64]          36864
group0/block1/conv2/bn/gamma:0         [64]                       64
group0/block1/conv2/bn/beta:0          [64]                       64
group1/block0/conv1/W:0                [3, 3, 64, 128]         73728
group1/block0/conv1/bn/gamma:0         [128]                     128
group1/block0/conv1/bn/beta:0          [128]                     128
group1/block0/conv2/W:0                [3, 3, 128, 128]       147456
group1/block0/conv2/bn/gamma:0         [128]                     128
group1/block0/conv2/bn/beta:0          [128]                     128
group1/block0/convshortcut/W:0         [1, 1, 64, 128]          8192
group1/block0/convshortcut/bn/gamma:0  [128]                     128
group1/block0/convshortcut/bn/beta:0   [128]                     128
group1/block1/conv1/W:0                [3, 3, 128, 128]       147456
group1/block1/conv1/bn/gamma:0         [128]                     128
group1/block1/conv1/bn/beta:0          [128]                     128
group1/block1/conv2/W:0                [3, 3, 128, 128]       147456
group1/block1/conv2/bn/gamma:0         [128]                     128
group1/block1/conv2/bn/beta:0          [128]                     128
group2/block0/conv1/W:0                [3, 3, 128, 256]       294912
group2/block0/conv1/bn/gamma:0         [256]                     256
group2/block0/conv1/bn/beta:0          [256]                     256
group2/block0/conv2/W:0                [3, 3, 256, 256]       589824
group2/block0/conv2/bn/gamma:0         [256]                     256
group2/block0/conv2/bn/beta:0          [256]                     256
group2/block0/convshortcut/W:0         [1, 1, 128, 256]        32768
group2/block0/convshortcut/bn/gamma:0  [256]                     256
group2/block0/convshortcut/bn/beta:0   [256]                     256
group2/block1/conv1/W:0                [3, 3, 256, 256]       589824
group2/block1/conv1/bn/gamma:0         [256]                     256
group2/block1/conv1/bn/beta:0          [256]                     256
group2/block1/conv2/W:0                [3, 3, 256, 256]       589824
group2/block1/conv2/bn/gamma:0         [256]                     256
group2/block1/conv2/bn/beta:0          [256]                     256
group3/block0/conv1/W:0                [3, 3, 256, 512]      1179648
group3/block0/conv1/bn/gamma:0         [512]                     512
group3/block0/conv1/bn/beta:0          [512]                     512
group3/block0/conv2/W:0                [3, 3, 512, 512]      2359296
group3/block0/conv2/bn/gamma:0         [512]                     512
group3/block0/conv2/bn/beta:0          [512]                     512
group3/block0/convshortcut/W:0         [1, 1, 256, 512]       131072
group3/block0/convshortcut/bn/gamma:0  [512]                     512
group3/block0/convshortcut/bn/beta:0   [512]                     512
group3/block1/conv1/W:0                [3, 3, 512, 512]      2359296
group3/block1/conv1/bn/gamma:0         [512]                     512
group3/block1/conv1/bn/beta:0          [512]                     512
group3/block1/conv2/W:0                [3, 3, 512, 512]      2359296
group3/block1/conv2/bn/gamma:0         [512]                     512
group3/block1/conv2/bn/beta:0          [512]                     512
linear/W:0                             [512, 1000]            512000
linear/b:0                             [1000]                   1000[36m
Number of trainable variables: 62
Number of parameters (elements): 11689512
Storage space needed for all trainable variables: 44.59MB[0m
[32m[0514 09:35:29 @base.py:209][0m Setup callbacks graph ...
[32m[0514 09:35:29 @argtools.py:146][0m [5m[31mWRN[0m Starting a process with 'fork' method is not safe and may consume unnecessary extra memory. Use 'forkserver' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
[32m[0514 09:35:30 @input_source.py:223][0m Setting up the queue 'DataParallelInferenceRunner/QueueInput/input_queue' for CPU prefetching ...
[32m[0514 09:35:30 @inference_runner.py:234][0m [InferenceRunner] Building tower 'InferenceTower0' on device /gpu:0 ...
[32m[0514 09:35:30 @inference_runner.py:234][0m [InferenceRunner] Building tower 'InferenceTower1' on device /gpu:1 with variable scope 'tower1'...
[32m[0514 09:35:30 @inference_runner.py:234][0m [InferenceRunner] Building tower 'InferenceTower2' on device /gpu:2 with variable scope 'tower2'...
[32m[0514 09:35:30 @inference_runner.py:234][0m [InferenceRunner] Building tower 'InferenceTower3' on device /gpu:3 with variable scope 'tower3'...
[32m[0514 09:35:31 @summary.py:46][0m [MovingAverageSummary] 4 operations in collection 'MOVING_SUMMARY_OPS' will be run with session hooks.
[32m[0514 09:35:31 @summary.py:93][0m Summarizing collection 'summaries' of size 7.
[32m[0514 09:35:31 @graph.py:98][0m Applying collection UPDATE_OPS of 40 ops.
[32m[0514 09:35:33 @base.py:230][0m Creating the session ...
[32m[0514 09:35:37 @base.py:236][0m Initializing the session ...
[32m[0514 09:35:37 @base.py:243][0m Graph Finalized.
[32m[0514 09:35:38 @concurrency.py:37][0m Starting EnqueueThread QueueInput/input_queue ...
[32m[0514 09:35:38 @graph.py:73][0m Running Op sync_variables/sync_variables_from_main_tower ...
[32m[0514 09:35:55 @param.py:158][0m [HyperParamSetter] At global_step=0, learning_rate is set to 0.100000
[32m[0514 09:35:55 @concurrency.py:37][0m Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[32m[0514 09:35:55 @inference_runner.py:96][0m [InferenceRunner] Will eval 782 iterations
[32m[0514 09:35:56 @base.py:275][0m Start Epoch 1 ...
[32m[0514 09:35:56 @input_source.py:556][0m Pre-filling StagingArea ...
[32m[0514 09:35:56 @input_source.py:560][0m 1 element was put into StagingArea on each tower.
[32m[0514 10:12:28 @base.py:285][0m Epoch 1 (global_step 5004) finished, time:36 minutes 32 seconds.
[32m[0514 10:12:28 @graph.py:73][0m Running Op sync_variables/sync_variables_from_main_tower ...
[32m[0514 10:12:45 @saver.py:79][0m Model saved to train_log/imagenet-resnet-d18-batch256/model-5004.
[32m[0514 10:12:45 @misc.py:109][0m Estimated Time Left: 2 days 15 hours 50 minutes 15 seconds
[32m[0514 10:13:51 @monitor.py:467][0m DataParallelInferenceRunner/QueueInput/queue_size: 50
[32m[0514 10:13:51 @monitor.py:467][0m GPUUtil/0: 94.979
[32m[0514 10:13:51 @monitor.py:467][0m GPUUtil/1: 73.501
[32m[0514 10:13:51 @monitor.py:467][0m GPUUtil/2: 75.286
[32m[0514 10:13:51 @monitor.py:467][0m GPUUtil/3: 74.376
[32m[0514 10:13:51 @monitor.py:467][0m QueueInput/queue_size: 48.985
[32m[0514 10:13:51 @monitor.py:467][0m l2_regularize_loss: nan
[32m[0514 10:13:51 @monitor.py:467][0m learning_rate: 0.1
[32m[0514 10:13:51 @monitor.py:467][0m train-error-top1: 1
[32m[0514 10:13:51 @monitor.py:467][0m train-error-top5: 1
[32m[0514 10:13:51 @monitor.py:467][0m val-error-top1: 1
[32m[0514 10:13:51 @monitor.py:467][0m val-error-top5: 1
[32m[0514 10:13:51 @monitor.py:467][0m xentropy-loss: nan
[32m[0514 10:13:51 @group.py:48][0m Callbacks took 82.481 sec in total. DataParallelInferenceRunner: 1 minute 5 seconds
[32m[0514 10:13:51 @base.py:275][0m Start Epoch 2 ...
[32m[0514 10:16:36 @base.py:293][0m Detected Ctrl-C and exiting main loop.
[32m[0514 10:16:36 @input_source.py:179][0m [EnqueueThread] Thread EnqueueThread QueueInput/input_queue Exited.
[32m[0514 10:16:36 @input_source.py:179][0m [EnqueueThread] Thread EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue Exited.

### 4. Your environment:

--------------------  -------------------------------------------------------------------
sys.platform          linux
Python                3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) [GCC 7.2.0]
Tensorpack            0.9.4
Numpy                 1.14.3
TensorFlow            1.7.0/v1.7.0-3-g024aecf414
TF Compiler Version   4.8.4
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.40.04
CUDA                  /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
NCCL                  /usr/lib/x86_64-linux-gnu/libnccl.so.2.1.2
CUDA_VISIBLE_DEVICES  None
GPU 0,1,2,3           Tesla K80
Free RAM              206.93/251.81 GB
CPU Count             40
cv2                   4.0.0
msgpack               0.6.1
python-prctl          True
--------------------  -------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
I suspect this is due to bugs in your old version of cudnn. Could you upgrade to cudnn 7.4 or 7.5?

**Comment by ppwwyyxx** [comment]
I just ran the same training for 1 epoch and could not observe the divergence.

**Comment by dxbdxx** [comment]
Thank you for your reply. The problem solved after upgrading to tensorflow1.12 and cudnn7.5.1. Here is the environment info now:
--------------------  -------------------------------------------------------------------
sys.platform          linux
Python                3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) [GCC 7.2.0]
Tensorpack            0.9.4
Numpy                 1.14.3
TensorFlow            1.12.0/v1.12.0-0-ga6d8ffae09
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.40.04
CUDA                  /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1
NCCL                  /usr/lib/x86_64-linux-gnu/libnccl.so.2.1.2
CUDA_VISIBLE_DEVICES  None
GPU 0,1,2,3           Tesla K80
Free RAM              223.09/251.81 GB
CPU Count             40
cv2                   4.0.0
msgpack               0.6.1
python-prctl          True
--------------------  -------------------------------------------------------------------
