### ISSUE TITLE
How to ignore the parameters of  full connected layer for finetuning

### ISSUE THREAD

**Issue by BigFishMaster** [tensorpack/tensorpack#1190]
I have trained a 1000-class ResNet-101 model using ```resnet_model.py```.  Then I want to finetune this model onto new dataset (about 400 classes), I use```SaverRestore```  as:
```python
config.session_init = SaverRestore(args.load, ignore=["global_step", "linear/b:0", "linear/W:0", "linear/W/Momentum:0", "linear/b/Momentum:0"])
```
I do not understand the ```ignore``` variable and I tried so many times to find the tensor name of the parameters of the last full-connected layer.  My questions are:

1. What does the ```Momentum``` mean in ```linear/W/Momentum:0``` ?
2. Which ones are really needed to ignore ("linear/b:0", "linear/W:0", "linear/W/Momentum:0", "linear/b/Momentum:0") ?
3. By ignoring those parameters, the finetuning process gets lower performance than that from scracth, e.g. after 30 epochs, the former has 98% top1 error rate while the latter one is only 84%, seems the pretrained parameters do not work.

**Comment by ppwwyyxx** [comment]
1. They are variables saved by the momentum optimizer.
2. That's correct.
3. That's a machine learning question and not related to tensorpack.

As mentioned in https://tensorpack.readthedocs.io/tutorial/save-load.html#transfer-learning, if it is not easy to figure out the names to ignore, you can just rename the layer in the model.
To figure out what names are in a checkpoint, you can also use https://github.com/tensorpack/tensorpack/blob/master/scripts/ls-checkpoint.py

**Comment by BigFishMaster** [comment]
Thanks and close issue.
