### ISSUE TITLE
COCO data layout instructions

### ISSUE THREAD

**Issue by armandmcqueen** [tensorpack/tensorpack#1193]
In the FasterRCNN [readme](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/README.md) , it says that that you need to lay out your COCO data like this:

```
COCO/DIR/
  annotations/
    instances_train201?.json
    instances_val201?.json
  train201?/
    COCO_train201?_*.jpg
  val201?/
    COCO_val201?_*.jpg
```

Training seems to be working (so far) with a data layout like

```
COCO/DIR/
  annotations/
    instances_train201?.json
    instances_val201?.json
  train201?/
   *.jpg
  val201?/
    *.jpg
```
where *.jpg looks like `000000066822.jpg`

Am I missing something in the code where that jpg prefix is important?

**Comment by ppwwyyxx** [comment]
The name only needs to match the file name in the json. The prefix is not important.
The names for COCO 2014 have that prefix, but the names for COCO 2017 do not. I'll update the readme to avoid confusion.
