### ISSUE TITLE
Multiple calls to BNReLU can not exist within a single scope

### ISSUE THREAD

**Issue by yselivonchyk** [tensorpack/tensorpack#1196]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

I put 2 BNReLU(...) calls side by side.

```
    net = BNReLU(input)
    net = BNReLU(net, name='PlEaSeDoNtFaIl')

```

Same issue appears whenever I try to put 2 calls within a single scope

### 2. What you observed:

In short: variable already exists message:

```
....
  File "/home/eugene/ves/tf113/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 848, in _get_single_variable
    traceback.format_list(tb))))
ValueError: Variable res0.0/bn/gamma already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

```

### 4. Your environment:

--------------------  -------------------------------------------------------------------
Python                3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
Tensorpack            v0.9.4-0-gf947192
TensorFlow            1.13.1/b'v1.13.1-0-g6612da8951'
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.56
CUDA                  /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
CUDNN                 /usr/local/cuda-9.0/lib64/libcudnn.so.7
NCCL
CUDA_VISIBLE_DEVICES  None
GPU 0                 GeForce GTX 1080 Ti
cv2                   4.1.0
msgpack               0.6.1
python-prctl          False
--------------------  -------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
You need to either give it a different name if you don't want to share variable, or use `tf.variable_scope(tf.get_variable_scope(), reuse=True)` if you do want to share variables.

`name=` is not the variable scope name. It is the name of the output tensor, per tensorflow convention. 
See https://tensorpack.readthedocs.io/modules/models.html#tensorpack.models.BNReLU.

**Comment by yselivonchyk** [comment]
Thank you for the answer.
A bit misleading way to fail nevertheless

**Comment by ppwwyyxx** [comment]
The `name` argument was there to mimic the API of other activation functions like `tf.nn.relu`. But I do feel that this argument is not useful and probably should better be removed.
