### ISSUE TITLE
Add Throughput Tracking Callback

### ISSUE THREAD

**Issue by armandmcqueen** [tensorpack/tensorpack#1197]
I would like to add a callback to Tensorpack that can be used to track training throughput, similar to GPUUtilizationTracker or the Host/GPU MemoryTrackers. I think this is a missing feature that is generic enough that it belongs in core Tensorpack.

I would use [this](https://github.com/armandmcqueen/tensorpack-mask-rcnn/blob/master/MaskRCNN/performance.py#L113) as my (rough) starting point. If you agree that this feature belongs in core Tensorpack, I'll open an initial PR for review.

**Comment by ppwwyyxx** [comment]
If I understand it correctly, although time per epoch is already printed in the log, but what you need in this feature request is to multiply it by batch size and stored in a structured way (e.g. tensorboard)?

**Comment by armandmcqueen** [comment]
Yup, that's exactly it.
