### ISSUE TITLE
Add fetches tensors dynamically

### ISSUE THREAD

**Issue by MikeyLev** [tensorpack/tensorpack#1200]
Hi,
First,Thanks for your wonderful work.
I'm training an object detector. In the end of my net I have  2 Tensors of confidence and location.
I can take those two tensors to compute cost function (it works and train). I also want  that at the end of each epoch  take those two tensors apply tf function and apply summary. 
I tried to use the  ProcessTensors callback but it says the graph is already finalized.
Should I use Callbacks? Somethinig else?
In my framework I build all the graph (including extra function) and only change the tensor in the feed dict of the session run main loop function when I want to log to summary.
Is there anything like it in TP? 

Thanks

**Comment by ppwwyyxx** [comment]
Use `tf.summary.xxx` on your tensor in the graph. Everything else is taken cared of and they will be summarized at the end of each epoch. 
See more options at https://tensorpack.readthedocs.io/tutorial/summary.html

**Comment by ppwwyyxx** [comment]
Closing and feel free to reopen if you have more questions.
