### ISSUE TITLE
How to remove the background ZMQbg processes when quitting the main process?

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1203]
Hi @ppwwyyxx , I have a question about the temperory abort when using Tensorpack. Sometimes the training will stuck in the training due to some system loading reason or else. And the data loading processing (based on `MultiProcessMapDataZMQ`) has started. Then I abort the main process by `kill process_id`. And the main process will stop while some background data processes named `ZMQbg/3` for data loading were not stopped. And some GPU memory usage can be found by `nvidia-smi`. In single machine, I can kill those background ZMQ processes one by one. But in a shared machine, others may also use the Tensorpack so I cannot kill those processes related the aborted main process.

Could you please provide a list in Tensorpack that records the background processes started by the main process?

**Comment by ppwwyyxx** [comment]
My impression was that as long as you install `python-prctl`, there shouldn't be background processes left running after the training is killed.

If that doesn't work, what about changing this signal:
https://github.com/tensorpack/tensorpack/blob/e97ce38dad5af583763f836ccc87ba14ea52f813/tensorpack/utils/concurrency.py#L196
to `SIGKILL` instead?

Also, do you have a way to easily reproduce this issue?

**Comment by Remember2018** [comment]
@ppwwyyxx sorry, it seems I didn't install the package. Thanks a lot!

**Comment by Remember2018** [comment]
Hi @ppwwyyxx , I have a question. Using `htop` command, I found many subprocesses attached one main process. Is this reasonable?

**Comment by ppwwyyxx** [comment]
It is reasonable.
