### ISSUE TITLE
is batch inference supported?

### ISSUE THREAD

**Issue by realwill** [tensorpack/tensorpack#1206]
is there batch inference demo? or how to change to support batch inference?

**Comment by realwill** [comment]
I mean the detection, faster rcnn or mask rcnn, not classification

**Comment by ppwwyyxx** [comment]
There is no batch inference for the R-CNN example.

**Comment by realwill** [comment]
can you give some suggestions for batch inference? and make me freeze the model for batch inference in tf?

now, I can train the model use tensorpack and freeze the model for inference in tf one image by one image.

**Comment by ppwwyyxx** [comment]
You'll need to first implement the graph for batch inference.
Tensorpack is an interface for model training, and in general it does not provide extra support for fast inference. (https://tensorpack.readthedocs.io/tutorial/inference.html#inference-after-training-what-tensorpack-does)

**Comment by realwill** [comment]
InvalidArgumentError (see above for traceback): Can not squeeze dim[0], expected a dimension of 1, got 2
	 [[node rpn_2/Squeeze (defined at oneframe_inference_pb.py:31)  = Squeeze[T=DT_FLOAT, squeeze_dims=[0], _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_2/transpose)]]
	 [[{{node generate_fpn_proposals/Lvl6/generate_rpn_proposals/nms_input_boxes/_105}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1138_generate_fpn_proposals/Lvl6/generate_rpn_proposals/nms_input_boxes", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

It seems generate_fpn_proposals don't support.

**Comment by ppwwyyxx** [comment]
It's not supported and that's why you'll need to first implement the graph for batch inference.

**Comment by ramanathan831** [comment]
Hey @ppwwyyxx, Where do implement the graph for batch inference, and is there any examples of a custom implementation of graph for other purposes
