### ISSUE TITLE
Data loading for small/tiny images

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1211]
Hi, Dear all, 
Tensorpack provides great and flexible data loading module, which is super fast. I have a question about data loading for tiny/small images (e.g., with size 32x128). If I have one billion of these images to loading, is there any good solution on how to load these image for training without considering to harm the disk? I mean if we read the images one by one with multi threads, these concurrent disk reads will harm the disk, right? Could Tensorpack provide an efficient but safe way for this circumstance? Thanks. 

What I thought is using the numpy arrays. Cache a number of those tiny images in the disk with numpy format and then load these files one by one into memory, then the disk loading will be alleviated. Does anybody know how to design these systems or could you please provide some useful resources to do this? Thanks a lot!

**Comment by ppwwyyxx** [comment]
> Cache a number of those tiny images in the disk with numpy format and then load these files one by one into memory

This is a reasonable approach but I don't see how it is related to tensorpack. 

Creating such files on disk is a pure numpy task.
Loading such files is a pure numpy function, which you can then connect to tensorpack dataflow (e.g., with `DataFromGenerator`.

**Comment by Remember2018** [comment]
Hi @ppwwyyxx , thanks a lot for your kind comment! I'll check them. In fact I'm not sure how to load the shared data for training in Tensorpack.
