### ISSUE TITLE
Model layer visualization

### ISSUE THREAD

**Issue by zxpeter** [tensorpack/tensorpack#1212]
Hi,
What should I do if I want to draw heatmap to visualize each layer's output ?
I find `intensity_to_rgb` in utils/viz.py and it seems convert ndarray into heatmap rather than a tensor.
Do we have some function like `visualize_activation` in Keras?
Thanks for your time.

**Comment by ppwwyyxx** [comment]
You can just use `tf.image.summary`.

The alexnet example uses it:  https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/alexnet.py

If you want to save tensor to files, you can use a callback, such as https://github.com/tensorpack/tensorpack/blob/eccba14e4461dc1d174de9db97896c8adf346780/tensorpack/callbacks/steps.py#L19-L43
