### ISSUE TITLE
Improved Wasserstein GAN example does not have n_critic hyperparameter

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [tensorpack/tensorpack#1214]
Like the title, in the WGAN-GP (improved WGAN) example, the paper states updating the critic n_critic=5 times for each generator update. This is not part of the current [example](https://github.com/tensorpack/tensorpack/blob/master/examples/GAN/Improved-WGAN.py). 

I'm still learning Tensorpack, and this was the exact reason for me to look up the example, but it wasn't there :(.

**Comment by ppwwyyxx** [comment]
It is there, except that I use 6 instead of 5. https://github.com/tensorpack/tensorpack/blob/891dc488876076c36d49b22c42a4ffe08682d9b6/examples/GAN/Improved-WGAN.py#L96

**Comment by Baukebrenninkmeijer** [comment]
I see, thanks for the quick reply!
