### ISSUE TITLE
Training Faster RCNN with own Dataset 

### ISSUE THREAD

**Issue by ilyes-hm** [tensorpack/tensorpack#1215]
I am trying to train Faster RCNN with my own Dataset.
The dataset hierarchy is as the following (like coco):
my_data/dir/
_______|__annotations/
_________________|__instances_train.json
_________________|__instances_val.json
_______|__train
_______|__validation

I have followed the NOTES file
When i run the training command line it shows me this:
`Traceback (most recent call last):
  File "./train.py", line 74, in <module>
    train_dataflow = get_train_dataflow()
  File "/home/ilyes/tensorpack/examples/FasterRCNN/data.py", line 374, in get_train_dataflow
    roidbs = list(itertools.chain.from_iterable(DatasetRegistry.get(x).training_roidbs() for x in cfg.DATA.TRAIN))
  File "/home/ilyes/tensorpack/examples/FasterRCNN/data.py", line 374, in <genexpr>
    roidbs = list(itertools.chain.from_iterable(DatasetRegistry.get(x).training_roidbs() for x in cfg.DATA.TRAIN))
  File "/home/ilyes/tensorpack/examples/FasterRCNN/dataset/dataset.py", line 90, in get
    assert name in DatasetRegistry._registry, "Dataset {} was not registered!".format(name)
AssertionError: Dataset train2019 was not registered!
`
I think i did not register the dataset well.

**Comment by ppwwyyxx** [comment]
As https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md#implementation-notes suggested, you need to call 
```
DatasetRegistry.register(name, lambda: YourDatasetSplit())
```
where name is "train2019" and YourDatasetSplit is `COCODetection(.....)`

**Comment by ilyes-hm** [comment]
Thank you for your quick respond
my train 2019 is "dir" so to make it clear:
`/home/detection/train2019/:
      annotations/:
              instances_train.json
              instaces_validation.json
      /train/xxx.jpg
     /validation/xxx.jpg`
so what i did not understand is where do i need to call
`DatasetRegistry.register(name,` lambda: YourDatasetSplit())`
in train.py?

**Comment by ppwwyyxx** [comment]
You should register it at the beginning of your code, or see datasets/coco.py

**Comment by ilyes-hm** [comment]
Thanks again

`def register_coco(basedir):
    for split in ["train2019", "val2019"]:
        DatasetRegistry.register("train2019" + split, lambda x=split: COCODetection(basedir, x))`

this is what did i edit and i am still struggling even when i tested with small coco 2014 Dataset it did not work

**Comment by ppwwyyxx** [comment]
Your directory names are "train" and "validation".

**Comment by ppwwyyxx** [comment]
And your code will register a dataset named "train2019train2019" because you add two strings.

**Comment by ilyes-hm** [comment]
The problem that the code does not register any dataset.

**Comment by ppwwyyxx** [comment]
```python
def register_coco(basedir):
    DatasetRegistry.register("train", lambda: COCODetection(basedir, "train"))
    DatasetRegistry.register("validation", lambda: COCODetection(basedir, "validation"))
```
write this in coco.py and use "train" and "validation" in `cfg.DATA.TRAIN/VAL`. 

If you met any issues, please post the issue following the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)

**Comment by ilyes-hm** [comment]
I have fixed it. the problem was with the config file.
The name of `cfg.DATA.TRAIN` in config.py file was coco_train and my data name was train 
Now when i try to train it with the following parameters i get an OOM problem:
1. NVIDIA Quadro p2000.
2. Cuda 10.1
3. ImageNet-ResNet101.
i think i need more GPU.
Thanks for the help.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
