### ISSUE TITLE
OOM error when use the lastest code.

### ISSUE THREAD

**Issue by realwill** [tensorpack/tensorpack#1216]
OOM in memory, no gpu. And the memory used grow all the time, no drop.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by realwill** [comment]
ok, I submit new issue. thanks!
