### ISSUE TITLE
Multi- GPU synchronization

### ISSUE THREAD

**Issue by MikeyLev** [tensorpack/tensorpack#1220]
Hi,
I took the trainer of FasterRCNN and change it to run only basic features without callbacks only training with NCCL.
I implemented my model which converges on my own framework. The problem is when I train with NUM_GPU = 2 I have some unexpected spikes which I can not recover. 
This is an example of my Loss in the two configurations. The only difference is the number of GPUs.
I perform these steps multiple times.
Any clue? Do I have to use specific function which are not in this example?
Thanks
![image](https://user-images.githubusercontent.com/30577980/58494320-85f79080-817d-11e9-9d39-928750434a26.png)

The Gray curve is the one with only one GPU.
The other Curve with two GPUS

**Comment by ppwwyyxx** [comment]
As said in the issue template:

> If you expect certain accuracy, only in one of the two conditions can we help with it: (1) You're unable to reproduce the accuracy documented in tensorpack examples. (2) It appears to be a tensorpack bug.
Otherwise, how to train a model to certain accuracy is a machine learning question. We do not answer machine learning questions and it is your responsibility to figure out how to make your models more accurate.

**Comment by MikeyLev** [comment]
Hi,
Like I said I have an implementation of my model in multi gpu with towers paradigm which converges, it seems to me like a tensor pack bug, synchronization or something else.. Do you have any idea or tool to debug?

**Comment by ppwwyyxx** [comment]
It does not seem like a tensorpack bug to me. And your gray curve is not stable either.
I recommend you to use a smaller learning rate instead.
