### ISSUE TITLE
Can I use TensorPack training FasterRCNN on AMD GPU?  

### ISSUE THREAD

**Issue by jiangzihanict** [tensorpack/tensorpack#1222]

**Comment by ppwwyyxx** [comment]
The FasterRCNN code has made no assumptions on the type of GPU it runs on.
So it should be able to run on AMD GPUs as long as the GPUs support the relevant ops (NCHW format convolution/pooling, etc).
But I have not used an AMD GPU so I don't know in general whether there are other issues on the tensorflow side.

**Comment by jiangzihanict** [comment]
@ppwwyyxx Thanks for your quick reply. The TensorPack bases on TensorFlow, So should it support any back end that TF supports?

**Comment by ppwwyyxx** [comment]
> The TensorPack bases on TensorFlow, So should it support any back end that TF supports?

Yes. 

But note that TF does not support all the operations on all the backend.

**Comment by jiangzihanict** [comment]
@ppwwyyxx Thank you so much. I'll close this issue.
