### ISSUE TITLE
How to export a model to .pb file from scratch

### ISSUE THREAD

**Issue by iamhankai** [tensorpack/tensorpack#1225]
I have a model defined by `ModelDesc` class. I just want to see the speed of the model running on a cellphone, and I do not have a trained checkpoint. How can I export the model to .pb file?

```python
pred_config = PredictConfig(
            session_init=get_model_loader(model_path), # the problem is I do not have model_path!!!
            model=model,
            input_names=['input'],
            output_names=['MobileNetV2/Predictions/Softmax']) 
ModelExporter(pred_config).export_compact('/home/model.pb', optimize=True, toco_compatible=True)
```

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.sessinit.JustCurrentSession

**Comment by iamhankai** [comment]
Using JustCurrentSession has error
```
FailedPreconditionError: Attempting to use uninitialized value MobileNetV2/Conv2d_7_up_pointwise/dw1/bn/variance/EMA
```

**Comment by iamhankai** [comment]
I find a tricky way to do this. Add init after https://github.com/tensorpack/tensorpack/blob/7c8cbba082a577c7eb48efd1925b59a38d41682f/tensorpack/tfutils/export.py#L64
with the two lines
```python
init=tf.global_variables_initializer()
sess.run(init)
```

**Comment by ppwwyyxx** [comment]
Thanks for finding this issue. It should be fixed now in the above commit.
