### ISSUE TITLE
Training FasterRCNN using scientific dataset

### ISSUE THREAD

**Issue by jiangzihanict** [tensorpack/tensorpack#1226]
I have a special dataset about extreme weather, each image has 16 channels and high resolution(768*1152), see https://extremeweatherdataset.github.io/. 
My questions are:
1. Since there is no pre-trained model of the weather data, can I train the whole model including the base network?
2. The FasterRCNN code is implemented with COCO dataset. Just to make the code work, all I need to do is transform our dataset to COCO format?  Do I need to modify the model because of the specificity of our dataset？

Thanks a lot if anyone can help.

**Comment by ppwwyyxx** [comment]
1. As said in the README, we support training from scratch. But you can also see from the README and the relevant paper that it is not easy.
2. You need to make sure your images can be correctly read (by `TrainingDataPreprocessor`).
And you need to modify the input channels from 3 to 16 (in `model.inputs()`).
And you need to read https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md

**Comment by jiangzihanict** [comment]
Thanks, Wu.  I'll try it.

**Comment by jiangzihanict** [comment]
Thanks for your tips, It works on the weather data, and I'm curious where batchsize can be tuned, it seems to be fixed in the fasterrcnn code. 




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            jiangzihan
                            
                            
                                
                                    邮箱：jiangzihan@ict.ac.cn
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 06/06/2019 00:47, Yuxin Wu wrote: 
As said in the README, we support training from scratch. But you can also see from the README and the relevant paper that it is not easy.
You need to make sure your images can be correctly read (by TrainingDataPreprocessor).
And you need to modify the input channels from 3 to 16 (in model.inputs()).
And you need to read https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tensorpack/tensorpack/issues/1226?email_source=notifications\u0026email_token=AFICFFUAPBW4VU3LJCUIDHTPY7UMZA5CNFSM4HTSOCXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXAJ4ZA#issuecomment-499162724",
"url": "https://github.com/tensorpack/tensorpack/issues/1226?email_source=notifications\u0026email_token=AFICFFUAPBW4VU3LJCUIDHTPY7UMZA5CNFSM4HTSOCXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXAJ4ZA#issuecomment-499162724",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ppwwyyxx** [comment]
Batch size is equal to the number of GPUs used. But you can still tune it equivalently by using AccumGradOptimizer.

**Comment by jiangzihanict** [comment]
Hello, @ppwwyyxx . When I was training(batch_size=1), I found that FasterRCNN (ResNet-C4) takes up 16GB of GPU memory.  Is this normal?

**Comment by ppwwyyxx** [comment]
Tensorflow by default uses all available GPU memory.

**Comment by jiangzihanict** [comment]
The model is not as big as 16 G, so what is the memory used for? If I switch to a GPU with a smaller memory (12G), it takes up 8G and hints that I can gain performance by expanding the memory.

**Comment by ppwwyyxx** [comment]
You can find the answers in Tensorflow documentation: https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth

To use it with tensorpack, there is a `session_config` argument in `TrainConfig`.

**Comment by jiangzihanict** [comment]
Hi @ppwwyyxx, Is there a `model.summary() `(just like Keras) method for visualiazing model architecture in TensorPack?

**Comment by jiangzihanict** [comment]
Hi @ppwwyyxx, Is there a model.summary() (just like Keras) method for printing model architecture in TensorPack?

**Comment by ppwwyyxx** [comment]
Keras's `model.summary` prints shape of outputs and parameters. Both are already printed in tensorpack before training.
