### ISSUE TITLE
Custom Polygon dataset Mask-RCNN object detection

### ISSUE THREAD

**Issue by xyzdcgan** [tensorpack/tensorpack#1228]
I am creating custom mask-rcnn object detection model.
I labeled the data with polygon shape and created csv file.

I am not able to create tf record from csv as, it has polygon set rather then rectangle bounding box.
Can you help in creating tf record..?

Also i am using this tensroflow, and using mask_rcnn_resnet101_atrous_coco from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

And configuring config file and giving path for it.

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html

Using this kind of implementation for mask-rcnn, so I can get checkpoint file. 
Rather then using a pre trained h5 model of mask-rcnn

Thanks

**Comment by ppwwyyxx** [comment]
Nothing in the issue has anything to do with tensorpack. closing
