### ISSUE TITLE
Train FasterRCNN with NO BBOX (groundtruth) images

### ISSUE THREAD

**Issue by Zhenjie-cao** [tensorpack/tensorpack#1230]
I removed "filter" in data.py, but I still broke the code when trying to **train the model with NO BBOX images**. How shall I modify the code to train NO BBOX images? My dataset consists of **huge amount of NO BBOX images**, aka images with no target, thanks!

**Comment by ppwwyyxx** [comment]
Training using images without groundtruth is not supported. You can implement the relevant changes by modifying the models at where it breaks.

**Comment by ppwwyyxx** [comment]
It's now supported in the above commit. There aren't many changes needed to handle empty inputs.

**Comment by JayParanjape** [comment]
What changes are required exactly? 
In my case, I want to have a custom dataset, so I modified the balloons.py file. For the images with no targets, I returned a roidb dict with roidb[boxes']=[]. 
But this gives me an error like:
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 0 values, but the requested shape has 4
	 [[{{node tower0/encode_bbox_target/Reshape_2}}]]
	 [[tower0/fastrcnn/outputs/class/BiasAdd/_945]]
  (1) Invalid argument: Input to reshape is a tensor with 0 values, but the requested shape has 4
	 [[{{node tower0/encode_bbox_target/Reshape_2}}]]
0 successful operations.
0 derived errors ignored.

Please let me know the correct way to pass such images. Thanks in advance

**Comment by JayParanjape** [comment]
There was an error elsewhere in the code. I am able to train it correctly with passing roidb['boxes] = np.zeros((0,4) and setting the DATA.FILTER_EMPTY_ANNOTATIONS=False in the config argument
