### ISSUE TITLE
Future of our MaskRCNN fork

### ISSUE THREAD

**Issue by armandmcqueen** [tensorpack/tensorpack#1235]
Hi,

We at AWS created [this](https://github.com/armandmcqueen/tensorpack-mask-rcnn) Mask RCNN repo based on your great work. It's completely focused on throughput for R50-FPN training so we rewrote a lot of the code to handle batches, we require using custom TF ops/binary, we made MaskRCNN-specific changes to the Tensorpack library, and we have broken/removed several features (non-FPN, Cascade, etc). We also want the freedom to continue to make non-compatible changes to optimize R50-FPN throughput as needed.

I don't see a realistic path to merge our work back into your upstream repo so our current plan is to release and support it as a standalone AWS repository, with the README referencing your repo as our starting point. Before doing that, we wanted to check with you to make sure that you don't see a way to merge our work into yours and to hear if you have any major problems with our fork that we can address.

-Armand

**Comment by ppwwyyxx** [comment]
Thanks for the great work!
Merging the Mask R-CNN changes back seems to be pretty hard indeed. However it does seem that your changes on the tensorpack library (e.g., about fp16, loss scaling etc) can be implemented without modifying the library, or merged to the library. If that's successful it will also make your repo much simpler. If you think that's worth doing, we can start discussions about the individual changes.

**Comment by armandmcqueen** [comment]
I definitely agree - we really want to get away from having changes inside of the tensorpack lib. 

Our thinking on mixed precision is that once 1.14 is fully out, NVIDIA's auto mixed precision is the easiest path. We also added code to downcast variables, but it looks like Tensorpack now supports that directly.

There are a couple changes I need to follow up on (I'm not 100% sure why we did [this](https://github.com/armandmcqueen/tensorpack-mask-rcnn/blame/master/tensorpack/models/pool.py#L130)  or what the performance impact was for example).

One thing that might be useful to upstream is the ability to set op-level seeds, like we do [here](https://github.com/armandmcqueen/tensorpack-mask-rcnn/blame/master/tensorpack/models/conv2d.py#L38).

**Comment by ppwwyyxx** [comment]
Loss scaling should be doable directly on the graph/optimizer level without touching tensorpack.

For seeds, my impression is that `tf.random.set_random_seed` can achieve the same effect of determinism. Why is per-op seed needed?

**Comment by armandmcqueen** [comment]
If you only set the graph-level seed, the op-level seed will be the same as long as the graph stays the same. If you change the graph, the op seed will change (we're not 100% sure how much the graph needs to change before causing a new op seed). 

We rely on the op-level seed to ensure consistency during development, particularly when we are optimizing or rewriting a certain part of the model and we want to rule out the possibility of a changed seed in a different part of the model impacting our accuracy. 

It might not be necessary if we had a better understanding of what graph changes lead to new op seeds and which don't.
