### ISSUE TITLE
Performance of multi-scale training decreased 

### ISSUE THREAD

**Issue by zdwong** [tensorpack/tensorpack#1236]
Thanks for your great work!
When I use multi-scale training in my own datasets, the performance is worse than single-scale training. I guess the implementation of multi-scale training is wrong. Are you sure that the implementation of multi-scale training is right? @ppwwyyxx

**Comment by ppwwyyxx** [comment]
See the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md):


+ "The examples do not perform as expected after I change the models/dataset/parameters/etc.":

  Tensorpack maintainers make sure the examples perform well without modifications.
  But it's your job to pick the model and parameters that are suitable for your own situation.
  We cannot help with such questions unless they appear to be a bug in tensorpack.

+ "Why my own model doesn't perform well?", "I don't understand this paper you implement.",
  "How should I change the parameters for my own dataset?":

  We do not answer machine learning questions.
