### ISSUE TITLE
problem using weights of `COCO-MaskRCNN-R101FPN3xCasAug.npz` - result is bad. 

### ISSUE THREAD

**Issue by aaxwaz** [tensorpack/tensorpack#1239]
I re-downloaded the repo and model files again, and retried it, and it works now. Even though I don't know why. But thanks and please close the issue.

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template:
(1) If you're using examples, what's the command you run:
(2) If you're using examples, have you made any changes to the examples? Paste git status; git diff here:
