### ISSUE TITLE
DoReFa : how are the quantized and unquantized weights stored and used?

### ISSUE THREAD

**Issue by akm190** [tensorpack/tensorpack#1240]
Hi,
I am trying to understand the working of the DoReFa example in tensorpack. (svhn-digit-dorefa.py) 
I have read through the paper and this issue too: https://github.com/tensorpack/tensorpack/issues/31 . From these two sources I understand that the weights are maintained in floating point and for the forward pass we quantize them before using them in the fully-connected and convolutional layers. I am not able to understand the implementation of this part in the code.
1) Does    "with remap_variables(binarize_weight)"    quantize the actual floating point variables before using them in the forward pass or does it generate a new copy of the variables?
2) Also, in the backward pass, will the original floating point variables be updated or is the quantized copy of the variables going to be updated?
3) How are we indicating that the forward pass should use quantized ( or remap_variables) while the backward pass should use the original floating point variables?

Thanks for your help.

**Comment by ppwwyyxx** [comment]
1. There is no concept of "copy" in tensorflow so I'm not sure what you're trying to ask. The variables stay unquantized, if that's what you want to know.
2. The floating point variables are updated.
3. Because in tensorflow the optimizer optimizes trainable variables (in this case the unquantized floating point variables).

**Comment by akm190** [comment]
Thank you for your response. I think I am confused about the working of "with remap_variables(binarize_weight)" and its use with the graph. 

I understand The "remap_variables" function gets executed, which fetches all the trainable variables and quantizes them and returns a tensor containing quantized values. This tensor is in turn used by the operations in the graph to produce outputs. 
But then during the backward pass, will the compute_gradients use the quantized tensor or the floating values of the variable for computing gradients?
Can you please explain that how does this "remap_variables" functionality interact with the graph, especially when the gradients are being computed. 
Apologies if I am not framing my question correctly. I am not extremely familiar with complete flow of tensorflow. Thanks again for your help.

**Comment by ppwwyyxx** [comment]
remap_variables does not affect the mechanism with which the gradients are being computed: Each op in the graph defines how its gradient is computed using its input and output
