### ISSUE TITLE
Tensorpack DoReFaNet ResNet example on CIFAR100

### ISSUE THREAD

**Issue by snownus** [tensorpack/tensorpack#1241]
Recently, I wanna to use the Tensorpack Dorefanet examples to train cifar100 dataset from scratch. However, the start initial learning rate needs to set very small such as 0.0001 even it works.  
Tensorpack DoReFaNet example code:
https://github.com/tensorpack/tensorpack/blob/master/examples/DoReFa-Net/resnet-dorefa.py 

I was wondering whether it is related to the code settings, especially some manual settings such as 
https://github.com/tensorpack/tensorpack/blob/22f410e244a51fc4106396963b42a801fac23d0e/examples/DoReFa-Net/resnet-dorefa.py#L107

and https://github.com/tensorpack/tensorpack/blob/22f410e244a51fc4106396963b42a801fac23d0e/examples/DoReFa-Net/resnet-dorefa.py#L40 

Or why not use the ResNet code directly in https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py

@ppwwyyxx , can you provide more explanations??? or any suggestions if I want to train a DoReFaNet model based with ResNet on CIFAR100.  Thanks!

**Comment by ppwwyyxx** [comment]
See the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md):

## Some typical questions that we DO NOT answer:

"The examples do not perform as expected after I change the models/dataset/parameters/etc."

Tensorpack maintainers make sure the examples perform well without modifications. But it's your job to pick the model and parameters that are suitable for your own situation. We cannot help with such questions unless they appear to be a bug in tensorpack.

**Comment by snownus** [comment]
@ppwwyyxx , Thanks all the same. But, I would suggest that it is better to provide more details on some weird codes to help us figure out the problems. such as:
https://github.com/tensorpack/tensorpack/blob/22f410e244a51fc4106396963b42a801fac23d0e/examples/DoReFa-Net/resnet-dorefa.py#L107

**Comment by ppwwyyxx** [comment]
The line was explained as "a bug", so there isn't much more to say. In a normal network you apparently do not need to have this line.

See also https://github.com/tensorpack/tensorpack/issues/40#issuecomment-271124312

**Comment by snownus** [comment]
@ppwwyyxx , I see, thanks so much!
