### ISSUE TITLE
why using cfg.RPN.BATCH_PER_IM when calculating box losses for RPN?

### ISSUE THREAD

**Issue by PacteraKun** [tensorpack/tensorpack#1242]
In the **rpn_losses** function of _model_rpn.py_ file, the box losses is divided by the number of all the anchors, which is **cfg.RPN.BATCH_PER_IM**. But from the paper, it said it should be divided by the number of positive anchors instead of all the anchors. Am I right? Thanks.

**Comment by ppwwyyxx** [comment]
> But from the paper, it said it should be divided by the number of positive anchors

Where in the paper?

**Comment by PacteraKun** [comment]
Here is the loss function. 
![image](https://user-images.githubusercontent.com/40010065/59867433-08b9d880-9343-11e9-9db9-968581c4750a.png)
In the loss function, Nreg is not exactly the same as Ncls, where Ncls = 256 and λ = 10, Nreg ∼ 2400. Nreg/λ is approximately close to Ncls. Your code should be right. Thank you for your replay.
