### ISSUE TITLE
I meet a bug "KeyError: 'MaxBytesInUse'" when I try to print the op.names

### ISSUE THREAD

**Issue by maliyong** [tensorpack/tensorpack#1243]
I meet a bug "KeyError: 'MaxBytesInUse'" when I try to print the op.names,What should I do?

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by ppwwyyxx** [comment]
Closing as there is no response.
