### ISSUE TITLE
NVML error lib version mismatch

### ISSUE THREAD

**Issue by Rov67777** [tensorpack/tensorpack#1244]
When running tensorpack I have the following error with NVML library. This does not stop the program from running but still outputs an error message.

> [0624 14:45:33 @base.py:209] Setup callbacks graph ...
> Process Process-3:
> Traceback (most recent call last):
>   File "/data/anaconda/envs/tf_py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/data/anaconda/envs/tf_py36/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/data/anaconda/envs/tf_py36/lib/python3.6/site-packages/tensorpack/callbacks/prof.py", line 107, in worker
>     with NVMLContext() as ctx:
>   File "/data/anaconda/envs/tf_py36/lib/python3.6/site-packages/tensorpack/utils/nvml.py", line 164, in __enter__
>     _check_return(_NVML.get_function("nvmlInit_v2")())
>   File "/data/anaconda/envs/tf_py36/lib/python3.6/site-packages/tensorpack/utils/nvml.py", line 48, in _check_return
>     raise NvmlException(ret)
> tensorpack.utils.nvml.NvmlException: NVML_ERROR_LIB_RM_VERSION_MISMATCH
> [0624 14:45:34 @inference_runner.py:149] [InferenceRunner] Building tower 'InferenceTower' on device /gpu:0 ...
> sigmoid

I use :
- tensorflow 1.14
- tensorpack 0.9.5
- Anaconda python 3.6

**Comment by ppwwyyxx** [comment]
As said in nvidia documentation: https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceEnumvs.html

> NVML_ERROR_LIB_RM_VERSION_MISMATCH = 18
 RM detects a driver/library version mismatch.

It's likely that you did not reboot the machine since last time the driver is updated.
