### ISSUE TITLE
Generator with MapData terminates unexpectedly with StopIteration

### ISSUE THREAD

**Issue by dps42** [tensorpack/tensorpack#1245]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, tell us what you did:**
  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

  Here's the code
[z_debug2.zip](https://github.com/tensorpack/tensorpack/files/3321523/z_debug2.zip)

  I ran 'python create_lmdb_debug.py' then 'python debug2.py'

  The dataflow created with a function 'load_lmdb_working()' using MapDataComponent is working fine, but the one with 'load_lmdb3()' using a "MapData" is not working and terminates unexpectedly with StopIteration.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

(dps42_dev) C:\AI_Workspace\z_debug2>python debug2.py
[0624 11:31:39 @format.py:92] Found 3 entries in train_debug.lmdb
[0624 11:31:39 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
Traceback (most recent call last):
  File "debug2.py", line 144, in <module>
    batch_X_train, batch_y_encoded_train = train_generator.generate_train2()
  File "debug2.py", line 120, in generate_train2
    data = next( self.ds.__iter__() )
StopIteration

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

The Dataflow using a MapData should work without terminating unexpectedly with 'StopIteration'.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect certain training results (e.g., accuracy), only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to train a model is a machine learning question.
We do not answer machine learning questions and it is your responsibility to
figure out how to make your models more accurate.

### 4. Your environment:
  + Paste the output of this command: `python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
    If this command failed, tell us your version of Python/TF/tensorpack.
  + You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.
  + Include relevant hardware information, e.g. number of GPUs used for training, amount of RAM.

Windows 10

sys.platform          win32
Python                3.5.2 | packaged by conda-forge | (default, Jan 19 2017, 15:41:23) [MSC v.1900 64 bit (AMD64)]
Tensorpack            v0.9.4-99-g22f410e2-dirty
Numpy                 1.13.3
TensorFlow            1.10.0/b'unknown'
TF Compiler Version   MSVC 190024215
TF CUDA support       True
TF MKL support        False
Nvidia Driver
CUDA
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   Not found with NVML
Free RAM              113.82/127.67 GB
CPU Count             20
cv2                   4.1.0
msgpack               0.5.6
python-prctl          False

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
It stops iteration because the mapping function you provided returns `None`.
As the [documentation](https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.MapData) said if your mapping function returns None the data is discarded/skipped. Therefore all your data are skipped and the dataflow stops.

**Comment by dps42** [comment]
Thank you for the explanation. My bad..
