### ISSUE TITLE
where predict.py do in examples/FasterRCNN ?

### ISSUE THREAD

**Issue by shiqin-zhang** [tensorpack/tensorpack#1246]
I run predict.py like this:

`python predict.py --predict imgs/1.jpg --load /home/shiqin.zhang/FasterRCNN-Data/ImageNet-R50-AlignPadding.npz`

but there is nothing changed in the `output.png`. so could you tell me what `predict.py` and `ImageNet-R50-AlignPadding.npz` really do to the `imgs/1.jpg`.

**Comment by ppwwyyxx** [comment]
You should use a model in the table in the README.

**Comment by shiqin-zhang** [comment]
thx a lot, I use the model in the table and get the right output.
