### ISSUE TITLE
How to convert quantized weights to integer ?

### ISSUE THREAD

**Issue by zhouchch3** [tensorpack/tensorpack#1247]
After training the (8,8,32) AlexNet with dorefa-alexnet.py, I use the recommanded fw.py to quantize the  weights:
`import tensorflow as tf
from tensorflow.python import pywrap_tensorflow
import numpy as np
import os
model_dir = "./train_log/alexnet-dorefa-8,8,32/"
checkpoint_path = os.path.join(model_dir, "model-5000")
reader = pywrap_tensorflow.NewCheckpointReader(checkpoint_path)
var_to_shape_map = reader.get_variable_to_shape_map()
print("############# PRINT WEIGHT ##############")
key = 'conv0/W'

print("tensor_name: ", key)
weight0 = reader.get_tensor(key)
print(weight0)
print("########### Quantized Weight #############")
bitW = 8
def quantize(x,k):
    n = float(2**k - 1)
    return tf.round(x * n) / n
def fw(x):
    if bitW == 32:
        return x
    if bitW == 1:   # BWN
        E = tf.stop_gradient(tf.reduce_mean(tf.abs(x)))
        return tf.sign(x / E) * E
    x = tf.tanh(x)
    x = x / tf.reduce_max(tf.abs(x)) * 0.5 + 0.5
    return 2 * quantize(x, bitW) - 1
sess = tf.Session()
print( sess.run( fw(weight0) ) )`

I get following weights.txt, but the weights are **float not integer**. How can I do? Thank you!

`[-0.01960784  0.10588241 -0.19999999  0.1686275   0.00392163  0.30196083
 -0.10588235 -0.03529412  0.00392163  0.01176476 -0.04313725 -0.16862744
 -0.27843136  0.01176476 -0.00392157 -0.16862744  0.18431377 -0.09803921
 -0.10588235  0.20000005 -0.26274508  0.09019613  0.07450986 -0.05098039
  0.24705887 -0.01176471 -0.14509803  0.09019613 -0.40392154 -0.1372549
 -0.0745098  -0.02745098  0.00392163 -0.02745098 -0.38823527 -0.06666666
  0.06666672 -0.08235294  0.0196079  -0.08235294  0.09019613 -0.34117645
 -0.12156862  0.01176476 -0.11372548 -0.11372548 -0.12941176  0.05098045
  0.14509809  0.16078436  0.07450986  0.082353   -0.08235294 -0.0745098
  0.00392163 -0.27058822 -0.00392157 -0.6392157   0.17647064 -0.18431371
 -0.09019607  0.43529415  0.06666672  0.20784318 -0.15294117  0.14509809
 -0.14509803  0.04313731 -0.0745098  -0.06666666  0.02745104 -0.1607843
 -0.02745098  0.17647064 -0.0745098   0.2941177   0.38823533 -0.34117645
  0.20784318  0.21568632  0.17647064 -0.3333333   0.02745104  0.00392163
  0.02745104 -0.12941176 -0.21568626 -0.21568626  0.09803927 -0.06666666
  0.5529412  -0.05098039  0.09803927  0.11372554  0.0196079  -0.29411763
  0.3176471   0.05098045 -0.31764704 -0.09803921 -0.2235294   0.36470592
 -0.02745098  0.04313731 -0.00392157 -0.04313725  0.00392163  0.3803922
  0.02745104  0.09019613  0.254902    0.17647064  0.04313731  0.3176471`

**Comment by ppwwyyxx** [comment]
The code you pasted above converts integers to these float...

**Comment by zhouchch3** [comment]
For reading better, I paste the picture of code:
![image](https://user-images.githubusercontent.com/33385095/60384720-ded78300-9ab3-11e9-89fb-6af3fcf943a2.png)

Doesn't the code implement the following function copied from _DoreFa-Net_ paper ?. In this paper, the function is for quantizing weights? Is there anything I misunderstand ?
![image](https://user-images.githubusercontent.com/33385095/60384709-aafc5d80-9ab3-11e9-8a04-03bc250a0b23.png)

![image](https://user-images.githubusercontent.com/33385095/60384617-a7b4a200-9ab2-11e9-8a25-4544f91f1c1e.png)

**Comment by ppwwyyxx** [comment]
`tf.round` return integers
