### ISSUE TITLE
How to summary matrix into tensorboard histogram?

### ISSUE THREAD

**Issue by ToWeRT1An** [tensorpack/tensorpack#1248]
I am using [https://github.com/tensorpack/tensorpack/tree/master/examples/DoReFa-Net] and I want to save a matirx into histogram to see it's distribution.
i built a function 
```python
 def beforeBN(x):
    m = tf.Variable(x)
        if is_training:
            with train_summary_writer.as_default():        
                summary.histogram('beforeBN',x,step=get_global_step_var())
    return x
```
and I apply it into a layer

```python                   
  .Conv2D('conv5', 128, 3, padding='VALID')
                      .apply(fg)
                      .apply(beforeBN)
                      .BatchNorm('bn5')
```
But I got error like this:

> RuntimeError: Attempting to capture an EagerTensor without building a function.

I know it's because the format of x that leads to the bug. I have tried np.array(x), x.eval(),I have even tried using tf.constant() to replace x. But all of these failed. So how can I put them into summay.histogram?

**Comment by ppwwyyxx** [comment]
You need
```
.apply(lambda x: tf.summary.histogram('name', x)
```

See docs for details: https://tensorpack.readthedocs.io/tutorial/summary.html#tensorflow-summaries

**Comment by ToWeRT1An** [comment]
thanks a lot!
