### ISSUE TITLE
logging images into a single tag in tensorboard

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [tensorpack/tensorpack#1250]
I write a callback during training and put 12 images like:
```
....
#images.shape=[12, 640, 640, 3]
....
for idx, image in enumerate(images):
    self.trainer.monitors.put_image('validation_sample-{}'.format(idx), image)
```
It works and the result looks like this:
![image](https://user-images.githubusercontent.com/10048576/60560079-1a5aa180-9d81-11e9-8c60-f7b612e88470.png)

I was wondering if it is possible to merge them into one single tag with 12 images like(this is exactly what `tensorflow.summary.image('validation_sample', images, 12)` do):
![image](https://user-images.githubusercontent.com/10048576/60560146-5261e480-9d81-11e9-9e69-4ec6b2a74703.png)

Is there any function like  `put_images()`. If not, How can I implement a function to use`tensorflow.summary.image('validation_sample', images, 12)`  in my own callback?  I think it's much easier to visualize the result when training models like FasterRCNN.

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.Monitors.put_image

The docs say `put_image` takes 4D input already.
