### ISSUE TITLE
How to train custom dataset?

### ISSUE THREAD

**Issue by rasputin1917** [tensorpack/tensorpack#1251]
Hi guys, I have some questions for using tensorpack's faster R-CNN. 

So I want to train a model with my custom dataset. Untill now I was using matterports Mask RCNN which is doing a good job but I would like to test an implementation of faster RCNN. 

My training dataset format for Mask RCNN is the actual images and a file including boolean masks per image as it is in nucleus.py (https://github.com/matterport/Mask_RCNN/tree/master/samples/nucleus)  example. 

Can anybody help me about the format I need to use for training this faster rcnn implementation? How to create the dataset etc..?

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md#implementation-notes

**Comment by ppwwyyxx** [comment]
Added an example https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/BALLOON.md

**Comment by HuangBo-Terraloupe** [comment]
thanks for the friendly example.
Is the repo also suppport the training of Cascade R-CNN models only for object detection?
I mean ignore the segmentation.
I am trying to follow the Balloon example to run my custom training, in the preparation I found the annotation include segmentation mask.

**Comment by ppwwyyxx** [comment]
See the MODE_MASK option.
