### ISSUE TITLE
Training speed is faster than TestDataSpeed()

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [tensorpack/tensorpack#1253]
I wrote a dataflow which can process 24 images/sec( 1.5 it/s * batch=16) by using TestDataSpeed()

But training speed(Using QueueInput() with default arguments) is 52 images/sec(3.2 it/s * batch=16) and the queue size in tensorboard is always full, so does GPU utilization rate.

How could training run faster than image preprocessing speed?

**Comment by ppwwyyxx** [comment]
This should be impossible, and it might be due to an incorrect way of measuring speed (e.g. If the speed has high variance.

**Comment by ArtificialNotImbecile** [comment]
> This should be impossible, and it might be due to an incorrect way of measuring speed (e.g. If the speed has high variance.

Yes, you are right.  The reason that it's slow in the beginning is that opening too many threads on my computer costs a lot of time, but it gradually speeds up. I should've run a thorough test before asking.  Thanks a lot!
