### ISSUE TITLE
the Faster-Rcnn scaling efficiency is low by using Horovod Trainer

### ISSUE THREAD

**Issue by jiangzihanict** [tensorpack/tensorpack#1254]
Environment:

Framework: TensorFlow
Framework version: 1.12
Horovod version: 0.15.2
MPI version: 3.1.2
CUDA version: 9.0
NCCL version: 2.3.5
Python version: 3.5
OS and version: linux ubuntu 16.04
GCC version: 5.4
Your question:
We are scaling a FasterRCNN from 1 GPU to 32GPUs (4nodes, 8 GPUs per node). The performance numbers are as following:

1GPU: 5 images/s
8GPUs: 25 images/s
16GPUs(2 nodes): 41 images/s
32GPUs(4nodes): 80 images/s

So the scaling efficiency is only 50%? Even in the same node, the efficiency is only 60%. I read the performance data in Horovod's paper (the attached picture). Is this efficiency related to the model? In addition, our experiments are performed in docker, will this have any bad impact?
![Screen Shot 2019-07-04 at 4 38 32 PM](https://user-images.githubusercontent.com/22028950/60653665-0b591980-9e7d-11e9-94c4-89e8ee2dec00.png)

**Comment by ppwwyyxx** [comment]
In R-CNN each sample goes through different amount of computation, so it is unreasonable to compare speedup with traditional models.
In R-CNN each sample has different sizes and require longer cudnn warmup time, so how you measure the speedup matters a lot. It will be better if you show raw logs rather than your interpretation of them.

**Comment by ppwwyyxx** [comment]
But in any case there isn't much point measuring scalability of heterogeneous workload. Using a homogeneous model like https://github.com/tensorpack/benchmarks/tree/master/ResNet-MultiGPU to measure scalability makes more sense.

**Comment by jiangzihanict** [comment]
Got it. I noticed the scaling efficiency of FasterRcnn in [NOTES.md](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md) is up to 90%.  How do you measure it? Does every rank have to process exactly the same data?

**Comment by ppwwyyxx** [comment]
IIRC I resize all images to the same shape. In this case the amount of computation will still be different across GPUs, but closer. I will mention this in NOTES.md.

An opportunity for speed up might be to produce images of similar shapes together instead of in arbitrary order.
