### ISSUE TITLE
Train Faster R-CNN with images with no bounding boxes

### ISSUE THREAD

**Issue by Viky397** [tensorpack/tensorpack#1256]
Is there a way to train Faster R-CNN with images that have no labels on them? As of right now it filters all these images out, and after playing around with the scripts for a while it seems like it'll take more than removing the filter in data.py to fix it.

**Comment by ppwwyyxx** [comment]
>  after playing around with the scripts for a while it seems like it'll take more than removing the filter in data.py to fix it.

You are right. See also #1230

**Comment by Viky397** [comment]
"modifying the models at where it breaks" is what I have been doing. Was wondering if anyone has managed to achieve this yet. If we work together, we all succeed!

**Comment by ppwwyyxx** [comment]
It's now supported in the above commit. There aren't many changes needed to handle empty inputs.

**Comment by Viky397** [comment]
Thank you so much! :)
