### ISSUE TITLE
why Conv3D() be placed at CPU with gradproc.GlobalNormClip() 

### ISSUE THREAD

**Issue by courins** [tensorpack/tensorpack#1259]
Case 01
lr = tf.get_variable('learning_rate', initializer=1e-3, trainable=False)
opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
return optimizer.apply_grad_processors(opt, [gradproc.GlobalNormClip(10)])

get tf timeline result and too slow training speed

![image](https://user-images.githubusercontent.com/25920869/60956036-9bdba200-a334-11e9-9b82-3a0445ae8a60.png)

Case 02
lr = tf.get_variable('learning_rate', initializer=1e-3, trainable=False)
opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
return opt

get tf timeline result and normal training speed

![image](https://user-images.githubusercontent.com/25920869/60955960-76e72f00-a334-11e9-90cc-1f760ad0d24f.png)

i want to why? 
gradproc.GlobalNormClip() 's issue or tf.clip_by_global_norm()'s issue? 
or windows's issue?

my envs is 

win7 x64 System
Nvidia Geforce GTX 1080 (8G)
CUDA9.0
cuDNN7.0.5
tensorflow-gpu(1.6.0)
tensorpack (0.8.0)

how to get right result with using gradproc.GlobalNormClip()?
please help me!tks!

detailed descroption here:
https://github.com/amiralansary/tensorpack-medical/issues/10

**Comment by ppwwyyxx** [comment]
> Case 01
lr = tf.get_variable('learning_rate', initializer=1e-3, trainable=False)
opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
return optimizer.apply_grad_processors(opt, [gradproc.GlobalNormClip(10)])
get tf timeline result and too slow training speed

I add this optimizer to an official tensorpack example (imagenet-resnet.py) and tested it on TF 1.6. No significant slow down is observed.

Please try to provide enough details to reproduce the issue if you can.

**Comment by courins** [comment]
i just run https://github.com/amiralansary/tensorpack-medical/tree/master/examples/LandmarkDetection/DQN examples using https://github.com/amiralansary/tensorpack-medical/tree/master/examples/LandmarkDetection/DQN/data under my env.
the main difference is my windows system.
some ops be placed at CPU when using gradproc.GlobalNormClip()

**Comment by ppwwyyxx** [comment]
If you think code is the problem, please provide something that others can easily run to reproduce the issue.

If you think windows system is the problem, then it's unlikely I can help with that.

**Comment by ppwwyyxx** [comment]
If you don't know what to include to let others reproduce your issue, [tensorpack issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems---bugs.md) tells you.

Running 
```
python DQN.py --task train --algo DQN --gpu 0 --files './data/filenames/image_files.txt' './data/filenames/landmark_files.txt'
``` 
with the only changes from https://github.com/amiralansary/tensorpack-medical/issues/9#issuecomment-510309070 on tensorpack master and TF 1.13 does not show any slowdown.

**Comment by courins** [comment]
@ppwwyyxx thank you very much firstly.
i think tf maybe is the problem, i try to run again under TF1.13 and tensorpack master.

**Comment by courins** [comment]
I run this example under TF1.13.1-gpu and tensorpack master(0.9.5), not show any slowdown.
@ppwwyyxx Thanks a lot!
