### ISSUE TITLE
How to train my backbone network using tensorpack?

### ISSUE THREAD

**Issue by cocopambag** [tensorpack/tensorpack#1260]
Thank you for making a tensorpack.
Well, i want to use my backbone network. so, i modify example of FasterRCNN. so, backbone.py
Look at READMD.md, 

`./train.py --config \
    MODE_MASK=True MODE_FPN=True \
    DATA.BASEDIR=/path/to/COCO/DIR \
    BACKBONE.WEIGHTS=/path/to/ImageNet-R50-AlignPadding.npz`

here, "BACKBONE.WEIGHTS=/path/to/ImageNet-R50-AlignPadding.npz "
i don't have backbone weight..... How should i do? 
and i want to scratch training. so, i make a config.py 

here.
`MODE_FPN=True FPN.CASCADE=True
BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3]
FPN.NORM=GN BACKBONE.NORM=GN
FPN.FRCNN_HEAD_FUNC=fastrcnn_4conv1fc_gn_head
FPN.MRCNN_HEAD_FUNC=maskrcnn_up4conv_gn_head
PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800]
TRAIN.LR_SCHEDULE=[1500000,1580000,1620000]
BACKBONE.FREEZE_AT=0`

Is this the right way to change config.py?

Thank you!

**Comment by ppwwyyxx** [comment]
> i don't have backbone weight..... How should i do?

You should train your backbone first. The existing backbones are trained with tensorpack on ImageNet.

> and i want to scratch training. so, i make a config.py

It's very expensive, and you need to implement your backbones following the rules from the paper of training from scratch (https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN#faster-r-cnn--mask-r-cnn-on-coco). In brief, the rules in the paper are:
1. use GN or SyncBN
2. train longer

**Comment by cocopambag** [comment]
Ah, Thank you. i tried on
but, I encountered another errors... I'm sorry to keep asking.
i use to trainer is horovod!. and i have eight gpu. so, I entered the command.
here...
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NCCL_DEBUG=INFO mpirun -np 8 --output-filename mylog python -m train.py --config \
    DATA.BASEDIR=COCO/DIR \
    TRAINER=horovod
`
i meet error message.

> 'MPI_COMM_WORLD SIZE' not in os.environ

so.... Is this error an 'mpirun'?

**Comment by ppwwyyxx** [comment]
Please include full error message and the output of `mpirun --version; mpirun -np 1 env | grep MPI`.
You can just remove the assertion line and I think it should work the same.

**Comment by cocopambag** [comment]
i process `mpirun --version; mpirun -np 1 env | grep MPI`
and the result is blow.

`(tensorpack) yoohj@8gpu-ib:~/FasterRCNN$ mpirun --version; mpirun -np 1 env | grep MPI

mpirun (Open MPI) 2.0.1

Report bugs to http://www.open-mpi.org/community/help/
OMPI_MCA_pmix=^s1,s2,cray
OMPI_COMMAND=env
OMPI_MCA_orte_precondition_transports=a5527937ebbaef35-c57ecb5b53a2ec85
OMPI_MCA_orte_local_daemon_uri=315686912.0;usock;tcp://129.254.165.91,200.200.200.100,100.100.100                                                                                                           .15,172.17.0.1:39517;ud://1108.25.1
OMPI_MCA_orte_hnp_uri=315686912.0;usock;tcp://129.254.165.91,200.200.200.100,100.100.100.15,172.1                                                                                                           7.0.1:39517;ud://1108.25.1
OMPI_MCA_mpi_yield_when_idle=0
OMPI_MCA_orte_app_num=0
OMPI_UNIVERSE_SIZE=1
OMPI_MCA_orte_num_nodes=1
OMPI_MCA_shmem_RUNTIME_QUERY_hint=mmap
OMPI_MCA_orte_bound_at_launch=1
OMPI_MCA_ess=pmi
OMPI_MCA_orte_ess_num_procs=1
OMPI_COMM_WORLD_SIZE=1
OMPI_COMM_WORLD_LOCAL_SIZE=1
OMPI_MCA_orte_tmpdir_base=/tmp
OMPI_NUM_APP_CTX=1
OMPI_FIRST_RANKS=0
OMPI_APP_CTX_NUM_PROCS=1
OMPI_MCA_initial_wdir=/home/yoohj/FasterRCNN
OMPI_MCA_orte_launch=1
OMPI_MCA_ess_base_jobid=315686913
OMPI_MCA_ess_base_vpid=0
OMPI_COMM_WORLD_RANK=0
OMPI_COMM_WORLD_LOCAL_RANK=0
OMPI_COMM_WORLD_NODE_RANK=0
OMPI_MCA_orte_ess_node_rank=0
OMPI_FILE_LOCATION=/tmp/openmpi-sessions-1007@8gpu-ib_0/4817/1/0
`

And, 
Can i remove the assertion line? so, Does not it happend critical problem?
thank you.

**Comment by cocopambag** [comment]
i process mpirun --version; mpirun -np 1 env | grep MPI
and the result is blow.

`(tensorpack) yoohj@8gpu-ib:~/FasterRCNN$ mpirun --version; mpirun -np 1 env | grep MPI

mpirun (Open MPI) 2.0.1

Report bugs to http://www.open-mpi.org/community/help/
OMPI_MCA_pmix=^s1,s2,cray
OMPI_COMMAND=env
OMPI_MCA_orte_precondition_transports=a5527937ebbaef35-c57ecb5b53a2ec85
OMPI_MCA_orte_local_daemon_uri=315686912.0;usock;tcp://xxx.xxx.xxx.xxx,200.200.200.100,100.100.100 .15,172.17.0.1:39517;ud://1108.25.1
OMPI_MCA_orte_hnp_uri=315686912.0;usock;tcp://xxx.xxx.xxx.xxx,200.200.200.100,100.100.100.15,172.1 7.0.1:39517;ud://1108.25.1
OMPI_MCA_mpi_yield_when_idle=0
OMPI_MCA_orte_app_num=0
OMPI_UNIVERSE_SIZE=1
OMPI_MCA_orte_num_nodes=1
OMPI_MCA_shmem_RUNTIME_QUERY_hint=mmap
OMPI_MCA_orte_bound_at_launch=1
OMPI_MCA_ess=pmi
OMPI_MCA_orte_ess_num_procs=1
OMPI_COMM_WORLD_SIZE=1
OMPI_COMM_WORLD_LOCAL_SIZE=1
OMPI_MCA_orte_tmpdir_base=/tmp
OMPI_NUM_APP_CTX=1
OMPI_FIRST_RANKS=0
OMPI_APP_CTX_NUM_PROCS=1
OMPI_MCA_initial_wdir=/home/yoohj/FasterRCNN
OMPI_MCA_orte_launch=1
OMPI_MCA_ess_base_jobid=315686913
OMPI_MCA_ess_base_vpid=0
OMPI_COMM_WORLD_RANK=0
OMPI_COMM_WORLD_LOCAL_RANK=0
OMPI_COMM_WORLD_NODE_RANK=0
OMPI_MCA_orte_ess_node_rank=0
OMPI_FILE_LOCATION=/tmp/openmpi-sessions-1007@8gpu-ib_0/4817/1/0
`

And,
Can i remove the assertion line? so, Does not it happend critical problem?
thank you.

**Comment by ppwwyyxx** [comment]
Please include __full error message__ as well

**Comment by cocopambag** [comment]
here, error message 
`
(tensorpack) yoohj@8gpu-ib:~/FasterRCNN$ CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NCCL_DEBUG=INFO mpirun -np 8 --output-filename mylog python train.py --config     MODE_FPN=True FPN.CASCADE=True     DATA.BADIR=COCO/DIR     TRAINER=horovod
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[11256,1],3] (PID 3346)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
[8gpu-ib:03337] 7 more processes have sent help message help-opal-runtime.txt / opal_init:warn-fork
[8gpu-ib:03337] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
`
Thank you

**Comment by ppwwyyxx** [comment]
Thanks, I was asking about the error message of the python program, i.e. the assertion error that you reported.

**Comment by cocopambag** [comment]
python program error message. i find it !!!!!
I look at the mylog. and i find it problem. 
this is my mistake.... 
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NCCL_DEBUG=INFO mpirun -np 8 --output-filename mylog python -m train.py --config \ DATA.BASEDIR=COCO/DIR \ TRAINER=horovod `
it don't correct command!!
`python -m train.py` -> `python train.py` 
my mistake i'm so sorry.

and.. i try to train my backbone.py 
but, the monitor.py contents are no longer visible.
and  i check the contents of monitor.py in 'mylog.1.0', which is the result of mpirun.....
Is this what it is?
Thank you!!

**Comment by ppwwyyxx** [comment]
I cannot understand your question. I do not know what is "monitor.py" and how is it related to tensorpack. I cannot understand what you observed and what you expected to see.

The [tensorpack issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems---bugs.md) can help you explain more details.

**Comment by cocopambag** [comment]
Thank you for your comment.
hmm... This is another question. i want to use vovnet(this is what i made) instead of resnet.

so i modify backbone.py and i try to train this command 
`python -m train.py --config \ DATA.BASEDIR=COCO/DIR  `

but, the readme is written this command.
`./train.py --config \
    MODE_MASK=True MODE_FPN=True \
    DATA.BASEDIR=/path/to/COCO/DIR \
    BACKBONE.WEIGHTS=/path/to/ImageNet-R50-AlignPadding.npz`


so, i don't use 'BACKBONE.WEIGHTS' parameter because i don't have backbone weight of vovnet.
if there is no backbone weight here, where is the learned weight left? 

thank you for reading!!

**Comment by ppwwyyxx** [comment]
> if there is no backbone weight here, where is the learned weight left?

Since you don't have backbone weight, what do you mean by "the learned weight"?

If you don't specify the config, the weight will be randomly initialized.

**Comment by cocopambag** [comment]
Ah ha!! 
weight will be radomly initialized!! 
Thank you. i understand.
What I wanted to tell you is that i need the ckpt i need to predict.

This problem seems to be resolved.
