### ISSUE TITLE
How can i use fine-turning in DoReFa-net?

### ISSUE THREAD

**Issue by baizeboob** [tensorpack/tensorpack#1263]
I want to train or optimize only certain layers(fct layer) of DoRefo-net , so I use fine-turning in alexnet-dorefa.py by following way: Using minimize method to take an optional argument var_list, a list of variables to be adjusted through back-propagation. See following code:
 `def _get_optimizer(self): `
         `lr = tf.get_variable('learning_rate', initializer=1e-4, trainable=False) `
         `tvars = tf.trainable_variables()`
         `g_vars = [var for var in tvars if 'fct' in var.name]`
        ` return tf.train.AdamOptimizer(1e-4, epsilon=1e-5).minimize(self.cost,var_list=g_vars)`

But it gets wrong as following:
`  grads = opt.compute_gradients(
AttributeError: 'Operation' object has no attribute 'compute_gradients'
`

what is wrong with this issue? Is there another way to achieve the fine-turning in DoReFa-net @tensorpack？

Note: The input command is `python ./alexnet-dorefa_***.py --dorefa 1,8,32 --data /data/ImageNet/imagenet/ILSVRC2015/Data/CLS-LOC --gpu 0,1`

**Comment by ppwwyyxx** [comment]
> I want to train or optimize only certain layers(fct layer) of DoRefo-net

https://tensorpack.readthedocs.io/tutorial/faq.html#how-to-freeze-some-variables-in-training
