### ISSUE TITLE
Faster-RCNN outputs two class labels in one bounding box

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1264]
Hi I'm using the Faster-RCNN module of Tensorpack. And I found a strange problem. After trainging the Faster-RCNN with 720000 iterations using 4 GPUs. And after being deployed, the model will outputs some different class labels in the same bounding box. Please check the following outputs:

    all pred_boxes
    [[ 26.396263    9.007713  122.73848    30.237213 ]
     [ 77.81743    13.256683   85.787766   26.171234 ]
     [ 60.119705   12.936951   67.804665   25.473648 ]
     [ 25.903313   12.475304   33.975273   25.105072 ]
     [ 96.60037    13.7632065 104.027985   26.510788 ]
     [ 42.85447    12.861534   50.677887   25.453796 ]
     [112.54819    21.776718  120.677795   29.949356 ]
     [ 41.901222   12.423477   50.033913   25.51213  ]
     [114.07869    11.468361  121.510605   19.963806 ]
     [113.66882    11.212532  121.80649    19.93155  ]
     [112.76721    21.759552  121.72537    29.968262 ]
     [ 25.212234   12.235214   33.14897    26.05365  ]
     [ 96.64612    13.79985   104.983215   27.457184 ]]
    all labels [111   0   0   1   6   1   4   0   0   3   1   0   8]
    all scores [0.9998647  0.9951749  0.99021345 0.96291673 0.9350704  0.86680984
     0.83631796 0.74103004 0.6907046  0.50689065 0.48967427 0.44830406

In the position of  `[112.54819    21.776718  120.677795   29.949356 ]` and  `[112.76721    21.759552  121.72537    29.968262 ]`, there are two different labels `4` and `1` with score of `0.83631796` and `0.48967427`. And the same thing will also occur in `[ 42.85447    12.861534   50.677887   25.453796 ]` and `[ 41.901222   12.423477   50.033913   25.51213  ]` with labels of `1` and `0` and score of `0.86680984` and `0.74103004`, respectively. 

I checked the dataset, it seems there are some labeling errors in there. Is this the main reason for this kind of problem? Could you please help some advice? Thanks.

**Comment by ppwwyyxx** [comment]
This is how the model works. The model by design does not avoid making different predictions in nearby bounding boxes.

**Comment by Remember2018** [comment]
@ppwwyyxx Thanks Yuxin!
