### ISSUE TITLE
A strange training stuck

### ISSUE THREAD

**Issue by wkoa** [tensorpack/tensorpack#1269]
So I have met the same stuck just like [https://github.com/tensorpack/tensorpack/issues/1134](Issue#1134). Any ideas can solve this bug? Comment two line?
`    # if not is_horovod:
    #     callbacks.append(GPUUtilizationTracker())`

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
