### ISSUE TITLE
List annotations out from the prediction output (png image)

### ISSUE THREAD

**Issue by pepeuno** [tensorpack/tensorpack#1272]
+ If you did something with tensorpack and it failed, PLEASE STOP HERE and use the "Unexpected Problems /
  Bugs" category.

+ Your question is probably answered in [tutorials](http://tensorpack.readthedocs.io/tutorial/index.html#user-tutorials). Read it first.

+ We answer "HOW to do X with Tensorpack" for a well-defined specific X.
  X must be something that you conceptually know how to do, but are unable to do due to lack of knowledge about Tensorpack.
  We don't answer vague questions like "How to do semantic segmentation in Tensorpack".

+ We also answer "HOW/WHY Tensorpack does X" for some X that Tensorpack or its examples are doing.

Some typical questions that we DO NOT answer:

+ "Could you improve/implement an example/paper?":

  We have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you.
  If you don't know how to do something yourself, you may ask a usage question.

+ "The examples do not perform as expected after I change the models/dataset/parameters/etc.":

  Tensorpack maintainers make sure the examples perform well without modifications.
  But it's your job to pick the model and parameters that are suitable for your own situation.
  We cannot help with such questions unless they appear to be a bug in tensorpack.

+ "Why my own model doesn't perform well?", "I don't understand this paper you implement.",
  "How should I change the parameters for my own dataset?":

  We do not answer machine learning questions.

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

Hi, 

I trained FasterRCNN model to detect traffic signs. When I do inference I got a png image which is a composition of two images, one on the left with the previous image (no action on it) and one on the right showing bounding boxes and the name of the elements detected. 

This may not be a question to launch here (maybe yes) but I would appreciate a feedback if possible. Here the question: How can I list out the elements detected in the png image? in other words if I got detected 4 prohibited signs, 3 stop signs and 1 speed sign, how can I list those elements out in a list or array or whatever structure I would like?, I would like to get something like: ["4 prohibited","3 stops signs", "1 speed sign"]

Many thanks!

**Comment by ppwwyyxx** [comment]
You can print them in the code yourself.

**Comment by hasan-nn** [comment]
hello, i have a related question
i want to get all the prediction, but i want to run prediction on all the images in a given directory not a single image.Is there an already implemented way or i have to modify on the code ?

**Comment by ppwwyyxx** [comment]
Please modify `predict.py`.

**Comment by hasan-nn** [comment]
okay thank you!
