### ISSUE TITLE
Retrieve tensor values during inference

### ISSUE THREAD

**Issue by T1anZhenYu** [tensorpack/tensorpack#1274]
I am using "DumpTensors" to retrieve tensor values duing Training. How can I get the same tensor's value during inference? As far as I know, this callbacks only works during training.
Thanks a lot.

**Comment by ppwwyyxx** [comment]
See
https://tensorpack.readthedocs.io/tutorial/inference.html#inference-after-training-what-tensorpack-does

**Comment by T1anZhenYu** [comment]
Thanks for your quickly reply!

**Comment by T1anZhenYu** [comment]
I am sorry but I still don't get it. I implement the "OfflinePredictor" like this:

def eval_classification(model, sessinit, dataflow):
    pred_config = PredictConfig(
        model=model,
        session_init=sessinit,
        input_names=['input', 'label'],
        output_names=['wrong-top1']
    )
    acc1 = RatioCounter()
    pred = FeedfreePredictor(pred_config, StagingInput(QueueInput(dataflow), device='/gpu:0'))
    for _ in tqdm.trange(dataflow.size()):
        top1 = pred()[0]
        batch_size = top1.shape[0]
        acc1.feed(top1.sum(), batch_size)

Then, I call the model using this:
`
python ./tensorpack/examples/DoReFa-Net-eidt/svhn-digit-dorefa.py --dorefa 1,2,32 --load ./dorefa_log/svhn-dorefa-1,2,32/model-4721 --eval
`

But the 'DumpTensor' callback doesn't work. It seems that 'PredictConfig' doesn't have 'Callbacks' parameter, so how can I get the tensor value without "DumpTensor".
Thansk a lot

**Comment by ppwwyyxx** [comment]
Add the tensor you want to evaluate to:
`output_names=['wrong-top1']`.
Then `pred()` will return it.
