### ISSUE TITLE
How to extract weight data using tensorpack

### ISSUE THREAD

**Issue by cocopambag** [tensorpack/tensorpack#1275]
Hi, everyone. 
I use examples of FasterRCNN. so, i use R50-FPN and config is standard.
then, i want to extract weight data which i trained it.
Thank you

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/save-load.html#work-with-a-tf-checkpoint

**Comment by cocopambag** [comment]
Thank you for your comment.
I see it!!
