### ISSUE TITLE
What is the most suitable combination of (W,A,G) for AlexNet@BWN?

### ISSUE THREAD

**Issue by baizeboob** [tensorpack/tensorpack#1277]
I used the combination of (W,A,G = 1,8,32) on ILSVRC2015 for AlexNet@BWN, but the Val-error-top1 ranged from 0.53074 to 0.68202.

**Comment by ppwwyyxx** [comment]
There is no most suitable combination if there is no definition of "suitable". You need to pick your own parameters for your situation.

**Comment by baizeboob** [comment]
Hello.
In my view, the most suitable combination of (W,A,G) is  to get closer to unquantified network accuracy.
So, from your experience, what is the most suitable combination of (W,A,G)?

**Comment by ppwwyyxx** [comment]
Then the most suitable combination is (32, 32, 32). 
The slightly less suitable combination is (8, 32, 32).
