### ISSUE TITLE
cannot connect to tensorpack model zoo.

### ISSUE THREAD

**Issue by junsukchoe** [tensorpack/tensorpack#1280]
Hi, 

Currently I cannot connect to [tensorpack model zoo](https://models.tensorpack.com).
It only shows an error message, 502 Bad Gateway. The pre-trained models are not available any more?

Thanks,
Junsuk

**Comment by ppwwyyxx** [comment]
It seems temporarily down. @patwie

**Comment by junsukchoe** [comment]
Oh, Thank you for the quick reply!
Then I'll be waiting. Thanks!

**Comment by PatWie** [comment]
The serve needs to reboot because of security updates (yet another CPU related security issue fix). I will restart the web server when at home today.

**Comment by PatWie** [comment]
The model zoo is online again.

**Comment by ppwwyyxx** [comment]
Thanks!!
