### ISSUE TITLE
How to calculate gradients of a list of y with respect to a single x?

### ISSUE THREAD

**Issue by T1anZhenYu** [tensorpack/tensorpack#1281]
tf.gradients([y1,y2,y3...],x) always return (dy1+dy2+dy3+...)/dx. I want to get [dy1/dx, dy2/dx, dy3/dx...]. So I am wondering whether Tensorpack has the feature to return the list of gradients rather the the sum of gradients?

Besides, I have tried using loop to calculate the gradients one by one and it's very slow.

Thanks a lot.

**Comment by ppwwyyxx** [comment]
This is a tensorflow question. See for example https://github.com/tensorflow/tensorflow/issues/675

**Comment by T1anZhenYu** [comment]
Thanks for answering. I am now aware of the difficutly of implementing this feature.
