### ISSUE TITLE
Max/MinSaver failed on Windows because of inconsistent path names

### ISSUE THREAD

**Issue by qq456cvb** [tensorpack/tensorpack#1294]
In my project, I first set the logger path by `logger.set_logger_dir('E:/train_log')` and set callbacks by `callbacks=[ModelSaver(), PeriodicTrigger(MaxSaver('acc'), every_k_epochs=1)]`.

In MinSaver's `_save` method, L141 `path = ckpt.model_checkpoint_path` gives me a path like `E:/train_log\\model-100` with **both slashes and backslashes**. However in L155, `files_to_copy` contains paths like `E:\\train_log\\model-100.data-00000-of-00001` with **only backslashes**. This would make the string replacement in L157 fail without any explicit error logs.

After setting the logger path with only backslashes, it works. Maybe it is better to warn the user about slashes?

**Comment by ppwwyyxx** [comment]
`E:/train_log` doesn't seem like a legal windows path to me. 

Perhaps this can be automatically fixed by standardizing the user input, e.g. adding a line `self.checkpoint_dir = os.path.abspath(self.checkpoint_dir)` in `__init__`.

**Comment by qq456cvb** [comment]
Thanks for your reply. I prefer to use paths with only slashes since it works on both Linux and Windows and paths like `E:/train_log` or `./train_log` are actually recognized in Windows Python. Before I solved this issue by removing slashes, it confuses me a little bit that why ModelSaver works but MinSaver fails. So maybe there should be some warnings or a standardization as you proposed.
