### ISSUE TITLE
How can I print the model configuration data, such as the type of optimizer being used? Similar to ScalarPrinter

### ISSUE THREAD

**Issue by ShaharGigi** [tensorpack/tensorpack#1295]

**Comment by ppwwyyxx** [comment]
You define the optimizer, so you can print it when you define it.

**Comment by ShaharGigi** [comment]
Thanks for the quick reply! I'd rather read it (and more configuration data) directly from the config or trainer objects. Is it possible?

**Comment by ppwwyyxx** [comment]
No. It does not provide such feature, and since it is the user who provides optimizer to trainer, such feature doesn't seem necessary.

**Comment by ShaharGigi** [comment]
Thank you for the clarification.
