### ISSUE TITLE
ImportError: No module named tensorpack.dataflow

### ISSUE THREAD

**Issue by maryam69898895** [tensorpack/tensorpack#1297]
Hello, I'm running  a train.py code for pose estimation. After to run it, I get this error:
/home/maryam/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "tf_pose/train.py", line 14, in <module>
    from pose_dataset import get_dataflow_batch, DataFlowToQueue, CocoPose
  File "/home/maryam/tf-pose-estimation-master/tf_pose/pose_dataset.py", line 24, in <module>
    from tensorpack.dataflow import MultiThreadMapData
ImportError: No module named tensorpack.dataflow

Can anyone help me?

**Comment by ppwwyyxx** [comment]
Please install tensorpack following the readme.

If that fails, please post following the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)
