### ISSUE TITLE
Can i use to .ckpt file?

### ISSUE THREAD

**Issue by cocopambag** [tensorpack/tensorpack#1299]
Hi, everyone. 

i use to Faster rcnn example. then, i want to use `backbone.weight`. 

i have a .ckpt files. but, example use ,npz files. 

so, I wonder if it's available.

thank you.

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model-to-a-session

**Comment by cocopambag** [comment]
Thank you! 
i have to use `SaverRestor` !
