### ISSUE TITLE
Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB with freed_by_count=0.

### ISSUE THREAD

**Issue by tyut11103** [tensorpack/tensorpack#1303]
When i train the faster-rcnn model shown in the example，I Get the output: "W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available." 
I trained the model in a distributed environment ,run two containers with overlay network in two services machines. Every service has a Tesla P4 GPU，I had set "tf_config.gpu_options.allow_growth = True", and the Memory-Usage goes  7419MiB /  7611MiB  .
Need I cut down the BatchSize ? And how?  Thx

**Comment by ppwwyyxx** [comment]
You don't have to do anything if it can train.

If you want to reduce memory usage, you can use smaller backbone, smaller `FRCNN.BATCH_PER_IM`, smaller image size, etc.
