### ISSUE TITLE
session_init ignored when passed to AutoResumeTrainConfig

### ISSUE THREAD

**Issue by shf3125** [tensorpack/tensorpack#1304]
There is a simple use case that causes resumed-training to fail, and seems to be a small incompatibility issue between `ModelSaver` and `AutoResumeTrainConfig`.
`ModelSaver` accepts a `checkpoint_dir` input, (and defaults this `checkpoint_dir` to the `logger.get_log_dir()`). 
`AutoResumeTrainConfig` accepts a `session_init` input, but then looks for the checkpoint file in the `logger.get_log_dir()`, overriding the `session_init` with `None` if this file is not found there.
This (often) results in failing the assertion of `found_sessinit == found_last_epoch`.

The way I see it, is that if a user decides to save checkpoints in some other non-default directory, and properly handles creating the restored `session_init`, then passing this into `AutoResumeTrainConfig` should work. 
If I'm not missing anything, then here's my fix:
In `AutoResumTrainConfig`'s \_\_init\_\_ method, under `if always_resume or 'session_init' not in kwargs:` one substitutes `sessinit = self._get_sessinit_resume()` with:
```
if 'session_init' in kwargs:  
    sessinit = kwargs['session_init']
else:
   sessinit = self._get_sessinit_resume()
 ```

Let me know if I'm missing something obvious or if there a less ugly fix...
Thanks!

**Comment by ppwwyyxx** [comment]
It is working as expected since it says that it will look for checkpoint in `logger.get_logger_dir`, and it says when `always_resume` is True, resume takes priority over provided arguments.

My suggestion is to not use `AutoResumeTrainConfig` if you need to manually provide a session_init. In that case why not just pass your `session_init` to `TrainConfig`?

**Comment by shf3125** [comment]
That may be the right thing to do. I just updated my TP version, and it
seems this is something that changed between versions, so my code still has
the AutoResumeTrainConfig usage.
I'll try your suggestion.
Thanks!

בתאריך יום ה׳, 22 באוג׳ 2019, 20:17, מאת Yuxin Wu ‏<notifications@github.com
