### ISSUE TITLE
How to get *.pb by *.meta and *.ckpt with tensorpack0.8.3

### ISSUE THREAD

**Issue by chenyanyin** [tensorpack/tensorpack#1310]
hello, i have a problem when I generate *.pb from *.meta and *.ckpt with FasterRCNN0.8.3. 
* *.ckpt convert *.pb by:
with tf.Session() as sess:    
&nbsp; &nbsp; saver.restore(sess, checkpoint_file)     
&nbsp; &nbsp; output_graph_def = graph_util.convert_variables_to_constants( sess=sess,input_graph_def=sess.graph_def, output_node_names=output_node_names.split(","))
&nbsp; &nbsp; with tf.gfile.GFile(pb_file, "wb") as f:   
&nbsp; &nbsp; &nbsp; &nbsp; f.write(output_graph_def.SerializeToString()) 
* and inference by *.pb
with tf.Graph().as_default():
&nbsp; &nbsp; output_graph_def = tf.GraphDef()
&nbsp; &nbsp; with open(pb_path, "rb") as f:
&nbsp; &nbsp; &nbsp; &nbsp; output_graph_def.ParseFromString(f.read())
&nbsp; &nbsp; &nbsp; &nbsp; tf.import_graph_def(output_graph_def, name="")
&nbsp; &nbsp; &nbsp; &nbsp; with tf.Session() as sess:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sess.run(tf.global_variables_initializer())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; input_image_tensor = sess.graph.get_tensor_by_name("image:0")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; output_tensor_boxes = sess.graph.get_tensor_by_name("tower-pred-0/output/boxes:0")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; boxes= sess.run(output_tensor_boxes, feed_dict={input_image_tensor: img})

an error occurred, there is no tensor 'image:0' in *.pb.
Because needs iteration, i can't  use FasterRCNN0.9.6, but i try it by same way with FasterRCNN0.9.6, that's right. I am very confused, and look forward to your reply.

**Comment by ppwwyyxx** [comment]
As said in the [documentation](https://tensorpack.readthedocs.io/tutorial/inference.html#step-1-build-the-model-graph), you should not attempt to use metagraph for inference. There is no guarantee on what names appear in the metagraph.

If you have to, you can inspect the pb file to see what tensors are inside. It could be something like `tower-pred-0/image`.

**Comment by chenyanyin** [comment]
> As said in the [documentation](https://tensorpack.readthedocs.io/tutorial/inference.html#step-1-build-the-model-graph), you should not attempt to use metagraph for inference. There is no guarantee on what names appear in the metagraph.
> 
> If you have to, you can inspect the pb file to see what tensors are inside. It could be something like `tower-pred-0/image`.

ok, i got it, thank you!
