### ISSUE TITLE
Limit GPU Memory During Inference

### ISSUE THREAD

**Issue by simongraham** [tensorpack/tensorpack#1313]
How can I limit the GPU memory during inference? Currently, I am using PredictConfig() , but am struggling to find a way to do this. Essentially, I need to make sure the GPU memory does not exceed 10GB 

Would appreciate any help :D

**Comment by ppwwyyxx** [comment]
You can use `session_creator=NewSessionCreator(config=...)` where config is a `tf.ConfigProto` that limits the gpu memory fraction.

**Comment by simongraham** [comment]
Thanks for the speedy reply!

In light of your response, I have modified the following code:

```
 gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.33)
        pred_config = PredictConfig(
            model        = model_constructor(),
            session_creator = NewSessionCreator(config=tf.ConfigProto(gpu_options=gpu_options)),
            session_init = get_model_loader(model_path),
            input_names  = self.eval_inf_input_tensor_names,
            output_names = self.eval_inf_output_tensor_names)
        predictor = OfflinePredictor(pred_config)
```

However, despite it running it doesn't seem to actually put a cap on the memory usage of the GPU.

**Comment by ppwwyyxx** [comment]
Did you or your code initialize the GPU before creating the predict config? Functions like `tf.test.is_gpu_available` or `get_num_gpu` may also initialize the GPU. TensorFlow cannot accept options after the GPU has been initialized. Maybe that's something to look at.

One rule of thumb is to make sure that
```
tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices:
```
is not printed before creating the predict config.

**Comment by simongraham** [comment]
Yes, you were completely right. Commenting out  `tf.test.is_gpu_available` meant that the above code worked. 

Thanks for this and thanks even more for TensorPack!
