### ISSUE TITLE
HED example does not work on CPU

### ISSUE THREAD

**Issue by entron** [tensorpack/tensorpack#1314]
When I tried to run the [HED example](https://github.com/tensorpack/tensorpack/tree/master/examples/HED) on a CPU only machine it gave the error "Default MaxPoolingOp only supports NHWC on device type CPU". The code works on GPU though. 

Also I used GPU to train a model and exported the trained model to the TF serving format. If I run tensorflow serving on a CPU machine I still have the same problem.

Is there a way to make the model running on CPU?

**Comment by ppwwyyxx** [comment]
To run on CPU, you need to implement the model in a way that supports CPU. i.e., use NHWC format, or use TensorFlow with MKL enabled.

**Comment by entron** [comment]
Thank you very much!
