### ISSUE TITLE
#1316 blocks using GCS path for ModelSaver

### ISSUE THREAD

**Issue by tamamachi** [tensorpack/tensorpack#1317]
#1316 adds `os.path.normpath` into ModelSaver's initializer.
After this change, when you specify GCS URI like `gs://BUCKET/PATH`, checkpoint_dir is transformed into invalid format like `gs:/BUCKET/PATH` ( `//` becomes `/`).

**Comment by ppwwyyxx** [comment]
#1316 is actually solving this issue. It does not normalize `gs://`.

**Comment by tamamachi** [comment]
Ah, you're right. I misunderstood the changes.
