### ISSUE TITLE
Return Multi-labeled scores instead of highest score as final_score in faster_rcnn

### ISSUE THREAD

**Issue by Jhyn-Pham** [tensorpack/tensorpack#1318]
Hi
I did have a glance at example/FasterRCNN/modeling/model_frcnn.py
I found that https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/modeling/model_frcnn.py#L178 
this function is responsible for returning final_labels, final_score, etc.. at https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/predict.py#L69
I see that it only return a label with highest score, but I want to see a full score with all clarified classes corresponding with each box, and I have no idea what to modify, so if someone could point where to start it would be nice.
Thank you.

**Comment by Jhyn-Pham** [comment]
Thanks for the reply, it does help me a lot, but I have bit confused about "filtered_ids" in examples/FasterRCNN/modeling/model_frcnn.py
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/modeling/model_frcnn.py#L196
It' said that it'll return the value with shape Fx2, So, what is the value of F , and what the value of 2 columns represent for ?

**Comment by ppwwyyxx** [comment]
If you understand the shape of "scores", then Tensorflow documentation can tell you the shape of "filtered_ids".
https://www.tensorflow.org/api_docs/python/tf/where
