### ISSUE TITLE
different results between eval and pb

### ISSUE THREAD

**Issue by lighter7** [tensorpack/tensorpack#1321]
I ran training and testing, and output the test results when training reached a certain number of times. At the same time, I saved the pb file from the same checkpoint. Corresponding to the same training model, the new results by loading the pb file is different from the test results of eval. I want to ask if anyone has encountered similar problems.

**Comment by ppwwyyxx** [comment]
There might be a bug in either a library or your code, but one cannot tell much with limited information you provide.
If you would like others to look into your issue, please provide enough information to let others reproduce your issue.

**Comment by lighter7** [comment]
Solved.
Unlike the official model, the preprocessing of image scaling are not packaged into the model in tensorpack. When using the Pb files, it is necessary to add preprocessing (resize the image) and post-processing (boxes in the results need to be resized according to the resize ratio of preprocessing).
