### ISSUE TITLE
Training on image of no object

### ISSUE THREAD

**Issue by chenxiaodanhit** [tensorpack/tensorpack#1324]
### 1. What you did: I trained maskrcnn structure on my own breast ultrasound images using the following command: 
'./train.py --config MODE_MASK=False MODE_FPN=True DATA.BASEDIR=/media/sdc/cxd/FasterRCNN/COCO_convert/anno BACKBONE.WEIGHTS=ImageNet-R50-AlignPadding.npz'
### 2. What you observed: It turns out that list indexes must be integers or slices,not str.
![image](https://user-images.githubusercontent.com/46680345/65105363-47753280-da07-11e9-9253-cf9757f8785e.png)
### 4. Your environment:

tensflow 1.9.0

tensorpack 0.9.8

GTX 1080

MemoryUsage 8G

**Comment by ppwwyyxx** [comment]
You can use `if-else` before calling `decode`. The error is from your code (`cocoeval.py`), and doesn't seem related to tensorpack.

**Comment by chenxiaodanhit** [comment]
Thank you very much!
