### ISSUE TITLE
'function' object has no attribute 'symbolic_function'

### ISSUE THREAD

**Issue by Vonisoa** [tensorpack/tensorpack#1325]
### 1. What you did:
I tried using `PReLU` and its attribute `symbolic_function` but when I run my code I got the following error:

### 2. What you observed:
I got the error saying that `'function' object has no attribute 'symbolic_function'`
>   File "DQN.py", line 88, in _get_DQN_prediction
>     with argscope(Conv3D, nl=PReLU.symbolic_function, use_bias=True):
> AttributeError: 'function' object has no attribute 'symbolic_function'

### 4. Your environment:

> sys.platform         win32
> Python               3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
> Tensorpack           v0.9.8-0-gb6318616
> Numpy                1.17.0
> TensorFlow           1.13.1/b'unknown'
> TF Compiler Version  MSVC 190024215
> TF CUDA support      False
> TF MKL support       False
> Free RAM             3.98/11.69 GB
> CPU Count            4
> cv2                  4.1.0
> msgpack              0.5.4
> python-prctl         False

**Comment by ppwwyyxx** [comment]
Could you use `lambda x: PReLU('prelu', x)` instead? It should work the same so I think it's not necessary to support a hidden API for something that can be done in a more straightforward way. Sorry if that breaks your code.
