### ISSUE TITLE
Disable printing graph / variables

### ISSUE THREAD

**Issue by simongraham** [tensorpack/tensorpack#1332]
Hi,  

Thanks for the amazing work!

Is there a way to disable printing the entire graph / variables when loading a model? Currently, I am using PredictConfig() during inference and because I am ensembling multiple models, this clogs up the terminal.

**Comment by ppwwyyxx** [comment]
```python
from tensorpack.models.registry import disable_layer_logging
disable_layer_logging()
```

this is not yet a public API. but it seems reasonable to make it one

**Comment by simongraham** [comment]
great, thanks for this!
