### ISSUE TITLE
Entering bounding boxes as pixel coordinates or relative coordinates

### ISSUE THREAD

**Issue by hasan-nn** [tensorpack/tensorpack#1334]
hello ,
i have a really simple question.
i have registered my own dataset successfully, however i wanted to know if i should enter the bounding box labels as pixel coordinates of the image or relative coordinates {divide x1,x2 by width divide y1,y2 by height } ?

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/35599506a7fc31a619d6f2be3844c2bd8dd9c1b1/examples/FasterRCNN/config.py#L97-L98

btw, for "pixel coordinates", they should be in the range [0, width] or [0, height]

**Comment by hasan-nn** [comment]
Thank you very much :)
