### ISSUE TITLE
Training stuck for faster rcnn on coco dataset for only person class. 

### ISSUE THREAD

**Issue by dvlshah** [tensorpack/tensorpack#1335]
I want to train faster rcnn on coco data using pretrained "COCO-MaskRCNN-R50FPN2x.npz" weights for person class only. 

I am facing issue of training getting stuck. Please see the image below.

![error_2](https://user-images.githubusercontent.com/16095226/66258280-0f207300-e7c1-11e9-82b8-1d0b4371a6ea.PNG)

![error_1](https://user-images.githubusercontent.com/16095226/66258286-15165400-e7c1-11e9-9f1a-845e304cb42b.PNG)

Also the GPU utilization is zero.

I have added the ignore_mismatch=True while reading the weights to ignore the loading last fc layer because the pretrained weights have 80 classes while I want to train only for 2.(BG,Person)

**Comment by ppwwyyxx** [comment]
Could you first try the command in the example and code without modifications, to rule out environment issues?
If it is not an environment issue, could you post following the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)
that you deleted?

More specifically:
* By "train person class only", what exactly did you do?
* By "stuck", what exactly did you observe: What are the logs, What is the last screen you saw, and how long have you waited for it.

**Comment by dvlshah** [comment]
I ran the code without my modifications. Its running fine. 

I want to train faster rcnn for only two classes ["BG","Person"] from coco dataset, so I did modifications in register coco for setting class names as the above instead of taking all 80 classes.

The other modification I did was while loading the Backbone.Weights, to avoid the last layer mismatch I added "ignore_mismatch =True" in the SmartInit call to avoid the consideration of last layer while loading pretrained weights

The second screenshot attached above shows the last screen I saw. Is there any other modification I need to do in order to meet above specifications.

**Comment by ppwwyyxx** [comment]
I cannot tell what modifications you did. It would be more useful if you could describe what you did following the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md). More specifically:

(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

To train on only one category you'll also need to skip objects of other categories in `coco.py` when loading the annotations.

**Comment by dvlshah** [comment]
Shifted the issue under the given template. Please check.
