### ISSUE TITLE
how to enter then List Of polygons for mask-rcnn Correctly?

### ISSUE THREAD

**Issue by hasan-nn** [tensorpack/tensorpack#1345]
### 1. What you did:
Hello , i am trying to register my data for Mask-rcnn .
Actually the problem is with the correct shape of entering the polygons.
According to this:

**segmentation: k lists of numpy arrays (one for each instance).
            Each list of numpy arrays corresponds to the mask for one instance.
            Each numpy array in the list is a polygon of shape Nx2,
            because one mask can be represented by N polygons.
            Each row in the Nx2 array is a (x, y) coordinate.**
I understood that for each image we have a list of numpy arrays, where each numpy array corresponds to an instance and is composed of (x,y) coordinates.

So i implemented this part of code in my DataSplit :

```
for i in range(len(cur_label['classes'])):
                    cur_xs=x_coo[i]
                    cur_ys=y_coo[i]
                    cur_bx=bbxx[i]
                    len1=len(cur_xs)
                    len2=len(cur_ys)
                    if(len1!=len2):
                        raise ValueError("polygon coordinates dont match")
                    polygon_now=[]
                    for j in range(len1):
                        xnow=float(cur_xs[j])
                        ynow=float(cur_ys[j])
                        polygon_now.append([xnow,ynow])
                    all_polygons.append(np.asarray(polygon_now).reshape(-1,2).astype('float32'))
                roidb["segmentation"]=all_polygons

```
where :+1: 
cur_xs[i], and cur_ys[i] hold the x and y coordinates of the instance polygon 
**all_polygons has the shape of 
list(numpyarray1([x1,y1],[x2,y2]....),numpyarray2([x1,y1],[x2,y2]....)....)**

**### 2. What you observed:
However i am getting this error with or without using .reshape(-1,2):**
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/NotSynced/tensorpack/tensorpack/dataflow/parallel_map.py", line 258, in run
    dp = self.map_func(dp)
  File "/content/gdrive/My Drive/CNRS/Colab/XviewMaskRCNN/mask-rcnn/data.py", line 136, in __call__
    polys = [tfms.apply_coords(p) for p in polys]
  File "/content/gdrive/My Drive/CNRS/Colab/XviewMaskRCNN/mask-rcnn/data.py", line 136, in <listcomp>
    polys = [tfms.apply_coords(p) for p in polys]
  File "/usr/local/NotSynced/tensorpack/tensorpack/dataflow/imgaug/transform.py", line 295, in <lambda>
    return lambda x: self._apply(x, name)
  File "/usr/local/NotSynced/tensorpack/tensorpack/dataflow/imgaug/transform.py", line 290, in _apply
    x = getattr(t, meth)(x)
  File "/usr/local/NotSynced/tensorpack/tensorpack/dataflow/imgaug/transform.py", line 128, in apply_coords
    coords[:, 0] = coords[:, 0] * (self.new_w * 1.0 / self.w)
IndexError: too many indices for array
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by ppwwyyxx** [comment]
> I understood that for each image we have a list of numpy arrays, where each numpy array corresponds to an instance and is composed of (x,y) coordinates.

This is not true. As the document says:

> segmentation: k lists of numpy arrays (one for each instance).
Each list of numpy arrays corresponds to the mask for one instance.
Each numpy array in the list is a polygon of shape Nx2,
because one mask can be represented by N polygons.

It's k lists of numpy arrays. Not a list of numpy arrays.
