### ISSUE TITLE
How to debug the memory consumption in MultiProcessMapData?

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1348]
Hi Yuxin, I'm using the FasterRCNN module in Tensorpack. I found using `MultiProcessMapData` leads to the gradually increase of CPU memory consumption. I set the `cfg.DATA.NUM_WORKERS=4` in `config.py`. And in early stage, the CPU memory usage is about `15Gb`, after tens of epochs of training, the CPU memory usage is increased to `30Gb` (in my pc, the maximum CPU memory is 32Gb). Then, the system becomes slow and the training speed is also slow. 

I'm porting the batched data flow in `https://github.com/armandmcqueen/tensorpack-mask-rcnn/blob/a98bb06401c5c76f98ad77349218fe3f0fe17076/MaskRCNN/data.py#L481`. 

Is it possible that there is some memory leaks in the `get_batch_train_dataflow`? If convenient, could you please give some advice on how to debug this kind of problems? Thanks.

**Comment by ppwwyyxx** [comment]
Run the dataflow alone first to see whether it has memory leak: https://tensorpack.readthedocs.io/tutorial/dataflow.html#run-the-dataflow.
Then, simplify the dataflow gradually.

You may want to try `set_start_method` (exists in our `FasterRCNN/train.py`), which should avoid an issue with forking that looks like memory leak.

**Comment by Remember2018** [comment]
@ppwwyyxx Hi Yuxin, thank you for your kind advice. 

In fact, I have commented the two lines as there is an error like this:

    Traceback (most recent call last):
      File "train.py", line 32, in <module>
         mp.set_start_method('spawn')
      File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
         raise RuntimeError('context has already been set')
     RuntimeError: context has already been set

**Comment by Remember2018** [comment]
@ppwwyyxx  I found add `force=True` will solve the above problem.

    mp.set_start_method('spawn', force=True)

**Comment by Remember2018** [comment]
But there is another problem:

    AttributeError: Can't pickle local object 'get_batch_train_dataflow.<locals>.preprocess'

**Comment by ppwwyyxx** [comment]
That's usually because some libraries you imported have mistakenly set start method at import time.
I know that old versions of tqdm do this, but maybe there are certain versions of other libraries making similar mistakes that I'm not aware of.

Setting `force=True` should be fine.

> 'get_batch_train_dataflow.<locals>.preprocess'

Our code no longer has this function because lambda is not supported by "spawn"

**Comment by Remember2018** [comment]
@ppwwyyxx Yuxin, thanks a lot for your kind reply!
