### ISSUE TITLE
tracing the GPU memory usage

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1351]
Hi Yuxin, I'm training the FCOS model using Tensorpack. The following is some logging infos.

![A439EE7A-2854-4033-A358-F922DD095B2E](https://user-images.githubusercontent.com/43327429/67291775-a2251100-f514-11e9-8290-875cec22c315.png)

It seems there are some bad GPU memory allocation somewhere. Is it possible to trace where the bad GPU allocation is? Or could we find the operations or tensors that leads to the bad memory allocation? Thanks.

**Comment by ppwwyyxx** [comment]
That's usually a safe message from tensorflow and no need to worry. I do not know how to trace it and it's a tensorflow message, so you can ask in tensorflow issues for help.

**Comment by Remember2018** [comment]
@ppwwyyxx Hi Yuxin, got it. Thanks a lot for your kindly comment!
