### ISSUE TITLE
How can we save model in the .h5 format using tensorpack - keras ? or can I save the model in .h5 format directly using tensorpack  ?

### ISSUE THREAD

**Issue by roshan-gopalakrishnan** [tensorpack/tensorpack#1354]
+ Note that you can implement a lot of features by extending Tensorpack
  (See http://tensorpack.readthedocs.io/tutorial/index.html#extend-tensorpack).
  It does not have to be added to Tensorpack unless you have a good reason.

+ "Could you implement a paper / other variants of a paper / additional features of a paper ?"
  -- The answer is: we have no plans to do so.
	We take feature requests on the library, but not on examples.
  We don't implement papers or variants/features of a paper for you,
  unless it can demonstrate some Tensorpack features not yet demonstrated in the existing examples.
  If you don't know how to do something yourself, you may ask a usage question.

**Comment by ppwwyyxx** [comment]
It's not supported
