### ISSUE TITLE
During training, how to feed the output of last iteration into the model at the next iteration?

### ISSUE THREAD

**Issue by JesseYang** [tensorpack/tensorpack#1358]
As in transformer-xl, when training, the network output of last sample will be fed into the network as memory for the next sample. Can tensorpack do this?

**Comment by ppwwyyxx** [comment]
The [PTB example](https://github.com/tensorpack/tensorpack/tree/master/examples/PennTreebank) does this by saving the states into an variable. A StagingArea (i.e. a queue on GPU) can also be used for this.

**Comment by JesseYang** [comment]
Thanks! I will try it.
