### ISSUE TITLE
Request help on how to use the StageingInput

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1361]
Hi Yuxin, I found you have provided the `StageingInput` interface in  https://github.com/tensorpack/tensorpack/blob/0641618d311bd358abef7e864afe1868d97c1f14/tensorpack/input_source/input_source.py#L538

Suppose the network has the folloing inputs:

        net_inputs = [tf.placeholder(tf.float32, [None, None, None, 3], name='images'),
                      tf.placeholder(tf.float32, [None, None, 4], name='gt_boxes'),
                      tf.placeholder(tf.int64, [None, None], name='gt_labels'),
                      tf.placeholder(tf.int32, [None, ], name='orig_gt_counts')]

        inputs_list = []
        for i in range(num_gpus):
            inputs_list.append(net_inputs)
        put_op_list = []
        get_op_list = []
        for i in range(num_gpus):
            with tf.device("/GPU:{}".format(i)):
                area = StagingArea(dtypes=[tf.float32, tf.float32, tf.int64, tf.int32],
                                   shapes=(tf.TensorShape([None, None, None, 3]),
                                           tf.TensorShape([None, None, 4]),
                                           tf.TensorShape([None, None]),
                                           tf.TensorShape([None, ])),
                                   capacity=1)
                put_op_list.append(area.put(inputs_list[i]))
                get_op_list.append(area.get())

then, how to integrate these inputs into the `StageingArea`? And when using the `MultiProcessMapData` in `Tensorpack`, how to bridge these two interfaces? The `MultiProcessMapData` dataflow needs to produce a list of batch data, right? I'm not sure. If convenient, could you please help provide an example on how to use this or give some advice? Thanks.

**Comment by ppwwyyxx** [comment]
I don't get what you're trying to do. Are you attempting to use `StagingArea` without tensorpack trainer? In that case it's not a tensorpack question.

The `MultiProcessMapData` dataflow produces anything that the `map_func` (which you provide to it) returns.

**Comment by Remember2018** [comment]
Hi Yuxin, thanks a lot for comments! Sorry for my misunderstanding. `Tensorpack` has automatically adopted the `StagingInput` in `FasterRCNN` with multi-gpu settings. I'll learn that.

Yes, I'm trying to use the `StagingArea` in an independent network. My understanding is that the data prefetching queue will directly cache the data in the GPU memory (i.e., `StagingArea`), but when I set the `capacity=1` or `capacity=64`, it seems no obvious increase in terms of GPU memory, and the GPU utilization sometimes are 60%, sometimes 99%.
