### ISSUE TITLE
How to use Lowres Pictures with Tensorpack?

### ISSUE THREAD

**Issue by Razor1O9** [tensorpack/tensorpack#1362]
Greetings,

I would like to ask how I have to change the parameters in the config to adopt for lower resolution pictures. I'm using the COCO-MaskRCNN-R50FPNx2 Model, I've changed the Output-Layer to only contain 2 Neurons ('_background_' and 'glasses'). 

I have a Dataset with 2000 images of a set of glasses, all images have 224x224 resolution. All images are labeled with a Mask and saved in valid COCO-Format.

The following parameters are set differently compared to the standard config.py :

#preprocessing
_C.PREPROC.TRAIN_SHORT_EDGE_SIZE = [224,224]
_C.PREPROC.TEST_SHORT_EDGE_SIZE = 224
_C,PREPROC.MAX_SIZE = 224

#anchors
-C.RPN.ANCHOR_STRIDE = 7
_C.RPN.ANCHOR_SIZES = (14,28,56,112,224)

Are my parameters set correctly or do I properly have to change additional parameters? 

Thanks in advance,
David

**Comment by ppwwyyxx** [comment]
In general we cannot help users find parameters for their models, so closing.

The anchor sizes do not look reasonable. I suggest you not changing them.
