### ISSUE TITLE
A question on RPN loss in FasterRCNN

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1363]
Hi Yuxin, in this line, 
https://github.com/tensorpack/tensorpack/blob/0641618d311bd358abef7e864afe1868d97c1f14/examples/FasterRCNN/modeling/model_rpn.py#L94
why did the `delta` set to `1.0/9`? Is there any reasons here?

And in this line, the `box_loss` in RPN is divided by the `cfg.RPN.BATCH_PER_IM`,
https://github.com/tensorpack/tensorpack/blob/0641618d311bd358abef7e864afe1868d97c1f14/examples/FasterRCNN/modeling/model_rpn.py#L98
but the `box_loss` is computed on the `positive` anchors, so is this reasonable? Why not divided by the `num_pos`? And the number of `positive` anchors will vary between images, right? 

I saw the original `FasterRCNN` code, they have a `bbox_inside_weights` and a `bbox_outside_weights` for the RPN loss computation, in `Tensorpack`, these are simplified. 

If convenient, could you please give some advice? Thanks.

**Comment by ppwwyyxx** [comment]
Both followed what Detectron did.

**Comment by Remember2018** [comment]
@ppwwyyxx Thank you Yuxin! But in the batch with size of 256, the foreground anchors seems much less than the number of background anchors.
