### ISSUE TITLE
Early stopping for training FasterRCNN

### ISSUE THREAD

**Issue by habib0098** [tensorpack/tensorpack#1365]
Hi and thanks for your excellent work!

I am training FasterRCNN on my own dataset. I was wondering which metric is monitored during the training/validation for saving the best model? Also how I can add early stopping based on the metric that is being monitored,

Thanks

**Comment by ppwwyyxx** [comment]
>  I was wondering which metric is monitored during the training/validation for saving the best model?

no metric is monitored to save the best model

By writing a callback, you can access history monitor data and stop training when you need to. See https://tensorpack.readthedocs.io/tutorial/extend/callback.html#what-you-can-do-in-the-callback
