### ISSUE TITLE
asking advice for faster dataflow pipeline

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#1369]
I would like to understand more about Tensorpack's dataflow.
To ease my question, let me assume a simple case with some made-up numbers.

Let's say my data flow looks like:
````
data = SomeData(...)
ds = MapData(data, fn_A)              # 10ms  per data
ds = MapData(data, fn_B)              # 100ms per data
ds = MapData(data, fn_C)              # 50ms  per data
df = BatchData(ds, 16)
````

Q1. If `fn_A`, `fn_B`, and `fn_C` functions takes 10ms, 100ms, and 50ms, respectively, for one data point, where should I put `Multi{Thread,Process}MapData`? Should I assign it for `fn_B`, the bottleneck? 
  
- I'm guessing here that I can have only one `Multi{Thread,Process}MapData`, is it right?
- If true and if I give enough parallelism to `fn_B`, then the data pipeline can't be faster than 50ms per data (next bottleneck `fn_C`)?
- Or, can I apply `Multi{Thread,Process}MapData` to all three functions?

Q2. Let's say I'm using the "ZMQ" thing with `num_proc=10`. Let's also say the class `SomeData` requires 2GB memory (e.g. self.dataset). Since ZMQ will have multiple clones of the entire class, it will require ~20GB, right?
- In contrast, `Multi{Thread,Process}MapData` with `num_proc=10` applies only a mapping function, so memory usage is still ~2GB?

Q3. If I'm using "ZMQ", should I put it before `BatchData` or after? Does it matter? 

Q4. In parallel examples, I didn't see any usage of 'Prefetch' functions (like `PrefetchData`, `MultiProcessPrefetchData`). What are these? In what cases are these useful?

Q5. What is the optimal way to design in general? (other than utilizing 'TestSpeed` benchmarks a lot)

**Comment by ppwwyyxx** [comment]
> I'm guessing here that I can have only one Multi{Thread,Process}MapData, is it right?

I have not verified that it works but I think you can have a `MultiProcessMapData(ds)` where `ds` comes from a `MultiThreadMapData`. This is not a common pattern though.

> If true and if I give enough parallelism to fn_B, then the data pipeline can't be faster than 50ms per data (next bottleneck fn_C)?

yes

> Or, can I apply Multi{Thread,Process}MapData to all three functions?

You can just apply it in the end and then it will parallelize all functions

>  Let's say I'm using the "ZMQ" thing with num_proc=10. Let's also say the class SomeData requires 2GB memory (e.g. self.dataset). Since ZMQ will have multiple clones of the entire class, it will require ~20GB, right?

Yes.

> In contrast, Multi{Thread,Process}MapData with num_proc=10 applies only a mapping function, so memory usage is still ~2GB?

Yes. For `MultiProcessMapData` you also need to make sure you don't make reference to data such as `self.dataset` in the mapping function.

> If I'm using "ZMQ", should I put it before BatchData or after? Does it matter?

It depends. You could try both.

> In parallel examples, I didn't see any usage of 'Prefetch' functions (like PrefetchData, MultiProcessPrefetchData). What are these? In what cases are these useful?

They are renamed to `MultiProcessRunner{ZMQ}`. https://tensorpack.readthedocs.io/tutorial/parallel-dataflow.html#run-multiple-identical-dataflows

**Comment by ywpkwon** [comment]
Let me ask a few follow-up questions:

Q1.
> You can just apply it in the end and then it will parallelize all functions

So, if I `ds = MapThreadData(data, 8, fn_C)`, then will `fn_A`, `fn_B` have benefits of parallelism? 

Q2.

In my case, to reduce the burden of map functions (`fn_A`, `fn_B`, `fn_C`, ...), I tried to prepare dataset as much as in `SomeData` class. 
- For example, all-image loading is impossible, but at least I can fully load all labels in advance, and do all GT class remapping in advance in `SomeData`. I did this to save label file loading IO on the fly, at least.
- `self.dataset` maybe look like `[{'img_path': ..., 'gt_classes': [0, 3, 1], 'gt_boxes': ..., 'some_meta': ..., ...}, ...]`
- This turns out, `SomeData` class requires quite a large memory with big data (than just having `gt_path`).

Question is:
- When I tried to use ZMQ, it seemed `SomeData` was too large to be cloned.
- I'm not sure how `MapThreadData` will be effective. (I will keep experimenting)
- Will it be better just having light Data Class (maybe only pointing file paths), and keeping IO functions or transforming functions in Map Functions even when those functions are common repetitive (like class number remapping)?

Sorry, since this must be not a specific question and example. I was wondering if I could get some general ideas.

**Comment by ppwwyyxx** [comment]
> So, if I ds = MapThreadData(data, 8, fn_C), then will fn_A, fn_B have benefits of parallelism?

No. You can let `f = fn_C(fn_B(fn_A()))` and parallelize `f`. 

> Will it be better just having light Data Class (maybe only pointing file paths), and keeping IO functions or transforming functions in Map Functions even when those functions are common repetitive (like class number remapping)?

To save memory this may make sense.

**Comment by ywpkwon** [comment]
Let me ask another question. This time I made a simple example.

```
class XData(RNGDataFlow):
    def __init__(self):
        super(XData, self).__init__()
        self.dataset = np.arange(5000)
        
    def __len__(self):
        return len(self.dataset)
    
    def __iter__(self):
        idxs = np.arange(len(self.dataset))
        self.rng.shuffle(idxs)
        for idx in idxs:
            yield self.dataset[idx]

xx = XData()
print(len(xx))     # 5000
```
This is a dummy class, and I added a map function.
```
import time
def map_for_train_fn(dp):
    sleep(1)
    return dp
yy1 = MapData(xx, map_for_train_fn)
yy2 = MultiThreadMapData(xx, 10, map_for_train_fn)
````
`TestDataSpeed(yy1).start()` gets 1 it/s
`TestDataSpeed(yy2).start()` gets 10 it/s
This works beautifully.

However, when I tested a different map function:
```
def map_for_train_fn(dp):
    t = np.random.randint(100, size=(230000, 2))
    a, b, c = np.unique(t, axis=0, return_counts=True, return_index=True)
    return dp
yy1 = MapData(xx, map_for_train_fn)
yy2 = MultiThreadMapData(xx, 10, map_for_train_fn)
```
Both `yy1` and `yy2` shows 6.02 it/s and 6.26 it/s. (No advantage by parallelism. The np.unique takes ~164 ms, so ~6 it/s makes sense when without parallelism.) How I can understand this?

**Comment by ppwwyyxx** [comment]
Because Python's threads are limited by GIL https://wiki.python.org/moin/GlobalInterpreterLock. That's why dataflow often uses processes.

**Comment by ywpkwon** [comment]
I see. After I skimmed what GIL is, what I am curious now is: In this example case, the `np.unique` input and output are defined ONLY IN a function (so when assuming a function runs in a thread, I feel like no python object is shared by different thread). Still, the GIL affects this case?

(Sorry, a detailed answer about GIL would be long, but can I have some brief idea?)

**Comment by ppwwyyxx** [comment]
GIL affects anything that is python code. So its effect depends on how much of `np.random.randint` and `np.unique` is implemented in python.
