### ISSUE TITLE
bug of subproc_call in tensorpack/utils/concurrency.py

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#1374]
when I use subproc_call  in python3 ( Python 3.5.2 , Ubuntu 16.04.3 LTS ) like:
`subproc_call('sleep 10', 3)`

while the cmd ends after 10s, not 3s as expected.

`[2019-12-19 19:26:50,805][WARNING][subproc_call]begin sleep~~~`
`[2019-12-19 19:27:00,812][WARNING][subproc_call]Command 'sleep 10' timeout!`

**Comment by ppwwyyxx** [comment]
This is a python bug that's fixed in later versions.
At least it works for me on Python 3.8.
