### ISSUE TITLE
[Placeholder]Detectron2 fbnet backbone 

### ISSUE THREAD

**Issue by no-1ne** [tensorpack/tensorpack#1375]
It was amazing to see detectron2, that's like the best of pytorch and tensorflow. Thank you for the great library. 

 according to @wat3rbro 
https://github.com/facebookresearch/detectron2/issues/12#issuecomment-565566046

https://github.com/facebookresearch/detectron2/issues/12#issuecomment-566822670 mobile friendly models are coming soon.  

Creating this issue as a placeholder to support fbnet backbone when even they are available. 

Once again thank you for the great library. 
Pardon if the category is wrong.

**Comment by ppwwyyxx** [comment]
Don't think this will happen. Closing.
