### ISSUE TITLE
Add supports for other optimizers like Nadam

### ISSUE THREAD

**Issue by crazydogen** [tensorpack/tensorpack#1376]
Hey,
I have written Nadam optimizer in  ModelDesc, but it seems that tensorpack don't support optimizer for `tf.keras.optimizer` yet.

`    "ModelDesc.optimizer() must return a tf.train.Optimizer! Got {} instead.".format(str(ret))
AssertionError: ModelDesc.optimizer() must return a tf.train.Optimizer! Got <tensorflow.python.keras.optimizer_v2.nadam.Nadam object at 0x2ad0c574b048> instead.
`
Could you add more supports for other optimizers (Not only `tf.train.Optimizer`)?

**Comment by ppwwyyxx** [comment]
I think you can already use `tf.contrib.opt.NadamOptimizer` because it is a subclass of `tf.train.Optimizer`.

We don't support keras optimizers.
