### ISSUE TITLE
How to provide 'gpu_options.allow_growth' when using PredictConfig?

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#1377]
`PredictConfig` seems to create a session for me (when a session is not given). Is it possible to give a config for the session like  `gpu_options.allow_growth=True`? 
If I want this, am I supposed to create a session and give it to the `PredictConfig`?

**Comment by ppwwyyxx** [comment]
It takes the option `session_creator`: https://tensorpack.readthedocs.io/modules/predict.html#tensorpack.predict.PredictConfig.

Some useful session_creators are in https://tensorpack.readthedocs.io/modules/tfutils.html#module-tensorpack.tfutils.sesscreate
