### ISSUE TITLE
Question about your resnet model for saliency map of cat.jpg

### ISSUE THREAD

**Issue by teeinn** [tensorpack/tensorpack#1378]
Hi, I've tried your code to make a saliency map for a cat.jpg.
I applied resnet_v1_50.ckpt to make sure this code is working. 
But the result seems weird. I've attached the pictures of result below. 
Please check and let me know what should I do to fix this. 
Thank you 

![abs-saliency](https://user-images.githubusercontent.com/45514456/71877952-cf757880-316d-11ea-9e7b-66287a09ebbc.jpg)
![blended](https://user-images.githubusercontent.com/45514456/71877953-cf757880-316d-11ea-8857-5beb658e69c0.jpg)
![neg](https://user-images.githubusercontent.com/45514456/71877954-cf757880-316d-11ea-97f3-5d93299b306e.jpg)
![pos](https://user-images.githubusercontent.com/45514456/71877956-d00e0f00-316d-11ea-801c-f88d9ac694af.jpg)

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
