### ISSUE TITLE
Why is l2_regularization using half of the decay value?

### ISSUE THREAD

**Issue by uulm-mschoen** [tensorpack/tensorpack#1381]
I have a question about the l2_regularization defined in line 29 of tensorpack/tensorpack/models/regularize.py.
Why do you apply the function on the half value of x? The comment '# oh these little dirty details' is funny but not informative.

**Comment by ppwwyyxx** [comment]
Because `tf.keras.regularizers.l2` and `tf.contrib.layers.l2_regularizer` are implemented differently. One is 2x larger than the other.
