### ISSUE TITLE
Error during training for custom dataset (images + mask PNG files)

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1382]
Hi,

I am trying ti train FasterRCNN using images + PNG masks.
To get polygons, I use openCV's findContours.
To get bounding boxes, I use top left + bottom - right of non-zero pixels of the mask.
I tested it to be working fine using the code in __main__ of my dataset (on the lines of balloon dataset).

But the training crashes even before starting with the following error. Nothing more is printed.

Can you please help?

Traceback (most recent call last):
  File "./train.py", line 76, in <module>
    train_dataflow = get_train_dataflow()
  File "/code/third-party/tensorpack/examples/FasterRCNN/data.py", line 343, in get_train_dataflow
    print_class_histogram(roidbs)
  File "/code/third-party/tensorpack/examples/FasterRCNN/data.py", line 49, in print_class_histogram
    gt_inds = np.where((entry["class"] > 0) & (entry["is_crowd"] == 0))[0]
ValueError: operands could not be broadcast together with shapes (3,) (4,)

**Comment by ppwwyyxx** [comment]
It says the two vector "class" and "is_crowd" in your dataset does not have the same length, which is illegal.

**Comment by vijaygill** [comment]
@ppwwyyxx You beat me to it! :) I was just about to post about my mistake!

I fixed it and yes indeed, it was just as you pointed out.

But thanks nevertheless for so prompt reply.

Keep up the good work!
