### ISSUE TITLE
How to use Tensorpack in Tensorflow 2.0

### ISSUE THREAD

**Issue by ming-nju** [tensorpack/tensorpack#1384]
+An error occurred while running the program 'DCGAN':
File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\models\batch_norm.py", line 9, in <module>
    from tensorflow.contrib.framework import add_model_variable
ModuleNotFoundError: No module named 'tensorflow.contrib'
How can i solve it?
Thank you very much!

**Comment by ppwwyyxx** [comment]
Please see README: https://github.com/tensorpack/tensorpack#install
