### ISSUE TITLE
How to run the codes in tensorpack ? AssertionError

### ISSUE THREAD

**Issue by ming-nju** [tensorpack/tensorpack#1385]
There is a error in DCGAN.py
File "E:/程序/tensorpack/examples/GAN/DCGAN.py", line 165, in <module>
 Argv: E:/程序/tensorpack/examples/GAN/DCGAN.py
    input=QueueInput(get_data()),
  File "E:/程序/tensorpack/examples/GAN/DCGAN.py", line 113, in get_data
    assert args.data
AssertionError
How to solve it?
Thank you

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/tree/master/examples/GAN says:
> Please see the docstring in each script for detailed usage and pretrained models. MultiGPU training is supported.
