### ISSUE TITLE
How to change graph when evaluating between epochs

### ISSUE THREAD

**Issue by andreanicastro** [tensorpack/tensorpack#1391]
I am trying to train a variational autoencoder with tensorpack and I am confused on how it should be done. 
After a training epoch I would like to run a InferenceRunner or a Callback with a different graph as there won't be an encoder any more. 

In the ideal case I would like to have two VAEs and use the latent code of one to be decoded by the other. 

At the current state, I only cause the callback to hang indefinitely. I think that is cause by the fact that I might be using a different graph from what I think.
Thanks for the help!

**Comment by ppwwyyxx** [comment]
`build_graph` is called with `self.training==False` during inference. You can use `if self.training` to build a different graph for inference.

**Comment by andreanicastro** [comment]
That was my understanding, actually. There must be a problem somewhere else. The fact that it hangs make me think of a race condition. Could it be the dataset? I will double check then

**Comment by devendraswamy** [comment]
How can i train the faster rcnn model with my own custom data , please help to fingout the solution.
