### ISSUE TITLE
TFF: Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by aynesss** [tensorpack/tensorpack#1395]
I use Tensorflow Federated TFF Version 0.11.0 When I execute this line 
`state, metrics = iterative_process.next(state, federated_train_data)
print('round 1, metrics={}'.format(metrics))`
IMAGE_SHAPE=(200,200,3) means NHWC
i find this error

`> InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU [[{{node StatefulPartitionedCall/StatefulPartitionedCall/sequential/max_pooling2d/MaxPool}}]] [[subcomputation/StatefulPartitionedCall_1/ReduceDataset]] [[subcomputation/StatefulPartitionedCall_1/ReduceDataset/_44]] (1) Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU [[{{node StatefulPartitionedCall/StatefulPartitionedCall/sequential/max_pooling2d/MaxPool}}]] [[subcomputation/StatefulPartitionedCall_1/ReduceDataset]] 0 successful operations. 0 derived errors ignored.`

**Comment by ppwwyyxx** [comment]
As the error says, TensorFlow's MaxPooling only supports NHWC option on CPU.
You need to use either GPU or NHWC.
