### ISSUE TITLE
How can i train the faster rcnn model with my own dataset ?

### ISSUE THREAD

**Issue by devendraswamy** [tensorpack/tensorpack#1396]
+ Note that you can implement a lot of features by extending Tensorpack
  (See http://tensorpack.readthedocs.io/tutorial/index.html#extend-tensorpack).
  It does not have to be added to Tensorpack unless you have a good reason.

+ "Could you implement a paper / other variants of a paper / additional features of a paper ?"
  -- The answer is: we have no plans to do so.
	We take feature requests on the library, but not on examples.
  We don't implement papers or variants/features of a paper for you,
  unless it can demonstrate some Tensorpack features not yet demonstrated in the existing examples.
  If you don't know how to do something yourself, you may ask a usage question.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN#other-datasets--implementation-details--speed

**Comment by devendraswamy** [comment]
Thank you so much for your reply , but that is trained on coco dataset only , could you tell where i need to give my custom dataset and where i need to change the code ??

kindly help me .

once again thank you!

**Comment by ppwwyyxx** [comment]
Please finish reading

![0210-22:27:07](https://user-images.githubusercontent.com/1381301/74215016-7dd07a00-4c54-11ea-8617-c19a9cac4ab8.png)

**Comment by devendraswamy** [comment]
Sure , Thank you !

**Comment by devendraswamy** [comment]
I have a doubt , I want to train the model for giving only bounding boxes on the image (without masking on the class ). Is it possible to train the model without masking and how ?

kindly help  me !

Thanking you !

**Comment by ppwwyyxx** [comment]
It is.
Set `MDOE_MASK=False`.
It's strongly recommended to read papers mentioned in the README to understand what some of the terminologies mean.

**Comment by devendraswamy** [comment]
Thank you so much for your response.

**Comment by devendraswamy** [comment]
one more help , i need your help for this. When i am kept the training of Pytorch faster rcnn model then my system was restarted.please help.

Thanking you in advance.

**Comment by ppwwyyxx** [comment]
The question is unrelated to this project

**Comment by devendraswamy** [comment]
Ok sir Thank you For the reply.
