### ISSUE TITLE
Why multiply 49 here?

### ISSUE THREAD

**Issue by iamhankai** [tensorpack/tensorpack#1397]
https://github.com/tensorpack/tensorpack/blob/b28cfa8a50b732651b3711d09afd0818083861b2/examples/DoReFa-Net/resnet-dorefa.py#L107

What will happen if without this line?

**Comment by ppwwyyxx** [comment]
Duplicate of https://github.com/tensorpack/tensorpack/issues/817#issuecomment-481762893

It will then not be able to produce correct output using the pre-trained model.
