### ISSUE TITLE
tutorial/efficient-dataflow MultiProcessMapDataZMQ example code error!

### ISSUE THREAD

**Issue by nyyznyyz1991** [tensorpack/tensorpack#1405]
When I run the following code:    
    ds = LMDBSerializer.load('./ILSVRC-train.lmdb', shuffle=False)
    ds = LocallyShuffleData(ds, 50000)

    def f(jpeg_str, label):
        return lots_of_augmentors.augment(cv2.imdecode(x, cv2.IMREAD_COLOR)), label
    ds = MultiProcessMapDataZMQ(ds, num_proc=25, map_func=f)
    ds = BatchData(ds, 256)

It got errors:
File "/home/AutoNet/tensorpack/dataflow/parallel_map.py", line 255, in run
    dp = self.map_func(dp)
TypeError: f() missing 1 required positional argument: 'label'

Tips:
I changed
MultiProcessMapDataZMQ(ds, num_proc=25, f)
to
MultiProcessMapDataZMQ(ds, num_proc=25, map_func=f)
because SyntaxError: positional argument follows keyword argument

**Comment by nyyznyyz1991** [comment]
The code for generating ILSVRC-train.lmdb is as follows:

import numpy as np
from tensorpack.dataflow import *
class BinaryILSVRC12(dataset.ILSVRC12Files):
    def __iter__(self):
        for fname, label in super(BinaryILSVRC12, self).__iter__():
            with open(fname, 'rb') as f:
                jpeg = f.read()
            jpeg = np.asarray(bytearray(jpeg), dtype='uint8')
            yield [jpeg, label]
ds0 = BinaryILSVRC12('/path/to/imagenet/', 'train', meta_dir="/path/to/imagenet/meta/") 
ds1 = MultiProcessRunnerZMQ(ds0, num_proc=1)
LMDBSerializer.save(ds1, './ILSVRC-train.lmdb')

**Comment by nyyznyyz1991** [comment]
@ppwwyyxx

**Comment by nyyznyyz1991** [comment]
It makes a difference after I revise the code :      
        ds = LMDBSerializer.load('./ILSVRC-train.lmdb', shuffle=False)
        ds = LocallyShuffleData(ds, 50000)
        augmentor = imgaug.AugmentorList(augmentors)
        def f(x):
            return augmentor.augment(cv2.imdecode(x[0], cv2.IMREAD_COLOR)), x[1]
        ds = MultiProcessMapDataZMQ(ds, num_proc=25, map_func=f)
        ds = BatchData(ds, batch_size, remainder=False, use_list=False)

**Comment by ppwwyyxx** [comment]
Seems like it's solved. Feel free to reopen if it's not the case.
You can learn about the issue in https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.MapData
