### ISSUE TITLE
[Error  ] convert detectron2 model (.pkl) to TFLite(.tflite) Unexpected value for attribute 'data_format'. Expected 'NHWC' Aborted

### ISSUE THREAD

**Issue by iamseyoun** [tensorpack/tensorpack#1407]
I want to convert detectron2 model (.pkl) to TFLite(.tflite)  for running to Android.
I follow following usage  ( /master/examples/FasterRCNN/convert_d2 )
finally I get out.pb  

**At last step, convert out.pb  to frozen_model.tflite
I encounter error: (Unexpected value for attribute 'data_format'. Expected 'NHWC' Aborted (core dumped))**

How solve this problem?

[Execution & Log]
================================================================
#### 2. Convert:

$ !python './drive/My Drive/coco/convert_d2.py' --d2-config 'detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' --d2-pkl './drive/My Drive/coco/model_final_f10217.pkl'  --output './drive/My Drive/coco/R50FPN-d2-converted.npz'
#### [output]
'MODE_MASK=True' 'MODE_FPN=True' 'FPN.CASCADE=False' 'BACKBONE.STRIDE_1X1=True' 'PREPROC.PIXEL_MEAN=[123.675,116.28,103.53]' 'PREPROC.PIXEL_STD=[1.0,1.0,1.0]' 

================================================================
#### 3. Use the above configs to verify the conversion is correct:
$!cd './drive/My Drive/coco/FasterRCNN' && python ./predict.py --evaluate ./out.json --load ../R50FPN-d2-converted.npz  --config DATA.BASEDIR=../../coco 'MODE_MASK=True' 'MODE_FPN=True' 'FPN.CASCADE=False' 'BACKBONE.STRIDE_1X1=True' 'PREPROC.PIXEL_MEAN=[123.675,116.28,103.53]' 'PREPROC.PIXEL_STD=[1.0,1.0,1.0]'

#### [output]
....
Loading and preparing results...
DONE (t=0.15s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=41.10s).
Accumulating evaluation results...
DONE (t=5.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.408
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.614
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.449
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.248
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.437
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.530
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.330
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.520
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.546
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.361
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.581
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.681
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=42.36s).
Accumulating evaluation results...
DONE (t=5.13s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.371
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.585
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.399
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.209
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.399
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.498
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.307
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.476
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.497
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.312
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.530
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.643

=============================================================
#### 4. Naively convert the model to a frozen pb file:
$ !cd './drive/My Drive/coco/FasterRCNN' && python ./predict.py --output-pb ./out.pb --load ../R50FPN-d2-converted.npz  --config DATA.BASEDIR=../../coco 'MODE_MASK=True' 'MODE_FPN=True' 'FPN.CASCADE=False' 'BACKBONE.STRIDE_1X1=True' 'PREPROC.PIXEL_MEAN=[123.675,116.28,103.53]' 'PREPROC.PIXEL_STD=[1.0,1.0,1.0]'

#### [output]
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/export.py:92: The name tf.saved_model.tag_constants.SERVING is deprecated. Please use tf.saved_model.SERVING instead.

[0311 04:49:16 @concurrency.py:266] WRN Command 'nvidia-smi -L' failed, return code=9
[0311 04:49:16 @concurrency.py:267] WRN NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
....

[0311 04:49:23 @collection.py:146] New collections created in tower : tf.GraphKeys.MODEL_VARIABLES of size 55
2020-03-11 04:49:23.467884: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-03-11 04:49:23.468298: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x26e2a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-11 04:49:23.468339: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[0311 04:49:23 @sessinit.py:223] Variables to restore from dict: conv0/W, conv0/bn/gamma, conv0/bn/beta, conv0/bn/mean/EMA, conv0/bn/variance/EMA, group0/block0/conv1/W, .....
group2/block0/convshortcut/bn/variance/EMA, group2/block1/conv1/W, group2/block1/conv1/bn/gamma, group2/block1/conv1/bn/beta, group2/block1/conv1/bn/mean/EMA, group2/block1/conv1/bn/variance/EMA, group2/block1/conv2/W, group2/block1/conv2/bn/gamma, group2/block1/conv2/bn/beta, group2/block1/conv2/bn/mean/EMA, group2/block1/conv2/bn/variance/EMA, group2/block1/conv3/W, group2/block1/conv3/bn/gamma, group2/block1/conv3/bn/beta, group2/block1/conv3/bn/mean/EMA, group2/block1/conv3/bn/variance/EMA, group2/block2/conv1/W, group2/block2/conv1/bn/gamma, group2/block2/conv1/bn/beta, group2/block2/conv1/bn/mean/EMA, group2/block2/conv1/bn/variance/EMA, group2/block2/conv2/W, group2/block2/conv2/bn/gamma, group2/block2/conv2/bn/beta, group2/block2/conv2/bn/mean/EMA, group2/block2/conv2/bn/variance/EMA, group2/block2/conv3/W, group2/block2/conv3/bn/gamma, group2/block2/conv3/bn/beta, group2/block2/conv3/bn/mean/EMA, group2/block2/conv3/bn/variance/EMA, group2/block3/conv1/W, group2/block3/conv1/bn/gamma, group2/block3/conv1/bn/beta, group2/block3/conv1/bn/mean/EMA, group2/block3/conv1/bn/variance/EMA, group2/block3/conv2/W, group2/block3/conv2/bn/gamma, group2/block3/conv2/bn/beta, group2/block3/conv2/bn/mean/EMA, group2/block3/conv2/bn/variance/EMA, group2/block3/conv3/W, group2/block3/conv3/bn/gamma, group2/block3/conv3/bn/beta, group2/block3/conv3/bn/mean/EMA, group2/block3/conv3/bn/variance/EMA, group2/block4/conv1/W, group2/block4/conv1/bn/gamma, group2/block4/conv1/bn/beta, group2/block4/conv1/bn/mean/EMA, group2/block4/conv1/bn/variance/EMA, group2/block4/conv2/W, group2/block4/conv2/bn/gamma, group2/block4/conv2/bn/beta, group2/block4/conv2/bn/mean/EMA, group2/block4/conv2/bn/variance/EMA, group2/block4/conv3/W, group2/block4/conv3/bn/gamma, group2/block4/conv3/bn/beta, group2/block4/conv3/bn/mean/EMA, group2/block4/conv3/bn/variance/EMA, group2/block5/conv1/W, group2/block5/conv1/bn/gamma, group2/block5/conv1/bn/beta, group2/block5/conv1/bn/mean/EMA, group2/block5/conv1/bn/variance/EMA, group2/block5/conv2/W, group2/block5/conv2/bn/gamma, group2/block5/conv2/bn/beta, group2/block5/conv2/bn/mean/EMA, group2/block5/conv2/bn/variance/EMA, group2/block5/conv3/W, group2/block5/conv3/bn/gamma, group2/block5/conv3/bn/beta, group2/block5/conv3/bn/mean/EMA, group2/block5/conv3/bn/variance/EMA, group3/block0/conv1/W, group3/block0/conv1/bn/gamma, group3/block0/conv1/bn/beta, group3/block0/conv1/bn/mean/EMA, group3/block0/conv1/bn/variance/EMA, group3/block0/conv2/W, group3/block0/conv2/bn/gamma, group3/block0/conv2/bn/beta, group3/block0/conv2/bn/mean/EMA, group3/block0/conv2/bn/variance/EMA, group3/block0/conv3/W, group3/block0/conv3/bn/gamma, group3/block0/conv3/bn/beta, group3/block0/conv3/bn/mean/EMA, group3/block0/conv3/bn/variance/EMA, group3/block0/convshortcut/W, group3/block0/convshortcut/bn/gamma, group3/block0/convshortcut/bn/beta, group3/block0/convshortcut/bn/mean/EMA, group3/block0/convshortcut/bn/variance/EMA, group3/block1/conv1/W, group3/block1/conv1/bn/gamma, group3/block1/conv1/bn/beta, group3/block1/conv1/bn/mean/EMA, group3/block1/conv1/bn/variance/EMA, group3/block1/conv2/W, group3/block1/conv2/bn/gamma, group3/block1/conv2/bn/beta, group3/block1/conv2/bn/mean/EMA, group3/block1/conv2/bn/variance/EMA, group3/block1/conv3/W, group3/block1/conv3/bn/gamma, group3/block1/conv3/bn/beta, group3/block1/conv3/bn/mean/EMA, group3/block1/conv3/bn/variance/EMA, group3/block2/conv1/W, group3/block2/conv1/bn/gamma, group3/block2/conv1/bn/beta, group3/block2/conv1/bn/mean/EMA, group3/block2/conv1/bn/variance/EMA, group3/block2/conv2/W, group3/block2/conv2/bn/gamma, group3/block2/conv2/bn/beta, group3/block2/conv2/bn/mean/EMA, group3/block2/conv2/bn/variance/EMA, group3/block2/conv3/W, group3/block2/conv3/bn/gamma, group3/block2/conv3/bn/beta, group3/block2/conv3/bn/mean/EMA, group3/block2/conv3/bn/variance/EMA, fpn/lateral_1x1_c2/W, fpn/lateral_1x1_c2/b, fpn/lateral_1x1_c3/W, fpn/lateral_1x1_c3/b, fpn/lateral_1x1_c4/W, fpn/lateral_1x1_c4/b, fpn/lateral_1x1_c5/W, fpn/lateral_1x1_c5/b, fpn/posthoc_3x3_p2/W, fpn/posthoc_3x3_p2/b, fpn/posthoc_3x3_p3/W, fpn/posthoc_3x3_p3/b, fpn/posthoc_3x3_p4/W, fpn/posthoc_3x3_p4/b, fpn/posthoc_3x3_p5/W, fpn/posthoc_3x3_p5/b, rpn/conv0/W, rpn/conv0/b, rpn/class/W, rpn/class/b, rpn/box/W, rpn/box/b, fastrcnn/fc6/W, fastrcnn/fc6/b, fastrcnn/fc7/W, fastrcnn/fc7/b, fastrcnn/outputs/class/W, fastrcnn/outputs/class/b, fastrcnn/outputs/box/W, fastrcnn/outputs/box/b, maskrcnn/fcn0/W, maskrcnn/fcn0/b, maskrcnn/fcn1/W, maskrcnn/fcn1/b, maskrcnn/fcn2/W, maskrcnn/fcn2/b, maskrcnn/fcn3/W, maskrcnn/fcn3/b, maskrcnn/deconv/W, maskrcnn/deconv/b, maskrcnn/conv/W, maskrcnn/conv/b
[0311 04:49:23 @sessinit.py:236] Restoring 307 variables from dict ...
[0311 04:49:26 @export.py:89] Output graph written to ./out.pb.

===============================================================
###  LAST STEP (pb --> tflite )  
import tensorflow as tf

graph_def_file = "./drive/My Drive/coco/FasterRCNN/out.pb"
input_arrays = ["image"]
output_arrays = ["output/masks"]
tflite_file = './drive/My Drive/coco/FasterRCNN/frozen_model.tflite'

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes={"image":[600,600,3]})
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
open(tflite_file, "wb").write(tflite_model)

#### [output]
ConverterError                            Traceback (most recent call last)
<ipython-input-15-c97c678c61a7> in <module>()
      8 converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes={"image":[600,600,3]})
      9 converter.optimizations = [tf.lite.Optimize.DEFAULT]
---> 10 tflite_model = converter.convert()
     11 open(tflite_file, "wb").write(tflite_model)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py in convert(self)
    981           input_tensors=self._input_tensors,
    982           output_tensors=self._output_tensors,
--> 983           **converter_kwargs)
    984     else:
    985       result = _toco_convert_graph_def(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    447       input_data.SerializeToString(),
    448       debug_info_str=debug_info_str,
--> 449       enable_mlir_converter=enable_mlir_converter)
    450   return data
    451 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198       stdout = _try_convert_to_unicode(stdout)
    199       stderr = _try_convert_to_unicode(stderr)
--> 200       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    201   finally:
    202     # Must manually cleanup files.

#### 2020-03-11 04:50:35.548528: F tensorflow/lite/toco/import_tensorflow.cc:2679] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Aborted (core dumped)

**Comment by ppwwyyxx** [comment]
tflite does not support arbitrary tensorflow model. How to convert a model to tflite is not a feature of tensorpack and therefore we do not provide support for it.

**Comment by Bhateja-Akash** [comment]
@ppwwyyxx Has this been solved? If not, What is the right procedure to export the model into TfLite format?

Will the way: (PyTorch -> Onnx -> TensorFlow -> TfLite) is a suitable for this conversion?
