### ISSUE TITLE
Example needed - log evaluated images in tensorboard for FasterRCNN training

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1408]
Hi,

I am looking for an example / any information on how to get some images of eval dataset to be shown in tensorboard with masks / bounding-boxes applied (like it shows in tensrflow's object detection API training).

I tried looking into callbacks. Looks like a combination of callbacks.Monitors.put_image might be helpful along with some code to run predictions. Also callbacks.PeriodicCallback might be needed to prevent this new callback to be called every epoch.

Thanks
Vijay

**Comment by ppwwyyxx** [comment]
You're right about the approach.
https://github.com/tensorpack/tensorpack/blob/07e464d81392c4e918e8c0f394793449866b0166/examples/GAN/CycleGAN.py#L184-L200
does something similar despite that you'll need some extra code to draw boxes

**Comment by vijaygill** [comment]
@ppwwyyxx Thanks for the quick reply (once again)!

I will try implementing something this weekend.

**Comment by vijaygill** [comment]
Hi

I did not get a chance to work on this idea since then. But today I wired up a crude callback The code is given below. It's called every 2 epochs (just for testing purposes using PeriodicCallback(ImageLogger(), every_k_epochs = 1).

I am getting different results from the checkpoint using checkpoint + OfflinePredictor and the predictor in the callback.

In the attached image, the left image is the one logged in tensorboard and the one on the right is the one predicted and rendered using prediction example.

Is there something I am missing / doing wrong here?

Note: the functions you see here being called but no code provided are the ones the predict example is using. Code has been copied or used by importing the required module.

Thanks.

PS: Sorry for the bad formatting of code. I could not get it right. It's just one class,

`
class ImageLogger(Callback):
    def _setup_graph(self):
        output_names=[
                'output/boxes',
                'output/scores',
                'output/labels',
                'output/masks',
                ]
        input_names=['image']
        self.pred = self.trainer.get_predictor(input_names, output_names)

    def _before_train(self):
        paths = glob.glob("/data2/*")
        self.image_infos = []
        for p in paths:
            img = cv2.imread(p, cv2.IMREAD_COLOR)
            if img is None:
                continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            logger.info("**** DEBUG: loaded test image : {0} with shape: {1}".format(p, img.shape))
            self.image_infos.append((p, img))
            if len(self.image_infos) > 20:
                break

    def _trigger(self):
        for img in self.image_infos:
            self._log_image(img)

    def _log_image(self, image_info):
        name, img = image_info
        img = img.copy()
        results = predict_image(img, self.pred)
        img = draw_final_outputs_blackwhite(img, results)
        h, w, c = img.shape
        scale = get_scale(w, h)
        img = imutils.resize(img, height = int( h / scale ), width = int( w / scale ) )
        self.trainer.monitors.put_image(name, img)
`


![Untitled](https://user-images.githubusercontent.com/8999486/80657275-18ce3880-8a7b-11ea-96e7-ce85397cfa98.png)
