### ISSUE TITLE
KeyError: 'roi_heads.res5.0.conv1.weight' when convert a detectron2 pkl file to npz

### ISSUE THREAD

**Issue by airqj** [tensorpack/tensorpack#1410]
### 1. What you did:
- I want to convert detectron2's rpn model to tensorpack,and i got a key error message: `KeyError: 'roi_heads.res5.0.conv1.weight'`. The configure file from [rpn_R_50_C4_1x](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/rpn_R_50_C4_1x.yaml),and pretrained file is [pretrainModel](https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/rpn_R_50_C4_1x/137258005/model_final_450694.pkl)

(1) **If you're using examples, what's the command you run:**
 - `python3 convert_d2/convert_d2.py --d2-config ~/SRC/detectron2/configs/COCO-Detection/rpn_R_50_C4_1x.yaml --d2-pkl model_final_450694.pkl  --output fastercnn.npz`

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, help us reproduce your issue:**

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:
(1) **Include the ENTIRE logs here:**
```
'MODE_MASK=False' 'MODE_FPN=False' 'BACKBONE.STRIDE_1X1=True' 'PREPROC.PIXEL_MEAN=[123.675,116.28,103.53]' 'PREPROC.PIXEL_STD=[1.0,1.0,1.0]' Traceback (most recent call last):
  File "convert_d2/convert_d2.py", line 141, in <module>
    tp_dict = convert_weights(d2_dict, cfg)
  File "convert_d2/convert_d2.py", line 63, in convert_weights
    f"group{grpid}/block{blkid}/conv1")
  File "convert_d2/convert_d2.py", line 39, in _convert_conv
    src_w = d.pop(src + ".weight").transpose(2, 3, 1, 0)
KeyError: 'roi_heads.res5.0.conv1.weight'

```

### 4. Your environment:
sys.platform          linux
Python                3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Tensorpack            v0.9.9-9-g6f0ba596-dirty
Numpy                 1.16.0
TensorFlow            1.14.0/v1.14.0-rc1-22-gaf24dc91b5
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.87.00
CUDA                  /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
NCCL
CUDA_VISIBLE_DEVICES  None
GPU 0                 GeForce RTX 2080 Ti
Free RAM              9.36/31.33 GB
CPU Count             16
cv2                   4.2.0
msgpack               1.0.0
python-prctl          False
sys.platform          linux
Python                3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Tensorpack            v0.9.9-9-g6f0ba596-dirty
Numpy                 1.16.0
TensorFlow            1.14.0/v1.14.0-rc1-22-gaf24dc91b5
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.87.00
CUDA                  /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
NCCL
CUDA_VISIBLE_DEVICES  None
GPU 0                 GeForce RTX 2080 Ti
Free RAM              9.36/31.33 GB
CPU Count             16
cv2                   4.2.0
msgpack               1.0.0
python-prctl          False

**Comment by ppwwyyxx** [comment]
As the README suggests: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2
, RPN is not a model that we supported.
