### ISSUE TITLE
Throughput monitor in distributed training using Horovod trainer

### ISSUE THREAD

**Issue by jiangzihanict** [tensorpack/tensorpack#1414]
Hi, @ppwwyyxx. I encountered a problem that I couldn't understand. 

I am training FasterRCNN provided in the example and using custom datasets. The training environment is two nodes with 16 GPUs (8 GPUs in each node).

I firstly train this model on one node (8GPUs), the throughput  is 40 images/s. However, when I train it on two nodes (16GPUs), the throughput is still 40 images/s. 

I monitor the GPU Utilization when training on two nodes. The GPU Utilization is the same for single-node and two-node training (Both 70-80%). It seems that the throughput should be doubled instead of staying 40 images/s.  

The only difference is the `it/s` shown  in the progress bar. The single node is `5it/s` and the two-node is `2.5it/s`. I think the reason for this is that the larger the number of GPUs, the larger the batch size. As  5\*8=2.5\*16=40, the throughput is always 40 images/s.

Another conflict is that if I use Hierarchical All-reduce, the GPU utilization will drop to 34%, but the throughput is still 40 image/s. As shown in the following figure, Whether the GPU utilization is 34% or 79%, there is the same throughput.
![WechatIMG1052](https://user-images.githubusercontent.com/22028950/77891784-145c0780-72a4-11ea-8998-132287f44d9c.jpeg)
<img width="541" alt="Screen Shot 2020-03-30 at 12 19 11 PM" src="https://user-images.githubusercontent.com/22028950/77891791-16be6180-72a4-11ea-83f7-bc8c8d655c2c.png">

I want to ask how is the throughput rate measured when there are multiple nodes?  Is it accurate in distributed training? The training uses NCCL for communication. The NCCL log shows that two communicators have been established (The following figure, one on rank0 and on one rank8). Is it possible the throughput monitor only shows the throughput in one communicator? 

<img width="569" alt="Screen Shot 2020-03-30 at 4 05 07 PM" src="https://user-images.githubusercontent.com/22028950/77889317-3c496c00-72a0-11ea-8f8b-be85c62a4894.png">

 The running command:
`/usr/local/mpi/bin/mpirun -np 16 --hostfile "src/hostfile" -bind-to none -map-by slot 
    -x NCCL_DEBUG=INFO \
    -x LD_LIBRARY_PATH \
    -x NCCL_SOCKET_IFNAME=eth0 \
    --allow-run-as-root \
    python src/train.py --logdir ${LOG_DIR} \
    --config MODE_MASK=False MODE_FPN=True \
    DATA.BASEDIR=${DATA_DIR} TRAINER=horovod`

Thanks!

**Comment by ppwwyyxx** [comment]
The throughput is accurate and uses all workers. Otherwise you wouldn't have measured a speedup in #1254

**Comment by jiangzihanict** [comment]
I have resized all the images to the same size and I also measured the flops per image. The results is 
the amount of calculation is very close. I doubt the measure of throughput since the GPU utilization of two-node training  is as the same as the single node.

**Comment by jiangzihanict** [comment]
I test the throughput on single node with 1, 4, and 8 GPUs respectively. The results are as follows. 
![Picture1](https://user-images.githubusercontent.com/22028950/77909387-d7057300-72bf-11ea-9ac2-29a9e6a85e3a.png)

**Comment by ppwwyyxx** [comment]
The results are contradicting your own findings in #1254. So I don't think I can give any help on that.

As always, an issue cannot be investigated unless instructions are provided to reproduce it. For this specific case it might be related to your environment so it might not be reproducible even with the instructions. But if you want to provide them, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
