### ISSUE TITLE
Simple question - is multi-GPU training as simple as adding another GPU?

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1418]
Hi,

Sorry for asking a simple question. Is having multi-GPU training as simple as adding another GPU card?

I added another GPU and I see GPU usage on both cards going to 93%+ (using nvidia-smi) but I did not notice the desired items/sec going up as  expected (from single GPU on same machine).

Thanks!

**Comment by ppwwyyxx** [comment]
FasterRCNN example will use all gpus it finds.

**Comment by vijaygill** [comment]
> FasterRCNN example will use all gpus it finds.

Thank you and closing the issue!

**Comment by vijaygill** [comment]
Just in case it helps anybody....
I was looking at items/sec in the progress bar during training when I thought the performance had not improved.

After a while when tensorboard was updated and looked at the throughput, I noticed significant difference from the single GPU training sessions I had before with same code and dataset.
