### ISSUE TITLE
Any plan to reproduce pointrend?

### ISSUE THREAD

**Issue by Yoopex** [tensorpack/tensorpack#1420]
Thank you for your greate job, I have reproduced pointrend with detectron2.
But it's not easy to deploy with detectron2.
So I desire reproducing pointrend on Tensopack.
Is there any plan to reproduce pointrend on Tensorpack?

Thanks.

**Comment by ppwwyyxx** [comment]
answered in https://github.com/tensorpack/tensorpack/issues/new?assignees=&labels=&template=feature-requests.md&title=
