### ISSUE TITLE
Training Mask RCNN on custom dataset with PNG mask annotations

### ISSUE THREAD

**Issue by anferico** [tensorpack/tensorpack#1427]
I have a dataset consisting of training images and mask annotations in the form of PNG images.

According to the [instructions](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md) for training Mask RCNN on my own custom dataset, I basically have to extend the `DatasetSplit` class and implement the required methods. In particular, when implementing the `training_roidbs` method, I have to stick to its interface, namely:
```
"""
Returns:
    roidbs (list[dict]):

Produce "roidbs" as a list of dict, each dict corresponds to one image with k>=0 instances.
and the following keys are expected for training:

file_name: str, full path to the image
boxes: numpy array of kx4 floats, each row is [x1, y1, x2, y2]
class: numpy array of k integers, in the range of [1, #categories], NOT [0, #categories)
is_crowd: k booleans. Use k False if you don't know what it means.
segmentation: k lists of numpy arrays.
    Each list of numpy arrays corresponds to the mask for one instance.
    Each numpy array in the list is a polygon of shape Nx2,
    because one mask can be represented by N polygons.
    Each row in the Nx2 array is a (x, y) coordinate.

    If your segmentation annotations are originally masks rather than polygons,
    either convert it, or the augmentation will need to be changed or skipped accordingly.

    Include this field only if training Mask R-CNN.
"""
```
Here are a couple questions:

1. What do x1, x2, x2, y2 refer to in `boxes`? I assume they are the top-left (x1, y1) and bottom-right (x2, y2) corners of the bounding box, though that's a little bit confusing since this is not how COCO stores bounding box annotations, which are in the format [x1, y1, width, height]

2. What is `is_crowd` used for? In COCO annotations, `iscrowd=1` means that the segmentation is in RLE (run length encoding) format, which is essentially the same thing as having a PNG mask instead of a polygon. So what would happen if I set `is_crowd=True` in the dictionary that this function returns? Would the other keys be interpreted differently? Would I have to set other keys in addition to those mentioned in the docstring?

**Comment by ppwwyyxx** [comment]
1. correct
2.
> iscrowd=1 means that the segmentation is in RLE (run length encoding) format

Actually this is not true. It means something else. You can find something in coco's docs or papers but just setting it to False as the doc suggests is fine.

However, the data parsing code in `data.py` does not currently handle RLE format. It assumes polygons.

No other keys are needed in addition to these.
