### ISSUE TITLE
ImageNet DataFlow iteration does not end

### ISSUE THREAD

**Issue by bhiziroglu** [tensorpack/tensorpack#1429]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

I am trying to create ImageNet dataflow as described here : https://tensorpack.readthedocs.io/tutorial/efficient-dataflow.html

- I created the 140GB ILSVRC-train.lmdb file following the tutorial.
- I added Augmentations & Parallelism.
- I use DataFlow alone without tensorpack, I call reset_state() first to initialize it, and then use the generator.
- The for loop does not finish and continue forever.

(1) **If you're using examples, what's the command you run:**

I am following the ImageNet tutorial : 
https://tensorpack.readthedocs.io/tutorial/efficient-dataflow.html

I use this snippet to create the lmdb file :
```
from tensorpack.dataflow import *
class BinaryILSVRC12(dataset.ILSVRC12Files):
    def __iter__(self):
        for fname, label in super(BinaryILSVRC12, self).__iter__():
            with open(fname, 'rb') as f:
                jpeg = f.read()
            jpeg = np.asarray(bytearray(jpeg), dtype='uint8')
            yield [jpeg, label]
ds0 = BinaryILSVRC12('/path/to/ILSVRC/', 'train')
ds1 = MultiProcessRunnerZMQ(ds0, num_proc=1)
LMDBSerializer.save(ds1, '/path/to/ILSVRC-train.lmdb')
```

Then I use my own augmentation flow to create the dataflow and iterate through it.
You can see the full code on question (3).

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

No, I did not make any changes.

(3) **If not using examples, help us reproduce your issue:**

Following code can reproduce this problem:

```
def mapf(dp):   
        fname, cls = dp.  
        im = cv2.imdecode(fname, cv2.IMREAD_COLOR)
        im = aug.augment(im)
        return im, cls

def getDataflow(batch_size=256):
    ds = LMDBSerializer.load('ILSVRC-train.lmdb', shuffle=False)
    ds = LocallyShuffleData(ds, 50000)
    augmentors = [
            imgaug.GoogleNetRandomCropAndResize()
    ]
    aug = imgaug.AugmentorList(augmentors)
    ds = MultiProcessMapDataZMQ(ds, num_proc=25, map_func=mapf)
    ds = BatchData(ds, batch_size, remainder=True)
    ds.reset_state()
    return ds

loader = getDataflow()

for data, label in loader:
    ...process data...

```
There are 1281167 images in ImageNet and with a batch size of 256, this for loop should iterate 5005 times. Each iteration should return data with 256 images except for the last iteration. However, this for loop goes on forever. I have also tried the for loop using enumeration :

```
for batch_id, (data, label) in enumerate(loader):
    ...process data...
```
This also goes on forever.

If I remove BatchData, everything works perfectly. Code:

```
def mapf(dp):   
        fname, cls = dp.  
        im = cv2.imdecode(fname, cv2.IMREAD_COLOR)
        im = aug.augment(im)
        return im, cls

def getDataflow(batch_size=256):
    ds = LMDBSerializer.load('ILSVRC-train.lmdb', shuffle=False)
    ds = LocallyShuffleData(ds, 50000)
    augmentors = [
            imgaug.GoogleNetRandomCropAndResize()
    ]
    aug = imgaug.AugmentorList(augmentors)
    ds = MultiProcessMapDataZMQ(ds, num_proc=25, map_func=mapf)
    ds.reset_state()
    return ds

loader = getDataflow()

for data, label in loader:
    ...process data...

```
What am I doing wrong? I also tried BatchData both with remainder=True and remainder=False and they both give the same result.

### 2. What you observed:

I observed that the for loop goes on forever and the problem only appears if BatchData is used.

### 3. What you expected, if not obvious.
I expected the for loop to iterate over the dataset and finish when there is no more data.

### 4. Your environment:
Python : 3.7.3
TF : Not installed
tensorpack: 0.10.1

**Comment by ppwwyyxx** [comment]
This is what the documentation says https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.LocallyShuffleData so it's working as expected.

**Comment by bhiziroglu** [comment]
Thanks for the answer. I removed LocallyShuffleData but the for loop still runs forever.
May I ask, why doesn't it make sense to stop the iteration once len(loader) is reached?

And also, why does the iteration stop when I don't include BatchData?

How can I simply create a for loop that will go over the dataset only one time to train the model for one epoch? And how would I restart the loader to start from the beginning for the next epoch?

**Comment by ppwwyyxx** [comment]
>  I removed LocallyShuffleData but the for loop still runs forever.

`MultiProcessMapDataZMQ(strict=False)` is also infinite by design.

> why doesn't it make sense to stop the iteration once len(loader) is reached?

explained in the docs and the above comment

> How can I simply create a for loop that will go over the dataset only one time to train the model for one epoch

Some of these dataflows do NOT give you exactly the same dataset as the docs explains. They also do not have the concept of "beginning" at all by definition of what they do. So don't use them if this is what you need. Most others dataflows including `MultiProcessMapDataZMQ(strict=True)` does terminate.
