### ISSUE TITLE
What GPUs do you use to train FasterRCNN？My GPUs are always out of memory.

### ISSUE THREAD

**Issue by cyfwry** [tensorpack/tensorpack#1430]
I try to train your FasterRCNN example in my GTX 1070ti which memory is 8G, but the training fail because it runs out of memory. What GPUs do you use to train FasterRCNN？
Is there any way to solve this problem?

**Comment by cyfwry** [comment]
Oh, by the way, I want to change the batchsize in the train to reduce the use of  memory, but I find that the batchsize is 1, is that correct?

**Comment by ppwwyyxx** [comment]
We use larger GPUs.
You can use smaller image resolution.

It's correct that batch size is 1
