### ISSUE TITLE
How to  speed up training in single GPU

### ISSUE THREAD

**Issue by ivald2016** [tensorpack/tensorpack#1439]
Hello, we are using Fasterrcnn example with COCO 2014 data and its augmentation.  Our lab has  only one RTX 2080, and training the whole model with totally 2800 epoch (180000*8 steps )takes  about 3 days.  That is so time-consuming and frustrating .  

I check that the default LR schedule is [0 0.01]  [1920 0.001]  [2560 0.0001]. I just wonder, if we halve the total iterations ,e.g.  1400 epoch, and shorten the  LR schedule in proportion to  [0 0.01] [960 0.001] [1280 0.0001], can we get the similar result with original setting? I think 0.05 mAP reduction is totally acceptable. 

Thanks a  lot!

**Comment by ppwwyyxx** [comment]
It's up to you how many iterations you want to train. We do not answer questions that are not specific to tensorpack.
