### ISSUE TITLE
GANTrainer, GANModelDesc issue

### ISSUE THREAD

**Issue by yzpick** [tensorpack/tensorpack#1442]
Hi, I am using the GANTrainer, but got this error:
AttributeError: 'Model' object has no attribute 'g_loss'

I basically just use Image2Image.py as a template and added my code into it, but somehow it does not work.

**Comment by ppwwyyxx** [comment]
The original `Image2Image.py` sets `g_loss` and will not have such error.
I'm not sure how I can help you since the issue is probably in your private code

**Comment by yzpick** [comment]
OK, got it. Thanks for confirming this, I will double check my own code then.
