### ISSUE TITLE
High value of false positives. How to reduce ?

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1446]
After evaluation, my model performs well, however, there is still high amount of false positives. 

Common approaches to decrease the value of false positives are:
- data augmentation
-  adding images without target class
- training from scratch
- Hard Example Mining

My questions are:

- does tensorpack support Hard Example Mining ?
- what are other techniques to achieve lower value of false positives ?

**Comment by ppwwyyxx** [comment]
> does tensorpack support Hard Example Mining ?

Tensorpack is a training interface and does not implement these training techniques. The detection example do not support hard example mining.

> what are other techniques to achieve lower value of false positives ?

We only discuss issues related to tensorpack at github issues.
