### ISSUE TITLE
Please read & provide the following information

### ISSUE THREAD

**Issue by mrgomdev** [tensorpack/tensorpack#1447]
### 1. What you did:

(1) **If you're using examples, what's the command you run:**
Using Anaconda3.7
scikit-learn > 0.20.3
tensorpack >= 0.9.8
```python
import numpy as np
from tensorpack.dataflow import RepeatedData, MapData, PrefetchData, DataFromList
from tensorpack.dataflow import TestDataSpeed
import sklearn
if __name__ == '__main__':
    source_rectified_df = RepeatedData(DataFromList([0.], shuffle=False), num=-1)
    def simulate_map_func(_) -> np.ndarray:
        r = np.random.normal(size=(100, 100))
        rr = r @ r
        return _
    simulated_df = MapData(source_rectified_df, func=simulate_map_func)
    simulated_df.reset_state()
    g = iter(simulated_df)
    b = next(g)
    TestDataSpeed(PrefetchData(simulated_df, num_prefetch=2, num_proc=2), size=10, warmup=1).start()
```

### 2. What you observed:

Test cannot completed. Nothing have proceed. No CPU Usage. No memory consumption.
However, with commented out 'import sklearn', everything goes fine.

### 4. Your environment:
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37_0
  - click=7.1.1=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - flask=1.1.1=py_1
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.3.3=py_0
  - glib=2.63.1=h5a9c865_0
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.27.2=py37hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=nompi_py37h513d04c_102
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.0=166
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm9=9.0.1=hc9558a2_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - nibabel=3.0.2=py_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.16.6=py37hbc911f0_0
  - numpy-base=1.16.6=py37hde5b4d6_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.3=py_0
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - piexif=1.1.3=py_2
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.11.4=py37he6710b0_0
  - pydicom=1.4.2=py_0
  - pydot=1.4.1=py37_0
  - pyopengl=3.1.1a1=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-lmdb=0.98=py37he6710b0_0
  - python_abi=3.7=1_cp37m
  - pyyaml=5.3.1=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - ruamel.yaml=0.16.6=py37h8f50634_1
  - ruamel.yaml.clib=0.2.0=py37h7b6447c_0
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.44.1=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - msgpack==1.0.0
    - msgpack-numpy==0.4.4.3
    - opencv-python==4.2.0.34
    - psutil==5.7.0
    - pydevd-pycharm==193.7288.30
    - pyqt5-stubs==5.14.1.1
    - python-prctl==1.7
    - pyzmq==19.0.0
    - tabulate==0.8.7
    - tensorpack==0.9.8

sys.platform          linux
Python                3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
Tensorpack            v0.9.8-0-gb6318616
Numpy                 1.16.6
TensorFlow            1.14.0/unknown
TF Compiler Version   5.4.0
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.440.64.00
CUDA                  /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
NCCL
CUDA_VISIBLE_DEVICES  0
GPU 0,1               GeForce RTX 2080 Ti
Free RAM              24.28/31.08 GB
CPU Count             12
cv2                   4.2.0
msgpack               1.0.0
python-prctl          True
--------------------  -------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
`reset_state` should be called [once and only once](https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.DataFlow.reset_state).
Because `TestDataSpeed` will call `reset_state` in order to use the dataflow, it is called twice, causing undefined behavior.

We'll update to provide better error messages.

**Comment by ppwwyyxx** [comment]
Root cause is https://github.com/numpy/numpy/issues/9248. Easy workaround is to use `spawn` or `forkserver`. In fact tensorpack already prints a warning that asks for this.

**Comment by ppwwyyxx** [comment]
Well it can be caused by either the `r = np.random.normal(size=(100, 100))` line due to locks held by numpy https://github.com/numpy/numpy/issues/9248 or `rr = r @ r` due to locks held by MKL. Solution is the same, though.

**Comment by mrgomdev** [comment]
I appreciate your reply. I can confirm that `multiprocessing.set_start_method('fork')` be the solution for this. (with slight changes of the code)
However, is there any reason related to sklearn , not to numpy?
I'm wandering why commenting out `import sklearn` makes all fine, even though multiprocessing.get_start_method() returns 'fork' in `tensorpack.utils.concurrency.py:start_proc_mask_signal()`. In my opinion, the problem would be from another point, not the combination of 'fork' and numpy.

**Comment by ppwwyyxx** [comment]
‘fork’ can cause potential problems when combined with anything that uses thread. `import sklearn` can affect the way numpy uses threads, depending on how sklearn/numpy are compiled.

**Comment by mrgomdev** [comment]
Understood. Compiled codes can affect other packages. Thank you for your maintenance activity. I can't move to tf.data in tf 2.1, having a lot of unnecessary details.
