### ISSUE TITLE
Faster RCNN   ValueError: Trying to load an array of shape (81,) into variable 'cascade_rcnn_stage1/outputs/class/b' whose shape is (3,).

### ISSUE THREAD

**Issue by fei161** [tensorpack/tensorpack#1450]
Faster RCNN 
ValueError: Trying to load an array of shape (81,) into variable 'cascade_rcnn_stage1/outputs/class/b' whose shape is (3,).

When I run my model, the program reports an error. May I ask where is the reason and if the application is done?

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by fei161** [comment]
@ppwwyyxx Thank you, I have found the answer in other issues. Set ignore_mismatch=True
