### ISSUE TITLE
I train my dataset,always raise "Some boxes have zero area"

### ISSUE THREAD

**Issue by zbsean** [tensorpack/tensorpack#1452]
CUDA_VISIBLE_DEVICES=0,1 python train.py \
      --config "DATA.VAL=('my_dataset_valid',)"  "DATA.TRAIN=('my_dataset_train',)" \
      TRAIN.BASE_LR=1e-3 \
      MODE_FPN=True \
      MODE_MASK=False \
      TRAIN.EVAL_PERIOD=0 \
      "TRAIN.LR_SCHEDULE=[1000]" \
      "PREPROC.TRAIN_SHORT_EDGE_SIZE=[800,1200]" \
      TRAIN.CHECKPOINT_PERIOD=1 \
      DATA.NUM_WORKERS=2 \
      TRAIN.NUM_GPUS=2 \
      FRCNN.BATCH_PER_IM=8 \
      --load ../pre_train/ImageNet-R101-AlignPadding.npz \
      --logdir ../train_log/

I train my dataset,always raise "Some boxes have zero area".
I check data.py and find TrainingDataPreprocessor ,it generate new boxes, boxes area always is  0.
How fix it ?

**Comment by ppwwyyxx** [comment]
`TrainingDataPreprocessor` takes boxes from your original dataset directly. So you'll want to check whether your dataset follows the format https://github.com/tensorpack/tensorpack/blob/b43488746b5b794d36a17f63e6da322f289366bf/examples/FasterRCNN/dataset/dataset.py#L15-L41 correctly.
Note that coordinates by default are not in [0, 1].

**Comment by zbsean** [comment]
I check source and find 
self.aug = imgaug.AugmentorList([
            CustomResize(cfg.PREPROC.TRAIN_SHORT_EDGE_SIZE, cfg.PREPROC.MAX_SIZE),
            imgaug.Flip(horiz=True)
        ])
intend Flip source image and boxes, but it generate mistake boxes , it's area is 0.

[ 8722.98    8601.601   9726.057  10810.9375 12193.718  10905.922
 12472.299  11821.677  11750.395  17476.857  15899.3955 14148.084
 12815.163  13658.579   6031.53    5327.6895  9240.584   8773.35
 10922.114  13621.998  12751.847  15228.601  20511.127  22191.15
 31911.002  39885.31   51963.99   25655.7    50242.996 ]
(781, 938, 3)
(774, 930, 3)
is 0
[ 4014.742  18734.04   20794.148  25247.223  29158.096  39422.543
 45802.188  54128.867  60609.125  64086.535  77004.4    81250.375
 83103.64   82948.17   34606.242  36877.883  32779.734  36463.668
 39309.723  37651.934  31318.992  34056.21   21260.861  10262.306
  3247.0842 16384.432  36883.004      0.     19903.838 ]

**Comment by ppwwyyxx** [comment]
Can you explain what is zero and why do you think they are zero? Showing code is preferred over words.

**Comment by zbsean** [comment]
this code is  reference sample source and change. 

def get_boxes(file_name):
    label_full_name=os.path.join("../train_data/labels_xml",file_name+".xml")
    tree = ET.parse(label_full_name)
    all_boxes1=[]
    all_boxes2=[]
    for obj in tree.findall("object"):
        bbox = obj.find("bndbox")
        xmin=float(bbox.find("xmin").text)
        ymin=float(bbox.find("ymin").text)
        xmax=float(bbox.find("xmax").text)
        ymax=float(bbox.find("ymax").text)

        xmin=xmin-1
        ymin=ymin-1

        o_width=abs(xmax-xmin)
        o_height=abs(ymax-ymin)

        all_boxes1.append([xmin,ymin,xmax,ymax])
        all_boxes2.append([xmin,ymin,o_width,o_height])
        

    boxes1=np.asarray(all_boxes1, dtype='float32')
    boxes2=np.asarray(all_boxes2, dtype='float32')
    return boxes1,boxes2

 aug = imgaug.AugmentorList([
            CustomResize([600,1200], 1333),
            imgaug.Flip(horiz=True,vert=False)
        ])
    file_name="2c543fde74e811ea834cf834418b57e9"
    boxes1,boxes2=get_boxes(file_name)
    boxes1_area=area(boxes1) 
    print(boxes1_area)
    image_full_name=os.path.join("../train_data/images",file_name+".jpg")
    im = cv2.imread(image_full_name, cv2.IMREAD_COLOR)
    cv2.imwrite("../test_data/2_1.jpg",im)
    print(np.shape(im))
    tfms = aug.get_transform(im)
    im = tfms.apply_image(im)
    cv2.imwrite("../test_data/2_2.jpg",im)
    print(np.shape(im))
    points = box_to_point4(boxes2)
    points = tfms.apply_coords(points)
    boxes = point4_to_box(points)
    if len(boxes):
        boxes_area=area(boxes) 
        np_1=np.min(boxes_area)
        if np_1<=0:
            print("is 0")
            print(boxes_area)

**Comment by ppwwyyxx** [comment]
Since these are your modified version of code and I don't know how they are being used I can't comment much on whether they are correct or not.

Though at least I can see it seems your "boxes2" is not in the correct format described above.

**Comment by zbsean** [comment]
Ok, I understand, train label is not coco format, its x1,y1,x2,y2 format. 
I change , it work, thank you

**Comment by zbsean** [comment]
btw , How set Epoch number? I check config.py and don't found。

**Comment by ppwwyyxx** [comment]
There is STEPS_PER_EPOCH and the steps number is controlled by LR_SCHEDULE (https://github.com/tensorpack/tensorpack/commit/9c1b1b7b200a66fe93afd00a47f3f198bb4e1393)
