### ISSUE TITLE
train raise  WRN The following variables are in the dict, but not found in the graph

### ISSUE THREAD

**Issue by zbsean** [tensorpack/tensorpack#1453]
I train my dataset and model FasterRCNN , raise WRN。
WRN The following variables are in the graph, but not found in the dict: fastrcnn/box/W
WRN The following variables are in the dict, but not found in the graph: group2/block10/conv1/W,
how fix it.

CUDA_VISIBLE_DEVICES=0,1 python train.py \
      --config "DATA.VAL=('my_dataset_valid',)"  "DATA.TRAIN=('my_dataset_train',)" \
      TRAIN.BASE_LR=1e-3 \
      MODE_FPN=False \
      MODE_MASK=False \
      TRAIN.EVAL_PERIOD=0 \
      "TRAIN.LR_SCHEDULE=[1000]" \
      "PREPROC.TRAIN_SHORT_EDGE_SIZE=[800,1200]" \
      TRAIN.CHECKPOINT_PERIOD=1 \
      DATA.NUM_WORKERS=2 \
      TRAIN.NUM_GPUS=2 \
      FRCNN.BATCH_PER_IM=8 \
      TRAIN.STEPS_PER_EPOCH=500 \
      --load ../pre_train/ImageNet-R101-AlignPadding.npz \
      --logdir ../train_log/

**Comment by ppwwyyxx** [comment]
The command tried to load a ResNet101 dict to a ResNet 50 model, so some variables in the dict are not in the graph.
The command tried to load a imagenet-pretrained backbone model to a detection model, so some variables detection-specific variables are not in the dict.
