### ISSUE TITLE
frcnn prediction all results are BG

### ISSUE THREAD

**Issue by fei161** [tensorpack/tensorpack#1456]
There are two types of my own sample set. The prediction result of the training model can accurately mark the position of the box, but it cannot predict the category result, because the prediction category of all boxes is BG.
I checked the eval results, it seems that the accuracy of the class indicator is quite high, but the fact is that the prediction results are completely wrong.
I have 1726 sample frames. There is basically only one sample frame per image. The ratio of the two categories is about 5:1. STEPS_PER_EPOCH=400, max_epoch is about 1600, the reference training model is the result when training to about 200 epochs.
--------------------  ------------

model parameters

{'BACKBONE': {'FREEZE_AFFINE': False,
              'FREEZE_AT': 0,
              'NORM': 'FreezeBN',
              'RESNET_NUM_BLOCKS': [3, 4, 23, 3],
              'STRIDE_1X1': False,
              'TF_PAD_MODE': False,
              'WEIGHTS': '/ceph/sofiezhou/drainage_detector_fasterrcnn/model/COCO-MaskRCNN-R101FPN9xGNCasAugScratch.npz'},
 'CASCADE': {'BBOX_REG_WEIGHTS': [[10.0, 10.0, 5.0, 5.0], [20.0, 20.0, 10.0, 10.0],
                                  [30.0, 30.0, 15.0, 15.0]],
             'IOUS': [0.5, 0.6, 0.7]},
 'DATA': {'ABSOLUTE_COORD': True,
          'BASEDIR': '/ceph/sofiezhou/drainage_detector_fasterrcnn/data',
          'CLASS_NAMES': ['BG', 'drainage', 'qrcode'],
          'FILTER_EMPTY_ANNOTATIONS': True,
          'LOGER': '/ceph/sofiezhou/drainage_detector_fasterrcnn/model/fasterrcnn_worker20_gpu2_0605',
          'NUM_CATEGORY': 2,
          'NUM_WORKERS': 20,
          'TRAIN': ('coco_train2014',),
          'VAL': ('coco_val2014',)},
 'FPN': {'ANCHOR_STRIDES': (4, 8, 16, 32, 64),
         'CASCADE': True,
         'FRCNN_CONV_HEAD_DIM': 256,
         'FRCNN_FC_HEAD_DIM': 1024,
         'FRCNN_HEAD_FUNC': 'fastrcnn_2fc_head',
         'MRCNN_HEAD_FUNC': 'maskrcnn_up4conv_head',
         'NORM': 'None',
         'NUM_CHANNEL': 256,
         'PROPOSAL_MODE': 'Level',
         'RESOLUTION_REQUIREMENT': 32},
 'FRCNN': {'BATCH_PER_IM': 512,
           'BBOX_REG_WEIGHTS': [10.0, 10.0, 5.0, 5.0],
           'FG_RATIO': 0.25,
           'FG_THRESH': 0.5},
 'MODE_FPN': True,
 'MODE_MASK': False,
 'MRCNN': {'ACCURATE_PASTE': True, 'HEAD_DIM': 256},
 'PREPROC': {'MAX_SIZE': 1344.0,
             'PIXEL_MEAN': [123.675, 116.28, 103.53],
             'PIXEL_STD': [58.395, 57.12, 57.375],
             'TEST_SHORT_EDGE_SIZE': 800,
             'TRAIN_SHORT_EDGE_SIZE': [800, 800]},
 'RPN': {'ANCHOR_RATIOS': (0.5, 1.0, 2.0),
         'ANCHOR_SIZES': (32, 64, 128, 256, 512),
         'ANCHOR_STRIDE': 16,
         'BATCH_PER_IM': 256,
         'CROWD_OVERLAP_THRESH': 9.99,
         'FG_RATIO': 0.5,
         'HEAD_DIM': 1024,
         'MIN_SIZE': 0,
         'NEGATIVE_ANCHOR_THRESH': 0.3,
         'NUM_ANCHOR': 15,
         'POSITIVE_ANCHOR_THRESH': 0.7,
         'PROPOSAL_NMS_THRESH': 0.7,
         'TEST_PER_LEVEL_NMS_TOPK': 1000,
         'TEST_POST_NMS_TOPK': 1000,
         'TEST_PRE_NMS_TOPK': 6000,
         'TRAIN_PER_LEVEL_NMS_TOPK': 2000,
         'TRAIN_POST_NMS_TOPK': 2000,
         'TRAIN_PRE_NMS_TOPK': 12000},
 'TEST': {'FRCNN_NMS_THRESH': 0.5,
          'RESULTS_PER_IM': 100,
          'RESULT_SCORE_THRESH': 0.05,
          'RESULT_SCORE_THRESH_VIS': 0.5},
 'TRAIN': {'BASE_LR': 0.01,
           'CHECKPOINT_PERIOD': 10,
           'EVAL_PERIOD': 10,
           'LR_SCHEDULE': [120000, 160000, 180000],
           'NUM_GPUS': 2,
           'STARTING_EPOCH': 1,
           'STEPS_PER_EPOCH': 400,
           'WARMUP': 1000,
           'WARMUP_INIT_LR': 1e-05,
           'WEIGHT_DECAY': 0.0001},
 'TRAINER': 'replicated'}
--------------------  ------------

train logs in 231 epoch

[32m[0610 10:20:19 @base.py:273][0m Start Epoch 231 ...
[32m[0610 10:23:41 @base.py:283][0m Epoch 231 (global_step 92400) finished, time:3 minutes 21 seconds.
[32m[0610 10:23:41 @graph.py:72][0m Running Op sync_variables/sync_variables_from_main_tower ...
[32m[0610 10:23:41 @misc.py:109][0m Estimated Time Left: 3 days 17 hours 12 minutes 39 seconds
[32m[0610 10:23:42 @monitor.py:476][0m GPUUtil/0: 94.244
[32m[0610 10:23:42 @monitor.py:476][0m GPUUtil/1: 93.328
[32m[0610 10:23:42 @monitor.py:476][0m HostFreeMemory (GB): 206.08
[32m[0610 10:23:42 @monitor.py:476][0m PeakMemory(MB)/gpu:0: 9394.3
[32m[0610 10:23:42 @monitor.py:476][0m QueueInput/queue_size: 49.704
[32m[0610 10:23:42 @monitor.py:476][0m Throughput (samples/sec): 3.9656
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/box_loss: 0.034824
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_loss: 0.051191
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/accuracy: 0.98964
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/false_negative: 0.99236
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/fg_accuracy: 0.0076423
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/num_fg_label: 5.3311
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/box_loss: 0.020411
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_loss: 0.030617
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/accuracy: 0.99443
[32m[0610 10:23:42 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/false_negative: 0.99977
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/fg_accuracy: 0.00022986
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/num_fg_label: 2.8028
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/box_loss: 0.0094847
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_loss: 0.020041
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/accuracy: 0.99653
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/false_negative: 1
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/fg_accuracy: 2.2737e-37
[32m[0610 10:23:43 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/num_fg_label: 1.7309
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 278.37
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 125.63
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 96.564
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 11.44
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 264.68
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 126.59
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 97.139
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 10.978
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 264.84
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 126.67
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 96.904
[32m[0610 10:23:43 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 10.983
[32m[0610 10:23:43 @monitor.py:476][0m learning_rate: 0.01
[32m[0610 10:23:43 @monitor.py:476][0m mean_gt_box_area: 75483
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/box_loss: 0.011649
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/label_loss: 0.0416
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/box_loss: 8.4818e-08
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_loss: 4.6891e-05
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.1: 0.5
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.2: 0.5
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.5: 0.5
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.1: 0.49999
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.2: 0.49999
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.5: 0.49999
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/num_pos_anchor: 4.7989e-05
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level2/num_valid_anchor: 194.99
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/box_loss: 0.0020026
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_loss: 0.016261
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.1: 0.046412
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.2: 0.5
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.5: 0.5
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.1: 0.54088
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.2: 0.45282
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.5: 0.45282
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/num_pos_anchor: 1.0344
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level3/num_valid_anchor: 45.559
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/box_loss: 0.0049735
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_loss: 0.015478
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.1: 0.17188
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.2: 0.17188
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.5: 0.2927
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.1: 0.59453
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.2: 0.59453
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.5: 0.56315
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/num_pos_anchor: 2.1426
[32m[0610 10:23:43 @monitor.py:476][0m rpn_losses/level4/num_valid_anchor: 11.255
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/box_loss: 0.0033475
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_loss: 0.0073649
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.1: 0.32145
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.2: 0.4065
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.5: 0.4065
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.1: 0.62997
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.2: 0.6153
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.5: 0.6153
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/num_pos_anchor: 1.9531
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level5/num_valid_anchor: 3.2716
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/box_loss: 0.0013252
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_loss: 0.0024493
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.1: 0.52652
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.2: 0.51165
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.5: 0.51165
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.1: 0.57968
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.2: 0.54211
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.5: 0.54211
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/num_pos_anchor: 0.76752
[32m[0610 10:23:44 @monitor.py:476][0m rpn_losses/level6/num_valid_anchor: 0.92031
[32m[0610 10:23:44 @monitor.py:476][0m sample_fast_rcnn_targets/num_bg: 506.67
[32m[0610 10:23:44 @monitor.py:476][0m sample_fast_rcnn_targets/num_fg: 5.3311
[32m[0610 10:23:44 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/best_iou_per_gt: 0.63434
[32m[0610 10:23:44 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.3: 0.99997
[32m[0610 10:23:44 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.5: 0.92935
[32m[0610 10:23:44 @monitor.py:476][0m total_cost: 0.51379
[32m[0610 10:23:44 @monitor.py:476][0m wd_cost: 0.29397
--------------------  ------------

eval logs in 230 epoch

[32m[0610 10:19:50 @eval.py:291][0m Running evaluation ...
[32m[0610 10:20:16 @coco.py:62][0m Instances loaded from instances_val2014.json.
[32m[0610 10:20:17 @monitor.py:476][0m GPUUtil/0: 94.652
[32m[0610 10:20:17 @monitor.py:476][0m GPUUtil/1: 93.672
[32m[0610 10:20:17 @monitor.py:476][0m HostFreeMemory (GB): 206.84
[32m[0610 10:20:17 @monitor.py:476][0m PeakMemory(MB)/gpu:0: 9394.3
[32m[0610 10:20:17 @monitor.py:476][0m QueueInput/queue_size: 49.775
[32m[0610 10:20:17 @monitor.py:476][0m Throughput (samples/sec): 3.9737
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/box_loss: 0.036574
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_loss: 0.049908
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/accuracy: 0.98957
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/false_negative: 0.99759
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/label_metrics/fg_accuracy: 0.0024137
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage1/fastrcnn_losses/num_fg_label: 5.3506
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/box_loss: 0.018166
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_loss: 0.028055
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/accuracy: 0.99498
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/false_negative: 1
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/label_metrics/fg_accuracy: 2.2334e-10
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage2/fastrcnn_losses/num_fg_label: 2.5224
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/box_loss: 0.004221
[32m[0610 10:20:17 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_loss: 0.017208
[32m[0610 10:20:18 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/accuracy: 0.99731
[32m[0610 10:20:18 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/false_negative: 1
[32m[0610 10:20:18 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/label_metrics/fg_accuracy: 2.2737e-37
[32m[0610 10:20:18 @monitor.py:476][0m cascade_loss_stage3/fastrcnn_losses/num_fg_label: 1.3531
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 271.77
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 130.38
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 97.938
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage1/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 11.904
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 261.84
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 131.46
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 97.717
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage2/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 11.525
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 261.89
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 132.14
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 96.988
[32m[0610 10:20:18 @monitor.py:476][0m cascade_rcnn_stage3/multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 11.525
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/IoU=0.5: 0
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/IoU=0.5:0.95: 0
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/IoU=0.75: 0
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/large: 0
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/medium: 0
[32m[0610 10:20:18 @monitor.py:476][0m coco_val2014-mAP(bbox)/small: -1
[32m[0610 10:20:18 @monitor.py:476][0m learning_rate: 0.01
[32m[0610 10:20:18 @monitor.py:476][0m mean_gt_box_area: 92729
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/box_loss: 0.015001
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/label_loss: 0.042338
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/box_loss: 1.4982e-21
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_loss: 2.4674e-05
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.1: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.2: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/precision_th0.5: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.1: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.2: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/label_metrics/recall_th0.5: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/num_pos_anchor: 4.6662e-19
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level2/num_valid_anchor: 193.4
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/box_loss: 0.0024359
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_loss: 0.015725
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.1: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.2: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/precision_th0.5: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.1: 0.45707
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.2: 0.45707
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/label_metrics/recall_th0.5: 0.45707
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/num_pos_anchor: 1.0997
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level3/num_valid_anchor: 45.424
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/box_loss: 0.0054516
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_loss: 0.016804
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.1: 0.18218
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.2: 0.18218
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/precision_th0.5: 0.5
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.1: 0.6071
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.2: 0.6071
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/label_metrics/recall_th0.5: 0.3474
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/num_pos_anchor: 2.7618
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level4/num_valid_anchor: 11.855
[32m[0610 10:20:18 @monitor.py:476][0m rpn_losses/level5/box_loss: 0.0047234
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_loss: 0.0081265
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.1: 0.27844
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.2: 0.32237
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/precision_th0.5: 0.32237
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.1: 0.6348
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.2: 0.6348
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/label_metrics/recall_th0.5: 0.6348
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/num_pos_anchor: 2.7113
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level5/num_valid_anchor: 4.3389
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/box_loss: 0.0023897
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_loss: 0.0016584
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.1: 0.55788
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.2: 0.56144
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/precision_th0.5: 0.56144
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.1: 0.61926
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.2: 0.58292
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/label_metrics/recall_th0.5: 0.58292
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/num_pos_anchor: 0.86487
[32m[0610 10:20:19 @monitor.py:476][0m rpn_losses/level6/num_valid_anchor: 0.98764
[32m[0610 10:20:19 @monitor.py:476][0m sample_fast_rcnn_targets/num_bg: 506.65
[32m[0610 10:20:19 @monitor.py:476][0m sample_fast_rcnn_targets/num_fg: 5.3506
[32m[0610 10:20:19 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/best_iou_per_gt: 0.59794
[32m[0610 10:20:19 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.3: 0.99954
[32m[0610 10:20:19 @monitor.py:476][0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.5: 0.83141
[32m[0610 10:20:19 @monitor.py:476][0m total_cost: 0.50603
[32m[0610 10:20:19 @monitor.py:476][0m wd_cost: 0.29456
--------------------  ------------

environment

sys.platform          linux
Python                3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) [GCC 7.3.0]
Tensorpack            v0.10.1-0-g8f831349
Numpy                 1.17.0
TensorFlow            1.14.0/v1.14.0-rc1-22-gaf24dc91b5
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/local/nvidia/lib64/libnvidia-ml.so.410.104
CUDA                  /usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
CUDNN                 /usr/local/cuda-9.0/lib64/libcudnn.so
NCCL                  /usr/lib64/libnccl.so.2.4.8
CUDA_VISIBLE_DEVICES  Unspecified
GPU 0,1               Tesla P40
Free RAM              224.84/250.98 GB
CPU Count             56
cv2                   4.2.0
msgpack               1.0.0
python-prctl          False
--------------------  ------------

Thanks for helping me！

**Comment by ppwwyyxx** [comment]
The dataset might be in a wrong format or require different parameters to train. This is not something we can help with.

**Comment by fei161** [comment]
I found that the model I used was COCO-MaskRCNN-R101FPN9xGNCasAugScratch.npz, but the parameter setting _C.MODE_MASK = False. Is it because I used the wrong model? But I found that the COCO* models in http://models.tensorpack.com/ are all maskrcnn, so should I use the pre-trained model of ImageNet*?

**Comment by ppwwyyxx** [comment]
A mask r-cnn model can be used with `MODE_MASK=False`.

**Comment by fei161** [comment]
[32m[0609 20:34:58 @timer.py:45][0m Load annotations for instances_train2014.json finished, time:0.0755 sec.
[32m[0609 20:34:59 @data.py:63][0m Ground-Truth category distribution:
[36m|  class   | #box   |  class  | #box   |
|:--------:|:-------|:-------:|:-------|
| drainage | 1433   | qrcode  | 293    |
|  total   | 1726   |         |        |[0m


The code can read the category of the box. Could this be the problem of the data format?

**Comment by fei161** [comment]
I changed the model to ImageNet-R101-AlignPadding.npz and modified the corresponding parameters, and the problem was solved.

**Comment by ppwwyyxx** [comment]
Then it's because originall you used COCO-MaskRCNN-R101FPN9xGNCasAugScratch with wrong configs.
