### ISSUE TITLE
{'error': 'Serving signature name: "serving_default" not found in signature def'}

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1457]
Here is how my graph looks like:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/masks:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 28, 28)
        name: output/masks:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict
```

And when Im calling the model from tensorflow server model:

```
curl -d '{"signature_name": "serving_default","instances":["/data"]}' -X POST http://localhost:8501/v1/models/a:predict
```
Im getting an error as in the topic. 

Could you help/clarify why ? signature is there !

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)). Now I cannot see how exactly this question is related to this project.

**Comment by vijaygill** [comment]
@Adblu In my following python code snippet, I use "prediction_pipeline" for signature_name and code works. 

```
    data = {
            "signature_name": "prediction_pipeline",
            "inputs": image
            }

    r = requests.post(url = "http://192.168.0.94:8501/v1/models/gillsoft:predict", json = data)

```

**Comment by Adblu** [comment]
@vijaygill How does your metagraf def looks like ?

**Comment by Adblu** [comment]
@vijaygill Weird. I have following request object:

```
data = json.dumps({"signature_name": "serving_default", "instances": x.tolist()})
headers = {"content-type": "application/json"}
``` 

and it works when I launch the server on ec2:

```
sudo docker run -p 8501:8501 --mount type=bind,source=/a/model,target=/models/a -e MODEL_NAME=a --gpus all -t tensorflow/serving:2.0.0-gpu --model_config_file=/home/ubuntu/car/serving/a/model/models.config/
```

But on sagemaker I still have the problem.

**Comment by vijaygill** [comment]
> @vijaygill How does your metagraf def looks like ?

@Adblu Sorry I did not notice that you had different signature_def in your message, and noticed only when I pasted mine as below. It seems your code should work with the signature_name you have.

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['prediction_pipeline']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/masks:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 28, 28)
        name: output/masks:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict
