### ISSUE TITLE
What is the biggest image size the model can accept ??

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1459]
I mean, are the images scaled down when the are pushed to the model ? 
I have tried with full HD size, and without scalling it down, it wont generate masks.

**Comment by ppwwyyxx** [comment]
What model is "the model"?

> are the images scaled down when the are pushed to the model ?

depends on how a model is used

A detection model can accept any size. What size is the best is a machine learning problem and not a valid tensorpack issue.

**Comment by Adblu** [comment]
Mask RCNN model to generate masks.

**Comment by ppwwyyxx** [comment]
The Mask R-CNN model implemented in tensorpack examples can accept any size that's not too small. What size is the best is a machine learning problem and not a valid tensorpack issue.
