### ISSUE TITLE
Base64 as input

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1460]
Here is my code to make an inference:

```
def send_request(im_path):
    img = np.array(Image.open(im_path))
    data = json.dumps({"signature_name": "serving_default", "instances": img.tolist()})
    headers = {"content-type": "application/json"}
    json_response = requests.post('http://' + SERVER_ADDRESS + ':' + SERVER_PORT + '/v1/models/a:predict', data=data,
                                  headers=headers)
    return json.loads(json_response.text), img.shape[:2]
```
As you can see, a list of nd.array is send to the model. That causes a lot of problems because the payload size is bigger than 5MB which is the AWS limit. 

Is it possible to send image encoded base64 ( base64.b64encode('image') ) to the model ? WIl it work ?

**Comment by ppwwyyxx** [comment]
The question does not seem related to this project as "tensorpack" doesn't even appear in the question. 
You might want to ask in other communities such as tensorflow-serving.

**Comment by Adblu** [comment]
@ppwwyyxx  I think that I have posted my question in the right place.Yes, it is related to tensorpack since I am using model trained using tensorpack. 

Here is the metagraph I have:
```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/masks:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 28, 28)
        name: output/masks:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict
```

As you can see the input is:         dtype: DT_FLOAT
and here is the data I am sending to the model during inference:

```
np.array(Image.open(im_path)).tolist()
```

What I want, it to be able to send base64 encoded image ( base64.b64encode('image') )
And the question is, is it possible ? DO I have to change something in config ? or in the model architecture ?

**Comment by ppwwyyxx** [comment]
Tensorpack is a training interface. It produces models in standard TensorFlow format and how to deploy them with tf-serving is not relevant to tensorpack.
