### ISSUE TITLE
AttributeError: 'MultiThreadMapData' object has no attribute '_evt'

### ISSUE THREAD

**Issue by john2choi** [tensorpack/tensorpack#1467]
Hello,
I got this AttributeError from "parallel_map.py".
if you have any solution, please give me advise.  thank you.

now I'm using below
python3
tensorflow 1.4.0

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Exception ignored in: <bound method MultiThreadMapData.__del__ of <tensorpack.dataflow.parallel_map.MultiThreadMapData object at 0x7f7a7d81cef0>>
Traceback (most recent call last):
  File "/tf/venv/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 203, in __del__
    if self._evt is not None:
AttributeError: 'MultiThreadMapData' object has no attribute '_evt'

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
