### ISSUE TITLE
AttributeError: 'GraphBuilder' object has no attribute 'get_inputs_desc'

### ISSUE THREAD

**Issue by tanmaysgs** [tensorpack/tensorpack#1470]
I was trying to implement the TGAN library, which uses tensorpack in it's requirements. While trying things out, I realized that my code was giving me the following error:

> AttributeError: 'GraphBuilder' object has no attribute 'get_inputs_desc'

On checking the **tensorpack.graphBuilder** more thoroughly, I found that the error was happening because there is no function like `get_inputs_desc` in it.
Was it deprecated in later versions? To implement I need to understand that what was its original purpose, and also if you can help that what can I use in its place, that would be great.

Thanks!

**Comment by ppwwyyxx** [comment]
There was never such a function in `GraphBuilder`. This method does exist in the class `ModelDesc` though, which you can find in documentation (https://tensorpack.readthedocs.io/).
