### ISSUE TITLE
How can I change the batch_size in examples/FasterRCNN?

### ISSUE THREAD

**Issue by zhayanli** [tensorpack/tensorpack#1471]
Thank you for your job. My question is how can I change the batch_size in examples/FasterRCNN. I did not find any batch_size in the code in use. I finded 'ds = MultiProcessMapData(ds, cfg.DATA.NUM_WORKERS, preprocess, buffer_size=buffer_size)' in data.py and changed to 'ds = MultiProcessMapAndBatchData(ds, cfg.DATA.NUM_WORKERS, preprocess, buffer_size=buffer_size)',then i ran python train.py with bug. I want to change the batch_size to improve the performance. Thank a lot.

**Comment by ppwwyyxx** [comment]
answered in https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md#model

**Comment by zhayanli** [comment]
We currently only support single image per GPU in this example?

**Comment by ppwwyyxx** [comment]
yes

**Comment by zhayanli** [comment]
Ok.Thanks a lot. But when you will support more than one image per GPU in training?

**Comment by ppwwyyxx** [comment]
There are no such plans.
