### ISSUE TITLE
Faster Rcnn Failed to run

### ISSUE THREAD

**Issue by AN-ZE** [tensorpack/tensorpack#1472]
Installation setting：
tensorflow=1.14
cuda=10
cudnn=7
python=3.6

Single card operation。

Failed to run：
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' used by node GPUMemoryTracker/MaxBytesInUse ith these attrs: [] 
Registered devices: [CPU, XLA_CPU, XLA_GPU] 
Registered kernels: device='GPU' 
[[GPUMemoryTracker/MaxBytesInUse]]

Is it a version issue？

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
