### ISSUE TITLE
dorefa-Net

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorpack/tensorpack#1475]
If I quantize the last layer, the validation is dropped, how to correct it?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/tensorpack/tensorpack/issues/new?assignees=&labels=&template=unexpected-problems---bugs.md&title=Please+read+%26+provide+the+following+information) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results documented in tensorpack examples.
(2) It appears to be a tensorpack bug.
