### ISSUE TITLE
How the experimental data was saved? could you tell me

### ISSUE THREAD

**Issue by THSWind** [tensorpack/tensorpack#1477]
I want to compare it with my adaptived ddqn algorithms, but I don't know how to save the experimental data is properly. Tensorboard? it's data looks strange. I'm so puzzled，help me pllllz

**Comment by ppwwyyxx** [comment]
Please describe what you'd like to do clearly.

**Comment by THSWind** [comment]
@ppwwyyxx 
Hello,
Thanks for your reply, I'd like to save total reward for every episode, and 'step', or 'scores' so that I can measure it's performance. I have seen some algorithm has processed the reward. some don't. That made me puzzle, some of them use tensorboard, but it's graph looks strange. I don't know if the data are reliable. 
I don't know whether I have made my question clear. If you understand, I hope you can help me. I'll appreciate it~

**Comment by ppwwyyxx** [comment]
`--task eval` computes evaluation score on an environment and should be the only metric that's used for comparison with other implementation.
