### ISSUE TITLE
How to do inference using .pb model

### ISSUE THREAD

**Issue by leeshienxdt** [tensorpack/tensorpack#1483]
I have trained a Faster RCNN model, and it is saved in .meta and .index file. In order to convert it to .pb file, I added the optional argument during inference: 'output-pb'. So now I have the .pb file (I supposed this is the correct and direct way to convert my model to .pb file), may I know how to perform inference using the .pb model? (If can, please provide an example)
Thanks in advance

**Comment by ppwwyyxx** [comment]
I don't know how you get the pb file so I cannot answer. In general, please see https://tensorpack.readthedocs.io/tutorial/inference.html for any question about inference.

**Comment by leeshienxdt** [comment]
Thanks for the quick reply and sorry for didn't mention clearly. The .pb file is actually getting from the `predict.py` in the FasterRCNN module (link: https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/predict.py) by setting the optional argument "output-pb" as `path/to/pb_model`. I've read the link that you mentioned but I'm not quite sure how to implement using that guideline as I'm not familiar with tensorflow's model (so far I've only been using keras), would appreciate alot if you can provide an example. Kindly let me know if you need further information.

**Comment by ppwwyyxx** [comment]
The pb model should accept inputs as defined in this line:https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/predict.py#L147

How to load and run a graph pb model is a tensorflow question and unrelated to tensorpack
