### ISSUE TITLE
ResNext32x4d-101 not obtaining reported accuracy

### ISSUE THREAD

**Issue by mgshmulik** [tensorpack/tensorpack#1488]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1)  python imagenet-resnet.py --mode resnext32x4d -d 101 --data /datasets/imagenet/ --batch 512
(2) No changes were made
On branch master
Your branch is up to date with 'origin/master'.

(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed: 

Running the script, I measured top1 error 21.87%, top5 error 5.96%. 

### 3. What you expected, if not obvious.
According to the readme file, the expected accuracy of running resnext-101 with batch-512 should be top1 error 21.05%, top5 error 5.73%.

### 4. Your environment:
--------------------  -----------------------------------------------------------------------------
sys.platform          linux
Python                3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Tensorpack            v0.10.1-35-g58fc1dea-dirty @/usr/local/lib/python3.6/dist-packages/tensorpack
Numpy                 1.18.1
TensorFlow            1.15.2/v1.15.0-92-g5d80e1e @/usr/local/lib/python3.6/dist-packages/tensorflow
TF Compiler Version   7.3.1 20180303
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.450.36.06
CUDA libs             /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
CUDNN libs            /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
TF built with CUDA    10
TF built with CUDNN   7
NCCL libs
CUDA_VISIBLE_DEVICES  Unspecified
GPU 0,1,2,3,4,5,6,7   GeForce GTX TITAN X
Free RAM              245.76/251.56 GB
CPU Count             96
Horovod               0.16.2 @/usr/local/lib/python3.6/dist-packages/horovod
cv2                   3.2.0
msgpack               1.0.0
python-prctl          False
--------------------  -----------------------------------------------------------------------------
Detecting GPUs using TensorFlow:
GPUs: /physical_device:GPU:0, /physical_device:GPU:1, /physical_device:GPU:2, /physical_device:GPU:3, /physical_device:GPU:4, /physical_device:GPU:5, /physical_device:GPU:6, /physical_device:GPU:7

**Comment by ppwwyyxx** [comment]
I don't remember the exact setting used to train it, but I think `--weight-decay-norm` is needed for all resnet >50 layers.
I probably used batch=256, though I don't think this matters.

**Comment by mgshmulik** [comment]
Thanks Yuxin Wu,
I'll try it and update once training is completed.

Best regards,
Shmulik

**Comment by ppwwyyxx** [comment]
I ran it again with `-d 101 --mode resnext32x4d --weight-decay-norm` and obtains 21.4%. This might better reflect its performance and the one in table might be a lucky run.

**Comment by mgshmulik** [comment]
Thank yoh very much,
My session is still running, will update when it's completed.

Best regards,
Shmulik
