### ISSUE TITLE
Some questions about ZMQInput

### ISSUE THREAD

**Issue by LMLzz** [tensorpack/tensorpack#1493]
Are there any examples of using ZMQInput or zmq_ops? Now I have a requirement: use zmq on the client to send data, and use ZMQInput on the server to continuously receive data and perform inference work.  In the process of using these two interface, I encountered some problems. I can  continue to receive data in the while loop and convert it to tf.dataset,  but when I tried to print it, something went wrong. The logic of my print function is as follows:
```
def print_dataset(data_set):
    iterator = data_set.make_initializable_iterator()
    next_element = iterator.get_next()
    num_batch = 0
    with tf.train.MonitoredTrainingSession() as sess:
        sess.run(iterator.initializer)
        while True:
            try:
                value = sess.run(next_element)
                print("Num Batch: ", num_batch)
                print("Batch value: ", value)
                num_batch += 1
            except tf.errors.OutOfRangeError:
                break     
```
When this function is not called, I can receive tensor continuously.

When this function is called, it can only output success at the first time. I am a newbie in this area, and it may be the problem caused by my improper use, so I would like to ask you for some suggestions or examples. Thank you very much and look forward to receiving your reply.
By the way, the error is as follows
```
terminate called after throwing an instance of 'zmq::error_t'
  what():  Address already in use
*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/../libtensorflow_framework.so.1(+0x10708ae)[0x7fb1f783c8ae]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fb2cde38730]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7fb2cd8b27bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7fb2cd89d535]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c983)[0x7fb229dae983]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x928c6)[0x7fb229db48c6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92901)[0x7fb229db4901]
/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/../libtensorflow_framework.so.1(+0x16cc53e)[0x7fb1f7e9853e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fb2cde2dfa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fb2cd9744cf]
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
        tensorflow::CurrentStackTrace()

        gsignal
        abort

        clone
*** End stack trace ***
Aborted (core dumped)
```

**Comment by ppwwyyxx** [comment]
As https://tensorpack.readthedocs.io/tutorial/extend/input-source.html says, all InputSource in tensorpack requires being used with tensorpack trainer. Other usage are not supported.
