### ISSUE TITLE
Knowledge distillation in Tensorpack

### ISSUE THREAD

**Issue by minhson** [tensorpack/tensorpack#1495]
Hello, could you give me the example for using Knowledge Distillation in tensorpack?
I tried and failed to implement it. 
Thanks you in advance!

**Comment by ppwwyyxx** [comment]
As long as you can build a graph and return a loss in tensoflow it should be able to train in tensorpack. This appears to be only a tensorflow question, unless there is any specific question about tensorpack you'd like to ask.

To do something like this in tensorflow you can:
```python
pred_teacher = teacher_model(input)
pred_student = student_model(input)
return loss_func(pred_teacher, pred_student)
```
