### ISSUE TITLE
ImportError:  cannot import name 'tfv1'

### ISSUE THREAD

**Issue by LinqingZhu** [tensorpack/tensorpack#1497]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
  I am using Mask/Faster RCNN examples, and I run
  python predict.py --predict 00000.jpg 00001.jpg --load ./weights/COCO-MaskRCNN-R101FPN9xGNCasAugScratch.npz

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
   No

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
Traceback (most recent call last):
  File "predict.py", line 23, in <module>
    from modeling.generalized_rcnn import ResNetC4Model, ResNetFPNModel
  File "/home/lqzhu/FasterRCNN/modeling/generalized_rcnn.py", line 4, in <module>
    from tensorpack import tfv1 as tf
ImportError: cannot import name 'tfv1'

```

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.

### 4. Your environment:
Python 3.6.11
TF 1.14.0
tensorpack 0.10.1

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`
If this command failed, also tell us your version of Python/TF/tensorpack.

Note that:

  + You can install tensorpack master by `pip install -U git+https://github.com/tensorpack/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
It seems you're using github master version of FasterRCNN example with an older version of tensorpack.

Please make sure tensorpack version is newer than the example.

**Comment by sisrfeng** [comment]
I download this release, but still  

> cannot import name 'tfv1' 

![image](https://user-images.githubusercontent.com/53520949/107142925-091a4380-696d-11eb-9503-c7ed42f934cb.png)

**Comment by sisrfeng** [comment]
Hi, what do you mean by  this?

> github master version of FasterRCNN example with an older version of tensorpack
Did you fork FasterRCNN from another repo? Could you please tell me which repo?
