### ISSUE TITLE
How to reduce the running time?

### ISSUE THREAD

**Issue by Saraaqzs** [tensorpack/tensorpack#1499]
I'm trying to run FasterRCNN COCO, but the size of the 2014 sample is ~40000 images and it takes a lot to run train.py on 2 GPUs so I would like to try with smaller sample size.
I do not understand which parameters I should change to reduce the size of the sample in the code? Or equivalently which parameters should I change to reduce the running time?

I have already reduced:

`_C.TRAIN.STEPS_PER_EPOCH `
`_C.TRAIN.EVAL_PERIOD`

in config.py file.
Thanks!

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/BALLOON.md shows a tiny example that trains a few minutes
