### ISSUE TITLE
How to load data produced on GPU?

### ISSUE THREAD

**Issue by topriss** [tensorpack/tensorpack#1500]
Firstly, thanks for your great jobs about Tensorpack.

My task is to train a video compression network, which takes in two images and outputs one coded image.
For each iter, I to load a sequence of images (say im0, im1, ... , im7). 
The network first takes in (im0, im1) and outputs (coded_im1,).
For the rest of images, The network takes in (coded_im_i, im_{i+1}) and outputs (coded_im_{i+1},).
Note here coded_im_i is on the GPU, and I want to load it into the net w.o. move it back to CPU and then to GPU.

Explaining using an example, I got stuck when trying to modify 
https://github.com/RenYang-home/OpenDVC/blob/master/OpenDVC_train_PSNR.py
into a multi-GPU tensorpack version.

Specifically, I dont know how to implement this part of the iter loop in tensorpack:
![F0F1](https://user-images.githubusercontent.com/12832507/101979894-04eae600-3c9c-11eb-9695-151939d1d709.png)

Any help is appreciated.

**Comment by ppwwyyxx** [comment]
The builtin trainers only work for single-dataloader single-cost optimization: https://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html#built-in-trainers 

Therefore to do this you need to either formulate your problem this way (e.g. by writing the loops in the model with `tf.while`) or implement a custom trainer (https://tensorpack.readthedocs.io/en/latest/tutorial/extend/trainer.html)
