### ISSUE TITLE
Export with tensorpack error when using tensorflow serving

### ISSUE THREAD

**Issue by xealml** [tensorpack/tensorpack#1503]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
<paste logs here>
use tensorflow serving and get

2021-01-14 12:03:30.625847: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: prediction_pipeline version: 1} failed: Not found: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`

and code is here

from tensorpack import PredictConfig, SmartInit

from audio_cls_tensorpack.tensorpack_vggish import VggModelInferOnly
from tensorpack.tfutils.export import ModelExporter
import tensorflow as tf

if __name__ == '__main__':
    voice_second = 10
    num_categories = 2

    model_path = './model.ckpt-23745'

    pred_config = PredictConfig(
        session_init=SmartInit(model_path),
        model=VggModelInferOnly(),
        input_names=['inputs'],
        output_names=['predictions']
    )
    ModelExporter(pred_config).export_serving( './served_model/1')

tensorflow serving config bash
model_name="check"
docker kill $model_name
docker rm $model_name

docker run \
  -t --rm \
  --name=$model_name \
  -p 8800:8800 -p 8801:8801 \
  -e CUDA_VISIBLE_DEVICES=4 \
  -v "/pb_models/served_model:/models/${model_name}" \
  -e MODEL_NAME=$model_name \
  tensorflow/serving:1.14.0-gpu \
  --port=8800 --rest_api_port=8801

```

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.

### 4. Your environment:

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`
If this command failed, also tell us your version of Python/TF/tensorpack.
but I install tensorpack using pip install tensorpack(on aliyun).
```
(py3) ➜  ~ pip list|grep tensor
tensorboard          1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
tensorpack           0.10.1
```

Note that:

  + You can install tensorpack master by `pip install -U git+https://github.com/tensorpack/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
