### ISSUE TITLE
AP are all zero

### ISSUE THREAD

**Issue by hhhhh74** [tensorpack/tensorpack#1506]
hi, thanks for your excellent work and sharing code with us, when i  use the faster-rcnn network to predict, the result of kitti dataset shows all AP are 0, and perhaps it is relevant with the TF callable model_func() ? which included in the /examples/faster-rcnn/eval.py.  if my guess is worng, would you like to give some advice about why are the AP all 0? Thank you very much,.
Best Regards.
Zhao Chen

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md) suggests:

> If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.
