### ISSUE TITLE
NotImplementedError when using custom-balloon dataset

### ISSUE THREAD

**Issue by ramanathan831** [tensorpack/tensorpack#1508]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
./train.py --config DATA.BASEDIR=~/data/balloon/ "DATA.VAL=('balloon_val',)"  "DATA.TRAIN=('balloon_train',)"
(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
git status:
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   config.py
        modified:   dataset/__init__.py
        modified:   dataset/balloon.py
        modified:   predict.py
        modified:   train.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        dataset/balloon_dataset.zip
        dataset/satpole.py

no changes added to commit (use "git add" and/or "git commit -a")
diff --git a/examples/FasterRCNN/config.py b/examples/FasterRCNN/config.py
index 79506efb..24e61f2f 100644
--- a/examples/FasterRCNN/config.py
+++ b/examples/FasterRCNN/config.py
@@ -92,12 +92,20 @@ _C.MODE_MASK = True        # Faster R-CNN or Mask R-CNN
 _C.MODE_FPN = True
 
 # dataset -----------------------
-_C.DATA.BASEDIR = '/path/to/your/DATA/DIR'
+_C.DATA.BASEDIR = '/home/data/dataset_augmented_Dec4'
 # All available dataset names are defined in `dataset/coco.py:register_coco`.
 # All TRAIN dataset will be concatenated for training.
-_C.DATA.TRAIN = ('coco_train2017',)   # i.e. trainval35k
+_C.DATA.TRAIN = ('satpole_train',)   # i.e. trainval35k
 # Each VAL dataset will be evaluated separately (instead of concatenated)
-_C.DATA.VAL = ('coco_val2017',)  # AKA minival2014
+_C.DATA.VAL = ('satpole_val',)  # AKA minival2014
+# # dataset -----------------------
+# _C.DATA.BASEDIR = '/home/data/balloon'
+# # All available dataset names are defined in `dataset/coco.py:register_coco`.
+# # All TRAIN dataset will be concatenated for training.
+# _C.DATA.TRAIN = ('balloon_train',)   # i.e. trainval35k
+# # Each VAL dataset will be evaluated separately (instead of concatenated)
+# _C.DATA.VAL = ('balloon_val',)  # AKA minival2014
+
 
 # These two configs will be populated later inside `finalize_configs`.
 _C.DATA.NUM_CATEGORY = -1  # without the background class (e.g., 80 for COCO)
diff --git a/examples/FasterRCNN/dataset/__init__.py b/examples/FasterRCNN/dataset/__init__.py
index cde99703..def04706 100644
--- a/examples/FasterRCNN/dataset/__init__.py
+++ b/examples/FasterRCNN/dataset/__init__.py
@@ -1,3 +1,4 @@
 from .dataset import *
 from .coco import *
 from .balloon import *
+from .satpole import *
\ No newline at end of file
diff --git a/examples/FasterRCNN/dataset/balloon.py b/examples/FasterRCNN/dataset/balloon.py
index f610d4fa..ac2e4af9 100644
--- a/examples/FasterRCNN/dataset/balloon.py
+++ b/examples/FasterRCNN/dataset/balloon.py
@@ -34,18 +34,20 @@ class BalloonDemo(DatasetSplit):
                 anno = anno["shape_attributes"]
                 px = anno["all_points_x"]
                 py = anno["all_points_y"]
-                poly = np.stack((px, py), axis=1) + 0.5
+                poly = np.stack((px, py), axis=1)
                 maxxy = poly.max(axis=0)
                 minxy = poly.min(axis=0)
 
                 boxes.append([minxy[0], minxy[1], maxxy[0], maxxy[1]])
                 segs.append([poly])
             N = len(annos)
+            print(fname,N)
             roidb["boxes"] = np.asarray(boxes, dtype=np.float32)
             roidb["segmentation"] = segs
             roidb["class"] = np.ones((N, ), dtype=np.int32)
             roidb["is_crowd"] = np.zeros((N, ), dtype=np.int8)
             ret.append(roidb)
+        print(ret)
         return ret
 
 
@@ -58,7 +60,7 @@ def register_balloon(basedir):
 
 if __name__ == '__main__':
     basedir = '~/data/balloon'
-    roidbs = BalloonDemo(basedir, "train").training_roidbs()
+    roidbs = BalloonDemo(basedir, "val").training_roidbs()
     print("#images:", len(roidbs))
 
     from viz import draw_annotation
diff --git a/examples/FasterRCNN/predict.py b/examples/FasterRCNN/predict.py
index 2d4b5a00..1ecd2a4a 100755
--- a/examples/FasterRCNN/predict.py
+++ b/examples/FasterRCNN/predict.py
@@ -15,7 +15,7 @@ from tensorpack.tfutils import SmartInit, get_tf_version_tuple
 from tensorpack.tfutils.export import ModelExporter
 from tensorpack.utils import fs, logger
 
-from dataset import DatasetRegistry, register_coco, register_balloon
+from dataset import DatasetRegistry, register_coco, register_satpole, register_balloon
 from config import config as cfg
 from config import finalize_configs
 from data import get_eval_dataflow, get_train_dataflow
@@ -124,8 +124,8 @@ if __name__ == '__main__':
     if args.config:
         cfg.update_args(args.config)
     register_coco(cfg.DATA.BASEDIR)  # add COCO datasets to the registry
+    register_satpole(cfg.DATA.BASEDIR)
     register_balloon(cfg.DATA.BASEDIR)
-
     MODEL = ResNetFPNModel() if cfg.MODE_FPN else ResNetC4Model()
 
     if not tf.test.is_gpu_available():
diff --git a/examples/FasterRCNN/train.py b/examples/FasterRCNN/train.py
index de79c59e..53a93743 100755
--- a/examples/FasterRCNN/train.py
+++ b/examples/FasterRCNN/train.py
@@ -5,15 +5,15 @@ import argparse
 
 from tensorpack import *
 from tensorpack.tfutils import collect_env_info
-
-from dataset import register_coco, register_balloon
+import sys
+sys.path.append("dataset/")
+from dataset import register_coco, register_satpole, register_balloon
 from config import config as cfg
 from config import finalize_configs
 from data import get_train_dataflow
 from eval import EvalCallback
 from modeling.generalized_rcnn import ResNetC4Model, ResNetFPNModel
 
-
 try:
     import horovod.tensorflow as hvd
 except ImportError:
@@ -36,8 +36,8 @@ if __name__ == '__main__':
     if args.config:
         cfg.update_args(args.config)
     register_coco(cfg.DATA.BASEDIR)  # add COCO datasets to the registry
-    register_balloon(cfg.DATA.BASEDIR)  # add the demo balloon datasets to the registry
-
+    register_satpole(cfg.DATA.BASEDIR)  # add the demo SMA_SAT datasets to the registry
+    register_balloon(cfg.DATA.BASEDIR)
     # Setup logging ...
     is_horovod = cfg.TRAINER == 'horovod'
     if is_horovod:

(3) **If not using examples, help us reproduce your issue:**
N/A

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
fastrcnn/outputs/class/W             [1024, 2]                  2048
fastrcnn/outputs/class/b             [2]                           2
fastrcnn/outputs/box/W               [1024, 8]                  8192
fastrcnn/outputs/box/b               [8]                           8
maskrcnn/fcn0/W                      [3, 3, 256, 256]         589824
maskrcnn/fcn0/b                      [256]                       256
maskrcnn/fcn1/W                      [3, 3, 256, 256]         589824
maskrcnn/fcn1/b                      [256]                       256
maskrcnn/fcn2/W                      [3, 3, 256, 256]         589824
maskrcnn/fcn2/b                      [256]                       256
maskrcnn/fcn3/W                      [3, 3, 256, 256]         589824
maskrcnn/fcn3/b                      [256]                       256
maskrcnn/deconv/W                    [2, 2, 256, 256]         262144
maskrcnn/deconv/b                    [256]                       256
maskrcnn/conv/W                      [1, 1, 256, 1]              256
maskrcnn/conv/b                      [1]                           1
Number of trainable variables: 168
Number of parameters (elements): 43749914
Storage space needed for all trainable variables: 166.89MB
[0128 21:08:34 @base.py:207] Setup callbacks graph ...
[0128 21:08:36 @argtools.py:138] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
WARNING:tensorflow:From /home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/callbacks/prof.py:268: The name tf.train.SessionRunArgs is deprecated. Please use tf.estimator.SessionRunArgs instead.

[0128 21:08:37 @prof.py:299] [HostMemoryTracker] Free RAM in setup_graph() is 490.27 GB.
[0128 21:08:37 @tower.py:135] Building graph for predict tower 'tower-pred-0' on device /gpu:0 ...
[0128 21:08:38 @collection.py:152] Size of these collections were changed in tower-pred-0: (tf.GraphKeys.MODEL_VARIABLES: 260->293)
[0128 21:08:38 @tower.py:135] Building graph for predict tower 'tower-pred-1' on device /gpu:1 with variable scope 'tower1'...
[0128 21:08:40 @collection.py:152] Size of these collections were changed in tower-pred-1: (tf.GraphKeys.MODEL_VARIABLES: 293->326)
[0128 21:08:40 @tower.py:135] Building graph for predict tower 'tower-pred-2' on device /gpu:2 with variable scope 'tower2'...
[0128 21:08:41 @collection.py:152] Size of these collections were changed in tower-pred-2: (tf.GraphKeys.MODEL_VARIABLES: 326->359)
[0128 21:08:41 @tower.py:135] Building graph for predict tower 'tower-pred-3' on device /gpu:3 with variable scope 'tower3'...
[0128 21:08:42 @collection.py:152] Size of these collections were changed in tower-pred-3: (tf.GraphKeys.MODEL_VARIABLES: 359->392)
Traceback (most recent call last):
  File "./train.py", line 119, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/train/interface.py", line 99, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/train/base.py", line 345, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/train/base.py", line 315, in train
    self.setup_callbacks(callbacks, monitors)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/train/base.py", line 209, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in setup_graph
    self._setup_graph()
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 68, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/home/ram/miniconda3/envs/venv/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in setup_graph
    self._setup_graph()
  File "/home/ram/smart_audit_satellite_train/tensorpack/examples/FasterRCNN/eval.py", line 235, in _setup_graph
    for k in range(self.num_predictor)]
  File "/home/ram/smart_audit_satellite_train/tensorpack/examples/FasterRCNN/eval.py", line 235, in <listcomp>
    for k in range(self.num_predictor)]
  File "/home/ram/smart_audit_satellite_train/tensorpack/examples/FasterRCNN/data.py", line 379, in get_eval_dataflow
    roidbs = DatasetRegistry.get(name).inference_roidbs()
  File "/home/ram/smart_audit_satellite_train/tensorpack/examples/FasterRCNN/dataset/dataset.py", line 54, in inference_roidbs
    raise NotImplementedError()
NotImplementedError
MultiProcessMapDataZMQ successfully cleaned-up.
```

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.

### 4. Your environment:

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`
If this command failed, also tell us your version of Python/TF/tensorpack.

No error

**I tried for custom dataset as per balloon.md to trigger a training, it threw the error "NotImplementedError" then I tried with balloon dataset itself, I'm getting the same issue**

**Comment by ppwwyyxx** [comment]
Evaluation is not supported on this dataset because it's not in COCO format.
Please use `TRAIN.EVAL_PERIOD=0` as the example shows (https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/BALLOON.md)

**Comment by ramanathan831** [comment]
Thanks for the prompt reply.

**Comment by ramanathan831** [comment]
Hi, Where do we mention the input size for the model for custom datasets, like 256x256 or 512x512

**Comment by ppwwyyxx** [comment]
users define how to process the data in the dataloader: https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/data.py#L75-L78
