### ISSUE TITLE
having issue in tensorflow.utils.rect

### ISSUE THREAD

**Issue by vjamishi** [tensorpack/tensorpack#1509]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:
<img width="578" alt="2" src="https://user-images.githubusercontent.com/30191005/106239504-bcc25b80-6228-11eb-81e8-8f3916c47cf7.png">

i am facing error in importing tensorflow Floatbox from tensorflow.utils.rect

it is showinf following error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a83bc89b1c0a> in <module>
      1 from tensorpack.utils import logger
----> 2 from tensorpack.utils.rect import FloatBox
      3 from tensorpack.utils.timer import timed_operation
      4 from tensorpack.utils.argtools import log_once

ModuleNotFoundError: No module named 'tensorpack.utils.rect'
    please guide me how to resolve this

**Comment by ppwwyyxx** [comment]
`from tensorpack.utils.rect` was deprecated 2.5 years ago so the failure is expected.
