### ISSUE TITLE
How can I use "PrefetchDataZMQ" or other Api to get dataflow in windows?

### ISSUE THREAD

**Issue by DYJ1234567890** [tensorpack/tensorpack#1510]
Hi,I use the Api:PrefetchDataZMQ() but get "AssertionError: ZMQ IPC doesn't support windows!".May you tell me what can I do to use this Api in windows os?

**Comment by DYJ1234567890** [comment]
Or do you offer other Api which can be used in windows to get dataflow ?

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/en/latest/modules/dataflow.html#tensorpack.dataflow.MultiProcessRunner is the alternative on windows
