### ISSUE TITLE
Oriented Bounding Box Training

### ISSUE THREAD

**Issue by ramanathan831** [tensorpack/tensorpack#1511]
Is there current support to train objects with orientations associated with them: x1,y1,x2,y2,theta-float?
If not, are there any short term plans, or are you open for pull request contribution?

**Comment by ppwwyyxx** [comment]
There is no such plans.

Tensorpack is a training interface - implementing more complicated models is not aligned with this goal. And given that I don't think there is a reasonable way to achieve what you described within 1000 lines of code, it's probably not a PR that we'll accept.
