### ISSUE TITLE
Detectron Conversion

### ISSUE THREAD

**Issue by morganOliveira2018** [tensorpack/tensorpack#1512]
### Attempt to use the Detectron2 Conversion tutorial to deploy the model:
Link: [convert_d2](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2)

1. I ran an example via the Colab command line (for testing only):
````
python convert_d2.py --d2-config /content/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --d2-pkl 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl' --output R50FPN-d2-converted.npz
````

2. Error:
````
File "<ipython-input-12-1cbc60055d71>", line 2
    python convert_d2.py --d2-config /content/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --d2-pkl 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl' --output R50FPN-d2-converted.npz
                    ^
SyntaxError: invalid syntax
````

Access link: [Detectron2 - Object Detection with PyTorch](https://colab.research.google.com/drive/1dftam-7nc6TGaUudHV0x1R5bumPpHSR-?usp=sharing)

Some suggestion @ppwwyyxx to correct the syntax, because I am in doubt what is the correct form.

**Comment by ppwwyyxx** [comment]
https://stackoverflow.com/questions/52343308/how-to-run-shell-script-file-on-ipython-at-google-colab
