### ISSUE TITLE
 Enlarging batch size per GPU with GPU Virtualization?(each GPU of mine has more than 32G MEM left now)

### ISSUE THREAD

**Issue by sisrfeng** [tensorpack/tensorpack#1513]
I notice:
> AMD will launch a new server graphics card that can be virtualized into 32 pieces

Would such technology help?

(What a waste~)
![image](https://user-images.githubusercontent.com/53520949/108281503-d537ed00-71ba-11eb-8d5e-cb149e3ff5ed.png)

**Comment by ppwwyyxx** [comment]
I can't understand the issue and it doesn't seem belong to any of the [issue categories](https://github.com/tensorpack/tensorpack/issues/new/choose).
