### ISSUE TITLE
How to get the output of the model at each training round?

### ISSUE THREAD

**Issue by lums199656** [tensorpack/tensorpack#1519]
Hi, I am training a GAN model. I want to convert the output of the generator to an array for operation at the end of each round of training. I tried for a long time but couldn't get an output of type array.
Thank you so much.

**Comment by ppwwyyxx** [comment]
Using the `ProcessTensors` callback https://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.ProcessTensors  with the right tensor name, user can specify an arbitrary function that will be called with the value of the tensor.
