### ISSUE TITLE
Conversion of DensePose to TensorFlow

### ISSUE THREAD

**Issue by martrim** [tensorpack/tensorpack#1521]
Hi, I have a question regarding the Detectron2 conversion script from [https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2). Is it possible to use the script to convert DensePose models to TensorFlow? If not, do you plan to add conversion of DensePose at some point in the near future?

Thank you very much in advance!

Kind regards,
Martin

**Comment by ppwwyyxx** [comment]
It's not implemented, and we don't plan to
