### ISSUE TITLE
convert keypoint_rcnn_R_50_FPN_3x.yaml fails with AssertionError

### ISSUE THREAD

**Issue by jk78346** [tensorpack/tensorpack#1524]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
```
python3 convert_d2.py --d2-config ~/detectron2/configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml --d2-pkl model_final_a6e10b.pkl --output R50FPN-d2-converted.npz
```

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
-- (1) the .yaml model is from source code of detectron2 as the path suggests
-- (2) the .pkl is downloaded from this  [webpage](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md) and this [model ](https://dl.fbaipublicfiles.com/detectron2/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl)
(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
'MODE_MASK=False' 'MODE_FPN=True' 'FPN.CASCADE=False' 'BACKBONE.STRIDE_1X1=True' 'PREPROC.PIXEL_MEAN=[123.675,116.28,103.53]' 'PREPROC.PIXEL_STD=[1.0,1.0,1.0]' Traceback (most recent call last):
  File "convert_d2.py", line 141, in <module>
    tp_dict = convert_weights(d2_dict, cfg)
  File "convert_d2.py", line 121, in convert_weights
    assert len(d) == 0, d.keys()
AssertionError: odict_keys(['roi_heads.keypoint_head.conv_fcn1.weight', 'roi_heads.keypoint_head.conv_fcn1.bias', 'roi_heads.keypoint_head.conv_fcn2.weight', 'roi_heads.keypoint_head.conv_fcn2.bias', 'roi_heads.keypoint_head.conv_fcn3.weight', 'roi_heads.keypoint_head.conv_fcn3.bias', 'roi_heads.keypoint_head.conv_fcn4.weight', 'roi_heads.keypoint_head.conv_fcn4.bias', 'roi_heads.keypoint_head.conv_fcn5.weight', 'roi_heads.keypoint_head.conv_fcn5.bias', 'roi_heads.keypoint_head.conv_fcn6.weight', 'roi_heads.keypoint_head.conv_fcn6.bias', 'roi_heads.keypoint_head.conv_fcn7.weight', 'roi_heads.keypoint_head.conv_fcn7.bias', 'roi_heads.keypoint_head.conv_fcn8.weight', 'roi_heads.keypoint_head.conv_fcn8.bias', 'roi_heads.keypoint_head.score_lowres.weight', 'roi_heads.keypoint_head.score_lowres.bias'])
```

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.

### 4. Your environment:

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`
If this command failed, also tell us your version of Python/TF/tensorpack.
 -- python3: 3.6.9

Note that:

  + You can install tensorpack master by `pip install -U git+https://github.com/tensorpack/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
As mentioned in https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2, only Faster/Mask/Cascade R-CNN are supported.

**Comment by jk78346** [comment]
Thank you for the quick reply. Actually I'm not familiar with the model architecture design. I only need to convert a keypoints detection model to tensorflow for my work. What alternative model is suggested? And what is the difference between Faster/Mask/Cascade R-CNNs? I think I only care about the model input/output format. And the reason why I choose COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml is because it is the example model used in [Vidoepose3D](https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md) (in the wild)

**Comment by jk78346** [comment]
I think I understand that those models you mentioned are for different goals(Object Detection/Instance Segmentation) rather than keypoints model that I want, thanks.
