### ISSUE TITLE
How to get the TfLite conversion done?

### ISSUE THREAD

**Issue by Bhateja-Akash** [tensorpack/tensorpack#1530]
Is there any suitable way for this conversion? If not, please provide some tips for a conversion like, 
PyTorch -> Onnx -> Tensorflow -> TfLite.

In the PyTorch to Onnx conversion, what is the required output format? I have followed the documentation, but stuck at a step that outputs the following:
``IndexError: too many indices for the tensor of dimension 2``

**Comment by ppwwyyxx** [comment]
Tensorpack is a training library. It produces standard tensorflow model as the outcome of training, and anything after that is not its responsibility.
