### ISSUE TITLE
Restoring a model from checkpoint in tensorflow

### ISSUE THREAD

**Issue by Abhishek2271** [tensorpack/tensorpack#1531]
Hi,

## WHAT I DID:
1. Trained a DoReFaNet at 1,2,6 bit widths with SVHN dataset.
2. Used the checkpoints to restore the model.

Is there any difference between running inference in the model restored from metafile and checkpoint vs. using the OffLinePredictor available within the TensorPack. 

According to the discussion in #863, even though weights on the saved quantized network are in Float32, quantized weights (float32 represented) and activations are used during inference (without having to manually change the weights with Fw) since Fw and Fa are defined in the graph itself. Is this still the same when we manually restore the model and run inference?
Is it possible to use the Tensorpack just to change the input order? 

I am really sorry if I sound a bit unclear in my problem, I am using DoreFaNet to create adversarial examples using an API that requires the model definition as input which is why I have to restore the model separately.

**Comment by ppwwyyxx** [comment]
>  running inference in the model restored from metafile 

That's not a proper way to run inference as we said in https://tensorpack.readthedocs.io/en/latest/tutorial/inference.html#step-1-build-the-model-graph, so I'm not sure what will happen.

**Comment by Abhishek2271** [comment]
@ppwwyyxx , thank you for the reply. I will try inference with the steps suggested.
