### ISSUE TITLE
Training MNIST model removes the channel dimension

### ISSUE THREAD

**Issue by Abhishek2271** [tensorpack/tensorpack#1534]
### 1. What you did:

I trained a simple MNIST model provided as an example in Tensorpack.

### 2. What you observed:

During extracting data from .tar file from MNIST dataset, an additional dimension is added at the end. This is understandable because although MNIST has single channel TensorFlow needs a channel dimension so that the final dimension is [NHWC].

The code which does this is in mnist.py

![image](https://user-images.githubusercontent.com/33551684/126376332-fa5aab5e-c4ba-4649-a250-4d7ef827e75f.png)

However, during training this dimension is removed and later is again added while building model.

![image](https://user-images.githubusercontent.com/33551684/126376602-f1e36ba6-6986-4db8-91eb-35fc2e68bb31.png)

I have been looking in the code and I am not sure where this dimension is removed. I think it is in QueueInput(dataset) during training but I am unable to debug it.
Is there any reason why this is removed and  is it possible to not remove it?

**Comment by ppwwyyxx** [comment]
The mnist data loader already removes the extra dimension:

https://github.com/tensorpack/tensorpack/blob/ff7de87f2013783641352a3786d931f9bd300ad4/tensorpack/dataflow/dataset/mnist.py#L108-L111

**Comment by Abhishek2271** [comment]
@ppwwyyxx  Thank you very much for the reply. I added the dimension and the training went normally.
