### ISSUE TITLE
the zmq pipe does not delete automatically 

### ISSUE THREAD

**Issue by ericxsun** [tensorpack/tensorpack#1535]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

with the code (newest dataflow， mac os Big Sur)
```
class Dataset(RNGDataFlow):
    def __init__(self, data):
        self.data = data

    def __iter__(self):
        return iter(self.data)

    def __len__(self):
        return len(self.data)


dataset = Dataset(list(range(100))
dataset = MultiProcessMapDataZMQ(dataset, num_proc=20, map_func=lambda x: x*2, buffer_size=10, strict=True)
dataset = MultiProcessRunnerZMQ(dataset, num_proc=1)

dataset.reset_state()
for x in dataset:
    print(x)
```

### 2. What you observed:
run the code, until it is finished. I found two file in my path: `dataflow-map-pipe-94fc13` and `dataflow-pipe-94fa6c`. And run again, two new files with same prefix `dataflow-map-pipe-` and `dataflow-pipe-` are created.

### 3. What you expected, if not obvious.

I thought they should be deleted automatically at the end. 

So why and how to deleted them automatically?

**Comment by ppwwyyxx** [comment]
This only happens on non-linux system and is expected, because only linux has anonymous pipe.

Automatic clean up can be implemented as an atexit handler when the pipe is created in the dataflow library.
