### ISSUE TITLE
Why pycocotools has no author, licence info neither a github repo or official website?

### ISSUE THREAD

**Issue by pokecheater** [tensorpack/tensorpack#1536]
Hi and sry for posting it right here.

I came to this gitrepo from the website https://pypi.org/project/pycocotools/  through the maintainer: https://pypi.org/user/ppwwyyxx/ which seems also to be the maintainer of this project. 

Sadly pycoocotools is missing some relevant information as: licence, website, gitrepo, full name author. 

Currently the legal use of pycocotools is unclear. Please @ppwwyyxx provide the necessary information.
Thanks in advance

**Comment by ppwwyyxx** [comment]
https://github.com/cocodataset/cocoapi contains relevant info.

**Comment by pokecheater** [comment]
Thank you @ppwwyyxx
