### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [tensorpack/tensorpack#1539]
Hello,I found a performance issue in the definition of `to_dataset` ,
tensorpack/tensorpack/blob/master/tensorpack/input_source/input_source.py,
[return dataset.map(mapper)](https://github.com/tensorpack/tensorpack/blob/1a79d595f7eda9dc9dc8428f4461680ed2222ab6/tensorpack/input_source/input_source.py#L467) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by ppwwyyxx** [comment]
It will not affect performance because the mapper that's referred to at this line is not a compute-bound function.
