### ISSUE TITLE
Resnet DoReFaNet implementation

### ISSUE THREAD

**Issue by Abhishek2271** [tensorpack/tensorpack#1542]
Hi @ppwwyyxx ,

I was looking into implementing DoReFaNet for ResNet and came across a link in the source of tensorpack in "/examples/ResNet/Cifar-10-resnet.py"   implementation. 

The code at https://github.com/tensorpack/tensorpack/pull/69 seems to be very old and now removed from the examples as well. I tried to implement it by updating it so that it works for the new code but there were exceptions while creating resnet blocks.

So now, I tried to implement the DoReFaNet in the new code in the tensorpack based on "/examples/ResNet/Cifar-10-resnet.py"  but in the old implementation, the activation quantization is done before pooling. ~~Should this not be after pooling (as seen in the screenshot)?~~ (sorry this was my misunderstanding, the _layer l_ is being pooled as opposed to my misunderstanding that c2 was being pooled. The quantization step now makes sense for activation quantization)

![image](https://user-images.githubusercontent.com/33551684/134562529-c3bc709a-3c78-4dab-abb5-78a1f1090055.png)

Also shouldn't the remap variables be used to quantize weights? In the old implementation this was different but I guess this was changed later.

![image](https://user-images.githubusercontent.com/33551684/134562899-245c9cf4-3a7c-4dfd-a4e2-e2b71135d151.png)

**Comment by ppwwyyxx** [comment]
> Also shouldn't the remap variables be used to quantize weights

Yes it should, and the current DoReFaNet example does that.
