### ISSUE TITLE
Exporting detectron2 model to pkl file

### ISSUE THREAD

**Issue by solarflarefx** [tensorpack/tensorpack#1544]
I am trying to use the  convert_d2.py script to convert my detectron2 model to tensorpack.  I have saved my config as a .yaml file, but I am unsure how to properly create the .pkl file so that I can load it into the convert_d2.py script.  Right now my neural network weights are in a .pth file.  I tried loading this instead of the .pkl file to convert_d2.py but this gave an error.

**Comment by kushagra97pal** [comment]
> 

Hi, solarflarefx did you try it using the pretrained file from the modelzoo: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl. This file.

**Comment by ppwwyyxx** [comment]
the `pkl` files were created by `torch.load` the pth file and dumping the dict of weights with `pkl.dump`. You can open the files in both format to see their format, and write a simple conversion script with no more than 10 lines of code.
