### ISSUE TITLE
No access to models.tensorpack.com

### ISSUE THREAD

**Issue by florian6973** [tensorpack/tensorpack#1550]
Hi!
In the example about FastRCNN I can't download the pretrained model http://models.tensorpack.com/FasterRCNN/COCO-MaskRCNN-R50FPN2x.npz
The link does not work. Is there any other place where I can find this file?
Thanks

**Comment by PatWie** [comment]
The server went down. I am rebooting it right now.

**Comment by PatWie** [comment]
Fixed

**Comment by ppwwyyxx** [comment]
Wow, thanks a lot @PatWie !
