### ISSUE TITLE
Site not accessible - http://models.tensorpack.com/

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1554]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

Tried to access http://models.tensorpack.com/ to download a pretrained model for Faster-RCNN example.

### 2. What you observed:

Got "This site can’t be reached" error in browser.

### 3. What you expected, if not obvious.

Expected site to be available.

**Comment by ppwwyyxx** [comment]
@PatWie would you mind taking a look?

**Comment by PatWie** [comment]
I would like to transfer those models to another place as I gonna shutdown the server (which randomly restarts).
If there is no alternative I would upload them to S3.

**Comment by PatWie** [comment]
I am hosting these models now under
https://s3.amazonaws.com/models.tensorpack.com

You probably need to change the CNAME entry.

**Comment by ppwwyyxx** [comment]
I configured the cname record. Now `http://models.tensorpack.com/index.html` works.
However, `http://models.tensorpack.com/` does not work. Is there an AWS configuration for it?

**Comment by PatWie** [comment]
Added static website hosting with default index.html document

http://models.tensorpack.com.s3-website-us-east-1.amazonaws.com/

works now with `index.html`.

**Comment by ppwwyyxx** [comment]
Thanks! Now it works if I change CNAME to `models.tensorpack.com.s3-website-us-east-1.amazonaws.com.` Is that the expected solution?
If I change it to `models.tensorpack.com.s3.amazonaws.com.` or `s3.amazonaws.com.`, then I still cannot access without `index.html`.
