### ISSUE TITLE
Add memory saving techniques to Tensorpack

### ISSUE THREAD

**Issue by michaelklachko** [tensorpack/tensorpack#654]
Please support InPlace Activated Batchnorm [1] and/or Gradient Checkpointing [2] in the examples (e.g. ResNet). I also saw an example of using TF memory optimizer [3], but I'm not sure if it's different from gradient checkpointing.
It would help further differentiate Tensorpack from other frameworks in terms of performance and efficiency. 

[1] https://arxiv.org/abs/1712.02616
[2] https://medium.com/@yaroslavvb/fitting-larger-networks-into-memory-583e3c758ff9
[3] http://tech.donghao.org/2017/11/10/training-dnn-with-less-memory-cost/

**Comment by ppwwyyxx** [comment]
@yaroslavvb do you know what https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/memory_optimizer.cc is doing? Is it also doing recomputation in backprop?

**Comment by yaroslavvb** [comment]
@ppwwyyxx yes. It works on graph_defs (proto in -> proto out) and also uses heuristics to determine which nodes to copy. It's not exactly checkpointing -- it'll find nodes with multiple consumers and duplicate them to allow to forget their value.  There's an update from @allenlavoie here, it sounds like it'll be a couple of quarters before it's ready https://github.com/openai/gradient-checkpointing/issues/13#issuecomment-360211530

**Comment by Skylion007** [comment]
It's pretty easy to monkey-patch Gradient Checkpointing in theory. We don't need any additional support to add it in.

**Comment by michaelklachko** [comment]
Where should I put the line

**Comment by yaroslavvb** [comment]
you can do something like this
```
import tensorflow as tf
tf.__dict__["gradients"] = memory_saving_gradients.gradients_memory
```
However, that only overrides `tf.gradients` method called from tensorflow namespace. If you call something like `Optimizer.minimize`, internally, that's going to call `gradients` method from a different namespace, probably this one

```
from tensorflow.python.ops import gradients
```

So to cover those usages, you may have to do
```
import tensorflow.python.ops as ops
ops.__dict__['gradients'] = memory_saving_gradients.gradients_memory
```

The underlying lesson is that this library is not quite production quality. Before going down this route, are you sure your use case needs it? IE, you could use smaller batch size for your resnet

**Comment by michaelklachko** [comment]
In my case, I modified a convolutional layer, however to test it, I have to compute 9x more feature maps in each layer, and reduce the results into a single map. I want to test this on ResNet model, so basically I have to run 9x wider ResNet-18, and I only have 4 GPUs. I already reduced batch size from 256 to 32, and also reduced the default number of feature maps in half. Now it barely fits in memory. I'm afraid further reduction of batch size might lead to issues with batchnorm, and the hyperparams were probably not optimized for such small batches.

That's why I think gradient-checkpointing would be an ideal method for me. 

I'm trying to figure out the right place to override tf.gradients in tensorpack, so I followed the path of optimizers:

https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L143
https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/train/trainers.py#L132
https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/train/tower.py#L115

After that I'm lost.

**Comment by yaroslavvb** [comment]
For monkey-patching you don't need to find the place where it's called, just put it in the beginning of the file somewhere.

But if you wanted to make sure you are monkey patching the right thing, you may need to find how it gets called. The trick is to add `import pdb; pdb.set_trace()` into gradients.py file in the beginning of call, ie [here](https://github.com/tensorflow/tensorflow/blob/8210052620ac994cca507eb9e94ba69327189195/tensorflow/python/ops/gradients_impl.py#L478). Then type "bt" to see who called it.

You can to modify this file in local installation, ie, on my computer it's this file
`/Users/yaroslav/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py`

**Comment by allenlavoie** [comment]
FWIW Grappler's memory optimizer gets reasonable memory savings on many models already (20%ish?) from recomputing "cheap" ops like batch norm. May be worth [flipping the config option](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/grappler/memory_optimizer_test.py#L180) in the `RunConfig` passed to your `Session` to check.

If you're using ops which aren't in my [beautiful hard-coded list](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/memory_optimizer.cc#L54) you might need to either [add "_recompute_hint"](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/grappler/memory_optimizer_test.py#L231) or append to the list.

Not full checkpointing, though, certainly.

**Comment by michaelklachko** [comment]
@yaroslavvb, so just to clarify, if I put
```
import memory_saving_gradients
tf.__dict__["gradients"] = memory_saving_gradients.gradients_memory 
```
here: https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/resnet_model.py#L6

It will enable checkpointing for the code launched in 
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py ?

**Comment by yaroslavvb** [comment]
I think you need to do the other one, since `tf.gradients` is never called directly by TensorPack, it's probably called indirectly as ops.gradients.

```
import tensorflow.python.ops as ops
ops.__dict__['gradients'] = memory_saving_gradients.gradients_memory
```

**Comment by michaelklachko** [comment]
@allenlavoie, I'm doing add_reduce op on the output from a normal conv2d layer (add :
https://github.com/michaelklachko/tensorpack/blob/learning/tensorpack/models/conv2d.py#L163

is that a cheap op to recompute? What would be its name string to add to your list (e.g. "ReduceSum"?)

**Comment by yaroslavvb** [comment]
@michaelklachko most things are cheap except matmul/conv, because you have low ratio of compute to volume of data needed

**Comment by allenlavoie** [comment]
@michaelklachko looks like that's just "Sum" and is not currently on the list. Feel free to add it and ping me on a PR.

**Comment by michaelklachko** [comment]
@allenlavoie, I just checked and I don't see https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/python/grappler/memory_optimizer_test.py file on my machine:

> michael@Pascal:/usr/local/lib/python2.7/dist-packages/tensorflow/python/grappler$ ll
> total 40K
> -rw-r--r-- 1 staff 4.9K Feb 15 16:40 cluster.py
> -rw-r--r-- 1 staff 6.2K Feb 15 16:40 cluster.pyc
> -rw-r--r-- 1 staff    0 Feb 15 16:40 __init__.py
> -rw-r--r-- 1 staff  199 Feb 15 16:40 __init__.pyc
> -rw-r--r-- 1 staff 3.3K Feb 15 16:40 item.py
> -rw-r--r-- 1 staff 4.1K Feb 15 16:40 item.pyc
> -rw-r--r-- 1 staff 1.8K Feb 15 16:40 tf_optimizer.py
> -rw-r--r-- 1 staff 1.5K Feb 15 16:40 tf_optimizer.pyc

**Comment by allenlavoie** [comment]
That's a unit test file, so presumably it gets excluded from the pip package to save space. You should be able to download / check it out and run it outside the repo if you want.

**Comment by michaelklachko** [comment]
@yaroslavvb I'm getting import error:
>>> import tensorflow.python.ops as ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'python'

**Comment by michaelklachko** [comment]
Thanks! Now I'm getting this error:

```
Traceback (most recent call last):
  File "/home/michael/tensorpack/examples/ResNet/imagenet-resnet.py", line 144, in <module>
    launch_train_with_config(config, trainer)
  File "/home/michael/tensorpack/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/michael/tensorpack/tensorpack/utils/argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/michael/tensorpack/tensorpack/train/tower.py", line 161, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/michael/tensorpack/tensorpack/train/trainers.py", line 155, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/michael/tensorpack/tensorpack/graph_builder/training.py", line 217, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/michael/tensorpack/tensorpack/graph_builder/training.py", line 113, in build_on_towers
    ret.append(func())
  File "/home/michael/tensorpack/tensorpack/train/tower.py", line 199, in get_grad_fn
    aggregation_method=self.AGGREGATION_METHOD)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 460, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/michael/tensorpack/examples/ResNet/resnet_model.py", line 13, in gradients_memory
    return memory_saving_gradients.gradients(ys, xs, grad_ys, checkpoints='memory', **kwargs)
  File "/usr/lib/python2.7/memory_saving_gradients.py", line 141, in gradients
    raise Exception('unable to find bottleneck tensors! please provide checkpoint nodes manually, or use checkpoints="speed".')
Exception: unable to find bottleneck tensors! please provide checkpoint nodes manually, or use checkpoints="speed".
```

I tried changing to checkpoints='speed', but then it seems like no checkpoints are being made (the model runs out of memory). 

Not sure if this is a gradient-checkpointing issue, or a tensorpack issue.

**Comment by yaroslavvb** [comment]
The automatic mode failed, so you have to provide checkpoint nodes manually. For manual nodes to save memory, you have to pick sets nodes which separate your computation graph, like described [here](https://medium.com/@yaroslavvb/fitting-larger-networks-into-memory-583e3c758ff9)

**Comment by michaelklachko** [comment]
@yaroslavvb but why did it fail? I'm trying to run default Resnet-18, similar to your deep_imagenet_benchmark.py setup. 

What would be a list of proper nodes to checkpoint for ResNet? And where do I pass it?

**Comment by michaelklachko** [comment]
@yaroslavvb Ok, I just specified a list of tensors manually like this:

```
import memory_saving_gradients
from tensorflow.python.ops import gradients
def gradients_memory(ys, xs, grad_ys=None, **kwargs):
    tensors = ['tower0/conv0/Relu:0', 'tower0/group0/block0/conv1/Relu:0']
    return memory_saving_gradients.gradients(ys, xs, grad_ys, checkpoints=tensors, **kwargs)
gradients.__dict__["gradients"] = gradients_memory
```

However, for some reason it does not see that list:

```
Traceback (most recent call last):
  File "/home/michael/tensorpack/examples/ResNet/imagenet-resnet.py", line 150, in <module>
    launch_train_with_config(config, trainer)
  File "/home/michael/tensorpack/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/michael/tensorpack/tensorpack/utils/argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/michael/tensorpack/tensorpack/train/tower.py", line 161, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/michael/tensorpack/tensorpack/train/trainers.py", line 155, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/michael/tensorpack/tensorpack/graph_builder/training.py", line 217, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/michael/tensorpack/tensorpack/graph_builder/training.py", line 113, in build_on_towers
    ret.append(func())
  File "/home/michael/tensorpack/tensorpack/train/tower.py", line 199, in get_grad_fn
    aggregation_method=self.AGGREGATION_METHOD)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 460, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/michael/tensorpack/examples/ResNet/resnet_model.py", line 27, in gradients_memory
    return memory_saving_gradients.gradients(ys, xs, grad_ys, checkpoints=tensors, **kwargs)
  File "/usr/lib/python2.7/memory_saving_gradients.py", line 184, in gradients
    raise Exception('no checkpoints nodes found or given as input! ')
Exception: no checkpoints nodes found or given as input! 
```

**Comment by yaroslavvb** [comment]
Here's an example of using manual checkpoints:

https://github.com/openai/gradient-checkpointing/blob/65bf6a97dd5244b5e0b5130cd2cc9d10575c224c/test/resnet_correctness_test.py#L247

You use the collection to store checkpoint tensors, and then use `strategy="collection"`

**Comment by michaelklachko** [comment]
@yaroslavvb I tried it and got exactly the same error as above. Why the above method does not work (supplying tensors list to checkpoints arg)?

**Comment by yaroslavvb** [comment]
You could use pdb to debug it, but I suggest first trying to specfy checkpoints it in the same was as done in the test -- https://github.com/openai/gradient-checkpointing/blob/65bf6a97dd5244b5e0b5130cd2cc9d10575c224c/test/resnet_correctness_test.py#L247

**Comment by devendraswamy** [comment]
How can i train the faster rcnn model with my  own dataset ?
