### ISSUE TITLE
BatchData should support components in dict or nested lists

### ISSUE THREAD

**Issue by bzamecnik** [tensorpack/tensorpack#768]
In Keras we often organize components of features/targets into dicts, which is practical when the model has many options that affect number of components and their shape.

Most Tensorpack DataFlows have no problem with that, except for BatchData which only expects flat list of components (not even nested list).

A workaround is to prepare flat list, apply BatchData and then reorganize components into the desired structure. However it's not quite nice. This should be responsibility of BatchData.

I'd be happy to implement this.

**Comment by Darthholi** [comment]
Upvote!

**Comment by ppwwyyxx** [comment]
Now most DataFlow assumes list. I feel some inconvenience with it as well. Allowing dict will be great!

**Comment by bzamecnik** [comment]
And I prepared a DataFlow that compares two others like zip, checks
recursively equality of their nested components and reports differences.
Useful regression testing to quickly see we broke anything. I'll try to
clean it up and make a PR. I wish I had it earlier today. :)

Dne čt, 17. 5. 2018 19:00 uživatel Yuxin Wu <notifications@github.com>
napsal:

**Comment by Darthholi** [comment]
So far I think it can be done in the code using:

```
    def _aggregate_batch(data_holder, use_list=False):
        if isinstance(data_holder[0], map):
            iterat_indices = data_holder[0].keys()
        else:
            size = len(data_holder[0])
            iterat_indices = range(size)
        result = []
        for k in iterat_indices:
```

...or even better having a separate function, that would give us iterator of indices to iterate over (indices for list, keys for map, anything for anything else ...)
