### ISSUE TITLE
Fast Prediction with Tensorpack

### ISSUE THREAD

**Issue by yg320** [tensorpack/tensorpack#772]
Hi!

Maybe I'm missing something here, but it seems that Tensorpack only supports feed-dict based prediction.
Is there a reason why no support exists for queue based (as well as Staging area based) prediction?

Thanks!

**Comment by ppwwyyxx** [comment]
Because tensorpack is a training interface and does not care about inference. Tensorflow has many inference techniques (serving, quantization, const folding, tensorrt, tflite,...) for different scenarios. These are probably more important than queues.

**Comment by ppwwyyxx** [comment]
That said it would surely be nice to have these features. Mark it as a possible future feature but it won't be my priority.
