### ISSUE TITLE
upload trained faster/mask rcnn model to model zoo

### ISSUE THREAD

**Issue by fangchao111** [tensorpack/tensorpack#776]
Can you upload trained models of mask/faster rcnn in model zoo?

Thank you!

R50-C4 | 64 | (600, 1024) | 280k | 33.1 | 18h on 8 V100s
-- | -- | -- | -- | -- | --
R50-C4 | 512 | (800, 1333) | 280k | 35.6 | 55h on 8 P100s
R50-C4 | 512 | (800, 1333) | 360k | 36.6 | 49h on 8 V100s
R50-FPN | 512 | (800, 1333) | 360k | 37.5 | 28h on 8 V100s
R50-C4 | 256 | (800, 1333) | 280k | 36.8/32.1 | 39h on 8 P100s
R50-C4 | 512 | (800, 1333) | 360k | 37.8/33.2 | 51h on 8 V100s
R50-FPN | 512 | (800, 1333) | 360k | 38.1/34.9 | 38h on 8 V100s
R101-C4 | 512 | (800, 1333) | 280k | 40.1/34.4 | 70h on 8 P100s
R101-C4 | 512 | (800, 1333) | 360k | 40.8/35.1 | 63h on 8 V100s

**Comment by ppwwyyxx** [comment]
Two best C4 models are uploaded already. 
I may upload a FPN one later, but I won't have time to manage every one of them..

**Comment by ppwwyyxx** [comment]
R50FPN model was uploaded.  I don't plan to upload those non-standard models. Closing this now.
