### ISSUE TITLE
How to use input_source without Trainers and Callbacks?

### ISSUE THREAD

**Issue by yijunCai** [tensorpack/tensorpack#783]
I‘ve wrote my customised DataFlow to read and process data for my tensorflow model, but I found feeding it to the graph with placeholders too slow. I tried using input_source.QueueInput() to convert my DataFlow into tensors with TF queues, but found the program got stucked after printing “Setting up the queue for CPU prefetching...".  My code looks like:
`df = MyDataFlow()    

df = dataflow.PrefetchDataZMQ(df)    

df = dataflow.BatchData(df,batch_size)   

source = input_source.QueueInput(df)   

source.setup(input_desc)   

source.reset_state()   

data = source.get_input_tensors()
`
It seems that the input_source package has something to do with the Trainer and Callbacks packages. Thus the code above cannot  run as I expected. Is there something wrong with my code? How do I use input_source package alone to build input pipeline for my tensorflow model?

**Comment by ppwwyyxx** [comment]
InputSource cannot be used alone.

 You're recommended to implement a custom trainer: http://tensorpack.readthedocs.io/tutorial/extend/trainer.html if you want to do anything substantially different from single-cost optimization.
