### ISSUE TITLE
some problem of zmq dataflow

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#787]
I read the Distributed DataFlow from [https://tensorpack.readthedocs.io/tutorial/efficient-dataflow.html](url)
I see the way to process the data on multi machines and send the data to train machine.
My test script is:
send_zmq.py
`from tensorpack import *`
`df = BatchData(dataset.Mnist('train'), 128)`
`send_dataflow_zmq(df, 'tcp://xxx:2222')`

revice_zmq.py
`from tensorpack import *`
`zmq_df = RemoteDataZMQ('tcp://0.0.0.0:2222')`
`zmq_df.reset_state()`
`zmp_data = zmq_df.get_data()`
` for data in zmp_data:`
`    print data`
 it works ok,

1. when I pass bind=True to send_dataflow_zmq ,I got the error:

`Traceback (most recent call last):`
`  File "send_zmq.py", line 4, in <module>`
`    send_dataflow_zmq(df, 'tcp://xxx:2222',bind=True)`
`  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/dataflow/remote.py", line 49, in send_dataflow_zmq`
`    socket.bind(addr)`
`  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind`
`  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc`
`zmq.error.ZMQError: Cannot assign requested address`

2. when I delete the line   zmq_df.reset_state() in revice_zmq.py, I got this
`Traceback (most recent call last):`
`  File "revice_zmq.py", line 21, in <module>`
 `   for data in zmp_data:`
`  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/dataflow/remote.py", line 128, in get_data`
`    self.cnt1 += 1 `
`AttributeError: 'RemoteDataZMQ' object has no attribute 'cnt1'`
 
I find the error because class RemoteDataZMQ don't init cnt1 in __init__ function.You may init cnt1 in __init__ or tell the user must reset_state before get_data clearly！

3. when I pass 
`Traceback (most recent call last):`
`  File "revice_data.py", line 22, in <module>`
`    for data in zmp_data:`
`  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5 py2.7.egg/tensorpack/dataflow/remote.py", line 126, in get_data`
`    dp = loads(socket.recv(copy=False))`
`  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/utils/serialize.py", line 42, in loads_pyarrow`
`    return pa.deserialize(buf)`
`  File "serialization.pxi", line 441, in pyarrow.lib.deserialize`
`  File "serialization.pxi", line 403, in pyarrow.lib.deserialize_from`
`  File "serialization.pxi", line 380, in pyarrow.lib.read_serialized`
 ` File "error.pxi", line 77, in pyarrow.lib.check_status`
`pyarrow.lib.ArrowInvalid: Old metadata version not supported`

what data is old meadata version,how should I fix it?

4.After my test ,I think this way is suitable for data dispersal of multi machines
My another problem is the train data is on only one machine and I must send data to multi distributed train machines. And different machines get the different batch train data, How should I use zmq?

**Comment by ppwwyyxx** [comment]
1. 
> when I pass bind=True to send_dataflow_zmq ,I got the error:

Then you need bind=False for the receiver side.

2.
> I find the error because class RemoteDataZMQ don't init cnt1 in init function.You may init cnt1 in init or tell the user must reset_state before get_data clearly！

It's clearly told in http://tensorpack.readthedocs.io/tutorial/dataflow.html

3. Could you describe what you did to cause such error?

4. Use `RemoteDataZMQ` with a remote ip address.

**Comment by yogurfrul** [comment]
1.I did pass bind=False to RemoteDataZMQ and the revicer holding when get_data .while the sender still got the same error

2. it works~

3. I pass format='zmq_op' to send_dataflow_zmq. I also Installed  zmq-ops in sender and revicer /usr/local/lib/python2.7/dist-packages/zmq_ops-0.1.0-py2.7.egg
how do I use zmq_ops on the receiver side?

4. I can not test it becase error 1 above

**Comment by ppwwyyxx** [comment]
1. If the error is `zmq.error.ZMQError: Cannot assign requested address`, then it's your network issue. Check your ip address is correct. Check your port is not occupied, etc.

3. The `zmq_ops` repo has an example to use it as a separate package. https://github.com/tensorpack/zmq_ops/blob/master/benchmark.py
To use it inside tensorpack, you can use [ZMQInput](http://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.ZMQInput) as the input source for the trainer.

**Comment by yogurfrul** [comment]
1.I also it's a network issue,but I don't how to fix it.
While if I use the default bind value ,the test runs ok
bind=False to send_dataflow_zmq and bind=True to RemoteDataZMQ
and I run the test succ with ipc send and bind =True

2.I run the benchmark.py send and recv ok.
pyarrow 0.9.0 do not support for deserialize the metadata version of  reviced dataflow BatchData(dataset.Mnist('train'), 128)

**Comment by ppwwyyxx** [comment]
1. And what is the address you use? I hope it's not `tcp://xxx:2222`.

2. This has nothing to do with pyarrow. As said you need `ZMQInput` as the receiver.
