### ISSUE TITLE
[Usage Question] What are the mean and std dev of expected inputs for saved models?

### ISSUE THREAD

**Issue by chrisyeh96** [tensorpack/tensorpack#789]
I'm using a ResNet-18 (v2, preact) model on a custom dataset, and I would like to use [TensorPack's model weights pre-trained on ImageNet](http://models.tensorpack.com/). I know that model weights are pretty specific to the mean and standard deviation of the inputs that they were trained on. **What are the mean and standard deviation of the inputs that the TensorPack ResNet-18 pre-trained weights expect?** I tried digging through the TensorPack source code and saw that there is some pre-processing performed on the ImageNet images, but I'm not exactly sure what is going on.

**Comment by ppwwyyxx** [comment]
The training script for that model is https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet, which imports the preprocessing at https://github.com/tensorpack/tensorpack/blob/3e65266830e2eadb924998be8e0c0cc65a7c4f8d/examples/ImageNetModels/imagenet_utils.py#L215-L230

**Comment by chrisyeh96** [comment]
Thanks for responding so quickly! Does this mean that the Tensorpack ResNet models expect inputs whose bands across the entire dataset have mean 0 and standard deviation 1?

**Comment by ppwwyyxx** [comment]
This is how the model is trained on ImageNet.
This does not imply what you're supposed to do on a different dataset. That's your decision to make. 

I would guess using the same constants I pasted above to preprocess the image is more reasonable. But such discussion is out of the scope of the project.
