### ISSUE TITLE
dump_event still only on chief worker with set_chief_only Flase

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#791]
I add GraphProfiler to callbacks list and set_chief_only=False 

GraphProfiler(dump_event=True,dump_tracing=False).set_chief_only(False)

dump_event  still work on chief worker (hvd.rank=0) When I run HorovodTrainer

**Comment by yogurfrul** [comment]
All rank would dump its graph .
I need the graph to ensure horovod only broadcast the variable at the begin of train from root_rank.
Other ranks get the grad after ring allreduce and apply it on its own and begin next step

**Comment by ppwwyyxx** [comment]
> I need the graph to ensure horovod only broadcast the variable at the begin of train from root_rank.
Other ranks get the grad after ring allreduce and apply it on its own and begin next step

This is exactly what happened.

`dump_event` dumps stuff to tensorboard. tensorboard will only be activated in the processes where `logger.set_logger_dir` get set. Maybe that's the reason? My example only set the directory for the master process, but you can set a different logger_dir for each process.

If this does not solve the problem, could you paste the log of a non-master process?

**Comment by ppwwyyxx** [comment]
You can look for "WRN logger directory was not set. Ignore TFEventWriter." in logs to see if the above is the reason.

**Comment by yogurfrul** [comment]
I set the logger dir by 
`logger.set_logger_dir(os.path.join('train_log', 'distributed-horovod',str(hvd.rank())), action='d')`

and only log.log file in the dir

**Comment by ppwwyyxx** [comment]
could you paste the log of a non-master process?

**Comment by yogurfrul** [comment]
^[[32m[0614 06:03:51 @logger.py:74]^[[0m Argv: distributed-horovod-mnist-convnet.py
^[[32m[0614 06:03:51 @fs.py:88]^[[0m ^[[5m^[[31mWRN^[[0m Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
^[[32m[0614 06:03:52 @trainers.py:346]^[[0m Horovod local rank=3
^[[32m[0614 06:03:52 @interface.py:31]^[[0m Automatically applying QueueInput on the DataFlow.
^[[32m[0614 06:03:52 @input_source.py:193]^[[0m Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
^[[32m[0614 06:03:52 @registry.py:121]^[[0m conv0 input: [None, 28, 28, 1]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m conv0 output: [None, 28, 28, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m pool0 input: [None, 28, 28, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m pool0 output: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m conv1 input: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m conv1 output: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m conv2 input: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m conv2 output: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m pool1 input: [None, 14, 14, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m pool1 output: [None, 7, 7, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m conv3 input: [None, 7, 7, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m conv3 output: [None, 7, 7, 32]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m fc0 input: [None, 7, 7, 32]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m fc0 output: [None, 512]
^[[32m[0614 06:03:52 @registry.py:121]^[[0m fc1 input: [None, 512]
^[[32m[0614 06:03:52 @registry.py:129]^[[0m fc1 output: [None, 10]
^[[32m[0614 06:03:52 @regularize.py:88]^[[0m regularize_cost() found 2 variables to regularize.
^[[32m[0614 06:03:52 @regularize.py:19]^[[0m The following tensors will be regularized: fc0/W:0, fc1/W:0
^[[32m[0614 06:03:52 @model_utils.py:63]^[[0m ^[[36mTrainable Variables:
^[[0mname       shape              dim
---------  --------------  ------

xxxx


Total #vars=12, #params=836522, size=3.19MB^[[0m
^[[32m[0614 06:03:52 @base.py:131]^[[0m ^[[5m^[[31mWRN^[[0m Callback MovingAverageSummary is chief-only, skipped.
^[[32m[0614 06:03:52 @base.py:131]^[[0m ^[[5m^[[31mWRN^[[0m Callback MergeAllSummaries_RunWithOp is chief-only, skipped.
**^[[32m[0614 06:03:52 @base.py:131]^[[0m ^[[5m^[[31mWRN^[[0m Callback TFEventWriter is chief-only, skipped.**
^[[32m[0614 06:03:52 @base.py:131]^[[0m ^[[5m^[[31mWRN^[[0m Callback JSONWriter is chief-only, skipped.
^[[32m[0614 06:03:52 @base.py:179]^[[0m Setup callbacks graph ...
^[[32m[0614 06:03:52 @base.py:197]^[[0m Creating the session ...
^[[32m[0614 06:03:58 @base.py:212]^[[0m Graph Finalized.
^[[32m[0614 06:03:58 @concurrency.py:37]^[[0m Starting EnqueueThread QueueInput/input_queue ...
^[[32m[0614 06:03:58 @graph.py:73]^[[0m Running Op horovod_broadcast/group_deps ...
^[[32m[0614 06:03:58 @common.py:774]^[[0m ^[[36mDataFlow Info:^[[0m
^[[32m[0614 06:04:16 @base.py:232]^[[0m Start Epoch 1 ...
^[[32m[0614 06:05:22 @base.py:242]^[[0m Epoch 1 (global_step 468) finished, time:1 minute 5 seconds.
^[[32m[0614 06:05:22 @base.py:232]^[[0m Start Epoch 2 ...
^[[32m[0614 06:08:16 @base.py:242]^[[0m Epoch 2 (global_step 936) finished, time:2 minutes 53 seconds.
^[[32m[0614 06:08:16 @base.py:246]^[[0m Training has finished!




I think the reason is in  **^[[32m[0614 06:03:52 @base.py:131]^[[0m ^[[5m^[[31mWRN^[[0m Callback TFEventWriter is chief-only, skipped.

**Comment by ppwwyyxx** [comment]
Oh right. I forgot that monitors are by default chief-only.
You can change that by provide `monitors=[TFEventWriter().set_chief_only(False), JSONWriter(), ScalarPrinter()]` in `TrainConfig`. Let me know if this is not the case.

I'll think about whether it's a good default or not.

**Comment by yogurfrul** [comment]
it works~
I think it't right to have a default,but the code is useless to check the chief_only of callbacks on train/base.py. 

    is_chief = True
    """
    Whether this process is the chief worker in distributed training.
    Certain callbacks will only be run by chief worker.
    """
xxx
        if not self.is_chief and cb.chief_only:
            logger.warn("Callback {} is chief-only, skipped.".format(str(cb)))
            return False
        else:
            self._callbacks.append(cb)
            return True

**Comment by ppwwyyxx** [comment]
Why?

**Comment by yogurfrul** [comment]
oh I'm confused .Never mind~
I get the events of a non-master process
I still find horovod_broadcast on tensorboard,and I choose one Session runs option ,the op disappear.
Now I can see the broadcast only run once at the variable init process
