### ISSUE TITLE
problem about run test and feature map

### ISSUE THREAD

**Issue by liuxiaowei199345** [tensorpack/tensorpack#800]
1.problem about run test
I use `tensorpack/scripts/dump-model-params.py` make already trained params to .npz. But when run `alexnet_dorefa.py --dorefa 1,2,32 --load XXX --run XX.jpg`. It encountered some problems :
```
Traceback (most recent call last):
  File "examples/DoReFa-Net/alexnet-dorefa.py", line 227, in <module>
    run_image(Model(), DictRestore(dict(np.load(args.load))), args.run)
  File "examples/DoReFa-Net/alexnet-dorefa.py", line 172, in run_image
    predictor = OfflinePredictor(pred_config)
  File "/home/XXX/workspace/tensorflow/tensorpack-master/tensorpack/predict/base.py", line 172, in __init__
    output_tensors = get_tensors_by_names(config.output_names)
  File "/home/XXX/workspace/tensorflow/tensorpack-master/tensorpack/tfutils/common.py", line 107, in get_tensors_by_names
    ret.append(G.get_tensor_by_name(varn))
  File "/home/XXX/Software/anaconda3/envs/XXX/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3766, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/XXX/Software/anaconda3/envs/XXX/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/XXX/Software/anaconda3/envs/XXX/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3632, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'output:0' refers to a Tensor which does not exist. The operation, 'output', does not exist in the graph."
```

2.How to get feature map data?
If I want to get feature map data after each ops, what should I do ?
And how to make feature map to .npz ?

**Comment by ppwwyyxx** [comment]
1. Fixed now.

2. If you want to do this during training, http://tensorpack.readthedocs.io/tutorial/faq.html#how-to-print-dump-intermediate-results-in-training
If you want to do this after training, add the names of tensors you want to dump to `OfflinePredictor`. http://tensorpack.readthedocs.io/tutorial/faq.html#how-to-print-dump-intermediate-results-in-training

**Comment by liuxiaowei199345** [comment]
Thanks. 
How to  add the names of tensors to `OfflinePredictor` ? The intermediate-results is `conv0` , `conv1` ,`bn1`, `pool1`....? How should I establish contact with them?

**Comment by liuxiaowei199345** [comment]
I use 
```python
            logits = (LinearWrap(image)
                .Conv2D('conv0', 96, 12, stride=4, padding='VALID')
                .print_tensor()  # conv0/output
                .apply(activate)
                #.......
```
got name of tensor. But I don't know that where add to ProcessTensor() .
Is it add to `OfflinePredictor`?

**Comment by ppwwyyxx** [comment]
There are `input_names` and `output_names` given to the PredictConfig, where you can define what do you want to feed to and fetch from the graph.

**Comment by liuxiaowei199345** [comment]
`ProcessTensors()` doesn't instance list names of tensor is exist or not?
Do I need use `callbacks()` in `OfflinePredictor`?

**Comment by ppwwyyxx** [comment]
> ProcessTensors() doesn't instance list names of tensor is exist or not?

I don't understand what you mean. You can find its documentation at http://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.ProcessTensors

> Do I need use callbacks() in OfflinePredictor?

As you can see from the documentation http://tensorpack.readthedocs.io/modules/predict.html, there is no such argument. Callbacks are only for training, and it is supposed to be set in `TrainConfig`.

**Comment by liuxiaowei199345** [comment]
Thanks very much.

And, I find some questions:
old:
```python
class Model(ImageNetModel):
    weight_decay = 5e-6
    weight_decay_pattern = 'fc.*/W'

    def get_logits(self, image):
        if BITW == 't':
            fw, fa, fg = get_dorefa(32, 32, 32)
            fw = ternarize
        else:
            fw, fa, fg = get_dorefa(BITW, BITA, BITG)
    #....
```

I found the accuracy to be low. So I guess there may be some problems. I add some code:
```python
class Model(ImageNetModel):
    weight_decay = 5e-6
    weight_decay_pattern = 'fc.*/W'

    def inputs(self):
        return [tf.placeholder(tf.float32, [None, 224, 224, 3], 'input'),
                tf.placeholder(tf.int32, [None], 'label')]

    def get_logits(self, image):
        if BITW == 't':
            fw, fa, fg = get_dorefa(32, 32, 32)
            fw = ternarize
        else:
            fw, fa, fg = get_dorefa(BITW, BITA, BITG)
    #...
```

The accuracy rate has changed. How about it?

**Comment by ppwwyyxx** [comment]
The accuracy should be similar to those in the readme. The code you added did nothing.

**Comment by ppwwyyxx** [comment]
Closing now as this is unrelated to the original issue. If you got accuracy that's very different from the readme, you can open an issue following the issue template so we can investigate.
