### ISSUE TITLE
StopIteration at the end of every epoch   keras+tensorpack

### ISSUE THREAD

**Issue by Michael3444** [tensorpack/tensorpack#811]
I wrote my own dataflow inherited from the RNGDataFlow, overrode the get_data() method
 def get_data(self):
        idxs = np.arange(self.size())
        self.rng.shuffle(idxs)
        for idx in idxs:
            yield [self.all_meta[idx]]
Then I uesd MapData  and PrefetchData to  augment my original data in multi-process,when I trained it,the generator stopped iteration at the end of each epoch,How do i fix my code  so that it will continue training instead of stopIteration

**Comment by Michael3444** [comment]
@ppwwyyxx  Sorry  ,maybe I did't explain it clearly,I trained my models with keras and wrote my data generator with tensorpack ,I wrote my own Dataflow inherited from the RNGDataFlow, overrode the get_data() method:
```
def get_data(self):
    idxs = np.arange(self.size())
    self.rng.shuffle(idxs)
    for idx in idxs:
        yield [self.all_meta[idx]]
```
but at the end of the first eopch,it stopped iteration,the error logs: 

> Traceback (most recent call last):
>   File "train_pose.py", line 225, in <module>
>     initial_epoch=last_epoch)
>   File "/home/lipengkun/anaconda2/envs/tf-pose-paf/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/home/lipengkun/anaconda2/envs/tf-pose-paf/lib/python3.5/site-packages/keras/engine/training.py", line 2011, in fit_generator
>     generator_output = next(output_generator)
> StopIteration

so ,I think the iterator is empty ,how do i fix my code so that at the end of the first epoch,the generator would  re-generate an iterator so that it could continued training

**Comment by ppwwyyxx** [comment]
Of course when `get_data` returns, the generator ends.
You can use `RepeatedData(dataflow, -1)` which will call `get_data` again after it returns.

**Comment by Michael3444** [comment]
OK ,Thanks a lot ,I will try that !
