### ISSUE TITLE
How to run PennTreebank example training on GPUs

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#812]
Although I pass --gpu=0,1 ,while training, I check GPU util by nvidia-smi, the gpu 0 and 1 still 0%
and no job running on it.
Why?

**Comment by ppwwyyxx** [comment]
This example is not written for multi gpu training.

**Comment by yogurfrul** [comment]
I set session_config=get_default_sess_config() to TrainConfig don't work

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/tutorial/trainer.html#multigpu-trainers

**Comment by yogurfrul** [comment]
oh  yes, 
I change the trainer to HorovodTrainer ,it works .
