### ISSUE TITLE
Error with Resize

### ISSUE THREAD

**Issue by prajwal1210** [tensorpack/tensorpack#814]
> **AttributeError: module 'tensorpack.dataflow.imgaug' has no attribute 'Resize'**

Whenever I run the Do-Re-Fa-Net code for SVHN dataset. I get this error. I use the command:
`./svhn-digit-dorefa.py --dorefa 1,1,32
`

**Comment by ppwwyyxx** [comment]
Check your logs carefully. There is probably a warning.

Next time please post issues following the issue template. In particular, include the entire logs.
