### ISSUE TITLE
input_source don't work ok with tf.contrib.tfprof.ProfileContext

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#815]
I want to use tensorflow profiler with tensorpack
so I write this code as [tensorflow guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/profiler#quick-start)

`    with tf.contrib.tfprof.ProfileContext('/tmp/train_dir') as pctx:`
`      train_loop()`

Then I got this error,it seems that the input_source make the profiler reach CUPTI subcriber limit 
`    Traceback (most recent call last):`
`      File "/usr/local/lib/python3.5/dist-packages/tensorpack-0.8.6-py3.5.egg/tensorpack/input_source/input_source.py", line 137, in run`
`        self.op.run(feed_dict=feed)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2377, in run`
`        _run_using_default_session(self, feed_dict, self.graph, session)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5215, in _run_using_default_session`
`        session.run(operation, feed_dict)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/profiler/profile_context.py", line 74, in _profiled_run`
`        fetches, feed_dict, options, run_metadata)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run`
`        run_metadata_ptr)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run`
`        feed_dict_tensor, options, run_metadata)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run`
`        run_metadata)`
`      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call`
`        raise type(e)(node_def, op, message)`
`    tensorflow.python.framework.errors_impl.UnavailableError: CUPTI subcriber limit reached.`
`    [0707 02:38:41 @input_source.py:150] EnqueueThread QueueInput/input_queue Exited.`

Then I change the code to only trace step [3,6], it works ok,and dump the trace to the profiler file.But the  train hold stuck when first epoch end,

`        with tf.contrib.tfprof.ProfileContext(logger.get_logger_dir(),trace_steps=range(3, 6), dump_steps=[6]) as pctx:`

**Comment by ppwwyyxx** [comment]
Adding this to the mnist example works fine. So please provide more details on what you did and what you observed.

**Comment by yogurfrul** [comment]
I have changed the mnist-convnet example trainer to the horovodtrainer
try 1:
add profiler in the train script as 
`    with tf.contrib.tfprof.ProfileContext(os.path.join('./train_log', str(hvd.rank())),trace_steps=range(3, 6),
                              dump_steps=[6]) as pctx:`
 `       launch_train_with_config(config, HorovodTrainer())`
it runs ok,but no profiler file generated .

try2:
add profiler in the tensorpack source tensorpack/train/base.py as
`    def main_loop(self, steps_per_epoch, starting_epoch, max_epoch):`
`        with tf.contrib.tfprof.ProfileContext(logget_logger_dir()) as pctx:`
 `           with self.sess.as_default():`
it generate profiler file but an exception 
`tensorflow.python.framework.errors_impl.UnavailableError: CUPTI subcriber limit reached.`

try3:
add profiler in the tensorpack source tensorpack/train/base.py as
`    def main_loop(self, steps_per_epoch, starting_epoch, max_epoch):`
`        with tf.contrib.tfprof.ProfileContext(logger.get_logger_dir(),trace_steps=range(3, 6), dump_steps=[6]) as pctx:`
 `           with self.sess.as_default():`

no exception found, and get the profiler file , but hold stuck when fisrt epoch end

**Comment by yogurfrul** [comment]
the profile_6 up is imcompeleted.
I change the PennTreebank example in the same way ,and try as third way
it runs ok and the profile file generated right.
so this problem may be between the QueueInput and ProfileContext

**Comment by ppwwyyxx** [comment]
Some debugging shows that `ProfileContext` is not thread safe.
Therefore it cannot be used with `QueueInput`. `QueueInput` will start a new thread to feed data into queues.
This is a tensorflow issue so there isn't much I can do.

**Comment by ppwwyyxx** [comment]
You can use alternative to `QueueInput` such as `data=TFDatasetInput(TFDatasetInput.dataflow_to_dataset(dataset_train, [tf.float32, tf.int32]))` which does not use threads.

In general I don't think ProfileContext is a good thing to use. It's implemented in a very very hacky way and that's doomed to cause trouble.

**Comment by yogurfrul** [comment]
can it  be used with StagingInput? I think yes
and How orignal tensorflow profiler prefetch data
Is there some way that I can profiler the traning process except QueueInput.

And must I change the tensorpack source code tensorpack/train/base.py to add profiler?

**Comment by ppwwyyxx** [comment]
You can use StagingInput.
I think originally they have not seriously tested such features, just like many other "fancy" features in tensorflow that does not work.
You can use GraphProfiler to profile. It works for all types of input.
You can use ProfileContext in your own code. You do not need to touch tensorpack source code.

**Comment by yogurfrul** [comment]
as try way 1: the training runs ok,but no profiler file generated .
then I try it on PennTreebank example ,it works ok.
so it's about the QueueInput ,not the tensorpack source code.
I would try TFDatasetInput

**Comment by yogurfrul** [comment]
TFDatasetInput works, and profiler runs ok.
TFDatasetInput coverts dataflow to tf.dataset and enable prefetch from disk to cpu using orignal tensorflow way？
Can I say TFDatasetInput do the same work with QueueInput just in different way by different speed.

**Comment by ppwwyyxx** [comment]
I don't know what is the "original tensorflow way".

This does not give you any prefetch. You can use `tf.data` API to add prefetch yourself, e.g.: `TFDatasetInput.dataflow_to_dataset(dataset_train, [tf.float32, tf.int32]).prefetch(100)`.

**Comment by yogurfrul** [comment]
I did it in this way:
init an _profile_context in GraphProfiler
`self._profile_context = tf.contrib.tfprof.ProfileContext(self._dir, debug=True)`
then add the run metadata of this step to the profiler
`self._profile_context.profiler.add_step(self.global_step, meta)`
finally dump the profiler on specify step of first epoch
`self._profile_context.profiler._write_profile(filename)`

it runs ok with QueueInput and dump the profiler
