### ISSUE TITLE
what is the second configuration for the performance table

### ISSUE THREAD

**Issue by MrWanter** [tensorpack/tensorpack#823]
In the Readme of faster rcnn example, for performance table, the mAP is listed as, e.g, for R50-FPN, the mAP(box/mask) : 38.2/34.9. what is second configuration, I cannot find it in the Readme file, is it the footnote: `1: Slightly different configurations`? but what does this means? Thanks!

**Comment by ppwwyyxx** [comment]
All the configurations are written in the last column. I don't quite understand what you're asking about.

**Comment by MrWanter** [comment]
Sorry, I misunderstood the table.
