### ISSUE TITLE
FPN example, how to upsample to odd sized features?

### ISSUE THREAD

**Issue by MrWanter** [tensorpack/tensorpack#824]
In the FPN faster rcnn example, to form feature piramid, the intermediate features need to be upsampled back to be compatible with larger feature, but when the larger feature has odd sized side, e.g., `1*75*50*C`, the next feature is `1*38*25*C`, but with unpooling, we get `1*76*50*C`, I'm wondering how this issue is dealt in the example implementation?

**Comment by ppwwyyxx** [comment]
Inputs are padded (in `resnet_fpn_backbone()`). This is the same as detectron.
