### ISSUE TITLE
How can I save checkpoint during an epoch

### ISSUE THREAD

**Issue by xiaoyaozzr** [tensorpack/tensorpack#825]
If the data is so big, one  epoch costs too long time. How can  I save checkpoint during an epoch instead of must waiting for one epoch end.
Thanks.

**Comment by ppwwyyxx** [comment]
Use http://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.PeriodicTrigger .

Or just set the epoch size to a smaller number..
