### ISSUE TITLE
Can we simplify the roialign to remove the avg pool part

### ISSUE THREAD

**Issue by MrWanter** [tensorpack/tensorpack#831]
The faster rcnn roi_align part cropped` 2* resolution`, then use` avg pool`: 
https://github.com/tensorpack/tensorpack/blob/17c25692fcbcb6d3235cacc3b67c3d26bf716084/examples/FasterRCNN/model_box.py#L167-L171
but in my case, the avgpool part needs to deal with the` N*proposal*C*2resolutio*2resolution` sized feature map, which caused OOM for the input size, so can we simplify this part so memory can be saved? like directly pool `resolutio*resolution` sized feature map

**Comment by ppwwyyxx** [comment]
It's up to you.

**Comment by MrWanter** [comment]
I really cant feature out why first crop `2*resolusion` then avg pool, is there reason specifically for `tf.image.crop_and_resize` ?

**Comment by ppwwyyxx** [comment]
If you're asking about whether it affects accuracy, I don't know but I think not.

To be consistent with the paper.

**Comment by MrWanter** [comment]
I see, thank you, I'll test it

**Comment by soldierofhell** [comment]
@twangnh did you finally test the accuracy? :)
