### ISSUE TITLE
Can I use Backbone model from TF.slim package?

### ISSUE THREAD

**Issue by deep-diver** [tensorpack/tensorpack#834]
Since there are lots of pre-trained models in TF.slim package, I want to make use of them.
Can I use them as a backbone model? if so, should I implement what?

Also, the pre-trained model comes with *.ckpt. Can I put *.ckpt as BACKBONE.WEIGHTS?
Thanks!

**Comment by ppwwyyxx** [comment]
You can use `.ckpt` as `BACKBONE.WEIGHTS`.
You'll need to build a graph that can correctly use the weights you load.

**Comment by ppwwyyxx** [comment]
C for Conv. I'd recommend you to read the papers listed in the README first. They have all the answers.
