### ISSUE TITLE
Custom Scalar Dashboard

### ISSUE THREAD

**Issue by PatWie** [tensorpack/tensorpack#836]
TensorBoard supports [custom scalars](
https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/custom_scalar).

This might be helpful to combine train and val costs plots. The correct place would be the inference runner, wouldn t it?

This is what it would look like:
https://github.com/tensorflow/tensorflow/pull/20902

**Comment by ppwwyyxx** [comment]
It looks like what's needed from a user is just to:
1. create a layout summary
2. call `trainer.monitors.put_summary()` somewhere (e.g. in before_train, or manually outside the training loop.

There seems to be many many options in creating a layout:  https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/custom_scalar/custom_scalar_demo.py#L60-L97. So I'm not sure if tensorpack should do it and make those decisions in step 1. But I'm not familiar with this feature, maybe those options are not important at all.

**Comment by PatWie** [comment]
The inference runner uses the prefix validation, no? Hence, the namings are clear by ScalarStats
https://github.com/tensorpack/tensorpack/blob/1554550de5322362af52b198587ee832b17f223b/examples/basics/mnist-tflayers.py#L125

These would be good candidates for the custom scalars. This would be a neat way to combine validation and training metrics in one chart without any ugly hacks.

**Comment by PatWie** [comment]
We do not need all options, just these from the PR over there:
https://github.com/tensorflow/tensorflow/pull/20902/files

**Comment by ppwwyyxx** [comment]
`ScalarStats` uses prefix, not inference runner. You can probably do this for ScalarStats automatically. But it will be hard to do this automatically for other Inferencer.
