### ISSUE TITLE
AssertionError: [nan nan nan]

### ISSUE THREAD

**Issue by saddy001** [tensorpack/tensorpack#839]
I am running the A3C-Gym example with a custom environment and get the following assertion during training of epoch 2:

```
exception calling callback for <Future at 0x7f72b87309b0 state=finished returned list>
Traceback (most recent call last):
  File "/home/saddy/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "./test.py", line 187, in cb
    assert np.all(np.isfinite(distrib)), distrib
AssertionError: [nan nan nan]
exception calling callback for <Future at 0x7f72b88a3320 state=finished returned list>
Traceback (most recent call last):
  File "/home/saddy/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "./test.py", line 187, in cb
    assert np.all(np.isfinite(distrib)), distrib
AssertionError: [nan nan nan]
```
The assert line is equal to line 170 in train-atari.py.
I am using Discrete(3) actions and the observation.shape is (84, 84, 3).
It seems that the action distribution got out of bounds. My question is, what are possible causes for this problem? Actually I don't know where to start debugging.

**Comment by ppwwyyxx** [comment]
If the original examples themselves are working, it's unlikely to be a tensorpack issue.
We don't help people debug their code and model. If you think you found a tensorpack bug, please post more details following the issue template.

My suggestion is to add some `tf.check_numerics` ops around some suspicious ops. Use smaller reward if they are dense. And use smaller learning rate.
