### ISSUE TITLE
More pre-trained Faster RCNN Model?

### ISSUE THREAD

**Issue by PacteraOliver** [tensorpack/tensorpack#840]
Hi, according to this [page](http://models.tensorpack.com/FasterRCNN)

| COCO-R101C4-MaskRCNN-Standard.npz | 196 MiB | (sha256) |
| -- | -- | -- |
| COCO-R50C4-MaskRCNN-Standard.npz | 128 MiB | (sha256)|
| COCO-R50FPN-MaskRCNN-Standard.npz | 158 MiB | (sha256)|
| ImageNet-R101-AlignPadding.npz | 158 MiB | (sha256)|
| ImageNet-R50-AlignPadding.npz | 91 MiB | (sha256)|
| ImageNet-R50-GroupNorm32-AlignPadding.npz | 88 MiB | (sha256)|

Will you provide more pretrained model such as `COCO-R101FPN` or `COCO-R152FPN`?

Thank you!

**Comment by ppwwyyxx** [comment]
No I have never trained them and have no plans to do so.

**Comment by engineer1109** [comment]
@PacteraOliver The model provided is very awful， purchase Titan or Tesla to train yourself

**Comment by ppwwyyxx** [comment]
The provided models are trained on COCO dataset and are just about as good as the official detectron models on this dataset.

**Comment by PacteraOliver** [comment]
@ppwwyyxx Have you ever considered to write a tool to transfer other pre-trained models such as [here](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) to npz model that tensorpack could use?

**Comment by ppwwyyxx** [comment]
Have no plans to do so
