### ISSUE TITLE
How to apply NMS in detect_one_image(img, model_func) of Faster RCNN

### ISSUE THREAD

**Issue by PacteraOliver** [tensorpack/tensorpack#844]
Hi,

I want to apply multi scale testing in Faster RCNN.

In this function [detect_one_image(img, model_func)](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/eval.py#L57-L90)

After `boxes, probs, labels, *masks = model_func(resized_img)`

I want to union all the boxes and probs for different scale testing results. Then I want to Apply NMS.

Any Ideas about how to apply NMS? Can we use `tf.image.non_max_suppression` ?
How to deal with the result of this function?

Did you implement a nms function for bounding box and scores?

Thank you.

**Comment by ppwwyyxx** [comment]
Sounds like you want to do something on numpy arrays. If that's the case this question is unrelated to tensorpack. 
You can implement the function with whatever tools you like, with or without tensorflow. You can use the corresponding function in tensorflow by creating a graph, a session, and run the op.
