### ISSUE TITLE
.npz model cannot work for tensorflow issue

### ISSUE THREAD

**Issue by vicdxxx** [tensorpack/tensorpack#845]
Hi guys,
    I followed instructions from https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN
    
use commad 
python .\train.py --config MODE_MASK=True MODE_FPN=False DATA.BASEDIR='G:/COCO' BACKBONE.WEIGHTS='F:/ModelZoo/Tensorflow/ImageNet-R50-AlignPadding.npz' 
    in windows10 dos window.

and I met 
Traceback (most recent call last):
  File ".\train.py", line 589, in <module>
    session_init = get_model_loader(cfg.BACKBONE.WEIGHTS) if cfg.BACKBONE.WEIGHTS else None
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\tensorpack\tfutils\sessinit.py", line 262, in get_model_loader
    return SaverRestore(filename)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\tensorpack\tfutils\sessinit.py", line 107, in __init__
    model_path = get_checkpoint_path(model_path)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\tensorpack\tfutils\varmanip.py", line 184, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: 'F:/ModelZoo/Tensorflow/ImageNet-R50-AlignPadding.npz'

It seems .npz cannot work here, do I need to convert .npz model to .ckpt model? or other way can bypass this issue?

**Comment by vicdxxx** [comment]
This problem is just caused by  windows10 dos windows cannot realize 'xxx' string, need convert to "xxx".
Solved.

**Comment by ppwwyyxx** [comment]
Sounds like it was solved.
In general, modifying the config file is more robust than setting everything from the command line. You can also add your own command line options for the config you want to change. For example `--load` can be used for `BACKBONE.WEIGHTS`.

**Comment by vicdxxx** [comment]
@ppwwyyxx 
Sure, that's a good idea. Thanks!
