### ISSUE TITLE
why we need tf.transpose(images, [0, 3, 1, 2]) ? 

### ISSUE THREAD

**Issue by lyyiangang** [tensorpack/tensorpack#849]
1. What you did:
I am trying to use [mobilenet](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.py) from slim in tersorpack, but I don't get expected result.
first, I import mobilenet and define a model like this:
```
import os
import argparse
import tensorflow as tf
from tensorpack import *
from tensorpack.tfutils.summary import *
from nets import mobilenet_v1

class MobileNetModel(ModelDesc):
    def build_graph(self, images, label):
            depth_multiplier = 1.0  # cadidate values: 0.25, 0.5, 0.75, 1.0
            num_classes = self.classnum
            is_training = get_current_tower_context().is_training
            if is_training:
                tf.summary.image("train_image", images, 10)
            images = tf.transpose(images, [0, 3, 1, 2]) # error occurs if remove this line           

            with tf.contrib.slim.arg_scope(mobilenet_v1.mobilenet_v1_arg_scope(is_training = is_training)):
                logits, _ = mobilenet_v1.mobilenet_v1(
                    images,
                    is_training = is_training,
                    depth_multiplier = depth_multiplier,
                    num_classes=num_classes)
                
            cost = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=label)
            cost = tf.reduce_mean(cost, name='cross_entropy_loss')

            correct = tf.to_float(tf.nn.in_top_k(logits, label, 1), name='correct')
            # monitor training error
            add_moving_summary(tf.reduce_mean(correct, name='accuracy'))

            # weight decay on all W of fc layers
            wd_cost = regularize_cost('fc.*/W', l2_regularizer(4e-4), name='regularize_loss')
            add_moving_summary(cost, wd_cost)

            add_param_summary(('.*/W', ['histogram']))   # monitor W
            return tf.add_n([cost, wd_cost], name='cost')
```
If I don't add  ```images = tf.transpose(images, [0, 3, 1, 2])```, I will get memory exhausted error. this behavior is strange. [mobilenet_v1.mobilenet_v1](https://github.com/tensorflow/models/blob/02a9969e94feb51966f9bacddc1836d811f8ce69/research/slim/nets/mobilenet_v1.py#L321) accepts input images with format [batch_size, height, width, channels], 
4. Your environment:
  + Operation system: Windows 10
  + Python version: 3.6.1
  + TF version: 1.8.0
  + Tensorpack version: 0.8.6

Thanks

**Comment by ppwwyyxx** [comment]
How is this issue related to tensorpack? It sounds like you just don't have enough memory.

**Comment by ppwwyyxx** [comment]
The input occupy the same amount of memory, but the computation is different and therefore will need different amount of memory.

Because it's usually faster this way.

**Comment by lyyiangang** [comment]
It's my fault rather than tensorpack's. Close this issue.
