### ISSUE TITLE
The ''steps'' in DeepQNetwork

### ISSUE THREAD

**Issue by silentobservers** [tensorpack/tensorpack#852]
Hi
I run the DQN code and find that it need only about 3.5 million ''global_steps'' to get 300+ mean scores.
In paper, they trained for a total of 50 million frames to get a final scores.
I am not sure about the relationship between ''steps'' and frames.
What does a ''step'' represent? 4 frames? Or something else?

**Comment by ppwwyyxx** [comment]
Each step is a sgd step on a batch of training data.
The relationship between this and frames is answered in the readme already.

**Comment by silentobservers** [comment]
Oh, I see
Thanks for your patience.
