### ISSUE TITLE
StagingInput only show once when apply_default_prefetch to multi gpus

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#856]
I use SyncMultiGPUTrainerReplicated on 8 GPUs
I see apply_default_prefetch  enable StagingInput ,but only saying Put 1 element into StagingArea once,
I want to check if all gpus get prefetch ,then I get the lines in source code:
```
 if towers is not None:
            log_deprecated("StagingInput(towers=)", "Devices are handled automatically.", "2018-03-31")

```
But I do not find where  all device are handled

**Comment by ppwwyyxx** [comment]
It was handled because `get_input_tensors` will be called on each device, 8 times in total.
