### ISSUE TITLE
'New TRAINABLE_VARIABLES shouldn't be created in InferenceTower'

### ISSUE THREAD

**Issue by taneslle** [tensorpack/tensorpack#859]
I define a function using `@layer_register` and used in `def get_logits` in the model with LinearWrap, but it would raise the error:

> AssertionError: New TRAINABLE_VARIABLES shouldn't be created in InferenceTower: InferenceTower/transfer_conv1/Variable:0, InferenceTower/transfer_conv1/Variable_1:0, InferenceTower/transfer_conv2/Variable:0, InferenceTower/transfer_conv2/Variable_1:0,

I did the same thing before, but it didn't went wrong, is the problem comes from my code or there has been something new updated in tensorpack?

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/tutorial/trainer.html#tower-trainer

If you can't figure out what's wrong after reading the above tutorial, post your layer implementation.

**Comment by taneslle** [comment]
@ppwwyyxx Here's the layer implementation
```
def InstanceNorm(net, train=True):
    batch, rows, cols, channels = [i.value for i in net.get_shape()]
    var_shape = [channels]
    mu, sigma_sq = tf.nn.moments(net, [1,2], keep_dims=True)
    shift = tf.Variable(tf.zeros(var_shape))
    scale = tf.Variable(tf.ones(var_shape))
    epsilon = 1e-3
    normalized = (net-mu)/(sigma_sq + epsilon)**(.5)
    return scale * normalized + shift
@layer_register()
def conv_layer(net, filters, kernel_size, strides, relu=True):
    net = Conv2D('conv', net, filters = filters, kernel_size = kernel_size, strides = strides)
    net = InstanceNorm(net)
    if relu:
        net = tf.nn.relu(net)
    return net
```
```
class Transform(ModelDesc):
    def __init__(self, data_format='NHWC'):
        pass
    def get_inputs(self):
        pass
    def get_logits(self, image):
        logits = (LinearWrap(image)
                     .conv_layer('transfer_conv1', filters=32, kernel_size=9, strides=1)
                     .conv_layer('transfer_conv2', 64)
                     .conv_layer('transfer_conv3', 128)
```
I was writing a style transfer model, `get_logits` used for transform input image to another style, and I also defined a vgg model in `class Transform` to extract features of styled_image and transformed_image.
I assume the problem is from the variables defined in `InstanceNorm`, but I can't see why.

**Comment by ppwwyyxx** [comment]
The link above explicitly said do not use `tf.Variable`

**Comment by taneslle** [comment]
@ppwwyyxx So sorry I didn't notice that when readling the link, thanks a lot
