### ISSUE TITLE
Run Inference after training

### ISSUE THREAD

**Issue by minhson** [tensorpack/tensorpack#863]
Hello!
I am sorry if it is unrelated to Tensorpack.
I runned the ResNet on Cifar10 dataset with Trained Ternary Quantization.
Now i dont know how to run Inference on the saved checkpoint after training.
I have already read "**Don’t Use Training Metagraph for Inference**" in Tensorpack documentation. 
However, i still dont know how to use this one as below exactly:
```
a, b = tf.placeholder(...), tf.placeholder(...)
with TowerContext('', is_training=False):
      model.build_graph(a, b)
```
Could you guide me to do that?
Thanks you in advance!

**Comment by ppwwyyxx** [comment]
There is an inference function in the TTQ example code already:
https://github.com/tensorpack/tensorpack/blob/17955e8955284d9f91f079dd515ebf1b1a29ec9b/examples/DoReFa-Net/alexnet-dorefa.py#L169-L193

**Comment by minhson** [comment]
Thanks you very much! 
But as i know, the trained model that is saved in checkpoint doesn’t have quantized weight.
So if i want to run Inference on quantized weight model, i have to change it manually?
If i have to do that, how can i do that?
Thanks you!

**Comment by ppwwyyxx** [comment]
1. quantize the saved weights by running fw() on them, as mentioned in https://github.com/tensorpack/tensorpack/issues/573
2. change the model so it does not run fw() on the weights.

1. and 2. cancel each other so there is actually no point doing so.

**Comment by minhson** [comment]
How can i change `meta = dataset.ILSVRCMeta()` `words = meta.get_synset_words_1000()` to Cifar10 dataset. Because there is no that kind of function in dataflow.dataset.Cifar10.

Thanks you!

**Comment by ppwwyyxx** [comment]
If you're asking about what each class means in cifar10, that's not a feature tensorpack provided, although it will make sense to add it. Now please figure that out yourself.

**Comment by minhson** [comment]
Thanks you!
I have just figured it out!

**Comment by minhson** [comment]
Hi!
Can i have 2 **remap_variables()** in code. Because i have 2 quantization function (one is normal TTQ, another is to change the weight again).
Thanks you!

**Comment by ppwwyyxx** [comment]
You can. And you probably don't want to nest them.

**Comment by minhson** [comment]
Hi!
How can i print value of weight variable during Inference. 
Thanks you!

**Comment by ppwwyyxx** [comment]
Use https://www.tensorflow.org/api_docs/python/tf/train/NewCheckpointReader to read your checkpoint.
Or with tensorpack predictor, add the name of variables to `output_names`.
Or use tf.Print.

**Comment by minhson** [comment]
Hi!
I am sorry if i asked some questions which isn't related to Tensorpack.
Could you show me how to change the value of variable individually?
For example: i only want to change some weights in a variable with shape = (3, 3, 16, 16)
Thanks you very much!

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.varmanip.load_chkpt_vars
https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.varmanip.save_chkpt_vars

**Comment by minhson** [comment]
Hi!
When i try to run `print((sess.run(w)))`, i got the error as below:
`FailedPreconditionError (see above for traceback): Attempting to use uninitialized value res1.0/conv1/Wn
	 [[Node: res1.0/conv1/Wn/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](res1.0/conv1/Wn)]]
	 [[Node: mul_4/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_49_mul_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

I tried to initialize the variables: `sess.run(tf.initialize_variables([v for v in tf.all_variables()]))` but i still get that error.
Thanks you!

**Comment by brisker** [comment]
@ppwwyyxx 
after training and getting the quantized model, how to print all the weights values of a specific layer, given the quantized model?

**Comment by ppwwyyxx** [comment]
The model is a standard TF checkpoint so you can read it with `tf.train.NewCheckpointReader`, or use https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.varmanip.load_chkpt_vars.

After loading a model you can refer to numpy documentation on how to save it into numpy format.

**Comment by brisker** [comment]
@ppwwyyxx 
I want to modify dorefa-net, but  I met a problem on how to define a learned variable which is like : `[alpha, a_1*alpha,a_2*alpha,...,a_k*alpha]`, in which `alpha`  and` a_1 ~a_k` are all learned numbers in this variable? Is this kind of variable supported in tensorpack?

**Comment by ppwwyyxx** [comment]
This is a tensorflow question and not related to tensorpack.

**Comment by minhson** [comment]
Hi!
How can i see the graph of Inference only in Tensorboard?
Thanks you!

**Comment by ppwwyyxx** [comment]
Build the graph yourself (by calling build_graph, for example) in inference mode only.
https://tensorpack.readthedocs.io/tutorial/inference.html
Then follow tensorflow documentation on how to use tensorboard.

**Comment by brisker** [comment]
@ppwwyyxx 
in tensorpack , how to print  the values of  a specific tensor?
in standard tensorflow, it is like this:
```
with tf.Session() as sess:     
           print(sess.run(product))
           print (product.eval())
```
or
`sess.run(tf.Print(.....,[....]))`
but in tensorpack, I can not find where the current session is.

**Comment by minhson** [comment]
Hi!
How can i resume training after interrupted it?
Thanks you!

**Comment by ppwwyyxx** [comment]
@brisker  if you mean during training: https://tensorpack.readthedocs.io/tutorial/faq.html#how-to-print-dump-intermediate-results-in-training

@minhson https://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model

**Comment by brisker** [comment]
@ppwwyyxx 
did you mean directly insert the following code into the training sciprt?
 `ProcessTensors(['tensor1', 'tensor2'], lambda tensor1, tensor2: print(tensor1, tensor2, tensor1 + tensor2))`

**Comment by ppwwyyxx** [comment]
It's a callback and you can read the relevant tutorials on how to use it: https://tensorpack.readthedocs.io/tutorial/callback.html

**Comment by brisker** [comment]
@ppwwyyxx 
Given this custom layer:
```
@layer_register()
def CustomOp(x):
   ........
```
and x is the activations between convolutional layers. But if I print the shape of x, the results are usually
something like :(none, 64,56,56) , which means the first dimension--batch_size dimension is unknown. But in my code, I need to reshape x to dimension[-1,1] and do other related operations. So if total_batch_size is 256, and I am using 8 gpus, is this "none" 256 or 256/8=32?

**Comment by ppwwyyxx** [comment]
The answer will be in your code which I don't know. If it's the examples then it should be 32.

**Comment by brisker** [comment]
@ppwwyyxx 
after changing that to 32, this error happens:
```
2018-09-18 16:50:16.397043: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: FIFOQueue '_1_DataParallelInferenceRunner/QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: DataParallelInferenceRunner/QueueInput/input_deque_7 = QueueDequeueV2[component_types=[DT_UINT8, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](DataParallelInferenceRunner/QueueInput/input_queue)]]
```

**Comment by ppwwyyxx** [comment]
Please post any problems following the issue template.

**Comment by brisker** [comment]
@ppwwyyxx 
if I want to create a variable with L2-regularizer, but I want to let the weight_decay to decreases over global_steps:

```
new_v = tf.get_variable(
                'new_v', [1,1], tf.float32,
                initializer=new_v_init,
                trainable=True)
                regularizer=tf.contrib.layers.l2_regularizer(weight_decay))
```
Is this supported in tensorpack?

**Comment by brisker** [comment]
@ppwwyyxx 
does the callbacks.DumpTensors() only support dump the tensors with names? 
what if a intermmediate variable?
suppose `a=b*2`, and I want to dump the 'a' variable into npz file, but a has no names. How to dump it into npz file?

**Comment by ppwwyyxx** [comment]
Every tensor has a name.
You can see the name of a tensor by `print(a)`. Or you can give it a new name by `a = tf.identity(a, name='name')`.

**Comment by brisker** [comment]
@ppwwyyxx 
how to save dump the tensors into npz file every 100 iters?
currently, directly writing callbacks= [DumpTensors(*****)] will save the tensors every iteration, which is too much regarding to the disk storage. How to save it every 100 or 1000 iters?

**Comment by ppwwyyxx** [comment]
PeriodicCallback

**Comment by brisker** [comment]
@ppwwyyxx 
if using PeriodicCallback, will still the tensors of a total epoch be saved to disk? Can I save the tensors of only 10 iters ?

**Comment by brisker** [comment]
@ppwwyyxx 
what I need to do is get the current global_step by `tf.train.get_or_create_global_step` and manipulate the graph variables according to the current global_steps., for example, 
```
if global_step==100, 
variable_1= variable_1 * 2, 
if global_step==200, 
variable_1=variable_1 + variable_2
```, etc. **But how to get the exact value of global_step in the code, and use this value instantly?**

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.get_global_step_var if you want to use it in the graph and https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.get_global_step_value if you want to use it in python.

**Comment by brisker** [comment]
@ppwwyyxx 
I am using tensorpack-0.8.6, and when I run global_step = get_global_step_value(), the code gives me an error:
```
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.6-py2.7.egg/tensorpack/tfutils/common.py", line 76, in get_global_step_value
    get_global_step_var())
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 58, in global_step
    return int(sess.run(global_step_tensor))
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by ppwwyyxx** [comment]
You cannot use "value" of tensor in a layer. Inside a layer you're defining the graph therefore you have to use symbolic tensor. When you define the graph there is no actual value of global step at all.

**Comment by brisker** [comment]
@ppwwyyxx 
so given an imagenet-resnet training task, here :https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py
, in this python script, where can I get the global_step_value, and feed this value as a parameter to the definition of a layer definition , for example ,feed it as a parameter of this function:https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/resnet_model.py#L39

**Comment by ppwwyyxx** [comment]
You cannot use `get_global_step_value` when you define a graph because the training has not started and there is no value. You can only use `get_global_step_var`

**Comment by ppwwyyxx** [comment]
Yes.
Also you cannot use `if step == 100` in graph definition because when you define the graph, there is no value and the comparison is impossible. You need to use `tf.cond` and other related functions.
I recommend you to read some tutorials about the concept of tensorflow graph.

**Comment by brisker** [comment]
@ppwwyyxx 
thanks for your advice.
Actually, I want to do this:
after **every 2 epoches**, I add my newly defined operation on one layer. So in the 1~2 epoch, only the first layer is added this operation, in the 3~4 epoch, the first and the second layer is added this operation. etc. until all the layers are added this operation. So I need to include the global_step value into the layers's definition (for example resnet). So did you have any advice on how to use this global_step_var tensor?

**Comment by brisker** [comment]
@ppwwyyxx 
sorry. Thanks for your patience.

**Comment by brisker** [comment]
@ppwwyyxx 
I have pulled a new issue about this problem , related to tensorpack.  https://github.com/tensorpack/tensorpack/issues/974

**Comment by minhson** [comment]
hello, what is the difference between OfflinePredictor and SimpleDatasetPredictor, because when i run inference on Imagenet with these functions, it give me different result.

**Comment by ppwwyyxx** [comment]
There is no difference. They will give you the same result under the same inputs provided if your model is deterministic.

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/_modules/tensorpack/predict/dataset.html#SimpleDatasetPredictor

If you can't figure out, please post an issue following the issue template with a reproducible example.
