### ISSUE TITLE
[Faster RCNN]SyncMultiGPUTrainerReplicated:8 GPU training much faster than 1 GPU?

### ISSUE THREAD

**Issue by meteortwinkle** [tensorpack/tensorpack#864]
1. What did:
Training command:
CUDA_VISIBLE_DEVICES='0' python /mydata/frcnn_train/tensorpack/examples/FasterRCNN/train.py --load /data_one/data/FasterRCNN/COCO-R50C4-MaskRCNN-Standard.npz --config MODE_MASK=True MODE_FPN=False  DATA.BASEDIR=/data_one/data/COCO/2017/ DATA.VAL='val2017' 

CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7' python /mydata/frcnn_train/tensorpack/examples/FasterRCNN/train.py --load /data_one/data/FasterRCNN/COCO-R50C4-MaskRCNN-Standard.npz --config MODE_MASK=True MODE_FPN=False  DATA.BASEDIR=/data_one/data/COCO/2017/ DATA.VAL='val2017' 

2、What observed：
epoch | step | horovod 1-1| multi-gpu 1-1| multi-gpu 1-8 | horovod 1-8
0 | 0 | 5 minutes 53 seconds | 6 minutes 5 seconds | 6 minutes 2 seconds | 14 minutes 38 seconds
1 | 500 | 4 minutes 32 seconds | 4 minutes 20 seconds | 2 minutes 42 seconds | 11 minutes 26 seconds
2 | 1000 | 4 minutes 26 seconds | 4 minutes 18 seconds | 2 minutes 19 seconds | 9 minutes 46 seconds
3 | 1500 | 4 minutes 4 seconds | 4 minutes 14 seconds | 2 minutes 3 seconds | 8 minutes 39 seconds
4 | 2000 | 3 minutes 57 seconds | 3 minutes 53 seconds | 1 minute 48 seconds | 7 minutes 40 seconds
5 | 2500 | 3 minutes 38 seconds | 3 minutes 46 seconds | 1 minute 49 seconds | 6 minutes 28 seconds
6 | 3000 | 3 minutes 42 seconds | 3 minutes 41 seconds | 1 minute 36 seconds | 6 minutes 15 seconds
7 | 3500 | 3 minutes 38 seconds | 3 minutes 32 seconds | 1 minute 38 seconds | 5 minutes 39 seconds
8 | 4000 | 3 minutes 32 seconds | 3 minutes 30 seconds | 1 minute 35 seconds | 5 minutes 12 seconds
9 | 4500 | 3 minutes 33 seconds | 3 minutes 36 seconds | 1 minute 29 seconds | 5 minutes 16 seconds
10 | 5000 | 3 minutes 28 seconds | 3 minutes 26 seconds | 1 minute 29 seconds | 5 minutes 19 seconds
11 | 5500 | 3 minutes 32 seconds | 3 minutes 22 seconds | 1 minute 30 seconds | 4 minutes 45 seconds
12 | 6000 | 3 minutes 29 seconds | 3 minutes 21 seconds | 1 minute 29 seconds | 4 minutes 46 seconds
13 | 6500 | 3 minutes 24 seconds | 3 minutes 25 seconds | 1 minute 26 seconds | 4 minutes 39 seconds
14 | 7000 | 3 minutes 25 seconds | 3 minutes 26 seconds | 1 minute 27 seconds | 4 minutes 40 seconds
15 | 7500 | 3 minutes 31 seconds | 3 minutes 22 seconds | 1 minute 28 seconds | 4 minutes 39 seconds
16 | 8000 | 3 minutes 22 seconds | 3 minutes 25 seconds | 1 minute 26 seconds | 4 minutes 35 seconds
17 | 8500 | 3 minutes 24 seconds | 3 minutes 25 seconds | 1 minute 28 seconds | 4 minutes 23 seconds
18 | 9000 | 3 minutes 21 seconds | 3 minutes 25 seconds | 1 minute 26 seconds | 4 minutes 27 seconds
19 | 9500 | 3 minutes 21 seconds | 3 minutes 25 seconds | 1 minute 27 seconds | 4 minutes 34 seconds
20 | 10000 | 3 minutes 25 seconds | 3 minutes 24 seconds | 1 minute 27 seconds | 4 minutes 24 seconds
21 | 10500 | 3 minutes 20 seconds | 3 minutes 25 seconds | 1 minute 24 seconds | 4 minutes 25 seconds
22 | 11000 | 3 minutes 22 seconds | 3 minutes 20 seconds | 1 minute 26 seconds | 4 minutes 15 seconds
23 | 11500 | 3 minutes 21 seconds | 3 minutes 20 seconds | 1 minute 26 seconds | 4 minutes 20 seconds
24 | 12000 | 3 minutes 20 seconds | 3 minutes 19 seconds | 1 minute 26 seconds | 4 minutes 16 seconds
25 | 12500 | 3 minutes 23 seconds | 3 minutes 26 seconds | 1 minute 26 seconds | 4 minutes 18 seconds
26 | 13000 | 3 minutes 21 seconds | 3 minutes 19 seconds | 1 minute 25 seconds | 4 minutes 19 seconds
27 | 13500 | 3 minutes 19 seconds | 3 minutes 22 seconds | 1 minute 23 seconds | 4 minutes 14 seconds
28 | 14000 | 3 minutes 17 seconds | 3 minutes 23 seconds | 1 minute 23 seconds | 4 minutes 16 seconds
29 | 14500 | 3 minutes 18 seconds | 3 minutes 23 seconds | 1 minute 24 seconds | 4 minutes 15 seconds
30 | 15000 | 3 minutes 16 seconds | 3 minutes 22 seconds | 1 minute 25 seconds | 4 minutes 10 seconds
31 | 15500 | 3 minutes 21 seconds | 3 minutes 23 seconds | 1 minute 22 seconds | 4 minutes 11 seconds
32 | 16000 | 3 minutes 16 seconds | 3 minutes 22 seconds | 1 minute 22 seconds | 4 minutes 14 seconds
33 | 16500 | 3 minutes 16 seconds | 3 minutes 18 seconds | 1 minute 23 seconds | 4 minutes 10 seconds
34 | 17000 | 3 minutes 19 seconds | 3 minutes 20 seconds | 1 minute 22 seconds | 4 minutes 11 seconds
35 | 17500 | 3 minutes 19 seconds | 3 minutes 18 seconds | 1 minute 23 seconds | 4 minutes 6 seconds
36 | 18000 | 3 minutes 20 seconds | 3 minutes 17 seconds | 1 minute 24 seconds | 4 minutes 8 seconds
37 | 18500 | 3 minutes 20 seconds | 3 minutes 21 seconds | 1 minute 23 seconds | 4 minutes 12 seconds
38 | 19000 | 3 minutes 21 seconds | 3 minutes 24 seconds | 1 minute 22 seconds | 4 minutes 13 seconds
39 | 19500 | 3 minutes 18 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 9 seconds
40 | 20000 | 3 minutes 18 seconds | 3 minutes 21 seconds | 1 minute 22 seconds | 4 minutes 13 seconds
41 | 20500 | 3 minutes 21 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 9 seconds
42 | 21000 | 3 minutes 19 seconds | 3 minutes 18 seconds | 1 minute 23 seconds | 4 minutes 12 seconds
43 | 21500 | 3 minutes 20 seconds | 3 minutes 21 seconds | 1 minute 23 seconds | 4 minutes 15 seconds
44 | 22000 | 3 minutes 20 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 12 seconds
45 | 22500 | 3 minutes 20 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
46 | 23000 | 3 minutes 22 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 12 seconds
47 | 23500 | 3 minutes 17 seconds | 3 minutes 19 seconds | 1 minute 22 seconds | 4 minutes 11 seconds
48 | 24000 | 3 minutes 19 seconds | 3 minutes 19 seconds | 1 minute 22 seconds | 4 minutes 8 seconds
49 | 24500 | 3 minutes 20 seconds | 3 minutes 19 seconds | 1 minute 24 seconds | 4 minutes 7 seconds
50 | 25000 | 3 minutes 15 seconds | 3 minutes 21 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
51 | 25500 | 3 minutes 18 seconds | 3 minutes 20 seconds | 1 minute 22 seconds | 4 minutes 7 seconds
52 | 26000 | 3 minutes 20 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
53 | 26500 | 3 minutes 19 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 20 seconds
54 | 27000 | 3 minutes 19 seconds | 3 minutes 22 seconds | 1 minute 24 seconds | 4 minutes 11 seconds
55 | 27500 | 3 minutes 17 seconds | 3 minutes 20 seconds | 1 minute 22 seconds | 4 minutes 9 seconds
56 | 28000 | 3 minutes 17 seconds | 3 minutes 16 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
57 | 28500 | 3 minutes 19 seconds | 3 minutes 18 seconds | 1 minute 21 seconds | 4 minutes 9 seconds
58 | 29000 | 3 minutes 21 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 10 seconds
59 | 29500 | 3 minutes 20 seconds | 3 minutes 22 seconds | 1 minute 22 seconds | 4 minutes 9 seconds
60 | 30000 | 3 minutes 23 seconds | 3 minutes 20 seconds | 1 minute 23 seconds | 4 minutes 7 seconds
61 | 30500 | 3 minutes 16 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 11 seconds
62 | 31000 | 3 minutes 17 seconds | 3 minutes 19 seconds | 1 minute 22 seconds | 4 minutes 6 seconds
63 | 31500 | 3 minutes 22 seconds | 3 minutes 19 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
64 | 32000 | 3 minutes 16 seconds | 3 minutes 22 seconds | 1 minute 23 seconds | 4 minutes 7 seconds
65 | 32500 | 3 minutes 17 seconds | 3 minutes 20 seconds | 1 minute 23 seconds | 4 minutes 9 seconds
66 | 33000 | 3 minutes 17 seconds | 3 minutes 21 seconds | 1 minute 22 seconds | 4 minutes 7 seconds
67 | 33500 | 3 minutes 16 seconds | 3 minutes 22 seconds | 1 minute 21 seconds | 4 minutes 8 seconds
68 | 34000 | 3 minutes 18 seconds | 3 minutes 20 seconds | 1 minute 23 seconds | 4 minutes 7 seconds
69 | 34500 | 3 minutes 18 seconds | 3 minutes 18 seconds | 1 minute 23 seconds | 4 minutes 5 seconds
70 | 35000 | 3 minutes 17 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 6 seconds
71 | 35500 | 3 minutes 19 seconds | 3 minutes 18 seconds | 1 minute 22 seconds | 4 minutes 8 seconds
72 | 36000 | 3 minutes 20 seconds | 3 minutes 17 seconds | 1 minute 21 seconds | 4 minutes 7 seconds
73 | 36500 | 3 minutes 17 seconds | 3 minutes 18 seconds | 1 minute 21 seconds | 4 minutes 12 seconds
74 | 37000 | 3 minutes 21 seconds | 3 minutes 20 seconds | 1 minute 21 seconds | 4 minutes 7 seconds

3. What  expected：
Why  was the training  so fast on 8 GPUs，even much faster than on 1 GPU？
And, I have also tried the other backbone（ex. default）, it showed that the model trained faster on  2 GPUs(or more)  than on 1 GPU.

4、Training Enviroment:
V100*8
tf:1.8
python:3.5
tensorpack:0.8.6

**Comment by ppwwyyxx** [comment]
Your third column is way too fast. I believe you've made mistakes in your code or setup or command and it's actually doing something other than you think.

**Comment by ppwwyyxx** [comment]
As a reference, when trained from scratch with standard settings, the time for the first several epochs on 8 V100s should be: 17min, 9min, 7min, 6min, 5min, for the same R50C4 model.

**Comment by ppwwyyxx** [comment]
I run some tests with today's master code and `--config MODE_MASK=True MODE_FPN=True` on 1 & 8 V100s, with `export TF_CUDNN_USE_AUTOTUNE=0` so the speed is faster and more stable at the beginning.

Starting from the 2nd epoch, 1 V100 takes 2min29s per epoch and 8 V100s take 2min51s per epoch.
