### ISSUE TITLE
[proposal] DataFlow design

### ISSUE THREAD

**Issue by PatWie** [tensorpack/tensorpack#869]
I propose to change the design of the dataflow to be more concise when using the python idiomatic variant of:

```python
class MyFlow(DataFlow):
   def __init__(self, ...):
   def __iter__(self, ...):
   def __len__(self, ....): 
```

This would make the code somewhat more consistent to other python objects:

```python
class SomeData(object):
  def __init__(self, start, len=10):
    super(SomeData, self).__init__()
    self.start = start
    self.len = len

  def __len__(self):
    return self.len

  def __iter__(self):
    for i in range(self.start, self.start + self.len):
      yield [i]


class AddOne(object):
  """docstring for AddOne"""

  def __init__(self, other_ds):
    super(AddOne, self).__init__()
    self.other_ds = other_ds

  def __len__(self):
    return len(self.other_ds)

  def __iter__(self):
    for i in self.other_ds:
      yield [i[0] + 1]


ds = SomeData(2, 3)
ds = AddOne(ds)
for dp in ds:
  print(dp)
```

In fact, all `dataflow.*`  objects are just glorified [container types](https://docs.python.org/3/reference/datamodel.html#emulating-container-types) (ok most of them). So why not using the python terminology then? To keep backward compatibility, the `get_data()` and `size()` can wrap the `__iter__` and `__len__`. I would advise against using `__next__` to not bloating the code.

I could do a pass and apply the changes accordingly, but I am not eager to open yet another PR -- and even more so when not discussed beforehand.

Maybe even `__str__` can take over the implementation of `PrintData`. I see currently no usage of PrintData outside debugging.

```python
ds = SomeData(2, 3)
print(ds)
```

seems a better fit and more descriptive than

```python
ds = SomeData(2, 3)
ds = PrintData(ds)
next(ds.get_data())
```

The only problem I can see is when using `PrintData` at multiple places. But again, `PrintData` shouldn't be deprecated. Instead `__str__` can be an additional feature. Or even better, `print(ds)` can print the entire dataflow information of all stacked dataflow mappings.

**Comment by ppwwyyxx** [comment]
`__iter__` and `__len__` sounds good!

For compatibility, we need to consider 

1. calling old code with new method
2. calling new code with old method.

Having `get_data` wrap `__iter__` would only solve 2. Having them wrap each other sound weird.

**Comment by PatWie** [comment]
I guess overriden `get_data` in the baseclass is sufficient:

1. base-class will take care of `get_data` and correctly forward to `__iter__`
2. `__iter__` will be called and everything is ok.

**Comment by PatWie** [comment]
If refactoring the dataflow is ok, there are some other aspects I would like to discuss or even rebel against:

- `reset_state` seems to be unnecessary long. Why not simply `reset`? There is no ambiguity but a high chance for typos when your mind is already pre-paring the code line.
- There should be a consistent naming: Currently, we have: `dp` for data point (which is ok) and we have `df` and `ds` for data-flow (I guess the latter is data-stream?). If would do another pass and just rename `ds` to `df`.

And the last point (not this PR) would be a guarantee to sample each data-point per epoch. As far as I understand, `Prefetch<someSuffix>` allows me to hog the entire CPU power and pre-process data. But having 12 worker processes gives me a [really high chance](https://en.wikipedia.org/wiki/Birthday_problem) to miss some examples in one epoch when each worker shuffles data.

**Comment by ppwwyyxx** [comment]
> I guess overwrite get_data in the base class is sufficient:

This does not solve the case to call old code (user-writter dataflow) with new method (__iter__).

**Comment by PatWie** [comment]
Then the only way is to use get_data() and just add __iter__(). Certainly, we do not want to do call reflection magic during pre-fetching. What about introducing a "(RNG)Dataflow_v2" class (similar to what TensorFlow is doing as a workaround to not break semver promises eg. concat_v2).

**Comment by ppwwyyxx** [comment]
I do hope nothing breaks.. I want to learn if there are any magic alternatives, before adopting a breaking change and worrying about version numbers..

**Comment by PatWie** [comment]
With the latest commit the following works:

```python
from tensorpack import *

class SomeOldDf(DataFlow):
    """docstring for SomeOldDf"""

    def __init__(self):
        super(SomeOldDf, self).__init__()

    def size(self):
        return 2

    def get_data(self):
        for dp in [1, 2]:
            yield [dp]


class SomeNewDf(DataFlow):
    """docstring for SomeNewDf"""

    def __init__(self):
        super(SomeNewDf, self).__init__()

    def __len__(self):
        return 2

    def __iter__(self):
        for dp in [1, 2]:
            yield [dp]


ds = SomeOldDf()
ds = BatchData(ds, 2)
print(next(ds.__iter__()))
print(next(ds.__iter__()))
print(ds.size())
print(len(ds))

ds = SomeOldDf()
ds = BatchData(ds, 2)
print(next(ds.get_data()))
print(next(ds.get_data()))
print(ds.size())
print(len(ds))

ds = SomeNewDf()
ds = BatchData(ds, 2)
print(next(ds.__iter__()))
print(next(ds.__iter__()))
print(ds.size())
print(len(ds))

ds = SomeNewDf()
ds = BatchData(ds, 2)
print(next(ds.get_data()))
print(next(ds.get_data()))
print(ds.size())
print(len(ds))
```

**Comment by ppwwyyxx** [comment]
Something like this would be cleaner:
```python
import six

class MyMeta(type):
    def __new__(meta, name, bases, dct):
        print("New class", name)
        if '__iter__' not in dct:
            print("Rename!")
            dct['__iter__'] = dct.pop('get_data')
        return super(MyMeta, meta).__new__(meta, name, bases, dct)
    def __init__(cls, name, bases, dct):
        print("Initializing class", name)
        super(MyMeta, cls).__init__(name, bases, dct)


@six.add_metaclass(MyMeta)
class MyBase(object):
    def __iter__(self):
        raise NotImplementedError

    def get_data(self):
        return self.__iter__()

class MyDerived(MyBase):
    def get_data(self):
        yield "Derive"

x = MyDerived()
print(list(x.get_data()))
print(list(iter(x)))
```

**Comment by PatWie** [comment]
Agree. Done.
