### ISSUE TITLE
MapDataComponent/AugmentImageComponent `index` must be `int`

### ISSUE THREAD

**Issue by npow** [tensorpack/tensorpack#870]
After upgrading from version 0.2.0 of tensorpack, we noticed that the `index` argument of the `MapDataComponent` and `AugmentImageComponent` was changed to be strictly an integer: https://github.com/tensorpack/tensorpack/commit/f2697f698809c27e24d8f6081c457f228343422d#diff-de615a485b911d152132e2216c8f554fL272.

Our datapoints are of type `dict`, so we were passing in `index` of type `str`. Would you be open to accepting a PR that supports `index` of type `Union[str, int]`?

**Comment by ppwwyyxx** [comment]
It was added. But in general most dataflows still assume list instead of dict. #768 aims to make dataflow work for dicts.
