### ISSUE TITLE
StageOp and  Unstage don't have a control dependence in StagingInput

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#871]
I  foud that StageOp and  Unstage don't have a control dependence in tesorboard
There is a  NoOp  depen on both of them
And I just found the code as below:
```
        def _before_run(self, ctx):
            # This has to happen once, right before the first iteration.
            # doing it in `before_train` may not work because QueueInput happens in before_train.
            if not self._initialized:
                self._initialized = True
                self._prefill()
            # Only step the stagingarea when the input is evaluated in this sess.run
            fetches = ctx.original_args.fetches
            if dependency_of_fetches(fetches, self._check_dependency_op):
                return self.fetches
```

that means that Unstage don't have to run before Stage except first step.
So,StageOp may run before Unstage in the following step, and there would have 2 batch of data in StagingArea ?
am I right?

**Comment by ppwwyyxx** [comment]
Yes

**Comment by yogurfrul** [comment]
why  not add a control dependence between Stage and Unstage  to make unstage run before stage .
so we can set the StagingArea  capacity to 1, it can work as the same way using smaller GPU memory

**Comment by ppwwyyxx** [comment]
Setting the capacity to 1 is enough to achieve what you said because the staging op will block if capacity is reached.
That sounds like a reasonable thing to do. However some benchmarks will be needed to see how it affects speed or memory.

**Comment by ppwwyyxx** [comment]
Capacity is now set to 1.

**Comment by yogurfrul** [comment]
glad to hear that my suggestion is accepted~
