### ISSUE TITLE
How to combine QueueInput and StagingInput?

### ISSUE THREAD

**Issue by lizaigaoge550** [tensorpack/tensorpack#873]
Hi, In the document, you saw "we recommend QueueInput + StagingInput as it’s good for most use cases".
but how to combine the QueueInput and StagingInput. In examples. i did not find related examples. Can you give me some examples about it. Thank you very much

**Comment by ppwwyyxx** [comment]
`StagingInput(QueueInput(...))`.
By calling `launch_train_with_config`, most examples already do this automatically.

**Comment by lizaigaoge550** [comment]
Thank you. When i call TrainConfig,  I can write it as TrainConfig(data=StagingInput(QueueInput(...))). Is it right?

**Comment by ppwwyyxx** [comment]
Yes
