### ISSUE TITLE
what is the exactly eviroment of Fasterrcnn example runs on?

### ISSUE THREAD

**Issue by AlgoHunt** [tensorpack/tensorpack#883]
Hi Yuxin Wu,

I tried to run your FasterRcnn example on the below setting ,the total cost and wd cost are all nan
tensorpack: 0.8.8(from source)
tensorflow:  1.10.0
python: 3.6

Than I tried anathoer envriroment which is as below, and the code work now. I have no idea why it fail in the newest version.
tensorpack: 0.8.8(from pypi)
tensorflow:  1.8.0
python: 3.6

**Comment by ppwwyyxx** [comment]
Please provide more details following the issue template.
In particular, please provide the command you use to:
1. get the source code to run
2. run

**Comment by AlgoHunt** [comment]
sorry about the confusing,

I clone the FasterRcnn example from 

https://github.com/tensorpack/tensorpack/tree/01245d68c30c223bb598d91b390d41abc7f94640

run it with
 `
python train.py
` 
the only change in config is I load a resnet50 backbone weights. and FPN = True

I also made some change in data.py from:
`
return ret
`
to
`
names = ['image', 'anchor_labels_lvl2', 'anchor_boxes_lvl2', 'anchor_labels_lvl3', 'anchor_boxes_lvl3', 'anchor_labels_lvl4', 'anchor_boxes_lvl4', 'anchor_labels_lvl5', 'anchor_boxes_lvl5', 'anchor_labels_lvl6', 'anchor_boxes_lvl6', 'gt_boxes', 'gt_labels', 'gt_masks']

return [ret[name] for name in names]
`

**Comment by AlgoHunt** [comment]
when trained with tf1.10.0 for 20 epoch

>  fastrcnn_losses/box_loss: 0.0022282
>  [32m[0902 01:57:11 @monitor.py:435] [0m fastrcnn_losses/label_loss: 0.028814
>  [32m[0902 01:57:11 @monitor.py:435] [0m fastrcnn_losses/label_metrics/accuracy: 0.9955
>  [32m[0902 01:57:11 @monitor.py:435] [0m fastrcnn_losses/label_metrics/false_negative: 1
>  [32m[0902 01:57:11 @monitor.py:435] [0m fastrcnn_losses/label_metrics/fg_accuracy: 2.2959e-37
>  [32m[0902 01:57:11 @monitor.py:435] [0m learning_rate: 0.01
>  [32m[0902 01:57:11 @monitor.py:435] [0m maskrcnn_loss/accuracy: 0.49791
>  [32m[0902 01:57:11 @monitor.py:435] [0m maskrcnn_loss/fg_pixel_ratio: 0.50209
>  [32m[0902 01:57:11 @monitor.py:435] [0m maskrcnn_loss/maskrcnn_loss: nan
>  [32m[0902 01:57:11 @monitor.py:435] [0m maskrcnn_loss/pos_accuracy: 2.3443e-37
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 511.92
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 0.080237
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 0.0023035
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 2.3035e-37
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level2: 2.222
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level3: 0.080237
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level4: 0.0023035
>  [32m[0902 01:57:11 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level5: 0
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/box_loss: 0.015912
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/label_loss: 0.12846
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/box_loss: 0.0099081
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_loss: 0.085681
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.1: 0.26406
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.2: 0.26406
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.5: 0.26406
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/num_pos_anchor: 4.6261
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level2/num_valid_anchor: 200.4
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/box_loss: 0.0043817
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_loss: 0.034303
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.1: 0.31281
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.2: 0.31281
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.5: 0.31281
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/num_pos_anchor: 2.068
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level3/num_valid_anchor: 45.1
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/box_loss: 0.001617
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_loss: 0.0082804
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.1: 0.41653
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.2: 0.41653
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.5: 0.41653
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/num_pos_anchor: 0.55376
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level4/num_valid_anchor: 9.2134
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/box_loss: 5.1986e-06
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_loss: 0.00018782
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.1: 0.49879
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.2: 0.49879
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.5: 0.49879
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/num_pos_anchor: 0.0049376
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level5/num_valid_anchor: 1.2441
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/box_loss: 0
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_loss: 6.2402e-06
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.1: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.2: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.5: 0.5
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/num_pos_anchor: 0
>  [32m[0902 01:57:11 @monitor.py:435] [0m rpn_losses/level6/num_valid_anchor: 0.04577
>  [32m[0902 01:57:11 @monitor.py:435] [0m sample_fast_rcnn_targets/num_bg: 509.7
>  [32m[0902 01:57:11 @monitor.py:435] [0m sample_fast_rcnn_targets/num_fg: 2.3046
>  [32m[0902 01:57:11 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/best_iou_per_gt: nan
>  [32m[0902 01:57:11 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.3: 0.16727
>  [32m[0902 01:57:11 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.5: 0.051163
>  [32m[0902 01:57:11 @monitor.py:435] [0m total_cost: nan
>  [32m[0902 01:57:11 @monitor.py:435] [0m wd_cost: nan

when trained with tf1.8.0 for 20 epoch

> [32m[0902 04:44:37 @monitor.py:435] [0m fastrcnn_losses/box_loss: 0.076984
>  [32m[0902 04:44:37 @monitor.py:435] [0m fastrcnn_losses/label_loss: 0.03472
>  [32m[0902 04:44:37 @monitor.py:435] [0m fastrcnn_losses/label_metrics/accuracy: 0.98665
>  [32m[0902 04:44:37 @monitor.py:435] [0m fastrcnn_losses/label_metrics/false_negative: 0.16149
>  [32m[0902 04:44:37 @monitor.py:435] [0m fastrcnn_losses/label_metrics/fg_accuracy: 0.83851
>  [32m[0902 04:44:37 @monitor.py:435] [0m learning_rate: 0.01
>  [32m[0902 04:44:37 @monitor.py:435] [0m maskrcnn_loss/accuracy: 0.88644
>  [32m[0902 04:44:37 @monitor.py:435] [0m maskrcnn_loss/fg_pixel_ratio: 0.44969
>  [32m[0902 04:44:37 @monitor.py:435] [0m maskrcnn_loss/maskrcnn_loss: 0.25286
>  [32m[0902 04:44:37 @monitor.py:435] [0m maskrcnn_loss/pos_accuracy: 0.39374
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 440.01
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 53.552
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 17.493
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 0.94497
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level2: 23.713
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level3: 3.6506
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level4: 0.13955
>  [32m[0902 04:44:37 @monitor.py:435] [0m multilevel_roi_align_mask/fpn_map_rois_to_levels/num_roi_level5: 0
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/box_loss: 0.0092716
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/label_loss: 0.0047935
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/box_loss: 0.0081492
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_loss: 0.0037865
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.1: 0.58309
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.2: 0.59838
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/precision_th0.5: 0.61808
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.1: 0.70027
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.2: 0.70025
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/label_metrics/recall_th0.5: 0.69964
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/num_pos_anchor: 5.3862
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level2/num_valid_anchor: 199.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/box_loss: 0.00070578
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_loss: 0.00034172
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.1: 0.59589
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.2: 0.61341
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/precision_th0.5: 0.61765
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.1: 0.63041
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.2: 0.63041
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/label_metrics/recall_th0.5: 0.63041
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/num_pos_anchor: 1.5428
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level3/num_valid_anchor: 44.827
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/box_loss: 0.0003572
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_loss: 0.00065178
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.1: 0.60173
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.2: 0.60216
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/precision_th0.5: 0.60358
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.1: 0.59635
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.2: 0.59635
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/label_metrics/recall_th0.5: 0.59635
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/num_pos_anchor: 0.92755
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level4/num_valid_anchor: 10.267
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/box_loss: 5.9436e-05
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_loss: 1.3451e-05
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.1: 0.51215
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.2: 0.51215
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/precision_th0.5: 0.51215
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.1: 0.51215
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.2: 0.51215
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/label_metrics/recall_th0.5: 0.51214
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/num_pos_anchor: 0.10742
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level5/num_valid_anchor: 1.4042
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/box_loss: 0
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_loss: 2.7921e-08
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.1: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.2: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/precision_th0.5: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.1: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.2: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/label_metrics/recall_th0.5: 0.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/num_pos_anchor: 0
>  [32m[0902 04:44:37 @monitor.py:435] [0m rpn_losses/level6/num_valid_anchor: 0.0015343
>  [32m[0902 04:44:37 @monitor.py:435] [0m sample_fast_rcnn_targets/num_bg: 484.5
>  [32m[0902 04:44:37 @monitor.py:435] [0m sample_fast_rcnn_targets/num_fg: 27.504
>  [32m[0902 04:44:37 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/best_iou_per_gt: 0.67628
>  [32m[0902 04:44:37 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.3: 0.86692
>  [32m[0902 04:44:37 @monitor.py:435] [0m sample_fast_rcnn_targets/proposal_metrics/recall_iou0.5: 0.76383
>  [32m[0902 04:44:37 @monitor.py:435] [0m total_cost: 0.84116
>  [32m[0902 04:44:37 @monitor.py:435] [0m wd_cost: 0.46254

**Comment by ppwwyyxx** [comment]
The code works well for its original purpose (training on COCO dataset).
Since you're using it for a different task you'll be responsible for making any necessary changes, including changing hyperparameters or data processing, to make it work. 
For example, if many of your image does not have a ground truth box, it could easily make training unstable. And you'll need to figure out the best setting to train it (e.g. change the fg/bg sampe strategy, etc).

Such problem is not considered a tensorpack issue, unless you have reasons to believe it's actually caused by a bug in the code rather than the change of dataset.
