### ISSUE TITLE
How can I see the value of parameters in the trained model?

### ISSUE THREAD

**Issue by SeunghyunMoon** [tensorpack/tensorpack#886]
I've trained a model that I arbitrary constructed. I'd like to see the value of the parameters in each layer. 
For example, when I construct the model like below,

Trainable Variables:
   name                  shape                   dim
=======       =========       =======
conv0/W:0        [3, 3, 3, 32]                    864
conv0/b:0          [32]                                 32
conv1/W:0        [3, 3, 32, 32]                 9216
conv1/b:0          [32]                                32
...

I want to see each value of all parameters conv0/W:0, conv0/b:0, conv1/W:0, conv1/b:0 ... like below.

conv0/W:0 = 

[ * , * , 0 , 0] = [ 1.3, -0.4, 0.7,
                        -1.2 -1.1, -0.8,
                         0.1, 1.1, -1.0]
[ * , * , 0 , 1] = [ 2.3, 0.2, -0.6,
                       -1.4 -1.6, -1.8,
                       0.2, -0.9, -1.3]
...
[*, *, 2, 31] = [ -1.0, -0.7, -0.9,
                      -1.3, 2.1, -1.1,
                       0.6, -0.5, -1.2]

conv0/b:0 = [ 12.1, -3.7, 2.3, ... , -2.1]

conv1/W:0 = 

[ * , * , 0 , 0] = [ 1.3, -0.4, 0.7,
 .                       -1.2 -1.1, -0.8,
 .                        0.1, 1.1, -1.0]
[ * , * , 0 , 1] = [ 2.3, 0.2, -0.6,
 .                       -1.4 -1.6, -1.8,
 .                        0.2, -0.9, -1.3]
...
[*, *, 31, 31] = [ -1.0, -0.7, -0.9,
 .                       -1.3, 2.1, -1.1,
 .                        0.6, -0.5, -1.2]

conv1/b:0 = [ 12.1, -3.7, 2.3, ... , -2.1]
...

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/tutorial/save-load.html
