### ISSUE TITLE
A problem about tf.sign(x / E) * E

### ISSUE THREAD

**Issue by xiezheng-cs** [tensorpack/tensorpack#888]
def fw(x):
        if bitW == 32:
            return x
        if bitW == 1:   # BWN
            E = tf.stop_gradient(tf.reduce_mean(tf.abs(x)))
            @tf.custom_gradient
            def _sign(x):
                return tf.sign(x / E) * E, lambda dy: dy
            return _sign(x)
        x = tf.tanh(x)
        x = x / tf.reduce_max(tf.abs(x)) * 0.5 + 0.5
        return 2 * quantize(x, bitW) - 1
In this part, when bitW==1, return tf.sign(x / E) * E={-E, 0, E}, but it should be {-E, E} follows DoReFa-Net paper. So, everyone, am I getting it wrong???

**Comment by ppwwyyxx** [comment]
You're right. To be more precise it should handle the case of zero. But the probability the weight become exactly zero is very small, so in practice it does not make a big difference.

**Comment by xiezheng-cs** [comment]
OK, thank you very much!
