### ISSUE TITLE
I can't install Tensorpack from the github!

### ISSUE THREAD

**Issue by Em-Lopez** [tensorpack/tensorpack#889]
This was the error I got: I don't know how.
C:\Users\cynth\Documents\Mini3\Scripts>activate tensorpack

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>pip install --upgrade git+https://github.com/tensorpack/tensorpack.git
Collecting git+https://github.com/tensorpack/tensorpack.git
  Cloning https://github.com/tensorpack/tensorpack.git to c:\users\cynth\appdata\local\temp\pip-req-build-_l51i5ko
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\tensorpack.egg-info
    writing pip-egg-info\tensorpack.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\tensorpack.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\tensorpack.egg-info\requires.txt
    writing top-level names to pip-egg-info\tensorpack.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\tensorpack.egg-info\SOURCES.txt'
    error: package directory 'find:                             # will call find_packages()' does not exist
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\cynth\AppData\Local\Temp\pip-req-build-_l51i5ko\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>

I'm using python 3.6.6
This is using the wrong folder, I suspect it's an issue with line endings

**Comment by Em-Lopez** [comment]
(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.0

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>pip install --upgrade git+https://github.com/tensorpack/tensorpack.git
Collecting git+https://github.com/tensorpack/tensorpack.git
  Cloning https://github.com/tensorpack/tensorpack.git to c:\users\cynth\appdata\local\temp\pip-req-build-4qxs6zaz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\tensorpack.egg-info
    writing pip-egg-info\tensorpack.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\tensorpack.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\tensorpack.egg-info\requires.txt
    writing top-level names to pip-egg-info\tensorpack.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\tensorpack.egg-info\SOURCES.txt'
    error: package directory 'find:                             # will call find_packages()' does not exist

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\cynth\AppData\Local\Temp\pip-req-build-4qxs6zaz\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>python --version
Python 3.6.6 :: Anaconda, Inc.

**Comment by Em-Lopez** [comment]
(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>pip3 --version
pip 18.0 from c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip (python 3.6)

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>pip3 --verbose install --upgrade git+https://github.com/tensorpack/tensorpack.git
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\cynth\AppData\Local\Temp\pip-ephem-wheel-cache-_cvvlhug
Created temporary directory: C:\Users\cynth\AppData\Local\Temp\pip-req-tracker-i80u1q2z
Created requirements tracker 'C:\\Users\\cynth\\AppData\\Local\\Temp\\pip-req-tracker-i80u1q2z'
Created temporary directory: C:\Users\cynth\AppData\Local\Temp\pip-install-b5w7vwrp
Collecting git+https://github.com/tensorpack/tensorpack.git
  Created temporary directory: C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf
  Cloning https://github.com/tensorpack/tensorpack.git to c:\users\cynth\appdata\local\temp\pip-req-build-_x5nasqf
  Running command git clone -q https://github.com/tensorpack/tensorpack.git C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf
  Added git+https://github.com/tensorpack/tensorpack.git to build tracker 'C:\\Users\\cynth\\AppData\\Local\\Temp\\pip-req-tracker-i80u1q2z'
  Running setup.py (path:C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf\setup.py) egg_info for package from git+https://github.com/tensorpack/tensorpack.git
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info\tensorpack.egg-info
    writing pip-egg-info\tensorpack.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\tensorpack.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\tensorpack.egg-info\requires.txt
    writing top-level names to pip-egg-info\tensorpack.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\tensorpack.egg-info\SOURCES.txt'
    error: package directory 'find:                             # will call find_packages()' does not exist
Cleaning up...
  Removing source in C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf
Removed git+https://github.com/tensorpack/tensorpack.git from build tracker 'C:\\Users\\cynth\\AppData\\Local\\Temp\\pip-req-tracker-i80u1q2z'
Removed build tracker 'C:\\Users\\cynth\\AppData\\Local\\Temp\\pip-req-tracker-i80u1q2z'
Command "python setup.py egg_info" failed with error code 1 in C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf\
Exception information:
Traceback (most recent call last):
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\operations\prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\operations\prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\req\req_install.py", line 636, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\cynth\documents\mini3\envs\tensorpack\lib\site-packages\pip\_internal\utils\misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\cynth\AppData\Local\Temp\pip-req-build-_x5nasqf\

(tensorpack) C:\Users\cynth\Documents\Mini3\Scripts>

**Comment by ppwwyyxx** [comment]
You may need to upgrade your setuptools.
