### ISSUE TITLE
 BatchData makes a dataflow extremely slow

### ISSUE THREAD

**Issue by kecsap** [tensorpack/tensorpack#890]
My problem is very similar to https://github.com/tensorpack/tensorpack/issues/618. I think the other user did not debug problem enough.

I adapted a generic jpeg reader based on https://github.com/tensorpack/tensorpack/blob/master/tensorpack/dataflow/dataset/ilsvrc.py

I describe two scenario how I measured the BatchData makes a dataflow brain dead slow:

build_dataset_loader = ImageDatasetLoader("/path")
build_dataset_dataflow = AugmentImageComponent(build_dataset_loader, augmentors)
// Speed: ~150/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()
build_dataset_dataflow = BatchData(build_dataset_dataflow, 512)
// Speed drops to ~0.6/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()
build_dataset_dataflow = PrefetchDataZMQ(build_dataset_dataflow, 4) 
// Speed "improves" to ~1.8/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()

If BatchData is reordered to the end:

build_dataset_loader = ImageDatasetLoader("/path")
build_dataset_dataflow = AugmentImageComponent(build_dataset_loader, augmentors)
// Speed: ~150/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()
build_dataset_dataflow = PrefetchDataZMQ(build_dataset_dataflow, 4) 
// Speed as expected: ~460-510/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()
build_dataset_dataflow = BatchData(build_dataset_dataflow, 512)
// Speed drops to ~0.6/it
TestDataSpeed(build_dataset_dataflow, size = 1000).start()

I tried out different batch sizes, but the result is the same.

Python version: 3.6
TF version: 1.10.0
Tensorpack version: Latest master
Hardware information: SSD for the jpeg images

**Comment by kecsap** [comment]
Yeah, now I realized this logic. It would be nice to write this done somewhere in the documentation. I did not expect that the it/s changes the meaning from images/sec into batches/sec.

**Comment by ppwwyyxx** [comment]
There is no concept of image or batch in dataflow. It just gives you "datapoints", whatever it is.
