### ISSUE TITLE
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:   device='GPU'  	 [[Node: PeakMemoryTracker/MaxBytesInUse = MaxBytesInUse[_device="/device:GPU:0"]()]]  MultiProcessMapDataZMQ successfully cleaned-up.

### ISSUE THREAD

**Issue by yuyijie1995** [tensorpack/tensorpack#892]
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:   device='GPU'  	 [[Node: PeakMemoryTracker/MaxBytesInUse = MaxBytesInUse[_device="/device:GPU:0"]()]]  MultiProcessMapDataZMQ successfully cleaned-up.

I found this error when I used the MaskRcnn example,and  I had completed this example before,but today this error happend. 
Python version is 3.6
tensorflowgpu 1.10
Tensorpack version:0.8.8
I have one 1080 GPU to use

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template.

**Comment by ppwwyyxx** [comment]
Closing because there is no response.

**Comment by AziziShekoofeh** [comment]
@yuyijie1995  Hi, Did you find any reason for this error? I am facing the simillar issue, but from my log, it seems before this error it is trying to run on CPU and the failure is due to that!

**Comment by ppwwyyxx** [comment]
This callback only works on GPUs.

**Comment by dengjianbo3** [comment]
@AziziShekoofeh you should add on an argument like " --device='0' " while using training command
