### ISSUE TITLE
How can I load data to TrainConfig in windows10

### ISSUE THREAD

**Issue by xiaoyaozzr** [tensorpack/tensorpack#896]
I defined this for dataflow : 
**ds = BatchData(ds, batch_size, remainder=False)** #########################

then when I define TrainConfig:
return TrainConfig(
        model=model,
        **data=ds,**  #########################
        callbacks=callbacks,
        extra_callbacks=[
            ProgressBar(extra_display),
            MergeAllSummaries(),
            RunUpdateOps()
        ],
        starting_epoch=starting_epoch,
        steps_per_epoch=ds.size(),
        max_epoch=max_epoch,
    )

in the below ######## lines:
I tried 
data = ds.get_data(); 
then in TrainConfig Itried:
data=data, 
dataflow=data

all these methods failed............

I can run succeed in linux using :
data = QueueInput(ds)
TrainConfig(
        model=model,
        data=StagingInput(data))
 
but in windows what can I do.....

**Comment by ppwwyyxx** [comment]
The last one is correct. If something fails, please post the issue following the issue template.

**Comment by ppwwyyxx** [comment]
Closing since there is no response.
