### ISSUE TITLE
Differences with Cascade-RCNN paper

### ISSUE THREAD

**Issue by LandyGuo** [tensorpack/tensorpack#898]
Thanks for sharing your code.  Some questions about your cascadeRCNN implementation:  
1) The scale_gradient implementation for cascade-rcnn: https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/model_cascade.py#L29, seems to stabilize the training, but I did not find the corresponding description in the original paper, is it needed?  
2) It seems that neither mean nor  variance normalization is performed during bounding box regression

hope for your response :)

**Comment by ppwwyyxx** [comment]
1. It is from personal communication with the author. It helps a bit.
2. https://github.com/tensorpack/tensorpack/blob/0dbcbac7ae5dc62f89ecdbe0961731513c11f2ec/examples/FasterRCNN/config.py#L181

**Comment by LandyGuo** [comment]
Thanks I see. Close it now
