### ISSUE TITLE
Run `/examples/GAN/CycleGAN.py` with `MultiGPUGANTrainer` 

### ISSUE THREAD

**Issue by songfh** [tensorpack/tensorpack#899]
When I ran`/examples/GAN/CycleGAN.py` with `MultiGPUGANTrainer` (Figure 1), it will stay at Figure 2.

Figure 1: ![gan2](https://user-images.githubusercontent.com/22196645/45669487-d6304480-bb52-11e8-9775-9dc9ef79e0cd.png)

Figure 2: ![gan](https://user-images.githubusercontent.com/22196645/45669473-cca6dc80-bb52-11e8-8e90-580c3e0a184f.png)

**Comment by ppwwyyxx** [comment]
`MultiGPUGANTrainer` automatically adds `StagingInput`. You have to remove `StagingInput` in your data because `StagingInput` cannot be nested together.
After the above commit it should now throw an error about this situation.
