### ISSUE TITLE
How many frames in one episode when evaluating DDQN? How to set the number?

### ISSUE THREAD

**Issue by silentobservers** [tensorpack/tensorpack#903]
Hi, nice to meet you.
I notice that in readme it is said that "An episode is limited to 10000 steps." However, in code ,i found 
############################
    env = AtariPlayer(ROM_FILE, frame_skip=ACTION_REPEAT, viz=viz,
                      live_lost_as_eoe=train, max_num_frames=60000)
############################
It seems that there are 60000 frames in one episode when evaluating. And in paper (DDQN), there are 18000 frames. Right? I am so confused about the differences.

**Comment by ppwwyyxx** [comment]
The readme has a mistake.

I cannot find the number 18000 in DDQN paper.
