### ISSUE TITLE
[Mask RCNN] HOW to deal with masks with holes?

### ISSUE THREAD

**Issue by wangg12** [tensorpack/tensorpack#907]
@ppwwyyxx The masks in Mask RCNN are represented by polygons. If an object has holes, then it will contains multiple polygons. However, when the polygons are converted to mask, the holes become foreground masks(see [this line](https://github.com/tensorpack/tensorpack/blob/7b8728f96b76774a5d345390cfb5607c8935d9e3/examples/FasterRCNN/data.py#L366)).

If I load the masks using the binary mask format, I can not use the augmentations through coordinates.

If I want to correctly handle the holes with the polygons representation, what should I do? 

Thanks.

**Comment by ppwwyyxx** [comment]
Any subset of pixels in an image can be represented by a list of polygons (in the extreme case you can represent each pixel by one polygon), so there should be no issues with the use of polygon. I do not see how the line of code you refer to is related to the discussion.

If you want to use masks for augmentation you can still augment each pixel in the mask.

**Comment by wangg12** [comment]
@ppwwyyxx I mean the function segmentation_to_mask will merge the polygon of the hole, so in the resulted mask, the hole part is filled by 1 but 0 is expected. That’s my problem.

**Comment by ppwwyyxx** [comment]
If you use only one polygon for the object with holes then that's a problem of the dataset.
Like I said any subset of pixels in an image can be represented by a list of polygons

**Comment by ppwwyyxx** [comment]
That again is just a problem with the dataset. You can apparently represent a donut by two polygons: the left part and the right part or the donut. If your data is not annotated like that there is nothing I can do.

**Comment by ppwwyyxx** [comment]
And again, if your data is originally in the form of masks, you can just augment all the pixels directly without converting to polygons.

**Comment by wangg12** [comment]
@ppwwyyxx Thanks. I think it might be easier by directly loading binary masks and changing the augmentation code.

**Comment by Caliphamin** [comment]
hello @ wangg12
I have this problem now
can you help me please
