### ISSUE TITLE
How to augment image and label together in image segmentation?

### ISSUE THREAD

**Issue by fsk119** [tensorpack/tensorpack#908]
Is there any function similar to ImageAugmentor.augment_coords when we do data augmentation in segmentation? Or any better ideas to do data augmentation?
Thank you for answering my question!

**Comment by ppwwyyxx** [comment]
augment_coords is the function to use.

**Comment by ppwwyyxx** [comment]
Or you can just use `augment` if your label is image..

**Comment by ppwwyyxx** [comment]
Examples that use `augment` to augment image and segmentation: #214 
Examples that use `augment_coords` to augment image and segmentation: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN
