### ISSUE TITLE
FasterRCNN scale jittering training

### ISSUE THREAD

**Issue by LandyGuo** [tensorpack/tensorpack#910]
Hi, I noticed that one of your cascade-RCNN training config got the following result in COCO:
![image](https://user-images.githubusercontent.com/16185531/45998077-38012900-c0d4-11e8-8604-22892054c517.png)

config:
`MODE_FPN=True FPN.CASCADE=True
BACKBONE.RESNET_NUM_BLOCK=[3,4,23,3]
TEST.RESULT_SCORE_THRESH=1e-4
PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800]
TRAIN.LR_SCHEDULE=[420000,500000,540000]
`

CascadeRCNN with almost doubled  training time and scale jittering seems to be the main reason compared to the standard config:
![image](https://user-images.githubusercontent.com/16185531/45998049-1bfd8780-c0d4-11e8-8fdf-ed3277ffcf04.png)

With scale jittering training,  is test config PREPROC.TEST_SHORT_EDGE_SIZE = (640+800)/2. more suitable compared with   PREPROC.TEST_SHORT_EDGE_SIZE = 800 ?  Following the single scale evaluation method in https://arxiv.org/abs/1409.1556

**Comment by ppwwyyxx** [comment]
What parameter to use is up to you. You're welcome to share new results with different parameters.

**Comment by LandyGuo** [comment]
thanks , I'll share if I get better results while playing with parameters
