### ISSUE TITLE
Quantization Function in SVHN-Dorefa

### ISSUE THREAD

**Issue by XinDongol** [tensorpack/tensorpack#920]
I am a little confused about your activation quantization function in svhn-dorefa
```python
def cabs(x):
      return tf.minimum(1.0, tf.abs(x), name='cabs')
def activate(x):
      return fa(cabs(x))
```

I plotted the foward function of this. 
```python
plt.figure()
def cabs(x):
    return tf.minimum(1.0, tf.abs(x), name='cabs')
def fa(x):
	return fa_fake(cabs(x))
_,fa_fake,_ = dorefa.get_dorefa(32,5,32)
plt.plot(sess.run(tf.range(-5,5,0.01)),sess.run(fa(tf.range(-5,5,0.01))),label='5-bit', alpha=0.5)

_,fa_fake,_ = dorefa.get_dorefa(32,2,32)
plt.plot(sess.run(tf.range(-5,5,0.01)),sess.run(fa(tf.range(-5,5,0.01))),label='2-bit', alpha=0.5)

_,fa_fake,_ = dorefa.get_dorefa(32,3,32)
plt.plot(sess.run(tf.range(-5,5,0.01)),sess.run(fa(tf.range(-5,5,0.01))),label='3-bit', alpha=0.5)

_,fa_fake,_ = dorefa.get_dorefa(32,4,32)
plt.plot(sess.run(tf.range(-5,5,0.01)),sess.run(fa(tf.range(-5,5,0.01))),label='4-bit', alpha=0.5)

plt.title('Forward')
plt.legend()
```
![image](https://user-images.githubusercontent.com/15049780/46505810-451ec600-c800-11e8-84c5-b843c4526743.png)

1. Why we want to abs(x) ?
2. I notice you use different scheme for AlexNet ? Any difference between them ?

Thanks a lot.

**Comment by ppwwyyxx** [comment]
I don't remember any specific reasons we use abs() for SVHN. I think clip(abs(x), 0, 1) and clip(x, 0, 1) should both work well as an activation function.

IIRC it's just one of the things we tried and happened to use on SVHN but not AlexNet, for no particular reasons.

**Comment by XinDongol** [comment]
Thanks for the quick reply. 
close this question.

**Comment by ppwwyyxx** [comment]
The code was updated to use the same activation as alexnet to avoid confusion. It has similar performance.

**Comment by XinDongol** [comment]
Thanks a lot.
