### ISSUE TITLE
Unexpected evaluate results on COCOVal2014

### ISSUE THREAD

**Issue by Dataphz** [tensorpack/tensorpack#922]
1. What you did:
  Directly using Example FasterRCNN :
     CUDA_VISIBLE_DEVICES=0 python train.py --evaluate eval.json
     MODE_PFN=True --MODE_MASK=False:

2. What you observed, including but not limited to the __entire__ logs.
   I evaluated the download model 'COCO-R50FPN-MaskRCNN-Standard.npz' on COCO val2014 dataset, and got unexpected mAP. The mAP of Bbox is 55.9, which is higher than state-of-the-art performances. Did download model 'COCO-R50FPN-MaskRCNN-Standard.npz' seen val2014 dataset when training? 

4. Your environment:
  + Python3.6.
  + TF version: 1.10.1.
  + Tensorpack version: 0.8.9.
  + 1 1080Ti.

**Comment by ppwwyyxx** [comment]
It's answered in the readme. The models were trained on trainval35k which overlaps with val2014.
