### ISSUE TITLE
Monitor tensors every batch

### ISSUE THREAD

**Issue by XinDongol** [tensorpack/tensorpack#923]
Default epoch monitors for training are quite useful. 

Could you give an example of how to monitor one tensor's value **every batch** ？(and write it to tensorboard file.)

Thanks a lot.

**Comment by XinDongol** [comment]
The thing is that I only want to monitor one tensor every batch. 
`MergeAllSummaries.period=1` will make all the other monitors called every batch too? 
I want to keep monitors like train_cost, val_cot called every epoch.

**Comment by ppwwyyxx** [comment]
Then you need to also mark "what" to summarize following the tutorial.
When you create the summaries with `tf.summary.xxx`, tag it with a different collection. See https://www.tensorflow.org/api_docs/python/tf/summary/scalar.
Then call `MergeAllSummaries` with the non-default collection name.
