### ISSUE TITLE
FasterRCNN with MODE_FPN=True train 5 time faster than MODE_FPN=False

### ISSUE THREAD

**Issue by Giangblackk** [tensorpack/tensorpack#931]
I tried to run FasterRCNN example, and i found that when MODE_FPN=False, the model trains with speed about 1 items/s, but with MODE_FPN=True, the model trains with speed 5 items/s.
How do I fix this to increase performance of training when MODE_FPN=False (using ResnetC4Model)
The version I used is currently latest commit on github.

- Python version: Conda Python 3.6.6
- TF version: 1.11.0
- Number of GPUs: 2 GTX 1080 Ti

**Comment by ppwwyyxx** [comment]
Closing as there is no response.
