### ISSUE TITLE
Question about `DataParallelInferenceRunner` when using TFRecord-style data pipeline

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#933]
Hello. I'm so happy when using Tensorpack. So great. :clap: 
I have a question about `DataParallelInferenceRunner`, and want to ask for an advice.

From the tutorial, I understood that Dataflow can be done using pure Python generator functions (using `yield`) or existing TFRecords, where the former could be
````
class MyRecords(object):
    def __init__(self, config):
        dataset = tf.data.TFRecordDataset(tfrecords, num_parallel_reads=340)
        .... some tf.data functions ...
        iterator = dataset.make_one_shot_iterator()
        self.next_batch = iterator.get_next()
df = MyRecords(config)
input = TensorInput(df.next_batch)
input = StagingInput(input, nr_stage=1)
````
and the latter could be
````
class MyFlow(RNGDataFlow):
    def __iter__(self):
        ... yeild somewhere ...
df = MyFlow(config)
df = BatchData(df, 3)
df = PrefetchDataZMQ(df, 3)  
input = QueueInput(df)
````

Back to the `DataParallelInferenceRunner` question, the callback assumes input is either `DataFlow` or `QueueInput` in its `__init__` function. If I am using TFRecord-style Data pipeline, what would be a good way to use the callback? Is there a way to convert from `TensorInput` to `QueueInput`?

**Comment by ppwwyyxx** [comment]
No such conversion exists. In general you can read TFRecord from pure python, with `tf.python_io.tf_record_iterator`. This will give you serialized bytes from the TFRecord and you'll need to decode the bytes into data points.

**Comment by ywpkwon** [comment]
I see. Thanks for the advice!
I'll leave a few random related links:
https://stackoverflow.com/questions/42394585/how-to-inspect-a-tensorflow-tfrecord-file
https://www.kaggle.com/mpekalski/reading-tfrecord
