### ISSUE TITLE
Tensorpack with Horovod 0.14.1?

### ISSUE THREAD

**Issue by armandmcqueen** [tensorpack/tensorpack#936]
I have been working with my fork of Tensorpack to run distributed Faster RCNN Horovod training and when I upgraded Horovod from 0.13.11 to 0.14.X, I now get segmentation faults immediately after launching training every time (running on 1 node, 8 GPUs). While I know there have been occasional segfaults with 0.13.11, training still worked the majority of the time and the segfaults happened much later in the training. This immediate segfault behavior with Horovod 0.14.X happens with both TF 1.11 and 1.10. Horovod training with tensorflow/benchmarks has not had any issues with the Horovod upgrade.

I am training with examples/FasterRCNN/train.py using TRAINER=horovod. 

I'm not asking you to try to solve my problem - our codebases are fairly out of sync and I know I'm not providing enough detail - but I was curious if you have had any similar problems using the Horovod trainer with Horovod 0.14.0 or later, particularly for the Faster RCNN example.

**Comment by ppwwyyxx** [comment]
Could you try `export TENSORPACK_SERIALIZE=msgpack`?
There is a bug in pyarrow that conflicts with horovod.

**Comment by ppwwyyxx** [comment]
Well I'm not sure if "your own version" will avoid `import pyarrow` after setting that environment variable.
Maybe just `pip uninstall pyarrow` and see what happened afterwards.

**Comment by armandmcqueen** [comment]
Yup, pyarrow was the issue and `pip uninstall pyarrow` resolved it. Thank you for the quick response!
