### ISSUE TITLE
ImportError: cannot import name 'FeedfreePredict'

### ISSUE THREAD

**Issue by wangzilu** [tensorpack/tensorpack#946]
__PLEASE ALWAYS INCLUDE__:
1. What you did:
  + If you're using examples:
   examples/ResNet/imagenet_utils.py
  + If not, tell us what you did that may be relevant.
    But we may not investigate it if there is no reproducible code.
  + Better to paste what you did instead of describing them.
2. What you observed, including but not limited to the __entire__ logs.
  ImportError: cannot import name 'FeedfreePredict'
3. What you expected, if not obvious.
4. Your environment:
  + Python version. python3.5 python2.7
  + TF version: `1.9`.
  + Tensorpack version: `0.8.9`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`.:
  + Hardware information, e.g. number of GPUs used.

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by wangzilu** [comment]
from tensorpack.predict.feedfree import FeedfreePredictor
I use this line instead.

**Comment by ppwwyyxx** [comment]
It is not available in tensorpack 0.8.9.

**Comment by wangzilu** [comment]
@ppwwyyxx so, which version should I use?
and how about if I use from tensorpack.predict.feedfree import FeedfreePredictor instead?

**Comment by ppwwyyxx** [comment]
It needs to be the latest version (github master branch). You've posted the installation instruction above.

**Comment by wangzilu** [comment]
@I tried install using pip install -U git+https://github.com/ppwwyyxx/tensorpack.git. However, it is still the version 0.8.9 and sitll can not import name 'FeedfreePredict', please check it.

**Comment by ppwwyyxx** [comment]
Please post relevant details following the issue template. 

> What you observed, including but not limited to the entire logs.
ImportError: cannot import name 'FeedfreePredict'

This is not the entire logs.

With a correct installation, this command:
```bash
python -c 'from tensorpack.predict import FeedfreePredictor'
```
will exit without errors.
