### ISSUE TITLE
TensorPack results on ResNet50, ResNet101, and ResNet152 for DoReFa-Net

### ISSUE THREAD

**Issue by snownus** [tensorpack/tensorpack#948]
Can release results of TensorPack results on ResNet50, ResNet101, and ResNet152?

**Comment by ppwwyyxx** [comment]
It's in the examples.

**Comment by ppwwyyxx** [comment]
We have not trained such models.

**Comment by ppwwyyxx** [comment]
Duplicate of #470 .
