### ISSUE TITLE
How should I set the number of iterations?

### ISSUE THREAD

**Issue by horizonheart** [tensorpack/tensorpack#950]
i train my dataset used by tensorpack ,but i don't know how to set up epoch. i used four gpu ,but the speed is a little slow.I'm not sure if my configuration is wrong. I  also used the detectron ，which can finish is 12 hours (100000 iteration)on the same  dataset!
![image](https://user-images.githubusercontent.com/16372054/47599700-f0790000-d9e5-11e8-874e-5fc7befd6f62.png)

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/train.py#L588-L589
