### ISSUE TITLE
i trained the coco2017 and the predict image is none

### ISSUE THREAD

**Issue by horizonheart** [tensorpack/tensorpack#955]
when i trained the coco2017 dataset,i just change the path of dataset and backone , the rest config is default .i  run the code by means of( python train.py)
![image](https://user-images.githubusercontent.com/16372054/47690024-5c967680-dc27-11e8-9081-5e86179e36d6.png)
the training process can be done successfully,but when i watch the tensorboard ,i found the map is incorrect.
![image](https://user-images.githubusercontent.com/16372054/47690084-9e272180-dc27-11e8-9a67-2515e36183dc.png)
![image](https://user-images.githubusercontent.com/16372054/47690098-a717f300-dc27-11e8-8a5d-408f28443130.png)

next,i predict the model and change the code which i want to predict images in a folder,the shell is as follows 
python /nfs/private/tensorpack-master/examples/FasterRCNN/train.py --predict /nfs/private/images/ --load /nfs/private/shell/train_log/maskrcnn/model-380000
![image](https://user-images.githubusercontent.com/16372054/47690228-2f969380-dc28-11e8-9401-91445bf9caf8.png)

the left is original picture and right is predict label，i found the the model can't predict any box ,the predict result is None
![image](https://user-images.githubusercontent.com/16372054/47690300-8734ff00-dc28-11e8-9d09-a526262c9ae8.png)

**Comment by ppwwyyxx** [comment]
`python train.py` is not the correct command to train. You need to use a pre-trained weights. Read the README for details.

**Comment by horizonheart** [comment]
> `python train.py` is not the correct command to train. You need to use a pre-trained weights. Read the README for details.

but if  the dataset don't have 80 NUM_CATEGORY,the pre-trained weights is wrong in the last .what should i do.

**Comment by horizonheart** [comment]
Do you mean that there  must have a backbone on the imagenet when training?

**Comment by ppwwyyxx** [comment]
The pre-trained weights to load for coco training is trained on imagenet and has nothing to do with the 80 categories.

I did not say that there must be a pre-trained backbone. There are ways to train without a pre-trained backbone, but `python train.py` is just the wrong command.

**Comment by horizonheart** [comment]
./train.py --config \
    MODE_MASK=True MODE_FPN=True \
    DATA.BASEDIR=/path/to/COCO/DIR \
    BACKBONE.WEIGHTS=/path/to/ImageNet-R50-Pad.npz \
this is your example .But i have change the config in the config.py other than the backnoe.weights. Why can't I run python train.py directly?

**Comment by ppwwyyxx** [comment]
You need to set `BACKBONE.WEIGHTS` in either `config.py` or the command line.

**Comment by horizonheart** [comment]
so, your mean is that i should set up the backbone anyway? thanks very much for your patient!

**Comment by ppwwyyxx** [comment]
And if you change your `config.py` to use ResNet101, you need to load a ResNet101 pre-trained model.

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you have other information to share.
