### ISSUE TITLE
why evaluation time  is so long

### ISSUE THREAD

**Issue by horizonheart** [tensorpack/tensorpack#956]
there is only 2000 images to evaluate ,but the evaluation time is so long.,which almost needs one hour.
![image](https://user-images.githubusercontent.com/16372054/47705228-ddbe2f80-dc60-11e8-8be6-fa4e62b0ec44.png)

**Comment by ppwwyyxx** [comment]
For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

I assume you're running one of the standard settings in the README. When trained with only 1 GPU, the evaluation time you saw is normal.

**Comment by horizonheart** [comment]
> For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
> 
> I assume you're running one of the standard settings in the README. When evaluated with only 1 GPU, the evaluation time you saw is normal.

i used four gpu

**Comment by ppwwyyxx** [comment]
The partial logs suggest that you're using one GPU.
If not, please post issues following the issue template: including the command you run and the entire logs.

**Comment by ppwwyyxx** [comment]
Closing as there is no update. Feel free to reopen if you have more information to share.
