### ISSUE TITLE
the super fast edition is not very fast

### ISSUE THREAD

**Issue by yuyijie1995** [tensorpack/tensorpack#957]
![superfast](https://user-images.githubusercontent.com/30818917/47720435-d743ae00-dc88-11e8-8970-b6d0efd4e37e.jpg)
I test it on a 1080ti GPU ,one frame inference time is 0.37s,even slower than fpn edition . 
I don't know what is wrong.

**Comment by ppwwyyxx** [comment]
super quick means quick training, not quick inference.
