### ISSUE TITLE
ImportError: cannot import name ModelExporter

### ISSUE THREAD

**Issue by s7ev3n** [tensorpack/tensorpack#958]
__PLEASE ALWAYS INCLUDE__:
1. What you did:
I would like to export my model to `.pb` file, following this link: https://tensorpack.readthedocs.io/tutorial/inference.html#exporter
2. What you observed, including but not limited to the __entire__ logs.
I can not import `ModelExporter`, `ImportError: cannot import name ModelExporter`, also `examples/basic/export-model.py` in the tutorial is missing, maybe should update the docs.
3. What you expected, if not obvious.
4. Your environment:
  + Python version: py2.7
  + TF version: tf1.6
  + Tensorpack version: 0.8.9

  + Hardware information, e.g. number of GPUs used.
    CPU: E5
    GPU: 1080Ti

**Comment by ppwwyyxx** [comment]
> What you did:
I would like to export my model to .pb file, following this link: https://tensorpack.readthedocs.io/tutorial/inference.html#exporter

This is what you want to do, not what you did. I still don't know what you did.

> What you observed, including but not limited to the entire logs.
I can not import ModelExporter, ImportError: cannot import name ModelExporter, also examples/basic/export-model.py in the tutorial is missing, maybe should update the docs.

This is not the entire logs. Please post full error message.

The example `export-model.py` can run with latest tensorpack (github master).

**Comment by s7ev3n** [comment]
What I did:

I simply tried to run `export-model.py`, and the error is `ImportError: cannot import name ModelExporter`. The `ModelExporter` just can not be imported. While importing other tensorpack modules has no problem.


The link in the tutorial is missing, because 'basic' in tutorial link:
 https://github.com/tensorpack/tensorpack/blob/master/examples/basic/export-model.py should be 'basics'.

**Comment by ppwwyyxx** [comment]
Then you probably need to upgrade tensorpack. The upgrade method is in the README and also in the issue template.

**Comment by s7ev3n** [comment]
The importing issue still exists after `pip install --upgrade git+https://github.com/tensorpack/tensorpack.git`.

**Comment by s7ev3n** [comment]
I copied `export.py` to my model export script folder, and modified importing ,such as `from ..utils import logger` to `from tensorpack.utils import logger`. It did not report importing issue. 
However, new issue is below:
`TypeError: optimize_for_inference() takes exactly 4 arguments (5 given)`
The script is below:
```
from export import ModelExporter
sess_init = SaverRestore(model_path=restore_ckpt, ignore=ignore_list)
pred_config = PredictConfig(model=model, 
                           session_init=sess_init,
                           input_names=['images'], 
                           output_names=['fullconv/output'])
ModelExporter(pred_config).export_compact('/compact_graph.pb')
```
