### ISSUE TITLE
[Q] multiple GPU training speed (slower as more GPUs)?

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#962]
Hi, I really like `Tensorpack`'s idea of using pure Python for data pipeline. I have been an intense Tensorflow user with `tf.slim` and now am trying several things with `Tensorpack`.

My question is about GPU utilization when using multiple GPUs. 

Before asking the question, as background, my data flow speed looks like below.
````
BATCH_SIZE = 128
PREFETCH = 4
df = MyDataFlow(config, 'trainvalminusminival', aug=True)
TestDataSpeed(df).start()              # 3068.39it/s

df = MapData(df, preprocess)     
TestDataSpeed(df).start()              # 1330.81it/s

df = BatchData(df, BATCH_SIZE)
TestDataSpeed(df).start()              # 11.02it/s (1330/128 ~= 11. so looks reasonable..)

df = MultiThreadMapData(df, 8, lambda dp: [seq.augment_images(dp[0]), dp[1]], buffer_size=26, strict=True)
TestDataSpeed(df).start()              # 6.02it/s (looks quite slow..)

df = PrefetchDataZMQ(df, PREFETCH)
TestDataSpeed(df).start()              # at peak ~16it/s (okay, maybe acceptable..) 
````

When I do `python train.py --cfg_touch TRAIN.BATCH_SIZE=680 DATA.IMAGE_SIZE=64 TRAIN.PREFETCH=8 --gpu 1`, GPU utilization becomes up to ~98%. Everything fine.

When I do `python train.py --cfg_touch TRAIN.BATCH_SIZE=680 DATA.IMAGE_SIZE=64 TRAIN.PREFETCH=16 --gpu 1,2`, the GPU utilization becomes up to ~89%. Note that I set the `PREFETCH` twice greater, since there are two GPUs.

If I use all GPUs (`--gpu 0,1,2,3`), the GPU utilization becomes around 60~70% no matter what I do. I tried small batch sizes too.

Would you say it is typical behavior (maybe due to Python's multi-threading/processing inefficiency at this moment? I am not familiar such details..)?
Is there something that I am doing wrong or that you can advice/suggest?

**Comment by ppwwyyxx** [comment]
> Would you say it is typical behavio

It's typical that GPU utilization becomes lower because no systems can scale linearly.

> (maybe due to Python's multi-threading/processing inefficiency at this moment?

To know what is the reason you'll need to benchmark the training and data separately to see whether the data is fast enough.
