### ISSUE TITLE
conflict among pyarrow, msgpack, horovod

### ISSUE THREAD

**Issue by zachluo** [tensorpack/tensorpack#964]
a similar problem with #936. As it says, pyarrow has conflict with horovod. When I add  TENSORPACK_SERIALIZE=msgpack in the environment, it turns to msgpack. Some problems, however, come as follows when I use MultiProcessMapDataZMQ.
BufferError: memoryview: underlying buffer is not C-contiguous. 
Any Suggestion?

Tensorflow: 1.11
tensorpack: 0.9.0
msgpack: (0,5,6)
horovod: 0.13.0

**Comment by ppwwyyxx** [comment]
For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by ppwwyyxx** [comment]
Closing as a duplicate of #977 
A complete bug report can often easily lead to the solution.
