### ISSUE TITLE
MinSaver saves wrong model without warning

### ISSUE THREAD

**Issue by maciejjaskowski** [tensorpack/tensorpack#966]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
Run mnist example https://github.com/tensorpack/tensorpack/blob/master/examples/basics/mnist-convnet.py

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
No changes.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

The model saved with MaxSaver is a model from epoch N+1 instead from the epoch N, as expected. Logs show no problem.

(2) **Other observations, if any:**
N/A

### 3. What you expected, if not obvious.
There are two problems:
1. the example is wrong, it should read:
```
callbacks=[
            ModelSaver(),   # save the model after every epoch
            InferenceRunner(    # run inference(for validation) after every epoch
                dataset_test,   # the DataFlow instance used for validation
                ScalarStats(['cross_entropy_loss', 'accuracy'])),
            MaxSaver('validation_accuracy'),  # save the model with highest accuracy (prefix 'validation_')
           
        ],
```
Note, the order in callbacks. If `InferenceRunner` is run last, as originally in the example, MaxSaver will read `_get_stat` after epoch N but will save model after epoch N+1. 

2. There is no safeguard against the original version. 

In my case, `_need_save()` could be changed to something like
```
    def _need_save(self):
        v = self._get_stat()
        assert v, "No InferenceRunner was run before executing MinSaver"
        return v > self.min if self.reverse else v < self.min
```

But I am not sure if it does not have some implications, I don't see.

3. I didn't find a piece of documentation suggesting that MaxSaver must be after InferenceRunner in callbacks.

### 4. Your environment:
N/A

I'll be happy to fix this either way once we settle on a solution.

**Comment by ppwwyyxx** [comment]
Nice catch. This should be conveyed more clearly in the docs, and detected automatically.

**Comment by maciejjaskowski** [comment]
Probably not a big deal if your model's performance does not variate too much epoch to epoch :-)
