### ISSUE TITLE
[Q] the proper way of using tensorflow slim models?

### ISSUE THREAD

**Issue by ywpkwon** [tensorpack/tensorpack#967]
I read the tutorial about model load/save. What I understand is that `tensorpack` basically uses a simple rule about model loading, which checks/matches tensors by their names.

To make sure, please let me ask a few things:
(1) Let's say I am applying ResNet 50 in `tensorflow.models.research.slim` to a custom dataset classification. Since the number of classes is different (i.e. the last layer), is it a proper way for me to manually export their `ckpt` file to `npz` excluding the last layer's weights and to load the `npz`?

(2) I guess this is the same when I use `tensorpack`'s ImageNet-ResNet. I.e., first download `ImageNet-ResNet-50.npz`, manually remove the last layer in the `npz` file, and use it?

(3) There is no **generous** model loading functionality, such as automatically ignoring when there are missing/redundant/same-name-but-different-shape tensors, right?

**Comment by ywpkwon** [comment]
One more!  Please see `tensorpack/scripts/checkpoint-manipulate.py`. There could be a bug?

In line 7 & 19--24,
```
from tensorpack.tfutils.varmanip import dump_chkpt_vars
...
    if args.model.endswith('.npy'):
        params = np.load(args.model, encoding='latin1').item()
    elif args.model.endswith('.npz'):
        params = dict(np.load(args.model))
    else:
        params = dump_chkpt_vars(args.model)    # <---- weird?
```
1. There is no `dump_chkpt_vars` in `tensorpack.tfutils.varmanip`.
2. This parts are for loading, so `dump_chkpt_vars` should be `load_chkpt_vars`, maybe?

**Comment by ppwwyyxx** [comment]
(1), (2), (3):
https://tensorpack.readthedocs.io/tutorial/save-load.html#transfer-learning
As mentioned in the docs, you only need to change the name in your code and don't need to do anything to the checkpoint, (or you can change the checkpoint as well). Missing tensor will be printed as warning and will not be loaded.
On the other hand, `same-name-but-different-shape` tensors will become an error.

**Comment by ppwwyyxx** [comment]
> This parts are for loading, so dump_chkpt_vars should be load_chkpt_vars, maybe?

Yes

**Comment by ywpkwon** [comment]
Thanks!! 

Plus, `np.save(args.dump, **params)` --> `np.savez(args.dump, **params)`.
