### ISSUE TITLE
In inference run for cifar10-resnet or imagenet-resnet, can we also report "validation cost" along with "validation error"?

### ISSUE THREAD

**Issue by jwook1004** [tensorpack/tensorpack#970]
Hi,

Thanks for a great work. I am trying to add an "--eval" option to ["cifar10-resnet.py"](https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/cifar10-resnet.py) following an example in ["eval_on_ILSVRC12()"](url). I noticed that "PredictConfig" can take an argument "output_names" to dump validation error (such as ["ClassificationError('wrong_vector')"](https://github.com/tensorpack/tensorpack/blob/69b68b266f1e7caceb1069dd7308b0fd2986f03d/examples/ResNet/cifar10-resnet.py#L166), but I was wondering if there's a way to also compute "validation cost" (i.e., loss computed over the validation set). I tried to find an example for doing it but failed. Could you share some advice?

Thanks,
Jungwook

**Comment by ppwwyyxx** [comment]
Just add the name of the cost tensor to `output_names`.
