### ISSUE TITLE
No memoized_method when trying to run Super Resolution example

### ISSUE THREAD

**Issue by notecola** [tensorpack/tensorpack#976]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
python3 enet-pat.py --vgg19 vgg19.npz --data train2017.zip

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**

(3) **If not using examples, tell us what you did here:**

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

Traceback (most recent call last):
  File "enet-pat.py", line 20, in <module>
    from GAN import SeparateGANTrainer, GANModelDesc
  File "/home/master/a/tensorpack/tensorpack/examples/SuperResolution/GAN.py", line 12, in <module>
    from tensorpack.utils.argtools import memoized_method
ImportError: cannot import name 'memoized_method'

It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 4. Your environment:
  + Python version:
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__)'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + Hardware information, e.g. number of GPUs used.

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by notecola** [comment]
Thanks for your fast response!
I am on a master branch actually:
```
root@tower:~/a/tensorpack# git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```
will try older examples now

**Comment by ppwwyyxx** [comment]
You may be using the examples from the master branch but the tensorpack library from an older commit (which you may have previously installed).

**Comment by notecola** [comment]
Exactly this, my fault!
