### ISSUE TITLE
Sharping mAP decrease after the realization of DoReFa to the ssd-vgg16 network

### ISSUE THREAD

**Issue by asjmasjm** [tensorpack/tensorpack#981]
Sorry for not writing according to the template as this problem is more relevant to DoReFa quantization than to the tensorpack itself and I cannot find a more suitable place to post.

I am trying to realize the DoReFa quantization on the ssd-vgg16 network using the VOC dataset for the classification and regression tasks. The results however shows a unreasonably sharping decrease (from normal mAP 77% to around 10%) under the 8 8 8 DoReFa configuration. I am wondering if similar works have been done and the same trouble encountered?

**Comment by ppwwyyxx** [comment]
I'm not familiar with any similar work that does SSD with our quantization. We've done semantic segmentation which seems to work fine.

Closing as this is not a tensorpack issue. I would in general recommend you to not quantize too many layers (some layers should not be quantized), and use pre-training on imagenet.
