### ISSUE TITLE
assert os.path.isdir(self._imgdir), self._imgdir AssertionError: /home/wrc/data/BDDdrivable_coco/COCO/val2014

### ISSUE THREAD

**Issue by yuyijie1995** [tensorpack/tensorpack#989]
1.I use the FasterRCNN and make my own COCO dataset.
![2018-11-26 14-03-05](https://user-images.githubusercontent.com/30818917/48995702-049a5380-f184-11e8-9d12-db1827a17a40.png)
![2018-11-26 14-02-54](https://user-images.githubusercontent.com/30818917/48995710-0a903480-f184-11e8-879d-a69fc1b4f0ae.png)
I do have this imgdir but this error is still happened . Can you give me some suggestions? Thanks a lot

**Comment by ppwwyyxx** [comment]
The error is unrelated to tensorpack because `os.path.isdir` is a python function.

**Comment by yuyijie1995** [comment]
Thanks for your reply, this error is fixed automatically,but another error happened .
 ERR [MultiProcessMapDataZMQ] buffer_size cannot be larger than the size of the DataFlow!
![2018-11-28 13-13-45](https://user-images.githubusercontent.com/30818917/49130548-7652d880-f30f-11e8-9d89-93330c3d2b91.png)
Can you give me some suggestions ?

**Comment by ppwwyyxx** [comment]
> [MultiProcessMapDataZMQ] buffer_size cannot be larger than the size of the DataFlow!

Then just make it smaller.

**Comment by StackL0nG** [comment]
您好，我也遇到了同样的问题，可以分享下您最终的解决办法吗？
Hello, I have encountered the same problem, can you share your final solution?
