### ISSUE TITLE
I have a problem about shufflenet

### ISSUE THREAD

**Issue by kapness** [tensorpack/tensorpack#990]
+ Note that you can implement a lot of features by extending Tensorpack
  (See http://tensorpack.readthedocs.io/en/latest/tutorial/index.html#extend-tensorpack).
  It does not have to be added to Tensorpack unless you have a good reason.

+ "Could you improve/implement an example/paper ?"
  -- The answer is: we have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you, unless it demonstrates 
  some Tensorpack features not yet demonstrated in the existing examples.
  If you don't know how to do something yourself, you may ask a usage question.
hi, can you provide training cost of shufflenet-v2 just like vgg16(30h with 8 P100s)?Thanks!@ppwwyyxx

**Comment by ppwwyyxx** [comment]
Shufflenet is highly bound by the speed of data (because the compute cost is very small), therefore the speed is mainly determined by your CPU and disk, not GPUs. On my machine it's about 10~15 minutes every epoch.
