### ISSUE TITLE
Adding Non-Scalar Data to Log File

### ISSUE THREAD

**Issue by vqdang** [tensorpack/tensorpack#998]
Hi, I currently need to add confusion matrix of validation per run to the log.log file for later checking. I can open the file, add it and close it within the call back also. But is there any way I can let tensorpack functions handle it? I want it to be handled in the same way the current log.log is made.

**Comment by ppwwyyxx** [comment]
`from tensorpack.utils import logger`
then use `logger.info`, etc.
https://docs.python.org/3/library/logging.html#logging.Logger.info
