### ISSUE TITLE
/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/prof.py:109: RuntimeWarning: invalid value encountered in true_divide   rst_queue.put(stats / cnt)

### ISSUE THREAD

**Issue by huangmozhilv** [tensorpack/tensorpack#999]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**

(3) **If not using examples, tell us what you did here:**
Here's my `train.py`:
```
cfg = TrainConfig(
            model=get_model(modelName=config.MODELNAME), 
            data=QueueInput(df),
            callbacks=[
                PeriodicCallback(
                    ModelSaver(max_to_keep=10, keep_checkpoint_every_n_hours=1),
                    every_k_epochs=1),
                ScheduledHyperParamSetter('learning_rate', 
                    [(40, config.BASE_LR*0.1),
                    (60, config.BASE_LR*0.01)]
                ),
                GPUUtilizationTracker(),
                PeakMemoryTracker(),
                EstimatedTimeLeft(),
            ],
            steps_per_epoch=stepnum,
            max_epoch=config.MAX_EPOCH,
            session_init=get_model_loader(args.load) if args.load else None,
        )
        # nccl mode gives the best speed
        trainer = SyncMultiGPUTrainerReplicated(get_nr_gpu(), mode='nccl')
        launch_train_with_config(cfg, trainer)
```
So the code is calling `GPUUtilizationTracker`. In the command line, I run ` CUDA_VISIBLE_DEVICES=1 python train.py`. 

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/prof.py:109: RuntimeWarning: invalid value encountered in true_divide
  rst_queue.put(stats / cnt)

[1205 13:30:53 @monitor.py:459] GPUUtil/1: nan
```
It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.

(2) **Other observations, if any:**
```
Others are normal.
```
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.
```
There should be no warning and GPUUtil/1 should not be nan
```
### 4. Your environment:
  + Python version: 3.6.6
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. v1.4.0-rc1-11-g130a514 1.4.0.
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`. 0.9.0
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used. 1 GPU used.

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
It would be better if you could post more logs according to the issue template.
In particular, I'm wondering whether your epoch is too short (<3 seconds) and the `GPUUtilizationTracker` hasn't collected enough samples.

**Comment by huangmozhilv** [comment]
Thanks a lot. It could be this reason. I am tuning the code and set the epoch as 5 steps which takes only 1 second. When the step_per_epoch set to 250, the issues disappear.

**Comment by ppwwyyxx** [comment]
Thanks. Then commit 7158eed should resolve this issue.
